// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using Planetoid_DB.Resources;

namespace Planetoid_DB;

/// <summary>Represents a Windows Form that provides a user interface for downloading files from a database and monitoring download progress.</summary>
/// <remarks>The form displays information such as download status, file size, source, date, speed, and estimated time remaining. It allows users to initiate, cancel, and track downloads, and provides options to copy relevant information to the clipboard. This form is typically used as a modal dialog within an application to facilitate file retrieval from a database.</remarks>
partial class DatabaseDownloaderForm
	{
	/// <summary>Required designer variable.</summary>
	/// <remarks>This field stores the components used by the form.</remarks>
	private System.ComponentModel.IContainer components = null;

	/// <summary>Clean up any resources being used.</summary>
	/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
	/// <remarks>This method is called by the runtime to release resources used by the form.</remarks>
	protected override void Dispose(bool disposing)
	{
		if (disposing && (components != null))
			components.Dispose();
		base.Dispose(disposing);
	}

	/// <summary>Required method for Designer support - do not modify the contents of this method with the code editor.</summary>
	/// <remarks>This method is automatically generated by the Windows Forms designer and should not be modified manually. It sets up the controls and their properties for the form.</remarks>
	private void InitializeComponent()
	{
		components = new System.ComponentModel.Container();
		System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(DatabaseDownloaderForm));
		kryptonManager = new Krypton.Toolkit.KryptonManager(components);
		tableLayoutPanel = new Krypton.Toolkit.KryptonTableLayoutPanel();
		labelStatusText = new Krypton.Toolkit.KryptonLabel();
		labelSizeValue = new Krypton.Toolkit.KryptonLabel();
		contextMenuCopyToClipboard = new ContextMenuStrip(components);
		toolStripMenuItemCopyToClipboard = new ToolStripMenuItem();
		labelSizeText = new Krypton.Toolkit.KryptonLabel();
		labelDateValue = new Krypton.Toolkit.KryptonLabel();
		labelSourceValue = new Krypton.Toolkit.KryptonLabel();
		labelDateText = new Krypton.Toolkit.KryptonLabel();
		labelSourceText = new Krypton.Toolkit.KryptonLabel();
		labelStatusValue = new Krypton.Toolkit.KryptonLabel();
		labelDownloadSpeed = new Krypton.Toolkit.KryptonLabel();
		labelDownloadSpeedValue = new Krypton.Toolkit.KryptonLabel();
		labelTimeValue = new Krypton.Toolkit.KryptonLabel();
		labelTime = new Krypton.Toolkit.KryptonLabel();
		kryptonStatusStrip = new Krypton.Toolkit.KryptonStatusStrip();
		labelInformation = new ToolStripStatusLabel();
		kryptoPanelMain = new Krypton.Toolkit.KryptonPanel();
		toolStripContainer = new ToolStripContainer();
		kryptonToolStripIcons = new Krypton.Toolkit.KryptonToolStrip();
		toolStripButtonDownload = new ToolStripButton();
		toolStripButtonCancel = new ToolStripButton();
		toolStripSeparator = new ToolStripSeparator();
		toolStripLabelProgress = new ToolStripLabel();
		kryptonProgressBarDownload = new Krypton.Toolkit.KryptonProgressBarToolStripItem();
		contextMenuSaveToFile = new ContextMenuStrip(components);
		toolStripMenuItemTextFiles = new ToolStripMenuItem();
		toolStripMenuItemSaveAsText = new ToolStripMenuItem();
		toolStripMenuItemSaveAsLatex = new ToolStripMenuItem();
		toolStripMenuItemSaveAsMarkdown = new ToolStripMenuItem();
		toolStripMenuItemSaveAsAsciiDoc = new ToolStripMenuItem();
		toolStripMenuItemSaveAsReStructuredText = new ToolStripMenuItem();
		toolStripMenuItemSaveAsTextile = new ToolStripMenuItem();
		toolStripMenuItemSaveAsTypst = new ToolStripMenuItem();
		toolStripMenuItemWriterDocuments = new ToolStripMenuItem();
		toolStripMenuItemSaveAsWord = new ToolStripMenuItem();
		toolStripMenuItemSaveAsOdt = new ToolStripMenuItem();
		toolStripMenuItemSaveAsRtf = new ToolStripMenuItem();
		toolStripMenuItemSaveAsAbiword = new ToolStripMenuItem();
		toolStripMenuItemSaveAsWps = new ToolStripMenuItem();
		toolStripMenuItemSpreadsheetDocuments = new ToolStripMenuItem();
		toolStripMenuItemSaveAsExcel = new ToolStripMenuItem();
		toolStripMenuItemSaveAsOds = new ToolStripMenuItem();
		toolStripMenuItemSaveAsCsv = new ToolStripMenuItem();
		toolStripMenuItemSaveAsTsv = new ToolStripMenuItem();
		toolStripMenuItemSaveAsPsv = new ToolStripMenuItem();
		toolStripMenuItemSaveAsEt = new ToolStripMenuItem();
		toolStripMenuItemXmlDocuments = new ToolStripMenuItem();
		toolStripMenuItemSaveAsHtml = new ToolStripMenuItem();
		toolStripMenuItemSaveAsXml = new ToolStripMenuItem();
		toolStripMenuItemSaveAsDocBook = new ToolStripMenuItem();
		toolStripMenuItemConfigurationFiles = new ToolStripMenuItem();
		toolStripMenuItemSaveAsJson = new ToolStripMenuItem();
		toolStripMenuItemSaveAsYaml = new ToolStripMenuItem();
		toolStripMenuItemSaveAsToml = new ToolStripMenuItem();
		toolStripMenuItemDatabaseScripts = new ToolStripMenuItem();
		toolStripMenuItemSaveAsSql = new ToolStripMenuItem();
		toolStripMenuItemSaveAsSqlite = new ToolStripMenuItem();
		toolStripMenuItemPortableDocuments = new ToolStripMenuItem();
		toolStripMenuItemSaveAsPdf = new ToolStripMenuItem();
		toolStripMenuItemSaveAsPostScript = new ToolStripMenuItem();
		toolStripMenuItemSaveAsEpub = new ToolStripMenuItem();
		toolStripMenuItemSaveAsMobi = new ToolStripMenuItem();
		toolStripMenuItemSaveAsXps = new ToolStripMenuItem();
		toolStripMenuItemSaveAsFictionBook2 = new ToolStripMenuItem();
		toolStripMenuItemSaveAsChm = new ToolStripMenuItem();
		tableLayoutPanel.SuspendLayout();
		contextMenuCopyToClipboard.SuspendLayout();
		kryptonStatusStrip.SuspendLayout();
		((System.ComponentModel.ISupportInitialize)kryptoPanelMain).BeginInit();
		kryptoPanelMain.SuspendLayout();
		toolStripContainer.BottomToolStripPanel.SuspendLayout();
		toolStripContainer.ContentPanel.SuspendLayout();
		toolStripContainer.TopToolStripPanel.SuspendLayout();
		toolStripContainer.SuspendLayout();
		kryptonToolStripIcons.SuspendLayout();
		contextMenuSaveToFile.SuspendLayout();
		SuspendLayout();
		// 
		// kryptonManager
		// 
		kryptonManager.GlobalPaletteMode = Krypton.Toolkit.PaletteMode.Global;
		kryptonManager.ToolkitStrings.MessageBoxStrings.LessDetails = "L&ess Details...";
		kryptonManager.ToolkitStrings.MessageBoxStrings.MoreDetails = "&More Details...";
		// 
		// tableLayoutPanel
		// 
		tableLayoutPanel.AccessibleDescription = "Groups the data";
		tableLayoutPanel.AccessibleName = "Information";
		tableLayoutPanel.AccessibleRole = AccessibleRole.Pane;
		tableLayoutPanel.ColumnCount = 2;
		tableLayoutPanel.ColumnStyles.Add(new ColumnStyle());
		tableLayoutPanel.ColumnStyles.Add(new ColumnStyle());
		tableLayoutPanel.ContextMenuStrip = contextMenuSaveToFile;
		tableLayoutPanel.Controls.Add(labelStatusText, 0, 0);
		tableLayoutPanel.Controls.Add(labelSizeValue, 1, 3);
		tableLayoutPanel.Controls.Add(labelSizeText, 0, 3);
		tableLayoutPanel.Controls.Add(labelDateValue, 1, 1);
		tableLayoutPanel.Controls.Add(labelSourceValue, 1, 2);
		tableLayoutPanel.Controls.Add(labelDateText, 0, 1);
		tableLayoutPanel.Controls.Add(labelSourceText, 0, 2);
		tableLayoutPanel.Controls.Add(labelStatusValue, 1, 0);
		tableLayoutPanel.Controls.Add(labelDownloadSpeed, 0, 6);
		tableLayoutPanel.Controls.Add(labelDownloadSpeedValue, 1, 6);
		tableLayoutPanel.Controls.Add(labelTimeValue, 1, 5);
		tableLayoutPanel.Controls.Add(labelTime, 0, 5);
		tableLayoutPanel.Dock = DockStyle.Fill;
		tableLayoutPanel.Location = new Point(0, 0);
		tableLayoutPanel.Name = "tableLayoutPanel";
		tableLayoutPanel.PanelBackStyle = Krypton.Toolkit.PaletteBackStyle.FormMain;
		tableLayoutPanel.RowCount = 7;
		tableLayoutPanel.RowStyles.Add(new RowStyle());
		tableLayoutPanel.RowStyles.Add(new RowStyle());
		tableLayoutPanel.RowStyles.Add(new RowStyle());
		tableLayoutPanel.RowStyles.Add(new RowStyle());
		tableLayoutPanel.RowStyles.Add(new RowStyle());
		tableLayoutPanel.RowStyles.Add(new RowStyle());
		tableLayoutPanel.RowStyles.Add(new RowStyle());
		tableLayoutPanel.Size = new Size(581, 166);
		tableLayoutPanel.TabIndex = 0;
		tableLayoutPanel.Enter += Control_Enter;
		tableLayoutPanel.Leave += Control_Leave;
		tableLayoutPanel.MouseEnter += Control_Enter;
		tableLayoutPanel.MouseLeave += Control_Leave;
		// 
		// labelStatusText
		// 
		labelStatusText.AccessibleDescription = "Status of the download";
		labelStatusText.AccessibleName = "Status";
		labelStatusText.AccessibleRole = AccessibleRole.Text;
		labelStatusText.Dock = DockStyle.Fill;
		labelStatusText.Location = new Point(3, 3);
		labelStatusText.Name = "labelStatusText";
		labelStatusText.Size = new Size(105, 20);
		labelStatusText.TabIndex = 0;
		labelStatusText.ToolTipValues.Description = "Status of the download.\r\nDouble-click or right-click to copy the information to the clipboard.";
		labelStatusText.ToolTipValues.EnableToolTips = true;
		labelStatusText.ToolTipValues.Heading = "Status";
		labelStatusText.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelStatusText.Values.Text = "&Status:";
		labelStatusText.DoubleClick += CopyToClipboard_DoubleClick;
		labelStatusText.Enter += Control_Enter;
		labelStatusText.Leave += Control_Leave;
		labelStatusText.MouseEnter += Control_Enter;
		labelStatusText.MouseLeave += Control_Leave;
		// 
		// labelSizeValue
		// 
		labelSizeValue.AccessibleDescription = "Shows the file size of the download";
		labelSizeValue.AccessibleName = "Size of the dowload file";
		labelSizeValue.AccessibleRole = AccessibleRole.Text;
		labelSizeValue.ContextMenuStrip = contextMenuCopyToClipboard;
		labelSizeValue.Dock = DockStyle.Fill;
		labelSizeValue.Location = new Point(114, 81);
		labelSizeValue.Name = "labelSizeValue";
		labelSizeValue.Size = new Size(464, 22);
		labelSizeValue.TabIndex = 7;
		labelSizeValue.ToolTipValues.Description = "Shows the file size of the download.\r\nDouble-click or right-click to copy the information to the clipboard.";
		labelSizeValue.ToolTipValues.EnableToolTips = true;
		labelSizeValue.ToolTipValues.Heading = "Size of the dowload file";
		labelSizeValue.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelSizeValue.Values.Text = "...";
		labelSizeValue.DoubleClick += CopyToClipboard_DoubleClick;
		labelSizeValue.Enter += Control_Enter;
		labelSizeValue.Leave += Control_Leave;
		labelSizeValue.MouseDown += Control_MouseDown;
		labelSizeValue.MouseEnter += Control_Enter;
		labelSizeValue.MouseLeave += Control_Leave;
		// 
		// contextMenuCopyToClipboard
		// 
		contextMenuCopyToClipboard.AccessibleDescription = "Shows the context menu for copying information to the clipboard";
		contextMenuCopyToClipboard.AccessibleName = "Context menu for copying database information to the clipboard";
		contextMenuCopyToClipboard.AccessibleRole = AccessibleRole.MenuPopup;
		contextMenuCopyToClipboard.AllowClickThrough = true;
		contextMenuCopyToClipboard.Font = new Font("Segoe UI", 9F);
		contextMenuCopyToClipboard.Items.AddRange(new ToolStripItem[] { toolStripMenuItemCopyToClipboard });
		contextMenuCopyToClipboard.Name = "contextMenuStrip";
		contextMenuCopyToClipboard.Size = new Size(214, 26);
		contextMenuCopyToClipboard.TabStop = true;
		contextMenuCopyToClipboard.Text = "Copy to clipboard";
		contextMenuCopyToClipboard.MouseEnter += Control_Enter;
		contextMenuCopyToClipboard.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemCopyToClipboard
		// 
		toolStripMenuItemCopyToClipboard.AccessibleDescription = "Copies the text/value to the clipboard";
		toolStripMenuItemCopyToClipboard.AccessibleName = "Copy to clipboard";
		toolStripMenuItemCopyToClipboard.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemCopyToClipboard.AutoToolTip = true;
		toolStripMenuItemCopyToClipboard.Image = FatcowIcons16px.fatcow_page_copy_16px;
		toolStripMenuItemCopyToClipboard.Name = "toolStripMenuItemCopyToClipboard";
		toolStripMenuItemCopyToClipboard.ShortcutKeyDisplayString = "Strg+C";
		toolStripMenuItemCopyToClipboard.ShortcutKeys = Keys.Control | Keys.C;
		toolStripMenuItemCopyToClipboard.Size = new Size(213, 22);
		toolStripMenuItemCopyToClipboard.Text = "&Copy to clipboard";
		toolStripMenuItemCopyToClipboard.Click += CopyToClipboard_DoubleClick;
		toolStripMenuItemCopyToClipboard.MouseEnter += Control_Enter;
		toolStripMenuItemCopyToClipboard.MouseLeave += Control_Leave;
		// 
		// labelSizeText
		// 
		labelSizeText.AccessibleDescription = "Shows the file size of the download";
		labelSizeText.AccessibleName = "Size";
		labelSizeText.AccessibleRole = AccessibleRole.Text;
		labelSizeText.Dock = DockStyle.Fill;
		labelSizeText.Location = new Point(3, 81);
		labelSizeText.Name = "labelSizeText";
		labelSizeText.Size = new Size(105, 22);
		labelSizeText.TabIndex = 6;
		labelSizeText.ToolTipValues.Description = "Shows the file size of the download.\r\nDouble-click or right-click to copy the information to the clipboard.";
		labelSizeText.ToolTipValues.EnableToolTips = true;
		labelSizeText.ToolTipValues.Heading = "Size";
		labelSizeText.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelSizeText.Values.Text = "Si&ze:";
		labelSizeText.DoubleClick += CopyToClipboard_DoubleClick;
		labelSizeText.Enter += Control_Enter;
		labelSizeText.Leave += Control_Leave;
		labelSizeText.MouseEnter += Control_Enter;
		labelSizeText.MouseLeave += Control_Leave;
		// 
		// labelDateValue
		// 
		labelDateValue.AccessibleDescription = "Shows the last modified date of the download file";
		labelDateValue.AccessibleName = "Date of the download file";
		labelDateValue.AccessibleRole = AccessibleRole.Text;
		labelDateValue.ContextMenuStrip = contextMenuCopyToClipboard;
		labelDateValue.Dock = DockStyle.Fill;
		labelDateValue.Location = new Point(114, 29);
		labelDateValue.Name = "labelDateValue";
		labelDateValue.Size = new Size(464, 20);
		labelDateValue.TabIndex = 3;
		labelDateValue.ToolTipValues.Description = "Shows the last modified date of the download.\r\nDouble-click or right-click to copy the information to the clipboard.";
		labelDateValue.ToolTipValues.EnableToolTips = true;
		labelDateValue.ToolTipValues.Heading = "Date of the download file";
		labelDateValue.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelDateValue.Values.Text = "...";
		labelDateValue.DoubleClick += CopyToClipboard_DoubleClick;
		labelDateValue.Enter += Control_Enter;
		labelDateValue.Leave += Control_Leave;
		labelDateValue.MouseDown += Control_MouseDown;
		labelDateValue.MouseEnter += Control_Enter;
		labelDateValue.MouseLeave += Control_Leave;
		// 
		// labelSourceValue
		// 
		labelSourceValue.AccessibleDescription = "Shows the download source";
		labelSourceValue.AccessibleName = "Source of the download";
		labelSourceValue.AccessibleRole = AccessibleRole.Text;
		labelSourceValue.ContextMenuStrip = contextMenuCopyToClipboard;
		labelSourceValue.Dock = DockStyle.Fill;
		labelSourceValue.Location = new Point(114, 55);
		labelSourceValue.Name = "labelSourceValue";
		labelSourceValue.Size = new Size(464, 20);
		labelSourceValue.TabIndex = 5;
		labelSourceValue.ToolTipValues.Description = "Shows the download source.\r\nDouble-click or right-click to copy the information to the clipboard.";
		labelSourceValue.ToolTipValues.EnableToolTips = true;
		labelSourceValue.ToolTipValues.Heading = "Source of the download";
		labelSourceValue.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelSourceValue.Values.Text = "...";
		labelSourceValue.DoubleClick += CopyToClipboard_DoubleClick;
		labelSourceValue.Enter += Control_Enter;
		labelSourceValue.Leave += Control_Leave;
		labelSourceValue.MouseDown += Control_MouseDown;
		labelSourceValue.MouseEnter += Control_Enter;
		labelSourceValue.MouseLeave += Control_Leave;
		// 
		// labelDateText
		// 
		labelDateText.AccessibleDescription = "Date of the download file";
		labelDateText.AccessibleName = "Date";
		labelDateText.AccessibleRole = AccessibleRole.Text;
		labelDateText.Dock = DockStyle.Fill;
		labelDateText.Location = new Point(3, 29);
		labelDateText.Name = "labelDateText";
		labelDateText.Size = new Size(105, 20);
		labelDateText.TabIndex = 2;
		labelDateText.ToolTipValues.Description = "Date of the download file.\r\nDouble-click or right-click to copy the information to the clipboard.";
		labelDateText.ToolTipValues.EnableToolTips = true;
		labelDateText.ToolTipValues.Heading = "Date";
		labelDateText.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelDateText.Values.Text = "&Date:";
		labelDateText.DoubleClick += CopyToClipboard_DoubleClick;
		labelDateText.Enter += Control_Enter;
		labelDateText.Leave += Control_Leave;
		labelDateText.MouseEnter += Control_Enter;
		labelDateText.MouseLeave += Control_Leave;
		// 
		// labelSourceText
		// 
		labelSourceText.AccessibleDescription = "Shows the download source";
		labelSourceText.AccessibleName = "Source";
		labelSourceText.AccessibleRole = AccessibleRole.Text;
		labelSourceText.Dock = DockStyle.Fill;
		labelSourceText.Location = new Point(3, 55);
		labelSourceText.Name = "labelSourceText";
		labelSourceText.Size = new Size(105, 20);
		labelSourceText.TabIndex = 4;
		labelSourceText.ToolTipValues.Description = "Shows the download source.\r\nDouble-click or right-click to copy the information to the clipboard.";
		labelSourceText.ToolTipValues.EnableToolTips = true;
		labelSourceText.ToolTipValues.Heading = "Source";
		labelSourceText.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelSourceText.Values.Text = "Sour&ce:";
		labelSourceText.DoubleClick += CopyToClipboard_DoubleClick;
		labelSourceText.Enter += Control_Enter;
		labelSourceText.Leave += Control_Leave;
		labelSourceText.MouseEnter += Control_Enter;
		labelSourceText.MouseLeave += Control_Leave;
		// 
		// labelStatusValue
		// 
		labelStatusValue.AccessibleDescription = "Shows the status of the download";
		labelStatusValue.AccessibleName = "Status of the download";
		labelStatusValue.AccessibleRole = AccessibleRole.Text;
		labelStatusValue.ContextMenuStrip = contextMenuCopyToClipboard;
		labelStatusValue.Dock = DockStyle.Fill;
		labelStatusValue.Location = new Point(114, 3);
		labelStatusValue.Name = "labelStatusValue";
		labelStatusValue.Size = new Size(464, 20);
		labelStatusValue.TabIndex = 1;
		labelStatusValue.ToolTipValues.Description = "Shows the status of the download.\r\nDouble-click or right-click to copy the information to the clipboard.";
		labelStatusValue.ToolTipValues.EnableToolTips = true;
		labelStatusValue.ToolTipValues.Heading = "Status of the download";
		labelStatusValue.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelStatusValue.Values.Text = "...";
		labelStatusValue.DoubleClick += CopyToClipboard_DoubleClick;
		labelStatusValue.Enter += Control_Enter;
		labelStatusValue.Leave += Control_Leave;
		labelStatusValue.MouseDown += Control_MouseDown;
		labelStatusValue.MouseEnter += Control_Enter;
		labelStatusValue.MouseLeave += Control_Leave;
		// 
		// labelDownloadSpeed
		// 
		labelDownloadSpeed.AccessibleDescription = "Shows the download speed";
		labelDownloadSpeed.AccessibleName = "Download speed";
		labelDownloadSpeed.AccessibleRole = AccessibleRole.Text;
		labelDownloadSpeed.Dock = DockStyle.Fill;
		labelDownloadSpeed.Location = new Point(3, 140);
		labelDownloadSpeed.Name = "labelDownloadSpeed";
		labelDownloadSpeed.Size = new Size(105, 24);
		labelDownloadSpeed.TabIndex = 10;
		labelDownloadSpeed.ToolTipValues.Description = "Shows the download speed.\r\nDouble-click or right-click to copy the information to the clipboard.";
		labelDownloadSpeed.ToolTipValues.EnableToolTips = true;
		labelDownloadSpeed.ToolTipValues.Heading = "Download speed";
		labelDownloadSpeed.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelDownloadSpeed.Values.Text = "Download s&peed:";
		labelDownloadSpeed.DoubleClick += CopyToClipboard_DoubleClick;
		labelDownloadSpeed.Enter += Control_Enter;
		labelDownloadSpeed.Leave += Control_Leave;
		labelDownloadSpeed.MouseEnter += Control_Enter;
		labelDownloadSpeed.MouseLeave += Control_Leave;
		// 
		// labelDownloadSpeedValue
		// 
		labelDownloadSpeedValue.AccessibleDescription = "Shows the download speed";
		labelDownloadSpeedValue.AccessibleName = "Download speed value";
		labelDownloadSpeedValue.AccessibleRole = AccessibleRole.Text;
		labelDownloadSpeedValue.ContextMenuStrip = contextMenuCopyToClipboard;
		labelDownloadSpeedValue.Dock = DockStyle.Fill;
		labelDownloadSpeedValue.Location = new Point(114, 140);
		labelDownloadSpeedValue.Name = "labelDownloadSpeedValue";
		labelDownloadSpeedValue.Size = new Size(464, 24);
		labelDownloadSpeedValue.TabIndex = 11;
		labelDownloadSpeedValue.ToolTipValues.Description = "Shows the download speed.\r\nDouble-click or right-click to copy the information to the clipboard.";
		labelDownloadSpeedValue.ToolTipValues.EnableToolTips = true;
		labelDownloadSpeedValue.ToolTipValues.Heading = "Download speed value";
		labelDownloadSpeedValue.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelDownloadSpeedValue.Values.Text = "...";
		labelDownloadSpeedValue.DoubleClick += CopyToClipboard_DoubleClick;
		labelDownloadSpeedValue.Enter += Control_Enter;
		labelDownloadSpeedValue.Leave += Control_Leave;
		labelDownloadSpeedValue.MouseDown += Control_MouseDown;
		labelDownloadSpeedValue.MouseEnter += Control_Enter;
		labelDownloadSpeedValue.MouseLeave += Control_Leave;
		// 
		// labelTimeValue
		// 
		labelTimeValue.AccessibleDescription = "Shows the elapsed time and estimated time of the download";
		labelTimeValue.AccessibleName = "Time value";
		labelTimeValue.AccessibleRole = AccessibleRole.Text;
		labelTimeValue.ContextMenuStrip = contextMenuCopyToClipboard;
		labelTimeValue.Dock = DockStyle.Fill;
		labelTimeValue.Location = new Point(114, 109);
		labelTimeValue.Name = "labelTimeValue";
		labelTimeValue.Size = new Size(464, 25);
		labelTimeValue.TabIndex = 9;
		labelTimeValue.ToolTipValues.Description = "Shows the elapsed time and estimated time of the download.\r\nDouble-click or right-click to copy the information to the clipboard.";
		labelTimeValue.ToolTipValues.EnableToolTips = true;
		labelTimeValue.ToolTipValues.Heading = "Time value";
		labelTimeValue.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelTimeValue.Values.Text = "...";
		labelTimeValue.DoubleClick += CopyToClipboard_DoubleClick;
		labelTimeValue.Enter += Control_Enter;
		labelTimeValue.Leave += Control_Leave;
		labelTimeValue.MouseDown += Control_MouseDown;
		labelTimeValue.MouseEnter += Control_Enter;
		labelTimeValue.MouseLeave += Control_Leave;
		// 
		// labelTime
		// 
		labelTime.AccessibleDescription = "Shows the elapsed time and estimated time of the download";
		labelTime.AccessibleName = "Time";
		labelTime.AccessibleRole = AccessibleRole.Text;
		labelTime.Dock = DockStyle.Fill;
		labelTime.Location = new Point(3, 109);
		labelTime.Name = "labelTime";
		labelTime.Size = new Size(105, 25);
		labelTime.TabIndex = 8;
		labelTime.ToolTipValues.Description = "Shows the elapsed time and estimated time of the download.\r\nDouble-click or right-click to copy the information to the clipboard.";
		labelTime.ToolTipValues.EnableToolTips = true;
		labelTime.ToolTipValues.Heading = "Time";
		labelTime.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelTime.Values.Text = "&Time (estimated):";
		labelTime.DoubleClick += CopyToClipboard_DoubleClick;
		labelTime.Enter += Control_Enter;
		labelTime.Leave += Control_Leave;
		labelTime.MouseEnter += Control_Enter;
		labelTime.MouseLeave += Control_Leave;
		// 
		// kryptonStatusStrip
		// 
		kryptonStatusStrip.AccessibleDescription = "Shows some information";
		kryptonStatusStrip.AccessibleName = "Status bar with some information";
		kryptonStatusStrip.AccessibleRole = AccessibleRole.StatusBar;
		kryptonStatusStrip.AllowClickThrough = true;
		kryptonStatusStrip.AllowDrop = true;
		kryptonStatusStrip.Dock = DockStyle.None;
		kryptonStatusStrip.Font = new Font("Segoe UI", 9F);
		kryptonStatusStrip.Items.AddRange(new ToolStripItem[] { labelInformation });
		kryptonStatusStrip.Location = new Point(0, 0);
		kryptonStatusStrip.Name = "kryptonStatusStrip";
		kryptonStatusStrip.ProgressBars = null;
		kryptonStatusStrip.RenderMode = ToolStripRenderMode.ManagerRenderMode;
		kryptonStatusStrip.ShowItemToolTips = true;
		kryptonStatusStrip.Size = new Size(581, 22);
		kryptonStatusStrip.SizingGrip = false;
		kryptonStatusStrip.TabIndex = 0;
		kryptonStatusStrip.TabStop = true;
		kryptonStatusStrip.Text = "Status bar";
		// 
		// labelInformation
		// 
		labelInformation.AccessibleDescription = "Shows some information";
		labelInformation.AccessibleName = "Shows some information";
		labelInformation.AccessibleRole = AccessibleRole.StaticText;
		labelInformation.AutoToolTip = true;
		labelInformation.Image = FatcowIcons16px.fatcow_lightbulb_16px;
		labelInformation.Name = "labelInformation";
		labelInformation.Size = new Size(144, 17);
		labelInformation.Text = "some information here";
		labelInformation.ToolTipText = "Shows some information";
		// 
		// kryptoPanelMain
		// 
		kryptoPanelMain.AccessibleDescription = "Groups the data";
		kryptoPanelMain.AccessibleName = "Panel";
		kryptoPanelMain.AccessibleRole = AccessibleRole.Pane;
		kryptoPanelMain.Controls.Add(tableLayoutPanel);
		kryptoPanelMain.Dock = DockStyle.Fill;
		kryptoPanelMain.Location = new Point(0, 0);
		kryptoPanelMain.Name = "kryptoPanelMain";
		kryptoPanelMain.PanelBackStyle = Krypton.Toolkit.PaletteBackStyle.FormMain;
		kryptoPanelMain.Size = new Size(581, 166);
		kryptoPanelMain.TabIndex = 9;
		kryptoPanelMain.TabStop = true;
		// 
		// toolStripContainer
		// 
		toolStripContainer.AccessibleDescription = "Container";
		toolStripContainer.AccessibleName = "Container";
		toolStripContainer.AccessibleRole = AccessibleRole.Pane;
		// 
		// toolStripContainer.BottomToolStripPanel
		// 
		toolStripContainer.BottomToolStripPanel.AccessibleDescription = "Just a panel";
		toolStripContainer.BottomToolStripPanel.AccessibleName = "Bottom panel";
		toolStripContainer.BottomToolStripPanel.AccessibleRole = AccessibleRole.Pane;
		toolStripContainer.BottomToolStripPanel.Controls.Add(kryptonStatusStrip);
		// 
		// toolStripContainer.ContentPanel
		// 
		toolStripContainer.ContentPanel.AccessibleDescription = "Just a panel";
		toolStripContainer.ContentPanel.AccessibleName = "Content panel";
		toolStripContainer.ContentPanel.AccessibleRole = AccessibleRole.Pane;
		toolStripContainer.ContentPanel.Controls.Add(kryptoPanelMain);
		toolStripContainer.ContentPanel.Size = new Size(581, 166);
		toolStripContainer.Dock = DockStyle.Fill;
		// 
		// toolStripContainer.LeftToolStripPanel
		// 
		toolStripContainer.LeftToolStripPanel.AccessibleDescription = "Just a panel";
		toolStripContainer.LeftToolStripPanel.AccessibleName = "Left panel";
		toolStripContainer.LeftToolStripPanel.AccessibleRole = AccessibleRole.Pane;
		toolStripContainer.Location = new Point(0, 0);
		toolStripContainer.Name = "toolStripContainer";
		// 
		// toolStripContainer.RightToolStripPanel
		// 
		toolStripContainer.RightToolStripPanel.AccessibleDescription = "Just a panel";
		toolStripContainer.RightToolStripPanel.AccessibleName = "Right panel";
		toolStripContainer.RightToolStripPanel.AccessibleRole = AccessibleRole.Pane;
		toolStripContainer.Size = new Size(581, 213);
		toolStripContainer.TabIndex = 11;
		toolStripContainer.Text = "toolStripContainer";
		// 
		// toolStripContainer.TopToolStripPanel
		// 
		toolStripContainer.TopToolStripPanel.AccessibleDescription = "Just a panel";
		toolStripContainer.TopToolStripPanel.AccessibleName = "Top panel";
		toolStripContainer.TopToolStripPanel.AccessibleRole = AccessibleRole.Pane;
		toolStripContainer.TopToolStripPanel.Controls.Add(kryptonToolStripIcons);
		// 
		// kryptonToolStripIcons
		// 
		kryptonToolStripIcons.AllowClickThrough = true;
		kryptonToolStripIcons.AllowItemReorder = true;
		kryptonToolStripIcons.Dock = DockStyle.None;
		kryptonToolStripIcons.Font = new Font("Segoe UI", 9F);
		kryptonToolStripIcons.Items.AddRange(new ToolStripItem[] { toolStripButtonDownload, toolStripButtonCancel, toolStripSeparator, toolStripLabelProgress, kryptonProgressBarDownload });
		kryptonToolStripIcons.Location = new Point(0, 0);
		kryptonToolStripIcons.Name = "kryptonToolStripIcons";
		kryptonToolStripIcons.Size = new Size(581, 25);
		kryptonToolStripIcons.Stretch = true;
		kryptonToolStripIcons.TabIndex = 0;
		kryptonToolStripIcons.TabStop = true;
		// 
		// toolStripButtonDownload
		// 
		toolStripButtonDownload.AccessibleDescription = "Downloads the selected file";
		toolStripButtonDownload.AccessibleName = "Download";
		toolStripButtonDownload.AccessibleRole = AccessibleRole.PushButton;
		toolStripButtonDownload.Image = FatcowIcons16px.fatcow_package_go_16px;
		toolStripButtonDownload.ImageTransparentColor = Color.Magenta;
		toolStripButtonDownload.Name = "toolStripButtonDownload";
		toolStripButtonDownload.Size = new Size(81, 22);
		toolStripButtonDownload.Text = "&Download";
		toolStripButtonDownload.Click += ButtonDownload_Click;
		toolStripButtonDownload.MouseEnter += Control_Enter;
		toolStripButtonDownload.MouseLeave += Control_Leave;
		// 
		// toolStripButtonCancel
		// 
		toolStripButtonCancel.AccessibleDescription = "Cancels the download";
		toolStripButtonCancel.AccessibleName = "Cancel download";
		toolStripButtonCancel.AccessibleRole = AccessibleRole.PushButton;
		toolStripButtonCancel.Image = FatcowIcons16px.fatcow_cancel_16px;
		toolStripButtonCancel.ImageTransparentColor = Color.Magenta;
		toolStripButtonCancel.Name = "toolStripButtonCancel";
		toolStripButtonCancel.Size = new Size(119, 22);
		toolStripButtonCancel.Text = "&Cancel download";
		toolStripButtonCancel.Click += ButtonCancel_Click;
		toolStripButtonCancel.MouseEnter += Control_Enter;
		toolStripButtonCancel.MouseLeave += Control_Leave;
		// 
		// toolStripSeparator
		// 
		toolStripSeparator.AccessibleDescription = "Just a separator";
		toolStripSeparator.AccessibleName = "Just a separator";
		toolStripSeparator.AccessibleRole = AccessibleRole.Separator;
		toolStripSeparator.Name = "toolStripSeparator";
		toolStripSeparator.Size = new Size(6, 25);
		// 
		// toolStripLabelProgress
		// 
		toolStripLabelProgress.AccessibleDescription = "Shows the progress of the download";
		toolStripLabelProgress.AccessibleName = "Progress";
		toolStripLabelProgress.AccessibleRole = AccessibleRole.StaticText;
		toolStripLabelProgress.AutoToolTip = true;
		toolStripLabelProgress.Name = "toolStripLabelProgress";
		toolStripLabelProgress.Size = new Size(52, 22);
		toolStripLabelProgress.Text = "&Progress";
		toolStripLabelProgress.MouseEnter += Control_Enter;
		toolStripLabelProgress.MouseLeave += Control_Leave;
		// 
		// kryptonProgressBarDownload
		// 
		kryptonProgressBarDownload.AccessibleDescription = "Shows the progress of the download";
		kryptonProgressBarDownload.AccessibleName = "ProgressBar";
		kryptonProgressBarDownload.Name = "kryptonProgressBarDownload";
		kryptonProgressBarDownload.Size = new Size(290, 22);
		kryptonProgressBarDownload.StateCommon.Back.Color1 = Color.Green;
		kryptonProgressBarDownload.StateDisabled.Back.ColorStyle = Krypton.Toolkit.PaletteColorStyle.OneNote;
		kryptonProgressBarDownload.StateNormal.Back.ColorStyle = Krypton.Toolkit.PaletteColorStyle.OneNote;
		kryptonProgressBarDownload.Values.Text = "";
		// 
		// contextMenuSaveToFile
		// 
		contextMenuSaveToFile.AccessibleDescription = "Save the list as file";
		contextMenuSaveToFile.AccessibleName = "Save list";
		contextMenuSaveToFile.AccessibleRole = AccessibleRole.MenuPopup;
		contextMenuSaveToFile.AllowClickThrough = true;
		contextMenuSaveToFile.Font = new Font("Segoe UI", 9F);
		contextMenuSaveToFile.Items.AddRange(new ToolStripItem[] { toolStripMenuItemTextFiles, toolStripMenuItemWriterDocuments, toolStripMenuItemSpreadsheetDocuments, toolStripMenuItemXmlDocuments, toolStripMenuItemConfigurationFiles, toolStripMenuItemDatabaseScripts, toolStripMenuItemPortableDocuments });
		contextMenuSaveToFile.Name = "contextMenuSaveList";
		contextMenuSaveToFile.Size = new Size(202, 158);
		contextMenuSaveToFile.TabStop = true;
		contextMenuSaveToFile.Text = "&Save list";
		// 
		// toolStripMenuItemTextFiles
		// 
		toolStripMenuItemTextFiles.AccessibleDescription = "Saves the list as text file";
		toolStripMenuItemTextFiles.AccessibleName = "Save as text file";
		toolStripMenuItemTextFiles.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemTextFiles.AutoToolTip = true;
		toolStripMenuItemTextFiles.DropDownItems.AddRange(new ToolStripItem[] { toolStripMenuItemSaveAsText, toolStripMenuItemSaveAsLatex, toolStripMenuItemSaveAsMarkdown, toolStripMenuItemSaveAsAsciiDoc, toolStripMenuItemSaveAsReStructuredText, toolStripMenuItemSaveAsTextile, toolStripMenuItemSaveAsTypst });
		toolStripMenuItemTextFiles.Image = FatcowIcons16px.fatcow_file_extension_txt_16px;
		toolStripMenuItemTextFiles.Name = "toolStripMenuItemTextFiles";
		toolStripMenuItemTextFiles.Size = new Size(201, 22);
		toolStripMenuItemTextFiles.Text = "&Text files";
		// 
		// toolStripMenuItemSaveAsText
		// 
		toolStripMenuItemSaveAsText.AccessibleDescription = "Saves the list as text file";
		toolStripMenuItemSaveAsText.AccessibleName = "Save as text";
		toolStripMenuItemSaveAsText.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsText.AutoToolTip = true;
		toolStripMenuItemSaveAsText.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsText.Name = "toolStripMenuItemSaveAsText";
		toolStripMenuItemSaveAsText.Size = new Size(201, 22);
		toolStripMenuItemSaveAsText.Text = "Save as &text";
		toolStripMenuItemSaveAsText.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsText.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsText.Click += SaveAsText_Click;
		// 
		// toolStripMenuItemSaveAsLatex
		// 
		toolStripMenuItemSaveAsLatex.AccessibleDescription = "Saves the list as Latex file";
		toolStripMenuItemSaveAsLatex.AccessibleName = "Save as Latex";
		toolStripMenuItemSaveAsLatex.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsLatex.AutoToolTip = true;
		toolStripMenuItemSaveAsLatex.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsLatex.Name = "toolStripMenuItemSaveAsLatex";
		toolStripMenuItemSaveAsLatex.Size = new Size(201, 22);
		toolStripMenuItemSaveAsLatex.Text = "Save as &Latex";
		toolStripMenuItemSaveAsLatex.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsLatex.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsLatex.Click += SaveAsLatex_Click;
		// 
		// toolStripMenuItemSaveAsMarkdown
		// 
		toolStripMenuItemSaveAsMarkdown.AccessibleDescription = "Saves the list as Markdown file";
		toolStripMenuItemSaveAsMarkdown.AccessibleName = "Save as Markdown";
		toolStripMenuItemSaveAsMarkdown.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsMarkdown.AutoToolTip = true;
		toolStripMenuItemSaveAsMarkdown.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsMarkdown.Name = "toolStripMenuItemSaveAsMarkdown";
		toolStripMenuItemSaveAsMarkdown.Size = new Size(201, 22);
		toolStripMenuItemSaveAsMarkdown.Text = "Save as &Markdown";
		toolStripMenuItemSaveAsMarkdown.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsMarkdown.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsMarkdown.Click += SaveAsMarkdown_Click;
		// 
		// toolStripMenuItemSaveAsAsciiDoc
		// 
		toolStripMenuItemSaveAsAsciiDoc.AccessibleDescription = "Saves the list as AsciiDoc file";
		toolStripMenuItemSaveAsAsciiDoc.AccessibleName = "Save as AsciiDoc";
		toolStripMenuItemSaveAsAsciiDoc.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsAsciiDoc.AutoToolTip = true;
		toolStripMenuItemSaveAsAsciiDoc.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsAsciiDoc.Name = "toolStripMenuItemSaveAsAsciiDoc";
		toolStripMenuItemSaveAsAsciiDoc.Size = new Size(201, 22);
		toolStripMenuItemSaveAsAsciiDoc.Text = "Save as &AsciiDoc";
		toolStripMenuItemSaveAsAsciiDoc.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsAsciiDoc.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsAsciiDoc.Click += SaveAsAsciiDoc_Click;
		// 
		// toolStripMenuItemSaveAsReStructuredText
		// 
		toolStripMenuItemSaveAsReStructuredText.AccessibleDescription = "Saves the list as reStructuredText file";
		toolStripMenuItemSaveAsReStructuredText.AccessibleName = "Save as reStructuredText";
		toolStripMenuItemSaveAsReStructuredText.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsReStructuredText.AutoToolTip = true;
		toolStripMenuItemSaveAsReStructuredText.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsReStructuredText.Name = "toolStripMenuItemSaveAsReStructuredText";
		toolStripMenuItemSaveAsReStructuredText.Size = new Size(201, 22);
		toolStripMenuItemSaveAsReStructuredText.Text = "Save as &reStructuredText";
		toolStripMenuItemSaveAsReStructuredText.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsReStructuredText.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsReStructuredText.Click += SaveAsReStructuredText_Click;
		// 
		// toolStripMenuItemSaveAsTextile
		// 
		toolStripMenuItemSaveAsTextile.AccessibleDescription = "Saves the list as Textile file";
		toolStripMenuItemSaveAsTextile.AccessibleName = "Save as Textile";
		toolStripMenuItemSaveAsTextile.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsTextile.AutoToolTip = true;
		toolStripMenuItemSaveAsTextile.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsTextile.Name = "toolStripMenuItemSaveAsTextile";
		toolStripMenuItemSaveAsTextile.Size = new Size(201, 22);
		toolStripMenuItemSaveAsTextile.Text = "Save as Te&xtile";
		toolStripMenuItemSaveAsTextile.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsTextile.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsTextile.Click += SaveAsTextile_Click;
		// 
		// toolStripMenuItemSaveAsTypst
		// 
		toolStripMenuItemSaveAsTypst.AccessibleDescription = "Saves the list as Typst file";
		toolStripMenuItemSaveAsTypst.AccessibleName = "Save as Typst";
		toolStripMenuItemSaveAsTypst.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsTypst.AutoToolTip = true;
		toolStripMenuItemSaveAsTypst.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsTypst.Name = "toolStripMenuItemSaveAsTypst";
		toolStripMenuItemSaveAsTypst.Size = new Size(201, 22);
		toolStripMenuItemSaveAsTypst.Text = "Save as T&ypst";
		toolStripMenuItemSaveAsTypst.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsTypst.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsTypst.Click += SaveAsTypst_Click;
		// 
		// toolStripMenuItemWriterDocuments
		// 
		toolStripMenuItemWriterDocuments.AccessibleDescription = "Saves the list as writer document";
		toolStripMenuItemWriterDocuments.AccessibleName = "Save as writer document";
		toolStripMenuItemWriterDocuments.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemWriterDocuments.AutoToolTip = true;
		toolStripMenuItemWriterDocuments.DropDownItems.AddRange(new ToolStripItem[] { toolStripMenuItemSaveAsWord, toolStripMenuItemSaveAsOdt, toolStripMenuItemSaveAsRtf, toolStripMenuItemSaveAsAbiword, toolStripMenuItemSaveAsWps });
		toolStripMenuItemWriterDocuments.Image = FatcowIcons16px.fatcow_file_extension_doc_16px;
		toolStripMenuItemWriterDocuments.Name = "toolStripMenuItemWriterDocuments";
		toolStripMenuItemWriterDocuments.Size = new Size(201, 22);
		toolStripMenuItemWriterDocuments.Text = "&Writer documents";
		// 
		// toolStripMenuItemSaveAsWord
		// 
		toolStripMenuItemSaveAsWord.AccessibleDescription = "Saves the list as Word file";
		toolStripMenuItemSaveAsWord.AccessibleName = "Save as Word";
		toolStripMenuItemSaveAsWord.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsWord.AutoToolTip = true;
		toolStripMenuItemSaveAsWord.Image = FatcowIcons16px.fatcow_page_white_word_16px;
		toolStripMenuItemSaveAsWord.Name = "toolStripMenuItemSaveAsWord";
		toolStripMenuItemSaveAsWord.Size = new Size(257, 22);
		toolStripMenuItemSaveAsWord.Text = "Save as &Word Text (DOCX)";
		toolStripMenuItemSaveAsWord.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsWord.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsWord.Click += SaveAsWord_Click;
		// 
		// toolStripMenuItemSaveAsOdt
		// 
		toolStripMenuItemSaveAsOdt.AccessibleDescription = "Saves the list as ODT file";
		toolStripMenuItemSaveAsOdt.AccessibleName = "Save as ODT";
		toolStripMenuItemSaveAsOdt.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsOdt.AutoToolTip = true;
		toolStripMenuItemSaveAsOdt.Image = FatcowIcons16px.fatcow_page_white_word_16px;
		toolStripMenuItemSaveAsOdt.Name = "toolStripMenuItemSaveAsOdt";
		toolStripMenuItemSaveAsOdt.Size = new Size(257, 22);
		toolStripMenuItemSaveAsOdt.Text = "Save as &OpenDocument Text (ODT)";
		toolStripMenuItemSaveAsOdt.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsOdt.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsOdt.Click += SaveAsOdt_Click;
		// 
		// toolStripMenuItemSaveAsRtf
		// 
		toolStripMenuItemSaveAsRtf.AccessibleDescription = "Saves the list as RTF file";
		toolStripMenuItemSaveAsRtf.AccessibleName = "Save as RTF";
		toolStripMenuItemSaveAsRtf.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsRtf.AutoToolTip = true;
		toolStripMenuItemSaveAsRtf.Image = FatcowIcons16px.fatcow_page_white_word_16px;
		toolStripMenuItemSaveAsRtf.Name = "toolStripMenuItemSaveAsRtf";
		toolStripMenuItemSaveAsRtf.Size = new Size(257, 22);
		toolStripMenuItemSaveAsRtf.Text = "Save as &Rich Text Format (RTF)";
		toolStripMenuItemSaveAsRtf.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsRtf.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsRtf.Click += SaveAsRtf_Click;
		// 
		// toolStripMenuItemSaveAsAbiword
		// 
		toolStripMenuItemSaveAsAbiword.AccessibleDescription = "Saves the list as Abiword file";
		toolStripMenuItemSaveAsAbiword.AccessibleName = "Save as Abiword";
		toolStripMenuItemSaveAsAbiword.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsAbiword.AutoToolTip = true;
		toolStripMenuItemSaveAsAbiword.Image = FatcowIcons16px.fatcow_page_white_word_16px;
		toolStripMenuItemSaveAsAbiword.Name = "toolStripMenuItemSaveAsAbiword";
		toolStripMenuItemSaveAsAbiword.Size = new Size(257, 22);
		toolStripMenuItemSaveAsAbiword.Text = "Save as &Abiword file (ABW)";
		toolStripMenuItemSaveAsAbiword.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsAbiword.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsAbiword.Click += SaveAsAbiword_Click;
		// 
		// toolStripMenuItemSaveAsWps
		// 
		toolStripMenuItemSaveAsWps.AccessibleDescription = "Saves the list as WPS file";
		toolStripMenuItemSaveAsWps.AccessibleName = "Save as WPS";
		toolStripMenuItemSaveAsWps.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsWps.AutoToolTip = true;
		toolStripMenuItemSaveAsWps.Image = FatcowIcons16px.fatcow_page_white_word_16px;
		toolStripMenuItemSaveAsWps.Name = "toolStripMenuItemSaveAsWps";
		toolStripMenuItemSaveAsWps.Size = new Size(257, 22);
		toolStripMenuItemSaveAsWps.Text = "Save as W&PS Office Writer (WPS)";
		toolStripMenuItemSaveAsWps.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsWps.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsWps.Click += SaveAsWps_Click;
		// 
		// toolStripMenuItemSpreadsheetDocuments
		// 
		toolStripMenuItemSpreadsheetDocuments.AccessibleDescription = "Saves the list as spreadsheet document";
		toolStripMenuItemSpreadsheetDocuments.AccessibleName = "Save as spreadsheet document";
		toolStripMenuItemSpreadsheetDocuments.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSpreadsheetDocuments.AutoToolTip = true;
		toolStripMenuItemSpreadsheetDocuments.DropDownItems.AddRange(new ToolStripItem[] { toolStripMenuItemSaveAsExcel, toolStripMenuItemSaveAsOds, toolStripMenuItemSaveAsCsv, toolStripMenuItemSaveAsTsv, toolStripMenuItemSaveAsPsv, toolStripMenuItemSaveAsEt });
		toolStripMenuItemSpreadsheetDocuments.Image = FatcowIcons16px.fatcow_file_extension_xls_16px;
		toolStripMenuItemSpreadsheetDocuments.Name = "toolStripMenuItemSpreadsheetDocuments";
		toolStripMenuItemSpreadsheetDocuments.Size = new Size(201, 22);
		toolStripMenuItemSpreadsheetDocuments.Text = "&Spreadsheet documents";
		// 
		// toolStripMenuItemSaveAsExcel
		// 
		toolStripMenuItemSaveAsExcel.AccessibleDescription = "Saves the list as Excel file";
		toolStripMenuItemSaveAsExcel.AccessibleName = "Save as Excel";
		toolStripMenuItemSaveAsExcel.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsExcel.AutoToolTip = true;
		toolStripMenuItemSaveAsExcel.Image = FatcowIcons16px.fatcow_page_white_excel_16px;
		toolStripMenuItemSaveAsExcel.Name = "toolStripMenuItemSaveAsExcel";
		toolStripMenuItemSaveAsExcel.Size = new Size(301, 22);
		toolStripMenuItemSaveAsExcel.Text = "Save as &Excel Spreadsheet (XLSX)";
		toolStripMenuItemSaveAsExcel.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsExcel.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsExcel.Click += SaveAsExcel_Click;
		// 
		// toolStripMenuItemSaveAsOds
		// 
		toolStripMenuItemSaveAsOds.AccessibleDescription = "Saves the list as ODS file";
		toolStripMenuItemSaveAsOds.AccessibleName = "Save as ODS";
		toolStripMenuItemSaveAsOds.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsOds.AutoToolTip = true;
		toolStripMenuItemSaveAsOds.Image = FatcowIcons16px.fatcow_page_white_excel_16px;
		toolStripMenuItemSaveAsOds.Name = "toolStripMenuItemSaveAsOds";
		toolStripMenuItemSaveAsOds.Size = new Size(301, 22);
		toolStripMenuItemSaveAsOds.Text = "Save as &OpenDocument Spreadsheet (ODS)";
		toolStripMenuItemSaveAsOds.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsOds.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsOds.Click += SaveAsOds_Click;
		// 
		// toolStripMenuItemSaveAsCsv
		// 
		toolStripMenuItemSaveAsCsv.AccessibleDescription = "Saves the list as CSV file";
		toolStripMenuItemSaveAsCsv.AccessibleName = "Save as CSV";
		toolStripMenuItemSaveAsCsv.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsCsv.AutoToolTip = true;
		toolStripMenuItemSaveAsCsv.Image = FatcowIcons16px.fatcow_page_white_excel_16px;
		toolStripMenuItemSaveAsCsv.Name = "toolStripMenuItemSaveAsCsv";
		toolStripMenuItemSaveAsCsv.Size = new Size(301, 22);
		toolStripMenuItemSaveAsCsv.Text = "Save as &Comma separated value (CSV)";
		toolStripMenuItemSaveAsCsv.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsCsv.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsCsv.Click += SaveAsCsv_Click;
		// 
		// toolStripMenuItemSaveAsTsv
		// 
		toolStripMenuItemSaveAsTsv.AccessibleDescription = "Saves the list as TSV file";
		toolStripMenuItemSaveAsTsv.AccessibleName = "Save as TSV";
		toolStripMenuItemSaveAsTsv.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsTsv.AutoToolTip = true;
		toolStripMenuItemSaveAsTsv.Image = FatcowIcons16px.fatcow_page_white_excel_16px;
		toolStripMenuItemSaveAsTsv.Name = "toolStripMenuItemSaveAsTsv";
		toolStripMenuItemSaveAsTsv.Size = new Size(301, 22);
		toolStripMenuItemSaveAsTsv.Text = "Save as &Tabulator separated value (TSV)";
		toolStripMenuItemSaveAsTsv.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsTsv.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsTsv.Click += SaveAsTsv_Click;
		// 
		// toolStripMenuItemSaveAsPsv
		// 
		toolStripMenuItemSaveAsPsv.AccessibleDescription = "Saves the list as PSV file";
		toolStripMenuItemSaveAsPsv.AccessibleName = "Save as PSV";
		toolStripMenuItemSaveAsPsv.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsPsv.AutoToolTip = true;
		toolStripMenuItemSaveAsPsv.Image = FatcowIcons16px.fatcow_page_white_excel_16px;
		toolStripMenuItemSaveAsPsv.Name = "toolStripMenuItemSaveAsPsv";
		toolStripMenuItemSaveAsPsv.Size = new Size(301, 22);
		toolStripMenuItemSaveAsPsv.Text = "Save as &Pipe separated value (PSV)";
		toolStripMenuItemSaveAsPsv.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsPsv.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsPsv.Click += SaveAsPsv_Click;
		// 
		// toolStripMenuItemSaveAsEt
		// 
		toolStripMenuItemSaveAsEt.AccessibleDescription = "Saves the list as ET";
		toolStripMenuItemSaveAsEt.AccessibleName = "Save as ET";
		toolStripMenuItemSaveAsEt.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsEt.AutoToolTip = true;
		toolStripMenuItemSaveAsEt.Image = FatcowIcons16px.fatcow_page_white_excel_16px;
		toolStripMenuItemSaveAsEt.Name = "toolStripMenuItemSaveAsEt";
		toolStripMenuItemSaveAsEt.Size = new Size(301, 22);
		toolStripMenuItemSaveAsEt.Text = "Save as &WPS Office Spreadsheet (ET)";
		toolStripMenuItemSaveAsEt.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsEt.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsEt.Click += SaveAsEt_Click;
		// 
		// toolStripMenuItemXmlDocuments
		// 
		toolStripMenuItemXmlDocuments.AccessibleDescription = "Saves the list as XML documents";
		toolStripMenuItemXmlDocuments.AccessibleName = "Save as XML documents";
		toolStripMenuItemXmlDocuments.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemXmlDocuments.AutoToolTip = true;
		toolStripMenuItemXmlDocuments.DropDownItems.AddRange(new ToolStripItem[] { toolStripMenuItemSaveAsHtml, toolStripMenuItemSaveAsXml, toolStripMenuItemSaveAsDocBook });
		toolStripMenuItemXmlDocuments.Image = FatcowIcons16px.fatcow_file_extension_bin_16px;
		toolStripMenuItemXmlDocuments.Name = "toolStripMenuItemXmlDocuments";
		toolStripMenuItemXmlDocuments.Size = new Size(201, 22);
		toolStripMenuItemXmlDocuments.Text = "&XML documents";
		// 
		// toolStripMenuItemSaveAsHtml
		// 
		toolStripMenuItemSaveAsHtml.AccessibleDescription = "Saves the list as HTML file";
		toolStripMenuItemSaveAsHtml.AccessibleName = "Save as HTML";
		toolStripMenuItemSaveAsHtml.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsHtml.AutoToolTip = true;
		toolStripMenuItemSaveAsHtml.Image = FatcowIcons16px.fatcow_page_white_code_16px;
		toolStripMenuItemSaveAsHtml.Name = "toolStripMenuItemSaveAsHtml";
		toolStripMenuItemSaveAsHtml.Size = new Size(163, 22);
		toolStripMenuItemSaveAsHtml.Text = "Save as &HTML";
		toolStripMenuItemSaveAsHtml.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsHtml.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsHtml.Click += SaveAsHtml_Click;
		// 
		// toolStripMenuItemSaveAsXml
		// 
		toolStripMenuItemSaveAsXml.AccessibleDescription = "Saves the list as XML file";
		toolStripMenuItemSaveAsXml.AccessibleName = "Save as XML";
		toolStripMenuItemSaveAsXml.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsXml.AutoToolTip = true;
		toolStripMenuItemSaveAsXml.Image = FatcowIcons16px.fatcow_page_white_code_16px;
		toolStripMenuItemSaveAsXml.Name = "toolStripMenuItemSaveAsXml";
		toolStripMenuItemSaveAsXml.Size = new Size(163, 22);
		toolStripMenuItemSaveAsXml.Text = "Save as &XML";
		toolStripMenuItemSaveAsXml.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsXml.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsXml.Click += SaveAsXml_Click;
		// 
		// toolStripMenuItemSaveAsDocBook
		// 
		toolStripMenuItemSaveAsDocBook.AccessibleDescription = "Saves the list as DocBook file";
		toolStripMenuItemSaveAsDocBook.AccessibleName = "Save as DocBook";
		toolStripMenuItemSaveAsDocBook.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsDocBook.AutoToolTip = true;
		toolStripMenuItemSaveAsDocBook.Image = FatcowIcons16px.fatcow_page_white_code_16px;
		toolStripMenuItemSaveAsDocBook.Name = "toolStripMenuItemSaveAsDocBook";
		toolStripMenuItemSaveAsDocBook.Size = new Size(163, 22);
		toolStripMenuItemSaveAsDocBook.Text = "Save as &DocBook";
		toolStripMenuItemSaveAsDocBook.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsDocBook.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsDocBook.Click += SaveAsDocBook_Click;
		// 
		// toolStripMenuItemConfigurationFiles
		// 
		toolStripMenuItemConfigurationFiles.AccessibleDescription = "Saves the list as configuration file";
		toolStripMenuItemConfigurationFiles.AccessibleName = "Save as configuration file";
		toolStripMenuItemConfigurationFiles.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemConfigurationFiles.AutoToolTip = true;
		toolStripMenuItemConfigurationFiles.DropDownItems.AddRange(new ToolStripItem[] { toolStripMenuItemSaveAsJson, toolStripMenuItemSaveAsYaml, toolStripMenuItemSaveAsToml });
		toolStripMenuItemConfigurationFiles.Image = FatcowIcons16px.fatcow_file_extension_bat_16px;
		toolStripMenuItemConfigurationFiles.Name = "toolStripMenuItemConfigurationFiles";
		toolStripMenuItemConfigurationFiles.Size = new Size(201, 22);
		toolStripMenuItemConfigurationFiles.Text = "&Configuration files";
		// 
		// toolStripMenuItemSaveAsJson
		// 
		toolStripMenuItemSaveAsJson.AccessibleDescription = "Saves the list as JSON file";
		toolStripMenuItemSaveAsJson.AccessibleName = "Save as JSON";
		toolStripMenuItemSaveAsJson.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsJson.AutoToolTip = true;
		toolStripMenuItemSaveAsJson.Image = FatcowIcons16px.fatcow_page_white_code_red_16px;
		toolStripMenuItemSaveAsJson.Name = "toolStripMenuItemSaveAsJson";
		toolStripMenuItemSaveAsJson.Size = new Size(146, 22);
		toolStripMenuItemSaveAsJson.Text = "Save as &JSON";
		toolStripMenuItemSaveAsJson.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsJson.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsJson.Click += SaveAsJson_Click;
		// 
		// toolStripMenuItemSaveAsYaml
		// 
		toolStripMenuItemSaveAsYaml.AccessibleDescription = "Saves the list as YAML file";
		toolStripMenuItemSaveAsYaml.AccessibleName = "Save as YAML";
		toolStripMenuItemSaveAsYaml.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsYaml.AutoToolTip = true;
		toolStripMenuItemSaveAsYaml.Image = FatcowIcons16px.fatcow_page_white_code_red_16px;
		toolStripMenuItemSaveAsYaml.Name = "toolStripMenuItemSaveAsYaml";
		toolStripMenuItemSaveAsYaml.Size = new Size(146, 22);
		toolStripMenuItemSaveAsYaml.Text = "Save as &YAML";
		toolStripMenuItemSaveAsYaml.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsYaml.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsYaml.Click += SaveAsYaml_Click;
		// 
		// toolStripMenuItemSaveAsToml
		// 
		toolStripMenuItemSaveAsToml.AccessibleDescription = "Saves the list as TOML file";
		toolStripMenuItemSaveAsToml.AccessibleName = "Save as TOML";
		toolStripMenuItemSaveAsToml.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsToml.AutoToolTip = true;
		toolStripMenuItemSaveAsToml.Image = FatcowIcons16px.fatcow_page_white_code_red_16px;
		toolStripMenuItemSaveAsToml.Name = "toolStripMenuItemSaveAsToml";
		toolStripMenuItemSaveAsToml.Size = new Size(146, 22);
		toolStripMenuItemSaveAsToml.Text = "Save as &TOML";
		toolStripMenuItemSaveAsToml.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsToml.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsToml.Click += SaveAsToml_Click;
		// 
		// toolStripMenuItemDatabaseScripts
		// 
		toolStripMenuItemDatabaseScripts.AccessibleDescription = "Saves the list as database script";
		toolStripMenuItemDatabaseScripts.AccessibleName = "Save as database script";
		toolStripMenuItemDatabaseScripts.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemDatabaseScripts.AutoToolTip = true;
		toolStripMenuItemDatabaseScripts.DropDownItems.AddRange(new ToolStripItem[] { toolStripMenuItemSaveAsSql, toolStripMenuItemSaveAsSqlite });
		toolStripMenuItemDatabaseScripts.Image = FatcowIcons16px.fatcow_file_extension_ptb_16px;
		toolStripMenuItemDatabaseScripts.Name = "toolStripMenuItemDatabaseScripts";
		toolStripMenuItemDatabaseScripts.Size = new Size(201, 22);
		toolStripMenuItemDatabaseScripts.Text = "&Database scripts";
		// 
		// toolStripMenuItemSaveAsSql
		// 
		toolStripMenuItemSaveAsSql.AccessibleDescription = "Saves the list as SQL script";
		toolStripMenuItemSaveAsSql.AccessibleName = "Save as SQL";
		toolStripMenuItemSaveAsSql.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsSql.AutoToolTip = true;
		toolStripMenuItemSaveAsSql.Image = FatcowIcons16px.fatcow_page_white_database_16px;
		toolStripMenuItemSaveAsSql.Name = "toolStripMenuItemSaveAsSql";
		toolStripMenuItemSaveAsSql.Size = new Size(168, 22);
		toolStripMenuItemSaveAsSql.Text = "Save as &SQL script";
		toolStripMenuItemSaveAsSql.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsSql.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsSql.Click += SaveAsSql_Click;
		// 
		// toolStripMenuItemSaveAsSqlite
		// 
		toolStripMenuItemSaveAsSqlite.AccessibleDescription = "Saves the list as SQLite file";
		toolStripMenuItemSaveAsSqlite.AccessibleName = "Save as SQLite";
		toolStripMenuItemSaveAsSqlite.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsSqlite.AutoToolTip = true;
		toolStripMenuItemSaveAsSqlite.Image = FatcowIcons16px.fatcow_page_white_database_16px;
		toolStripMenuItemSaveAsSqlite.Name = "toolStripMenuItemSaveAsSqlite";
		toolStripMenuItemSaveAsSqlite.Size = new Size(168, 22);
		toolStripMenuItemSaveAsSqlite.Text = "Save as SQ&Lite";
		toolStripMenuItemSaveAsSqlite.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsSqlite.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsSqlite.Click += SaveAsSqlite_Click;
		// 
		// toolStripMenuItemPortableDocuments
		// 
		toolStripMenuItemPortableDocuments.AccessibleDescription = "Saves the list as portable document";
		toolStripMenuItemPortableDocuments.AccessibleName = "Save as portable document";
		toolStripMenuItemPortableDocuments.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemPortableDocuments.AutoToolTip = true;
		toolStripMenuItemPortableDocuments.DropDownItems.AddRange(new ToolStripItem[] { toolStripMenuItemSaveAsPdf, toolStripMenuItemSaveAsPostScript, toolStripMenuItemSaveAsEpub, toolStripMenuItemSaveAsMobi, toolStripMenuItemSaveAsXps, toolStripMenuItemSaveAsFictionBook2, toolStripMenuItemSaveAsChm });
		toolStripMenuItemPortableDocuments.Image = FatcowIcons16px.fatcow_file_extension_pdf_16px;
		toolStripMenuItemPortableDocuments.Name = "toolStripMenuItemPortableDocuments";
		toolStripMenuItemPortableDocuments.Size = new Size(201, 22);
		toolStripMenuItemPortableDocuments.Text = "&Portable documents";
		// 
		// toolStripMenuItemSaveAsPdf
		// 
		toolStripMenuItemSaveAsPdf.AccessibleDescription = "Saves the list as PDF file";
		toolStripMenuItemSaveAsPdf.AccessibleName = "Save as PDF";
		toolStripMenuItemSaveAsPdf.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsPdf.AutoToolTip = true;
		toolStripMenuItemSaveAsPdf.Image = FatcowIcons16px.fatcow_page_white_acrobat_16px;
		toolStripMenuItemSaveAsPdf.Name = "toolStripMenuItemSaveAsPdf";
		toolStripMenuItemSaveAsPdf.Size = new Size(214, 22);
		toolStripMenuItemSaveAsPdf.Text = "Save as &PDF";
		toolStripMenuItemSaveAsPdf.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsPdf.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsPdf.Click += SaveAsPdf_Click;
		// 
		// toolStripMenuItemSaveAsPostScript
		// 
		toolStripMenuItemSaveAsPostScript.AccessibleDescription = "Saves the list as PostScript file";
		toolStripMenuItemSaveAsPostScript.AccessibleName = "Save as PostScript";
		toolStripMenuItemSaveAsPostScript.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsPostScript.AutoToolTip = true;
		toolStripMenuItemSaveAsPostScript.Image = FatcowIcons16px.fatcow_page_white_acrobat_16px;
		toolStripMenuItemSaveAsPostScript.Name = "toolStripMenuItemSaveAsPostScript";
		toolStripMenuItemSaveAsPostScript.Size = new Size(214, 22);
		toolStripMenuItemSaveAsPostScript.Text = "Save as Post&Script (PS)";
		toolStripMenuItemSaveAsPostScript.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsPostScript.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsPostScript.Click += SaveAsPostScript_Click;
		// 
		// toolStripMenuItemSaveAsEpub
		// 
		toolStripMenuItemSaveAsEpub.AccessibleDescription = "Saves the list as EPUB file";
		toolStripMenuItemSaveAsEpub.AccessibleName = "Save as EPUB";
		toolStripMenuItemSaveAsEpub.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsEpub.AutoToolTip = true;
		toolStripMenuItemSaveAsEpub.Image = FatcowIcons16px.fatcow_page_white_acrobat_16px;
		toolStripMenuItemSaveAsEpub.Name = "toolStripMenuItemSaveAsEpub";
		toolStripMenuItemSaveAsEpub.Size = new Size(214, 22);
		toolStripMenuItemSaveAsEpub.Text = "Save as &EPUB";
		toolStripMenuItemSaveAsEpub.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsEpub.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsEpub.Click += SaveAsEpub_Click;
		// 
		// toolStripMenuItemSaveAsMobi
		// 
		toolStripMenuItemSaveAsMobi.AccessibleDescription = "Saves the list as MOBI file";
		toolStripMenuItemSaveAsMobi.AccessibleName = "Save as MOBI";
		toolStripMenuItemSaveAsMobi.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsMobi.AutoToolTip = true;
		toolStripMenuItemSaveAsMobi.Image = FatcowIcons16px.fatcow_page_white_acrobat_16px;
		toolStripMenuItemSaveAsMobi.Name = "toolStripMenuItemSaveAsMobi";
		toolStripMenuItemSaveAsMobi.Size = new Size(214, 22);
		toolStripMenuItemSaveAsMobi.Text = "Save as &MOBI";
		toolStripMenuItemSaveAsMobi.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsMobi.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsMobi.Click += SaveAsMobi_Click;
		// 
		// toolStripMenuItemSaveAsXps
		// 
		toolStripMenuItemSaveAsXps.AccessibleDescription = "Saves the list as XPS file";
		toolStripMenuItemSaveAsXps.AccessibleName = "Save as XPS";
		toolStripMenuItemSaveAsXps.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsXps.AutoToolTip = true;
		toolStripMenuItemSaveAsXps.Image = FatcowIcons16px.fatcow_page_white_acrobat_16px;
		toolStripMenuItemSaveAsXps.Name = "toolStripMenuItemSaveAsXps";
		toolStripMenuItemSaveAsXps.Size = new Size(214, 22);
		toolStripMenuItemSaveAsXps.Text = "Save as &XPS";
		toolStripMenuItemSaveAsXps.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsXps.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsXps.Click += SaveAsXps_Click;
		// 
		// toolStripMenuItemSaveAsFictionBook2
		// 
		toolStripMenuItemSaveAsFictionBook2.AccessibleDescription = "Saves the list as FictionBook2 file";
		toolStripMenuItemSaveAsFictionBook2.AccessibleName = "Save as FB2";
		toolStripMenuItemSaveAsFictionBook2.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsFictionBook2.AutoToolTip = true;
		toolStripMenuItemSaveAsFictionBook2.Image = FatcowIcons16px.fatcow_page_white_acrobat_16px;
		toolStripMenuItemSaveAsFictionBook2.Name = "toolStripMenuItemSaveAsFictionBook2";
		toolStripMenuItemSaveAsFictionBook2.Size = new Size(214, 22);
		toolStripMenuItemSaveAsFictionBook2.Text = "Save as &FictionBook2 (FB2)";
		toolStripMenuItemSaveAsFictionBook2.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsFictionBook2.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsFictionBook2.Click += SaveAsFictionBook2_Click;
		// 
		// toolStripMenuItemSaveAsChm
		// 
		toolStripMenuItemSaveAsChm.AccessibleDescription = "Saves the list as CHM file";
		toolStripMenuItemSaveAsChm.AccessibleName = "Save as CHM";
		toolStripMenuItemSaveAsChm.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsChm.AutoToolTip = true;
		toolStripMenuItemSaveAsChm.Image = FatcowIcons16px.fatcow_page_white_acrobat_16px;
		toolStripMenuItemSaveAsChm.Name = "toolStripMenuItemSaveAsChm";
		toolStripMenuItemSaveAsChm.Size = new Size(214, 22);
		toolStripMenuItemSaveAsChm.Text = "Save as &CHM";
		toolStripMenuItemSaveAsChm.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsChm.MouseLeave += Control_Leave;
		toolStripMenuItemSaveAsChm.Click += SaveAsChm_Click;
		// 
		// DatabaseDownloaderForm
		// 
		AccessibleDescription = "Downloads the files";
		AccessibleName = "Download files";
		AccessibleRole = AccessibleRole.Dialog;
		AutoScaleDimensions = new SizeF(7F, 15F);
		AutoScaleMode = AutoScaleMode.Font;
		ClientSize = new Size(581, 213);
		ControlBox = false;
		Controls.Add(toolStripContainer);
		FormBorderStyle = FormBorderStyle.FixedToolWindow;
		Icon = (Icon)resources.GetObject("$this.Icon");
		MaximizeBox = false;
		MinimizeBox = false;
		Name = "DatabaseDownloaderForm";
		StartPosition = FormStartPosition.CenterParent;
		Text = "Downloader";
		tableLayoutPanel.ResumeLayout(false);
		tableLayoutPanel.PerformLayout();
		contextMenuCopyToClipboard.ResumeLayout(false);
		kryptonStatusStrip.ResumeLayout(false);
		kryptonStatusStrip.PerformLayout();
		((System.ComponentModel.ISupportInitialize)kryptoPanelMain).EndInit();
		kryptoPanelMain.ResumeLayout(false);
		toolStripContainer.BottomToolStripPanel.ResumeLayout(false);
		toolStripContainer.BottomToolStripPanel.PerformLayout();
		toolStripContainer.ContentPanel.ResumeLayout(false);
		toolStripContainer.TopToolStripPanel.ResumeLayout(false);
		toolStripContainer.TopToolStripPanel.PerformLayout();
		toolStripContainer.ResumeLayout(false);
		toolStripContainer.PerformLayout();
		kryptonToolStripIcons.ResumeLayout(false);
		kryptonToolStripIcons.PerformLayout();
		contextMenuSaveToFile.ResumeLayout(false);
		ResumeLayout(false);
	}
	private Krypton.Toolkit.KryptonManager kryptonManager;
	private Krypton.Toolkit.KryptonStatusStrip kryptonStatusStrip;
	private ToolStripStatusLabel labelInformation;
	private Krypton.Toolkit.KryptonPanel kryptoPanelMain;
	private Krypton.Toolkit.KryptonTableLayoutPanel tableLayoutPanel;
	private Krypton.Toolkit.KryptonLabel labelStatusText;
	private Krypton.Toolkit.KryptonLabel labelSizeValue;
	private Krypton.Toolkit.KryptonLabel labelSizeText;
	private Krypton.Toolkit.KryptonLabel labelDateValue;
	private Krypton.Toolkit.KryptonLabel labelSourceValue;
	private Krypton.Toolkit.KryptonLabel labelDateText;
	private Krypton.Toolkit.KryptonLabel labelSourceText;
	private Krypton.Toolkit.KryptonLabel labelStatusValue;
	private ContextMenuStrip contextMenuCopyToClipboard;
	private ToolStripMenuItem toolStripMenuItemCopyToClipboard;
	private ToolStripContainer toolStripContainer;
	private Krypton.Toolkit.KryptonToolStrip kryptonToolStripIcons;
	private ToolStripButton toolStripButtonDownload;
	private ToolStripButton toolStripButtonCancel;
	private ToolStripSeparator toolStripSeparator;
	private Krypton.Toolkit.KryptonProgressBarToolStripItem kryptonProgressBarDownload;
	private Krypton.Toolkit.KryptonLabel labelDownloadSpeed;
	private Krypton.Toolkit.KryptonLabel labelDownloadSpeedValue;
	private Krypton.Toolkit.KryptonLabel labelTimeValue;
	private Krypton.Toolkit.KryptonLabel labelTime;
	private ToolStripLabel toolStripLabelProgress;
	private ContextMenuStrip contextMenuSaveToFile;
	private ToolStripMenuItem toolStripMenuItemTextFiles;
	private ToolStripMenuItem toolStripMenuItemSaveAsText;
	private ToolStripMenuItem toolStripMenuItemSaveAsLatex;
	private ToolStripMenuItem toolStripMenuItemSaveAsMarkdown;
	private ToolStripMenuItem toolStripMenuItemSaveAsAsciiDoc;
	private ToolStripMenuItem toolStripMenuItemSaveAsReStructuredText;
	private ToolStripMenuItem toolStripMenuItemSaveAsTextile;
	private ToolStripMenuItem toolStripMenuItemSaveAsTypst;
	private ToolStripMenuItem toolStripMenuItemWriterDocuments;
	private ToolStripMenuItem toolStripMenuItemSaveAsWord;
	private ToolStripMenuItem toolStripMenuItemSaveAsOdt;
	private ToolStripMenuItem toolStripMenuItemSaveAsRtf;
	private ToolStripMenuItem toolStripMenuItemSaveAsAbiword;
	private ToolStripMenuItem toolStripMenuItemSaveAsWps;
	private ToolStripMenuItem toolStripMenuItemSpreadsheetDocuments;
	private ToolStripMenuItem toolStripMenuItemSaveAsExcel;
	private ToolStripMenuItem toolStripMenuItemSaveAsOds;
	private ToolStripMenuItem toolStripMenuItemSaveAsCsv;
	private ToolStripMenuItem toolStripMenuItemSaveAsTsv;
	private ToolStripMenuItem toolStripMenuItemSaveAsPsv;
	private ToolStripMenuItem toolStripMenuItemSaveAsEt;
	private ToolStripMenuItem toolStripMenuItemXmlDocuments;
	private ToolStripMenuItem toolStripMenuItemSaveAsHtml;
	private ToolStripMenuItem toolStripMenuItemSaveAsXml;
	private ToolStripMenuItem toolStripMenuItemSaveAsDocBook;
	private ToolStripMenuItem toolStripMenuItemConfigurationFiles;
	private ToolStripMenuItem toolStripMenuItemSaveAsJson;
	private ToolStripMenuItem toolStripMenuItemSaveAsYaml;
	private ToolStripMenuItem toolStripMenuItemSaveAsToml;
	private ToolStripMenuItem toolStripMenuItemDatabaseScripts;
	private ToolStripMenuItem toolStripMenuItemSaveAsSql;
	private ToolStripMenuItem toolStripMenuItemSaveAsSqlite;
	private ToolStripMenuItem toolStripMenuItemPortableDocuments;
	private ToolStripMenuItem toolStripMenuItemSaveAsPdf;
	private ToolStripMenuItem toolStripMenuItemSaveAsPostScript;
	private ToolStripMenuItem toolStripMenuItemSaveAsEpub;
	private ToolStripMenuItem toolStripMenuItemSaveAsMobi;
	private ToolStripMenuItem toolStripMenuItemSaveAsXps;
	private ToolStripMenuItem toolStripMenuItemSaveAsFictionBook2;
	private ToolStripMenuItem toolStripMenuItemSaveAsChm;
}
