// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage(category: "Interoperability", checkId: "SYSLIB1054:Verwenden Sie \\\"LibraryImportAttribute\\\" anstelle von \\\"DllImportAttribute\\\", um P/Invoke-Marshallingcode zur Kompilierzeit zu generieren.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Planetoid_DB.Program.CoInternetSetFeatureEnabled(System.Int32,System.Int32,System.Boolean)~System.Int32")]
[assembly: SuppressMessage(category: "Performance", checkId: "CA1834:Verwendung von \"StringBuilder.Append(char)\" erwägen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Planetoid_DB.ExportDataSheetForm.ToolStripMenuItemExportAsPdf_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage(category: "Performance", checkId: "CA1834:Verwendung von \"StringBuilder.Append(char)\" erwägen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Planetoid_DB.ExportDataSheetForm.ToolStripMenuItemExportAsRtf_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage(category: "Performance", checkId: "SYSLIB1045:In „GeneratedRegexAttribute“ konvertieren.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Planetoid_DB.PlanetoidDbForm.ProcessDesignationForUrl(System.String)~System.String")]
[assembly: SuppressMessage(category: "Style", checkId: "IDE0060:Nicht verwendete Parameter entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Planetoid_DB.Helpers.ListViewExporter.SaveAsExcel(System.Windows.Forms.ListView,System.String,System.String,System.Func{System.Int32,System.Windows.Forms.ListViewItem})")]
[assembly: SuppressMessage(category: "Style", checkId: "IDE0060:Nicht verwendete Parameter entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Planetoid_DB.Helpers.ListViewExporter.SaveAsCsv(System.Windows.Forms.ListView,System.String,System.String,System.Func{System.Int32,System.Windows.Forms.ListViewItem})")]
[assembly: SuppressMessage(category: "Style", checkId: "IDE0060:Nicht verwendete Parameter entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Planetoid_DB.Helpers.ListViewExporter.SaveAsTsv(System.Windows.Forms.ListView,System.String,System.String,System.Func{System.Int32,System.Windows.Forms.ListViewItem})")]
[assembly: SuppressMessage(category: "Style", checkId: "IDE0060:Nicht verwendete Parameter entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Planetoid_DB.Helpers.ListViewExporter.SaveAsPsv(System.Windows.Forms.ListView,System.String,System.String,System.Func{System.Int32,System.Windows.Forms.ListViewItem})")]
[assembly: SuppressMessage(category: "Style", checkId: "IDE0060:Nicht verwendete Parameter entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Planetoid_DB.Helpers.ListViewExporter.SaveAsEt(System.Windows.Forms.ListView,System.String,System.String,System.Func{System.Int32,System.Windows.Forms.ListViewItem})")]
[assembly: SuppressMessage(category: "Style", checkId: "IDE0060:Nicht verwendete Parameter entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Planetoid_DB.Helpers.TableLayoutPanelExporter.SaveAsExcel(System.Windows.Forms.TableLayoutPanel,System.String,System.String)")]
[assembly: SuppressMessage(category: "Style", checkId: "IDE0060:Nicht verwendete Parameter entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Planetoid_DB.Helpers.TableLayoutPanelExporter.SaveAsCsv(System.Windows.Forms.TableLayoutPanel,System.String,System.String)")]
[assembly: SuppressMessage(category: "Style", checkId: "IDE0060:Nicht verwendete Parameter entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Planetoid_DB.Helpers.TableLayoutPanelExporter.SaveAsTsv(System.Windows.Forms.TableLayoutPanel,System.String,System.String)")]
[assembly: SuppressMessage(category: "Style", checkId: "IDE0060:Nicht verwendete Parameter entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Planetoid_DB.Helpers.TableLayoutPanelExporter.SaveAsPsv(System.Windows.Forms.TableLayoutPanel,System.String,System.String)")]
[assembly: SuppressMessage(category: "Style", checkId: "IDE0060:Nicht verwendete Parameter entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Planetoid_DB.Helpers.TableLayoutPanelExporter.SaveAsEt(System.Windows.Forms.TableLayoutPanel,System.String,System.String)")]
[assembly: SuppressMessage(category: "Interoperability", checkId: "SYSLIB1096:In \"GeneratedComInterface\" konvertieren", Justification = "<Ausstehend>", Scope = "type", Target = "~T:Planetoid_DB.Helpers.ITaskbarList3")]
