// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using Krypton.Toolkit;

using Planetoid_DB.Resources;

using System.ComponentModel;

namespace Planetoid_DB;

/// <summary>Represents a dialog form that displays essential application information, including the version, title, description,
/// company, author, and copyright details, as well as information about third-party components used by the application.</summary>
/// <remarks>AppInfoForm provides users with a centralized interface to view key program details and offers
/// convenient options to copy information to the clipboard. The form is typically shown as a modal dialog and includes
/// accessibility features for improved usability. It is not intended to be modified directly; use the designer for
/// layout changes.</remarks>
partial class AppInfoForm
{
	/// <summary>Required designer variable.</summary>
	/// <remarks>This field is used by the Windows Forms designer to manage components.</remarks>
	private IContainer components = null;

	/// <summary>Clean up any resources being used.</summary>
	/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
	/// <remarks>This method is called when the form is being disposed.</remarks>
	protected override void Dispose(bool disposing)
	{
		if (disposing && (components != null))
		{
			components.Dispose();
		}
		base.Dispose(disposing);
	}

	#region Windows Form Designer generated code

	/// <summary>Required method for Designer support - do not modify
	/// the contents of this method with the code editor.</summary>
	/// <remarks>This method is automatically generated by the Windows Forms designer and should not be modified manually.
	/// It sets up the controls and their properties for the form.</remarks>
	private void InitializeComponent()
	{
		components = new Container();
		ComponentResourceManager resources = new ComponentResourceManager(typeof(AppInfoForm));
		contextMenuStripCopyToClipboard = new ContextMenuStrip(components);
		toolStripMenuItemCopyToClipboard = new ToolStripMenuItem();
		tabControlInfo = new TabControl();
		tabPageAbout = new TabPage();
		kryptonPictureBoxLogo = new KryptonPictureBox();
		kryptonPictureBoxVisualStudio = new KryptonPictureBox();
		kryptonPictureBoxDotNet = new KryptonPictureBox();
		kryptonPictureBoxCSharp = new KryptonPictureBox();
		kryptonLabelTitle = new KryptonLabel();
		kryptonLabelVersion = new KryptonLabel();
		kryptonLabelCompany = new KryptonLabel();
		kryptonLabelAuthor = new KryptonLabel();
		kryptonLabelDescription = new KryptonLabel();
		kryptonLabelCopyright = new KryptonLabel();
		kryptonLinkLabelWebsite = new KryptonLinkLabel();
		kryptonLinkLabelEmail = new KryptonLinkLabel();
		tabPageComponents = new TabPage();
		tabControlComponents = new TabControl();
		tabPageComponentApplicationIcon = new TabPage();
		kryptonLabelLicenseFlaticon = new KryptonLabel();
		kryptonLinkLabelFlaticon = new KryptonLinkLabel();
		kryptonLabelAuthorFlaticon = new KryptonLabel();
		kryptonTextBoxLicenseFlaticon = new KryptonTextBox();
		kryptonLabelIconHeadingFlaticon = new KryptonLabel();
		tabPageIconsetFatcow = new TabPage();
		kryptonTextBoxLicenseFatcow = new KryptonTextBox();
		kryptonLabelHeadingFatcowIcons = new KryptonLabel();
		kryptonLabelLicenseFatcow = new KryptonLabel();
		kryptonLinkLabelWebsiteFatcow = new KryptonLinkLabel();
		kryptonLabelAuthorsFatcow = new KryptonLabel();
		tabPageComponentKryptonSuite = new TabPage();
		kryptonTextBoxLicenseKryptonSuite = new KryptonTextBox();
		kryptonLabelHeadingKryptonSuite = new KryptonLabel();
		kryptonLabelLicenseKryptonSuite = new KryptonLabel();
		kryptonLabelVersionKryptonSuite = new KryptonLabel();
		kryptonLinkLabelWebsiteKryptonSuite = new KryptonLinkLabel();
		kryptonLabelAuthorsKryptonSuite = new KryptonLabel();
		tabPageComponentNLog = new TabPage();
		kryptonTextBoxLicenseNlog = new KryptonTextBox();
		kryptonLabelHeadingNlog = new KryptonLabel();
		kryptonLabelLicenseNlog = new KryptonLabel();
		kryptonLabelVersionNlog = new KryptonLabel();
		kryptonLinkLabelWebsiteNlog = new KryptonLinkLabel();
		kryptonLabelAuthorsNlog = new KryptonLabel();
		imageListTabAbout = new ImageList(components);
		pictureBoxBanner = new KryptonPictureBox();
		kryptoPanelMain = new KryptonPanel();
		kryptonStatusStrip = new KryptonStatusStrip();
		labelInformation = new ToolStripStatusLabel();
		kryptonManager = new KryptonManager(components);
		contextMenuStripCopyToClipboard.SuspendLayout();
		tabControlInfo.SuspendLayout();
		tabPageAbout.SuspendLayout();
		((ISupportInitialize)kryptonPictureBoxLogo).BeginInit();
		((ISupportInitialize)kryptonPictureBoxVisualStudio).BeginInit();
		((ISupportInitialize)kryptonPictureBoxDotNet).BeginInit();
		((ISupportInitialize)kryptonPictureBoxCSharp).BeginInit();
		tabPageComponents.SuspendLayout();
		tabControlComponents.SuspendLayout();
		tabPageComponentApplicationIcon.SuspendLayout();
		tabPageIconsetFatcow.SuspendLayout();
		tabPageComponentKryptonSuite.SuspendLayout();
		tabPageComponentNLog.SuspendLayout();
		((ISupportInitialize)pictureBoxBanner).BeginInit();
		((ISupportInitialize)kryptoPanelMain).BeginInit();
		kryptoPanelMain.SuspendLayout();
		kryptonStatusStrip.SuspendLayout();
		SuspendLayout();
		// 
		// contextMenuStripCopyToClipboard
		// 
		contextMenuStripCopyToClipboard.AccessibleDescription = "Shows the context menu for copying information to the clipboard";
		contextMenuStripCopyToClipboard.AccessibleName = "Context menu for copying information to the clipboard";
		contextMenuStripCopyToClipboard.AccessibleRole = AccessibleRole.MenuPopup;
		contextMenuStripCopyToClipboard.AllowClickThrough = true;
		contextMenuStripCopyToClipboard.Font = new Font("Segoe UI", 9F);
		contextMenuStripCopyToClipboard.Items.AddRange(new ToolStripItem[] { toolStripMenuItemCopyToClipboard });
		contextMenuStripCopyToClipboard.Name = "contextMenuStrip";
		contextMenuStripCopyToClipboard.Size = new Size(214, 26);
		contextMenuStripCopyToClipboard.TabStop = true;
		contextMenuStripCopyToClipboard.Text = "Copy to clipboard";
		contextMenuStripCopyToClipboard.MouseEnter += Control_Enter;
		contextMenuStripCopyToClipboard.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemCopyToClipboard
		// 
		toolStripMenuItemCopyToClipboard.AccessibleDescription = "Copies the text/value to the clipboard";
		toolStripMenuItemCopyToClipboard.AccessibleName = "Copy to clipboard";
		toolStripMenuItemCopyToClipboard.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemCopyToClipboard.AutoToolTip = true;
		toolStripMenuItemCopyToClipboard.Image = FatcowIcons16px.fatcow_page_copy_16px;
		toolStripMenuItemCopyToClipboard.Name = "toolStripMenuItemCopyToClipboard";
		toolStripMenuItemCopyToClipboard.ShortcutKeyDisplayString = "Strg+C";
		toolStripMenuItemCopyToClipboard.ShortcutKeys = Keys.Control | Keys.C;
		toolStripMenuItemCopyToClipboard.Size = new Size(213, 22);
		toolStripMenuItemCopyToClipboard.Text = "&Copy to clipboard";
		toolStripMenuItemCopyToClipboard.Click += CopyToClipboard_DoubleClick;
		toolStripMenuItemCopyToClipboard.MouseEnter += Control_Enter;
		toolStripMenuItemCopyToClipboard.MouseLeave += Control_Leave;
		// 
		// tabControlInfo
		// 
		tabControlInfo.AccessibleDescription = "Tabs with program information";
		tabControlInfo.AccessibleName = "Program information tabs";
		tabControlInfo.AccessibleRole = AccessibleRole.PageTabList;
		tabControlInfo.Controls.Add(tabPageAbout);
		tabControlInfo.Controls.Add(tabPageComponents);
		tabControlInfo.ImageList = imageListTabAbout;
		tabControlInfo.Location = new Point(4, 181);
		tabControlInfo.Name = "tabControlInfo";
		tabControlInfo.SelectedIndex = 0;
		tabControlInfo.ShowToolTips = true;
		tabControlInfo.Size = new Size(500, 283);
		tabControlInfo.TabIndex = 7;
		tabControlInfo.Enter += Control_Enter;
		tabControlInfo.Leave += Control_Leave;
		tabControlInfo.MouseEnter += Control_Enter;
		tabControlInfo.MouseLeave += Control_Leave;
		// 
		// tabPageAbout
		// 
		tabPageAbout.AccessibleDescription = "Shows information about the application";
		tabPageAbout.AccessibleName = "About";
		tabPageAbout.AccessibleRole = AccessibleRole.PageTab;
		tabPageAbout.Controls.Add(kryptonPictureBoxLogo);
		tabPageAbout.Controls.Add(kryptonPictureBoxVisualStudio);
		tabPageAbout.Controls.Add(kryptonPictureBoxDotNet);
		tabPageAbout.Controls.Add(kryptonPictureBoxCSharp);
		tabPageAbout.Controls.Add(kryptonLabelTitle);
		tabPageAbout.Controls.Add(kryptonLabelVersion);
		tabPageAbout.Controls.Add(kryptonLabelCompany);
		tabPageAbout.Controls.Add(kryptonLabelAuthor);
		tabPageAbout.Controls.Add(kryptonLabelDescription);
		tabPageAbout.Controls.Add(kryptonLabelCopyright);
		tabPageAbout.Controls.Add(kryptonLinkLabelWebsite);
		tabPageAbout.Controls.Add(kryptonLinkLabelEmail);
		tabPageAbout.ImageKey = "fatcow_information_16px.png";
		tabPageAbout.Location = new Point(4, 24);
		tabPageAbout.Name = "tabPageAbout";
		tabPageAbout.Size = new Size(492, 255);
		tabPageAbout.TabIndex = 0;
		tabPageAbout.Text = "About";
		tabPageAbout.ToolTipText = "Application information";
		tabPageAbout.UseVisualStyleBackColor = true;
		tabPageAbout.Enter += Control_Enter;
		tabPageAbout.Leave += Control_Leave;
		tabPageAbout.MouseEnter += Control_Enter;
		tabPageAbout.MouseLeave += Control_Leave;
		// 
		// kryptonPictureBoxLogo
		// 
		kryptonPictureBoxLogo.AccessibleDescription = "Shows the application logo";
		kryptonPictureBoxLogo.AccessibleName = "Application logo";
		kryptonPictureBoxLogo.AccessibleRole = AccessibleRole.Graphic;
		kryptonPictureBoxLogo.Image = (Image)resources.GetObject("kryptonPictureBoxLogo.Image");
		kryptonPictureBoxLogo.Location = new Point(330, 12);
		kryptonPictureBoxLogo.Name = "kryptonPictureBoxLogo";
		kryptonPictureBoxLogo.Size = new Size(150, 150);
		kryptonPictureBoxLogo.SizeMode = PictureBoxSizeMode.Zoom;
		kryptonPictureBoxLogo.TabIndex = 11;
		kryptonPictureBoxLogo.TabStop = false;
		kryptonPictureBoxLogo.ToolTipValues.Description = "Shows the application logo";
		kryptonPictureBoxLogo.ToolTipValues.EnableToolTips = true;
		kryptonPictureBoxLogo.ToolTipValues.Heading = "Application logo";
		kryptonPictureBoxLogo.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonPictureBoxLogo.MouseEnter += Control_Enter;
		kryptonPictureBoxLogo.MouseLeave += Control_Leave;
		// 
		// kryptonPictureBoxVisualStudio
		// 
		kryptonPictureBoxVisualStudio.AccessibleDescription = "Shows the Visual Studio 2026";
		kryptonPictureBoxVisualStudio.AccessibleName = "Visual Studio 2026";
		kryptonPictureBoxVisualStudio.AccessibleRole = AccessibleRole.Graphic;
		kryptonPictureBoxVisualStudio.Image = (Image)resources.GetObject("kryptonPictureBoxVisualStudio.Image");
		kryptonPictureBoxVisualStudio.Location = new Point(105, 207);
		kryptonPictureBoxVisualStudio.Name = "kryptonPictureBoxVisualStudio";
		kryptonPictureBoxVisualStudio.Size = new Size(48, 48);
		kryptonPictureBoxVisualStudio.SizeMode = PictureBoxSizeMode.Zoom;
		kryptonPictureBoxVisualStudio.TabIndex = 10;
		kryptonPictureBoxVisualStudio.TabStop = false;
		kryptonPictureBoxVisualStudio.ToolTipValues.Description = "Built with Visual Studio 2026";
		kryptonPictureBoxVisualStudio.ToolTipValues.EnableToolTips = true;
		kryptonPictureBoxVisualStudio.ToolTipValues.Heading = "Visual Studio 2026";
		kryptonPictureBoxVisualStudio.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonPictureBoxVisualStudio.MouseEnter += Control_Enter;
		kryptonPictureBoxVisualStudio.MouseLeave += Control_Leave;
		// 
		// kryptonPictureBoxDotNet
		// 
		kryptonPictureBoxDotNet.AccessibleDescription = "Shows the Dotnet logo";
		kryptonPictureBoxDotNet.AccessibleName = "DotNet logo";
		kryptonPictureBoxDotNet.AccessibleRole = AccessibleRole.Graphic;
		kryptonPictureBoxDotNet.Image = (Image)resources.GetObject("kryptonPictureBoxDotNet.Image");
		kryptonPictureBoxDotNet.Location = new Point(0, 207);
		kryptonPictureBoxDotNet.Name = "kryptonPictureBoxDotNet";
		kryptonPictureBoxDotNet.Size = new Size(48, 48);
		kryptonPictureBoxDotNet.SizeMode = PictureBoxSizeMode.Zoom;
		kryptonPictureBoxDotNet.TabIndex = 9;
		kryptonPictureBoxDotNet.TabStop = false;
		kryptonPictureBoxDotNet.ToolTipValues.Description = "Used .NET 10";
		kryptonPictureBoxDotNet.ToolTipValues.EnableToolTips = true;
		kryptonPictureBoxDotNet.ToolTipValues.Heading = ".NET 10";
		kryptonPictureBoxDotNet.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonPictureBoxDotNet.MouseEnter += Control_Enter;
		kryptonPictureBoxDotNet.MouseLeave += Control_Leave;
		// 
		// kryptonPictureBoxCSharp
		// 
		kryptonPictureBoxCSharp.AccessibleDescription = "Shows the C# logo";
		kryptonPictureBoxCSharp.AccessibleName = "C# logo";
		kryptonPictureBoxCSharp.AccessibleRole = AccessibleRole.Graphic;
		kryptonPictureBoxCSharp.Image = (Image)resources.GetObject("kryptonPictureBoxCSharp.Image");
		kryptonPictureBoxCSharp.Location = new Point(51, 207);
		kryptonPictureBoxCSharp.Name = "kryptonPictureBoxCSharp";
		kryptonPictureBoxCSharp.Size = new Size(48, 48);
		kryptonPictureBoxCSharp.SizeMode = PictureBoxSizeMode.Zoom;
		kryptonPictureBoxCSharp.TabIndex = 8;
		kryptonPictureBoxCSharp.TabStop = false;
		kryptonPictureBoxCSharp.ToolTipValues.Description = "Written in C#";
		kryptonPictureBoxCSharp.ToolTipValues.EnableToolTips = true;
		kryptonPictureBoxCSharp.ToolTipValues.Heading = "C# logo";
		kryptonPictureBoxCSharp.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonPictureBoxCSharp.MouseEnter += Control_Enter;
		kryptonPictureBoxCSharp.MouseLeave += Control_Leave;
		// 
		// kryptonLabelTitle
		// 
		kryptonLabelTitle.AccessibleDescription = "Shows the application name";
		kryptonLabelTitle.AccessibleName = "Application Name";
		kryptonLabelTitle.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelTitle.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLabelTitle.LabelStyle = LabelStyle.TitlePanel;
		kryptonLabelTitle.Location = new Point(4, 3);
		kryptonLabelTitle.Name = "kryptonLabelTitle";
		kryptonLabelTitle.Size = new Size(129, 29);
		kryptonLabelTitle.TabIndex = 0;
		kryptonLabelTitle.ToolTipValues.Description = "Shows the application name.\r\nDouble-click or right-click to copy the information to the clipboard.";
		kryptonLabelTitle.ToolTipValues.EnableToolTips = true;
		kryptonLabelTitle.ToolTipValues.Heading = "Application name";
		kryptonLabelTitle.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLabelTitle.Values.Text = "Planetoid-DB";
		kryptonLabelTitle.DoubleClick += CopyToClipboard_DoubleClick;
		kryptonLabelTitle.Enter += Control_Enter;
		kryptonLabelTitle.Leave += Control_Leave;
		kryptonLabelTitle.MouseDown += Control_MouseDown;
		kryptonLabelTitle.MouseEnter += Control_Enter;
		kryptonLabelTitle.MouseLeave += Control_Leave;
		// 
		// kryptonLabelVersion
		// 
		kryptonLabelVersion.AccessibleDescription = "Shows the version number";
		kryptonLabelVersion.AccessibleName = "Version";
		kryptonLabelVersion.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelVersion.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLabelVersion.Location = new Point(4, 38);
		kryptonLabelVersion.Name = "kryptonLabelVersion";
		kryptonLabelVersion.Size = new Size(95, 20);
		kryptonLabelVersion.TabIndex = 1;
		kryptonLabelVersion.ToolTipValues.Description = "Shows the version number.\r\nDouble-click or right-click to copy the information to the clipboard.";
		kryptonLabelVersion.ToolTipValues.EnableToolTips = true;
		kryptonLabelVersion.ToolTipValues.Heading = "Version number";
		kryptonLabelVersion.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLabelVersion.Values.Text = "Version: X.X.X.X";
		kryptonLabelVersion.DoubleClick += CopyToClipboard_DoubleClick;
		kryptonLabelVersion.Enter += Control_Enter;
		kryptonLabelVersion.Leave += Control_Leave;
		kryptonLabelVersion.MouseDown += Control_MouseDown;
		kryptonLabelVersion.MouseEnter += Control_Enter;
		kryptonLabelVersion.MouseLeave += Control_Leave;
		// 
		// kryptonLabelCompany
		// 
		kryptonLabelCompany.AccessibleDescription = "Shows the company name";
		kryptonLabelCompany.AccessibleName = "Company";
		kryptonLabelCompany.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelCompany.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLabelCompany.Location = new Point(4, 64);
		kryptonLabelCompany.Name = "kryptonLabelCompany";
		kryptonLabelCompany.Size = new Size(70, 20);
		kryptonLabelCompany.TabIndex = 2;
		kryptonLabelCompany.ToolTipValues.Description = "Shows the company name.\r\nDouble-click or right-click to copy the information to the clipboard.";
		kryptonLabelCompany.ToolTipValues.EnableToolTips = true;
		kryptonLabelCompany.ToolTipValues.Heading = "Company";
		kryptonLabelCompany.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLabelCompany.Values.Text = "[Company]";
		kryptonLabelCompany.DoubleClick += CopyToClipboard_DoubleClick;
		kryptonLabelCompany.Enter += Control_Enter;
		kryptonLabelCompany.Leave += Control_Leave;
		kryptonLabelCompany.MouseDown += Control_MouseDown;
		kryptonLabelCompany.MouseEnter += Control_Enter;
		kryptonLabelCompany.MouseLeave += Control_Leave;
		// 
		// kryptonLabelAuthor
		// 
		kryptonLabelAuthor.AccessibleDescription = "Shows the author name";
		kryptonLabelAuthor.AccessibleName = "Author";
		kryptonLabelAuthor.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelAuthor.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLabelAuthor.Location = new Point(4, 90);
		kryptonLabelAuthor.Name = "kryptonLabelAuthor";
		kryptonLabelAuthor.Size = new Size(56, 20);
		kryptonLabelAuthor.TabIndex = 3;
		kryptonLabelAuthor.ToolTipValues.Description = "Shows the author name.\r\nDouble-click or right-click to copy the information to the clipboard.";
		kryptonLabelAuthor.ToolTipValues.EnableToolTips = true;
		kryptonLabelAuthor.ToolTipValues.Heading = "Author";
		kryptonLabelAuthor.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLabelAuthor.Values.Text = "[Author]";
		kryptonLabelAuthor.DoubleClick += CopyToClipboard_DoubleClick;
		kryptonLabelAuthor.Enter += Control_Enter;
		kryptonLabelAuthor.Leave += Control_Leave;
		kryptonLabelAuthor.MouseDown += Control_MouseDown;
		kryptonLabelAuthor.MouseEnter += Control_Enter;
		kryptonLabelAuthor.MouseLeave += Control_Leave;
		// 
		// kryptonLabelDescription
		// 
		kryptonLabelDescription.AccessibleDescription = "Shows the program description";
		kryptonLabelDescription.AccessibleName = "Program description";
		kryptonLabelDescription.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelDescription.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLabelDescription.Location = new Point(4, 116);
		kryptonLabelDescription.Name = "kryptonLabelDescription";
		kryptonLabelDescription.Size = new Size(80, 20);
		kryptonLabelDescription.TabIndex = 4;
		kryptonLabelDescription.ToolTipValues.Description = "Shows the program description.\r\nDouble-click or right-click to copy the information to the clipboard.";
		kryptonLabelDescription.ToolTipValues.EnableToolTips = true;
		kryptonLabelDescription.ToolTipValues.Heading = "Description";
		kryptonLabelDescription.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLabelDescription.Values.Text = "[Description]";
		kryptonLabelDescription.DoubleClick += CopyToClipboard_DoubleClick;
		kryptonLabelDescription.Enter += Control_Enter;
		kryptonLabelDescription.Leave += Control_Leave;
		kryptonLabelDescription.MouseDown += Control_MouseDown;
		kryptonLabelDescription.MouseEnter += Control_Enter;
		kryptonLabelDescription.MouseLeave += Control_Leave;
		// 
		// kryptonLabelCopyright
		// 
		kryptonLabelCopyright.AccessibleDescription = "Shows the copyright";
		kryptonLabelCopyright.AccessibleName = "Copyright";
		kryptonLabelCopyright.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelCopyright.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLabelCopyright.Location = new Point(4, 142);
		kryptonLabelCopyright.Name = "kryptonLabelCopyright";
		kryptonLabelCopyright.Size = new Size(72, 20);
		kryptonLabelCopyright.TabIndex = 5;
		kryptonLabelCopyright.ToolTipValues.Description = "Shows the copyright.\r\nDouble-click or right-click to copy the information to the clipboard.";
		kryptonLabelCopyright.ToolTipValues.EnableToolTips = true;
		kryptonLabelCopyright.ToolTipValues.Heading = "Copyright";
		kryptonLabelCopyright.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLabelCopyright.Values.Text = "[Copyright]";
		kryptonLabelCopyright.DoubleClick += CopyToClipboard_DoubleClick;
		kryptonLabelCopyright.Enter += Control_Enter;
		kryptonLabelCopyright.Leave += Control_Leave;
		kryptonLabelCopyright.MouseDown += Control_MouseDown;
		kryptonLabelCopyright.MouseEnter += Control_Enter;
		kryptonLabelCopyright.MouseLeave += Control_Leave;
		// 
		// kryptonLinkLabelWebsite
		// 
		kryptonLinkLabelWebsite.AccessibleDescription = "Opens the website";
		kryptonLinkLabelWebsite.AccessibleName = "Website";
		kryptonLinkLabelWebsite.AccessibleRole = AccessibleRole.Link;
		kryptonLinkLabelWebsite.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLinkLabelWebsite.LinkBehavior = KryptonLinkBehavior.HoverUnderline;
		kryptonLinkLabelWebsite.Location = new Point(408, 207);
		kryptonLinkLabelWebsite.Name = "kryptonLinkLabelWebsite";
		kryptonLinkLabelWebsite.Size = new Size(72, 20);
		kryptonLinkLabelWebsite.TabIndex = 6;
		kryptonLinkLabelWebsite.ToolTipValues.Description = "Opens the website.";
		kryptonLinkLabelWebsite.ToolTipValues.EnableToolTips = true;
		kryptonLinkLabelWebsite.ToolTipValues.Heading = "Website";
		kryptonLinkLabelWebsite.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLinkLabelWebsite.Values.Image = FatcowIcons16px.fatcow_world_16px;
		kryptonLinkLabelWebsite.Values.Text = "Website";
		kryptonLinkLabelWebsite.LinkClicked += KryptonLinkLabelWebsite_LinkClick;
		kryptonLinkLabelWebsite.Enter += Control_Enter;
		kryptonLinkLabelWebsite.Leave += Control_Leave;
		kryptonLinkLabelWebsite.MouseDown += Control_MouseDown;
		kryptonLinkLabelWebsite.MouseEnter += Control_Enter;
		kryptonLinkLabelWebsite.MouseLeave += Control_Leave;
		// 
		// kryptonLinkLabelEmail
		// 
		kryptonLinkLabelEmail.AccessibleDescription = "Opens the mail client";
		kryptonLinkLabelEmail.AccessibleName = "E-Mail";
		kryptonLinkLabelEmail.AccessibleRole = AccessibleRole.Link;
		kryptonLinkLabelEmail.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLinkLabelEmail.LinkBehavior = KryptonLinkBehavior.HoverUnderline;
		kryptonLinkLabelEmail.Location = new Point(408, 230);
		kryptonLinkLabelEmail.Name = "kryptonLinkLabelEmail";
		kryptonLinkLabelEmail.Size = new Size(62, 20);
		kryptonLinkLabelEmail.TabIndex = 7;
		kryptonLinkLabelEmail.ToolTipValues.Description = "Opens the mail client.";
		kryptonLinkLabelEmail.ToolTipValues.EnableToolTips = true;
		kryptonLinkLabelEmail.ToolTipValues.Heading = "E-Mail";
		kryptonLinkLabelEmail.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLinkLabelEmail.Values.Image = FatcowIcons16px.fatcow_email_16px;
		kryptonLinkLabelEmail.Values.Text = "E-Mail";
		kryptonLinkLabelEmail.LinkClicked += KryptonLinkLabelEmail_LinkClick;
		kryptonLinkLabelEmail.Enter += Control_Enter;
		kryptonLinkLabelEmail.Leave += Control_Leave;
		kryptonLinkLabelEmail.MouseDown += Control_MouseDown;
		kryptonLinkLabelEmail.MouseEnter += Control_Enter;
		kryptonLinkLabelEmail.MouseLeave += Control_Leave;
		// 
		// tabPageComponents
		// 
		tabPageComponents.AccessibleDescription = "Shows information about third-party components";
		tabPageComponents.AccessibleName = "Components";
		tabPageComponents.AccessibleRole = AccessibleRole.PageTab;
		tabPageComponents.Controls.Add(tabControlComponents);
		tabPageComponents.ImageKey = "fatcow_bricks_16px.png";
		tabPageComponents.Location = new Point(4, 24);
		tabPageComponents.Name = "tabPageComponents";
		tabPageComponents.Size = new Size(492, 255);
		tabPageComponents.TabIndex = 1;
		tabPageComponents.Text = "Components";
		tabPageComponents.UseVisualStyleBackColor = true;
		tabPageComponents.Enter += Control_Enter;
		tabPageComponents.Leave += Control_Leave;
		tabPageComponents.MouseEnter += Control_Enter;
		tabPageComponents.MouseLeave += Control_Leave;
		// 
		// tabControlComponents
		// 
		tabControlComponents.AccessibleDescription = "Shows tabs with components information";
		tabControlComponents.AccessibleName = "Components information tab";
		tabControlComponents.AccessibleRole = AccessibleRole.PageTabList;
		tabControlComponents.Controls.Add(tabPageComponentApplicationIcon);
		tabControlComponents.Controls.Add(tabPageIconsetFatcow);
		tabControlComponents.Controls.Add(tabPageComponentKryptonSuite);
		tabControlComponents.Controls.Add(tabPageComponentNLog);
		tabControlComponents.Dock = DockStyle.Fill;
		tabControlComponents.Location = new Point(0, 0);
		tabControlComponents.Name = "tabControlComponents";
		tabControlComponents.SelectedIndex = 0;
		tabControlComponents.ShowToolTips = true;
		tabControlComponents.Size = new Size(492, 255);
		tabControlComponents.TabIndex = 18;
		tabControlComponents.Enter += Control_Enter;
		tabControlComponents.Leave += Control_Leave;
		tabControlComponents.MouseEnter += Control_Enter;
		tabControlComponents.MouseLeave += Control_Leave;
		// 
		// tabPageComponentApplicationIcon
		// 
		tabPageComponentApplicationIcon.AccessibleDescription = "Shows tab with application icon information";
		tabPageComponentApplicationIcon.AccessibleName = "Application icon tab";
		tabPageComponentApplicationIcon.AccessibleRole = AccessibleRole.PageTab;
		tabPageComponentApplicationIcon.Controls.Add(kryptonLabelLicenseFlaticon);
		tabPageComponentApplicationIcon.Controls.Add(kryptonLinkLabelFlaticon);
		tabPageComponentApplicationIcon.Controls.Add(kryptonLabelAuthorFlaticon);
		tabPageComponentApplicationIcon.Controls.Add(kryptonTextBoxLicenseFlaticon);
		tabPageComponentApplicationIcon.Controls.Add(kryptonLabelIconHeadingFlaticon);
		tabPageComponentApplicationIcon.Location = new Point(4, 24);
		tabPageComponentApplicationIcon.Name = "tabPageComponentApplicationIcon";
		tabPageComponentApplicationIcon.Padding = new Padding(3);
		tabPageComponentApplicationIcon.Size = new Size(484, 227);
		tabPageComponentApplicationIcon.TabIndex = 0;
		tabPageComponentApplicationIcon.Text = "Application icon";
		tabPageComponentApplicationIcon.ToolTipText = "Application icon";
		tabPageComponentApplicationIcon.UseVisualStyleBackColor = true;
		tabPageComponentApplicationIcon.Enter += Control_Enter;
		tabPageComponentApplicationIcon.Leave += Control_Leave;
		tabPageComponentApplicationIcon.MouseEnter += Control_Enter;
		tabPageComponentApplicationIcon.MouseLeave += Control_Leave;
		// 
		// kryptonLabelLicenseFlaticon
		// 
		kryptonLabelLicenseFlaticon.AccessibleDescription = "Shows the Flaticon license";
		kryptonLabelLicenseFlaticon.AccessibleName = "Flaticon license";
		kryptonLabelLicenseFlaticon.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelLicenseFlaticon.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLabelLicenseFlaticon.Location = new Point(6, 32);
		kryptonLabelLicenseFlaticon.Name = "kryptonLabelLicenseFlaticon";
		kryptonLabelLicenseFlaticon.Size = new Size(139, 20);
		kryptonLabelLicenseFlaticon.TabIndex = 11;
		kryptonLabelLicenseFlaticon.ToolTipValues.Description = "Shows the Flaticon license.\r\nDouble-click or right-click to copy the information to the clipboard.";
		kryptonLabelLicenseFlaticon.ToolTipValues.EnableToolTips = true;
		kryptonLabelLicenseFlaticon.ToolTipValues.Heading = "Flaticon license";
		kryptonLabelLicenseFlaticon.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLabelLicenseFlaticon.Values.Text = "License: Flaticon license";
		kryptonLabelLicenseFlaticon.DoubleClick += CopyToClipboard_DoubleClick;
		kryptonLabelLicenseFlaticon.Enter += Control_Enter;
		kryptonLabelLicenseFlaticon.Leave += Control_Leave;
		kryptonLabelLicenseFlaticon.MouseDown += Control_MouseDown;
		kryptonLabelLicenseFlaticon.MouseEnter += Control_Enter;
		kryptonLabelLicenseFlaticon.MouseLeave += Control_Leave;
		// 
		// kryptonLinkLabelFlaticon
		// 
		kryptonLinkLabelFlaticon.AccessibleDescription = "Opens the Flaticon website";
		kryptonLinkLabelFlaticon.AccessibleName = "Flaticon website";
		kryptonLinkLabelFlaticon.AccessibleRole = AccessibleRole.Link;
		kryptonLinkLabelFlaticon.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLinkLabelFlaticon.LinkBehavior = KryptonLinkBehavior.HoverUnderline;
		kryptonLinkLabelFlaticon.Location = new Point(163, 6);
		kryptonLinkLabelFlaticon.Name = "kryptonLinkLabelFlaticon";
		kryptonLinkLabelFlaticon.Size = new Size(318, 20);
		kryptonLinkLabelFlaticon.TabIndex = 10;
		kryptonLinkLabelFlaticon.ToolTipValues.Description = "Opens the Flaticon page.\r\nRight-click to copy the information to the clipboard.";
		kryptonLinkLabelFlaticon.ToolTipValues.EnableToolTips = true;
		kryptonLinkLabelFlaticon.ToolTipValues.Heading = "Flaticon website";
		kryptonLinkLabelFlaticon.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLinkLabelFlaticon.Values.Image = FatcowIcons16px.fatcow_world_16px;
		kryptonLinkLabelFlaticon.Values.Text = "https://www.flaticon.com/free-icon/asteroid_1086068";
		kryptonLinkLabelFlaticon.DoubleClick += KryptonLinkLabelFlaticon_LinkClick;
		kryptonLinkLabelFlaticon.Enter += Control_Enter;
		kryptonLinkLabelFlaticon.Leave += Control_Leave;
		kryptonLinkLabelFlaticon.MouseDown += Control_MouseDown;
		kryptonLinkLabelFlaticon.MouseEnter += Control_Enter;
		kryptonLinkLabelFlaticon.MouseLeave += Control_Leave;
		// 
		// kryptonLabelAuthorFlaticon
		// 
		kryptonLabelAuthorFlaticon.AccessibleDescription = "Shows the Flaticon authors";
		kryptonLabelAuthorFlaticon.AccessibleName = "Flaticon authors";
		kryptonLabelAuthorFlaticon.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelAuthorFlaticon.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLabelAuthorFlaticon.Location = new Point(378, 32);
		kryptonLabelAuthorFlaticon.Name = "kryptonLabelAuthorFlaticon";
		kryptonLabelAuthorFlaticon.Size = new Size(100, 20);
		kryptonLabelAuthorFlaticon.TabIndex = 9;
		kryptonLabelAuthorFlaticon.ToolTipValues.Description = "Shows the Flaticon authors.\r\nDouble-click or right-click to copy the information to the clipboard.";
		kryptonLabelAuthorFlaticon.ToolTipValues.EnableToolTips = true;
		kryptonLabelAuthorFlaticon.ToolTipValues.Heading = "Flaticon authors";
		kryptonLabelAuthorFlaticon.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLabelAuthorFlaticon.Values.Text = "Authors: monkik";
		kryptonLabelAuthorFlaticon.DoubleClick += CopyToClipboard_DoubleClick;
		kryptonLabelAuthorFlaticon.Enter += Control_Enter;
		kryptonLabelAuthorFlaticon.Leave += Control_Leave;
		kryptonLabelAuthorFlaticon.MouseDown += Control_MouseDown;
		kryptonLabelAuthorFlaticon.MouseEnter += Control_Enter;
		kryptonLabelAuthorFlaticon.MouseLeave += Control_Leave;
		// 
		// kryptonTextBoxLicenseFlaticon
		// 
		kryptonTextBoxLicenseFlaticon.AccessibleDescription = "Shows the Flaticon license";
		kryptonTextBoxLicenseFlaticon.AccessibleName = "Flaticon license";
		kryptonTextBoxLicenseFlaticon.AccessibleRole = AccessibleRole.Text;
		kryptonTextBoxLicenseFlaticon.Location = new Point(6, 58);
		kryptonTextBoxLicenseFlaticon.Multiline = true;
		kryptonTextBoxLicenseFlaticon.Name = "kryptonTextBoxLicenseFlaticon";
		kryptonTextBoxLicenseFlaticon.ScrollBars = ScrollBars.Vertical;
		kryptonTextBoxLicenseFlaticon.Size = new Size(472, 163);
		kryptonTextBoxLicenseFlaticon.TabIndex = 4;
		kryptonTextBoxLicenseFlaticon.Text = resources.GetString("kryptonTextBoxLicenseFlaticon.Text");
		kryptonTextBoxLicenseFlaticon.ToolTipValues.Description = "Shows the Flaticon license";
		kryptonTextBoxLicenseFlaticon.ToolTipValues.EnableToolTips = true;
		kryptonTextBoxLicenseFlaticon.ToolTipValues.Heading = "Flaticon";
		kryptonTextBoxLicenseFlaticon.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonTextBoxLicenseFlaticon.Enter += Control_Enter;
		kryptonTextBoxLicenseFlaticon.Leave += Control_Leave;
		kryptonTextBoxLicenseFlaticon.MouseDown += Control_MouseDown;
		kryptonTextBoxLicenseFlaticon.MouseEnter += Control_Enter;
		kryptonTextBoxLicenseFlaticon.MouseLeave += Control_Leave;
		// 
		// kryptonLabelIconHeadingFlaticon
		// 
		kryptonLabelIconHeadingFlaticon.AccessibleDescription = "Heading for the application icon section";
		kryptonLabelIconHeadingFlaticon.AccessibleName = "Application Icon heading";
		kryptonLabelIconHeadingFlaticon.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelIconHeadingFlaticon.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLabelIconHeadingFlaticon.LabelStyle = LabelStyle.BoldControl;
		kryptonLabelIconHeadingFlaticon.Location = new Point(6, 6);
		kryptonLabelIconHeadingFlaticon.Name = "kryptonLabelIconHeadingFlaticon";
		kryptonLabelIconHeadingFlaticon.Size = new Size(106, 20);
		kryptonLabelIconHeadingFlaticon.TabIndex = 0;
		kryptonLabelIconHeadingFlaticon.ToolTipValues.Description = "Heading for the application icon section.\r\nDouble-click or right-click to copy the information to the clipboard.";
		kryptonLabelIconHeadingFlaticon.ToolTipValues.EnableToolTips = true;
		kryptonLabelIconHeadingFlaticon.ToolTipValues.Heading = "Application Icon";
		kryptonLabelIconHeadingFlaticon.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLabelIconHeadingFlaticon.Values.Text = "Application Icon";
		kryptonLabelIconHeadingFlaticon.DoubleClick += CopyToClipboard_DoubleClick;
		kryptonLabelIconHeadingFlaticon.Enter += Control_Enter;
		kryptonLabelIconHeadingFlaticon.Leave += Control_Leave;
		kryptonLabelIconHeadingFlaticon.MouseDown += Control_MouseDown;
		kryptonLabelIconHeadingFlaticon.MouseEnter += Control_Enter;
		kryptonLabelIconHeadingFlaticon.MouseLeave += Control_Leave;
		// 
		// tabPageIconsetFatcow
		// 
		tabPageIconsetFatcow.AccessibleDescription = "Shows tab with FatCow icons information";
		tabPageIconsetFatcow.AccessibleName = "FatCow icons tab";
		tabPageIconsetFatcow.AccessibleRole = AccessibleRole.PageTab;
		tabPageIconsetFatcow.Controls.Add(kryptonTextBoxLicenseFatcow);
		tabPageIconsetFatcow.Controls.Add(kryptonLabelHeadingFatcowIcons);
		tabPageIconsetFatcow.Controls.Add(kryptonLabelLicenseFatcow);
		tabPageIconsetFatcow.Controls.Add(kryptonLinkLabelWebsiteFatcow);
		tabPageIconsetFatcow.Controls.Add(kryptonLabelAuthorsFatcow);
		tabPageIconsetFatcow.Location = new Point(4, 24);
		tabPageIconsetFatcow.Name = "tabPageIconsetFatcow";
		tabPageIconsetFatcow.Padding = new Padding(3);
		tabPageIconsetFatcow.Size = new Size(484, 227);
		tabPageIconsetFatcow.TabIndex = 1;
		tabPageIconsetFatcow.Text = "FatCow Icons";
		tabPageIconsetFatcow.ToolTipText = "FatCow Icons";
		tabPageIconsetFatcow.UseVisualStyleBackColor = true;
		tabPageIconsetFatcow.Enter += Control_Enter;
		tabPageIconsetFatcow.Leave += Control_Leave;
		tabPageIconsetFatcow.MouseEnter += Control_Enter;
		tabPageIconsetFatcow.MouseLeave += Control_Leave;
		// 
		// kryptonTextBoxLicenseFatcow
		// 
		kryptonTextBoxLicenseFatcow.AccessibleDescription = "Shows the CC BY 3.0 license";
		kryptonTextBoxLicenseFatcow.AccessibleName = "CC BY 3.0 license";
		kryptonTextBoxLicenseFatcow.AccessibleRole = AccessibleRole.Text;
		kryptonTextBoxLicenseFatcow.Location = new Point(6, 58);
		kryptonTextBoxLicenseFatcow.Multiline = true;
		kryptonTextBoxLicenseFatcow.Name = "kryptonTextBoxLicenseFatcow";
		kryptonTextBoxLicenseFatcow.ScrollBars = ScrollBars.Vertical;
		kryptonTextBoxLicenseFatcow.Size = new Size(472, 163);
		kryptonTextBoxLicenseFatcow.TabIndex = 18;
		kryptonTextBoxLicenseFatcow.Text = resources.GetString("kryptonTextBoxLicenseFatcow.Text");
		kryptonTextBoxLicenseFatcow.ToolTipValues.Description = "Shows the CC BY 3.0 license";
		kryptonTextBoxLicenseFatcow.ToolTipValues.EnableToolTips = true;
		kryptonTextBoxLicenseFatcow.ToolTipValues.Heading = "CC BY 3.0 license";
		kryptonTextBoxLicenseFatcow.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonTextBoxLicenseFatcow.Enter += Control_Enter;
		kryptonTextBoxLicenseFatcow.Leave += Control_Leave;
		kryptonTextBoxLicenseFatcow.MouseDown += Control_MouseDown;
		kryptonTextBoxLicenseFatcow.MouseEnter += Control_Enter;
		kryptonTextBoxLicenseFatcow.MouseLeave += Control_Leave;
		// 
		// kryptonLabelHeadingFatcowIcons
		// 
		kryptonLabelHeadingFatcowIcons.AccessibleDescription = "Heading for the FatCow Icons section";
		kryptonLabelHeadingFatcowIcons.AccessibleName = "FatCow Icons heading";
		kryptonLabelHeadingFatcowIcons.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelHeadingFatcowIcons.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLabelHeadingFatcowIcons.LabelStyle = LabelStyle.BoldControl;
		kryptonLabelHeadingFatcowIcons.Location = new Point(6, 6);
		kryptonLabelHeadingFatcowIcons.Name = "kryptonLabelHeadingFatcowIcons";
		kryptonLabelHeadingFatcowIcons.Size = new Size(93, 20);
		kryptonLabelHeadingFatcowIcons.TabIndex = 14;
		kryptonLabelHeadingFatcowIcons.ToolTipValues.Description = "Header for the FatCow Icons section\r\nDouble-click or right-click to copy the information to the clipboard.";
		kryptonLabelHeadingFatcowIcons.ToolTipValues.EnableToolTips = true;
		kryptonLabelHeadingFatcowIcons.ToolTipValues.Heading = "FatCow Icons";
		kryptonLabelHeadingFatcowIcons.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLabelHeadingFatcowIcons.Values.Text = "FatCow Icons";
		kryptonLabelHeadingFatcowIcons.DoubleClick += CopyToClipboard_DoubleClick;
		kryptonLabelHeadingFatcowIcons.Enter += Control_Enter;
		kryptonLabelHeadingFatcowIcons.Leave += Control_Leave;
		kryptonLabelHeadingFatcowIcons.MouseDown += Control_MouseDown;
		kryptonLabelHeadingFatcowIcons.MouseEnter += Control_Enter;
		kryptonLabelHeadingFatcowIcons.MouseLeave += Control_Leave;
		// 
		// kryptonLabelLicenseFatcow
		// 
		kryptonLabelLicenseFatcow.AccessibleDescription = "Shows the FatCow Icons license";
		kryptonLabelLicenseFatcow.AccessibleName = "FatCow Icons license";
		kryptonLabelLicenseFatcow.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelLicenseFatcow.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLabelLicenseFatcow.Location = new Point(6, 32);
		kryptonLabelLicenseFatcow.Name = "kryptonLabelLicenseFatcow";
		kryptonLabelLicenseFatcow.Size = new Size(108, 20);
		kryptonLabelLicenseFatcow.TabIndex = 17;
		kryptonLabelLicenseFatcow.ToolTipValues.Description = "Shows the FatCow Icons license.\r\nDouble-click or right-click to copy the information to the clipboard.";
		kryptonLabelLicenseFatcow.ToolTipValues.EnableToolTips = true;
		kryptonLabelLicenseFatcow.ToolTipValues.Heading = "FatCow Icons license";
		kryptonLabelLicenseFatcow.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLabelLicenseFatcow.Values.Text = "License: CC BY 3.0";
		kryptonLabelLicenseFatcow.DoubleClick += CopyToClipboard_DoubleClick;
		kryptonLabelLicenseFatcow.Enter += Control_Enter;
		kryptonLabelLicenseFatcow.Leave += Control_Leave;
		kryptonLabelLicenseFatcow.MouseDown += Control_MouseDown;
		kryptonLabelLicenseFatcow.MouseEnter += Control_Enter;
		kryptonLabelLicenseFatcow.MouseLeave += Control_Leave;
		// 
		// kryptonLinkLabelWebsiteFatcow
		// 
		kryptonLinkLabelWebsiteFatcow.AccessibleDescription = "Opens the FatCow Icons website";
		kryptonLinkLabelWebsiteFatcow.AccessibleName = "FatCow Icons website";
		kryptonLinkLabelWebsiteFatcow.AccessibleRole = AccessibleRole.Link;
		kryptonLinkLabelWebsiteFatcow.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLinkLabelWebsiteFatcow.LinkBehavior = KryptonLinkBehavior.HoverUnderline;
		kryptonLinkLabelWebsiteFatcow.Location = new Point(289, 6);
		kryptonLinkLabelWebsiteFatcow.Name = "kryptonLinkLabelWebsiteFatcow";
		kryptonLinkLabelWebsiteFatcow.Size = new Size(189, 20);
		kryptonLinkLabelWebsiteFatcow.TabIndex = 16;
		kryptonLinkLabelWebsiteFatcow.ToolTipValues.Description = "Opens the FatCow Icons website.";
		kryptonLinkLabelWebsiteFatcow.ToolTipValues.EnableToolTips = true;
		kryptonLinkLabelWebsiteFatcow.ToolTipValues.Heading = "FatCow Icons website";
		kryptonLinkLabelWebsiteFatcow.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLinkLabelWebsiteFatcow.Values.Image = FatcowIcons16px.fatcow_world_16px;
		kryptonLinkLabelWebsiteFatcow.Values.Text = "https://fatcow.com/free-icons";
		kryptonLinkLabelWebsiteFatcow.LinkClicked += KryptonLinkLabelFatCow_LinkClick;
		kryptonLinkLabelWebsiteFatcow.Enter += Control_Enter;
		kryptonLinkLabelWebsiteFatcow.Leave += Control_Leave;
		kryptonLinkLabelWebsiteFatcow.MouseDown += Control_MouseDown;
		kryptonLinkLabelWebsiteFatcow.MouseEnter += Control_Enter;
		kryptonLinkLabelWebsiteFatcow.MouseLeave += Control_Leave;
		// 
		// kryptonLabelAuthorsFatcow
		// 
		kryptonLabelAuthorsFatcow.AccessibleDescription = "Shows the FatCow Icons author";
		kryptonLabelAuthorsFatcow.AccessibleName = "FatCow Icons author";
		kryptonLabelAuthorsFatcow.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelAuthorsFatcow.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLabelAuthorsFatcow.Location = new Point(309, 32);
		kryptonLabelAuthorsFatcow.Name = "kryptonLabelAuthorsFatcow";
		kryptonLabelAuthorsFatcow.Size = new Size(169, 20);
		kryptonLabelAuthorsFatcow.TabIndex = 15;
		kryptonLabelAuthorsFatcow.ToolTipValues.Description = "Shows the FatCow Icons author.\r\nDouble-click or right-click to copy the information to the clipboard.";
		kryptonLabelAuthorsFatcow.ToolTipValues.EnableToolTips = true;
		kryptonLabelAuthorsFatcow.ToolTipValues.Heading = "FatCow Icons author";
		kryptonLabelAuthorsFatcow.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLabelAuthorsFatcow.Values.Text = "Author: FatCow Web Hosting";
		kryptonLabelAuthorsFatcow.DoubleClick += CopyToClipboard_DoubleClick;
		kryptonLabelAuthorsFatcow.Enter += Control_Enter;
		kryptonLabelAuthorsFatcow.Leave += Control_Leave;
		kryptonLabelAuthorsFatcow.MouseDown += Control_MouseDown;
		kryptonLabelAuthorsFatcow.MouseEnter += Control_Enter;
		kryptonLabelAuthorsFatcow.MouseLeave += Control_Leave;
		// 
		// tabPageComponentKryptonSuite
		// 
		tabPageComponentKryptonSuite.AccessibleDescription = "Shows tab with Krypton Suite information";
		tabPageComponentKryptonSuite.AccessibleName = "Krypton Suite tab";
		tabPageComponentKryptonSuite.AccessibleRole = AccessibleRole.PageTab;
		tabPageComponentKryptonSuite.Controls.Add(kryptonTextBoxLicenseKryptonSuite);
		tabPageComponentKryptonSuite.Controls.Add(kryptonLabelHeadingKryptonSuite);
		tabPageComponentKryptonSuite.Controls.Add(kryptonLabelLicenseKryptonSuite);
		tabPageComponentKryptonSuite.Controls.Add(kryptonLabelVersionKryptonSuite);
		tabPageComponentKryptonSuite.Controls.Add(kryptonLinkLabelWebsiteKryptonSuite);
		tabPageComponentKryptonSuite.Controls.Add(kryptonLabelAuthorsKryptonSuite);
		tabPageComponentKryptonSuite.Location = new Point(4, 24);
		tabPageComponentKryptonSuite.Name = "tabPageComponentKryptonSuite";
		tabPageComponentKryptonSuite.Padding = new Padding(3);
		tabPageComponentKryptonSuite.Size = new Size(484, 227);
		tabPageComponentKryptonSuite.TabIndex = 2;
		tabPageComponentKryptonSuite.Text = "Krypton Suite";
		tabPageComponentKryptonSuite.ToolTipText = "Krypton Suite";
		tabPageComponentKryptonSuite.UseVisualStyleBackColor = true;
		tabPageComponentKryptonSuite.Enter += Control_Enter;
		tabPageComponentKryptonSuite.Leave += Control_Leave;
		tabPageComponentKryptonSuite.MouseEnter += Control_Enter;
		tabPageComponentKryptonSuite.MouseLeave += Control_Leave;
		// 
		// kryptonTextBoxLicenseKryptonSuite
		// 
		kryptonTextBoxLicenseKryptonSuite.AccessibleDescription = "Shows the Krypton Suite BSD 3-Clause license";
		kryptonTextBoxLicenseKryptonSuite.AccessibleName = "Krypton Suite license";
		kryptonTextBoxLicenseKryptonSuite.AccessibleRole = AccessibleRole.Text;
		kryptonTextBoxLicenseKryptonSuite.Location = new Point(6, 84);
		kryptonTextBoxLicenseKryptonSuite.Multiline = true;
		kryptonTextBoxLicenseKryptonSuite.Name = "kryptonTextBoxLicenseKryptonSuite";
		kryptonTextBoxLicenseKryptonSuite.ScrollBars = ScrollBars.Vertical;
		kryptonTextBoxLicenseKryptonSuite.Size = new Size(472, 137);
		kryptonTextBoxLicenseKryptonSuite.TabIndex = 19;
		kryptonTextBoxLicenseKryptonSuite.Text = resources.GetString("kryptonTextBoxLicenseKryptonSuite.Text");
		kryptonTextBoxLicenseKryptonSuite.ToolTipValues.Description = "Shows the BSD 3-Clause license";
		kryptonTextBoxLicenseKryptonSuite.ToolTipValues.EnableToolTips = true;
		kryptonTextBoxLicenseKryptonSuite.ToolTipValues.Heading = "BSD 3-Clause license";
		kryptonTextBoxLicenseKryptonSuite.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonTextBoxLicenseKryptonSuite.Enter += Control_Enter;
		kryptonTextBoxLicenseKryptonSuite.Leave += Control_Leave;
		kryptonTextBoxLicenseKryptonSuite.MouseEnter += Control_Enter;
		kryptonTextBoxLicenseKryptonSuite.MouseLeave += Control_Leave;
		// 
		// kryptonLabelHeadingKryptonSuite
		// 
		kryptonLabelHeadingKryptonSuite.AccessibleDescription = "Heading for the Krypton Suite section";
		kryptonLabelHeadingKryptonSuite.AccessibleName = "Krypton Suite heading";
		kryptonLabelHeadingKryptonSuite.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelHeadingKryptonSuite.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLabelHeadingKryptonSuite.LabelStyle = LabelStyle.BoldControl;
		kryptonLabelHeadingKryptonSuite.Location = new Point(6, 6);
		kryptonLabelHeadingKryptonSuite.Name = "kryptonLabelHeadingKryptonSuite";
		kryptonLabelHeadingKryptonSuite.Size = new Size(191, 20);
		kryptonLabelHeadingKryptonSuite.TabIndex = 4;
		kryptonLabelHeadingKryptonSuite.ToolTipValues.Description = "Heading for the Krypton Suite section.\r\nDouble-click or right-click to copy the information to the clipboard.";
		kryptonLabelHeadingKryptonSuite.ToolTipValues.EnableToolTips = true;
		kryptonLabelHeadingKryptonSuite.ToolTipValues.Heading = "Krypton Suite Standard Toolkit";
		kryptonLabelHeadingKryptonSuite.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLabelHeadingKryptonSuite.Values.Text = "Krypton Suite Standard Toolkit";
		kryptonLabelHeadingKryptonSuite.DoubleClick += CopyToClipboard_DoubleClick;
		kryptonLabelHeadingKryptonSuite.Enter += Control_Enter;
		kryptonLabelHeadingKryptonSuite.Leave += Control_Leave;
		kryptonLabelHeadingKryptonSuite.MouseDown += Control_MouseDown;
		kryptonLabelHeadingKryptonSuite.MouseEnter += Control_Enter;
		kryptonLabelHeadingKryptonSuite.MouseLeave += Control_Leave;
		// 
		// kryptonLabelLicenseKryptonSuite
		// 
		kryptonLabelLicenseKryptonSuite.AccessibleDescription = "Shows the Krypton Suite license";
		kryptonLabelLicenseKryptonSuite.AccessibleName = "Krypton Suite license";
		kryptonLabelLicenseKryptonSuite.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelLicenseKryptonSuite.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLabelLicenseKryptonSuite.Location = new Point(6, 58);
		kryptonLabelLicenseKryptonSuite.Name = "kryptonLabelLicenseKryptonSuite";
		kryptonLabelLicenseKryptonSuite.Size = new Size(129, 20);
		kryptonLabelLicenseKryptonSuite.TabIndex = 8;
		kryptonLabelLicenseKryptonSuite.ToolTipValues.Description = "Shows the Krypton Suite license.\r\nDouble-click or right-click to copy the information to the clipboard.";
		kryptonLabelLicenseKryptonSuite.ToolTipValues.EnableToolTips = true;
		kryptonLabelLicenseKryptonSuite.ToolTipValues.Heading = "Krypton Suite license";
		kryptonLabelLicenseKryptonSuite.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLabelLicenseKryptonSuite.Values.Text = "License: BSD 3-Clause";
		kryptonLabelLicenseKryptonSuite.DoubleClick += CopyToClipboard_DoubleClick;
		kryptonLabelLicenseKryptonSuite.Enter += Control_Enter;
		kryptonLabelLicenseKryptonSuite.Leave += Control_Leave;
		kryptonLabelLicenseKryptonSuite.MouseDown += Control_MouseDown;
		kryptonLabelLicenseKryptonSuite.MouseEnter += Control_Enter;
		kryptonLabelLicenseKryptonSuite.MouseLeave += Control_Leave;
		// 
		// kryptonLabelVersionKryptonSuite
		// 
		kryptonLabelVersionKryptonSuite.AccessibleDescription = "Shows the Krypton Suite version";
		kryptonLabelVersionKryptonSuite.AccessibleName = "Krypton Suite version";
		kryptonLabelVersionKryptonSuite.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelVersionKryptonSuite.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLabelVersionKryptonSuite.Location = new Point(6, 32);
		kryptonLabelVersionKryptonSuite.Name = "kryptonLabelVersionKryptonSuite";
		kryptonLabelVersionKryptonSuite.Size = new Size(119, 20);
		kryptonLabelVersionKryptonSuite.TabIndex = 5;
		kryptonLabelVersionKryptonSuite.ToolTipValues.Description = "Shows the Krypton Suite version.\r\nDouble-click or right-click to copy the information to the clipboard.";
		kryptonLabelVersionKryptonSuite.ToolTipValues.EnableToolTips = true;
		kryptonLabelVersionKryptonSuite.ToolTipValues.Heading = "Krypton Suite version";
		kryptonLabelVersionKryptonSuite.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLabelVersionKryptonSuite.Values.Text = "Version: 100.26.1.19";
		kryptonLabelVersionKryptonSuite.DoubleClick += CopyToClipboard_DoubleClick;
		kryptonLabelVersionKryptonSuite.Enter += Control_Enter;
		kryptonLabelVersionKryptonSuite.Leave += Control_Leave;
		kryptonLabelVersionKryptonSuite.MouseDown += Control_MouseDown;
		kryptonLabelVersionKryptonSuite.MouseEnter += Control_Enter;
		kryptonLabelVersionKryptonSuite.MouseLeave += Control_Leave;
		// 
		// kryptonLinkLabelWebsiteKryptonSuite
		// 
		kryptonLinkLabelWebsiteKryptonSuite.AccessibleDescription = "Opens the Krypton Suite website";
		kryptonLinkLabelWebsiteKryptonSuite.AccessibleName = "Krypton Suite website";
		kryptonLinkLabelWebsiteKryptonSuite.AccessibleRole = AccessibleRole.Link;
		kryptonLinkLabelWebsiteKryptonSuite.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLinkLabelWebsiteKryptonSuite.LinkBehavior = KryptonLinkBehavior.HoverUnderline;
		kryptonLinkLabelWebsiteKryptonSuite.Location = new Point(268, 6);
		kryptonLinkLabelWebsiteKryptonSuite.Name = "kryptonLinkLabelWebsiteKryptonSuite";
		kryptonLinkLabelWebsiteKryptonSuite.Size = new Size(210, 20);
		kryptonLinkLabelWebsiteKryptonSuite.TabIndex = 7;
		kryptonLinkLabelWebsiteKryptonSuite.ToolTipValues.Description = "Opens the Krypton Suite GitHub page.\r\nRight-click to copy the information to the clipboard.";
		kryptonLinkLabelWebsiteKryptonSuite.ToolTipValues.EnableToolTips = true;
		kryptonLinkLabelWebsiteKryptonSuite.ToolTipValues.Heading = "Krypton Suite website";
		kryptonLinkLabelWebsiteKryptonSuite.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLinkLabelWebsiteKryptonSuite.Values.Image = FatcowIcons16px.fatcow_world_16px;
		kryptonLinkLabelWebsiteKryptonSuite.Values.Text = "https://github.com/Krypton-Suite";
		kryptonLinkLabelWebsiteKryptonSuite.LinkClicked += KryptonLinkLabelKryptonSuite_LinkClick;
		kryptonLinkLabelWebsiteKryptonSuite.Enter += Control_Enter;
		kryptonLinkLabelWebsiteKryptonSuite.Leave += Control_Leave;
		kryptonLinkLabelWebsiteKryptonSuite.MouseDown += Control_MouseDown;
		kryptonLinkLabelWebsiteKryptonSuite.MouseEnter += Control_Enter;
		kryptonLinkLabelWebsiteKryptonSuite.MouseLeave += Control_Leave;
		// 
		// kryptonLabelAuthorsKryptonSuite
		// 
		kryptonLabelAuthorsKryptonSuite.AccessibleDescription = "Shows the Krypton Suite authors";
		kryptonLabelAuthorsKryptonSuite.AccessibleName = "Krypton Suite authors";
		kryptonLabelAuthorsKryptonSuite.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelAuthorsKryptonSuite.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLabelAuthorsKryptonSuite.Location = new Point(273, 32);
		kryptonLabelAuthorsKryptonSuite.Name = "kryptonLabelAuthorsKryptonSuite";
		kryptonLabelAuthorsKryptonSuite.Size = new Size(205, 20);
		kryptonLabelAuthorsKryptonSuite.TabIndex = 6;
		kryptonLabelAuthorsKryptonSuite.ToolTipValues.Description = "Shows the Krypton Suite authors.\r\nDouble-click or right-click to copy the information to the clipboard.";
		kryptonLabelAuthorsKryptonSuite.ToolTipValues.EnableToolTips = true;
		kryptonLabelAuthorsKryptonSuite.ToolTipValues.Heading = "Krypton Suite authors";
		kryptonLabelAuthorsKryptonSuite.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLabelAuthorsKryptonSuite.Values.Text = "Authors: Krypton-Suite contributors";
		kryptonLabelAuthorsKryptonSuite.DoubleClick += CopyToClipboard_DoubleClick;
		kryptonLabelAuthorsKryptonSuite.Enter += Control_Enter;
		kryptonLabelAuthorsKryptonSuite.Leave += Control_Leave;
		kryptonLabelAuthorsKryptonSuite.MouseDown += Control_MouseDown;
		kryptonLabelAuthorsKryptonSuite.MouseEnter += Control_Enter;
		kryptonLabelAuthorsKryptonSuite.MouseLeave += Control_Leave;
		// 
		// tabPageComponentNLog
		// 
		tabPageComponentNLog.AccessibleDescription = "Shows tab with NLog information";
		tabPageComponentNLog.AccessibleName = "NLog information tab";
		tabPageComponentNLog.AccessibleRole = AccessibleRole.PageTab;
		tabPageComponentNLog.Controls.Add(kryptonTextBoxLicenseNlog);
		tabPageComponentNLog.Controls.Add(kryptonLabelHeadingNlog);
		tabPageComponentNLog.Controls.Add(kryptonLabelLicenseNlog);
		tabPageComponentNLog.Controls.Add(kryptonLabelVersionNlog);
		tabPageComponentNLog.Controls.Add(kryptonLinkLabelWebsiteNlog);
		tabPageComponentNLog.Controls.Add(kryptonLabelAuthorsNlog);
		tabPageComponentNLog.Location = new Point(4, 24);
		tabPageComponentNLog.Name = "tabPageComponentNLog";
		tabPageComponentNLog.Padding = new Padding(3);
		tabPageComponentNLog.Size = new Size(484, 227);
		tabPageComponentNLog.TabIndex = 3;
		tabPageComponentNLog.Text = "NLog";
		tabPageComponentNLog.ToolTipText = "NLog";
		tabPageComponentNLog.UseVisualStyleBackColor = true;
		tabPageComponentNLog.Enter += Control_Enter;
		tabPageComponentNLog.Leave += Control_Leave;
		tabPageComponentNLog.MouseEnter += Control_Enter;
		tabPageComponentNLog.MouseLeave += Control_Leave;
		// 
		// kryptonTextBoxLicenseNlog
		// 
		kryptonTextBoxLicenseNlog.AccessibleDescription = "Shows the BSD 3-Clause license";
		kryptonTextBoxLicenseNlog.AccessibleName = "BSD 3-Clause license";
		kryptonTextBoxLicenseNlog.AccessibleRole = AccessibleRole.Text;
		kryptonTextBoxLicenseNlog.Location = new Point(6, 84);
		kryptonTextBoxLicenseNlog.Multiline = true;
		kryptonTextBoxLicenseNlog.Name = "kryptonTextBoxLicenseNlog";
		kryptonTextBoxLicenseNlog.ScrollBars = ScrollBars.Vertical;
		kryptonTextBoxLicenseNlog.Size = new Size(472, 137);
		kryptonTextBoxLicenseNlog.TabIndex = 19;
		kryptonTextBoxLicenseNlog.Text = resources.GetString("kryptonTextBoxLicenseNlog.Text");
		kryptonTextBoxLicenseNlog.ToolTipValues.Description = "Shows the BSD 3-Clause license";
		kryptonTextBoxLicenseNlog.ToolTipValues.EnableToolTips = true;
		kryptonTextBoxLicenseNlog.ToolTipValues.Heading = "BSD 3-Clause License";
		kryptonTextBoxLicenseNlog.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonTextBoxLicenseNlog.Enter += Control_Enter;
		kryptonTextBoxLicenseNlog.Leave += Control_Leave;
		kryptonTextBoxLicenseNlog.MouseEnter += Control_Enter;
		kryptonTextBoxLicenseNlog.MouseLeave += Control_Leave;
		// 
		// kryptonLabelHeadingNlog
		// 
		kryptonLabelHeadingNlog.AccessibleDescription = "Heading for the NLog section";
		kryptonLabelHeadingNlog.AccessibleName = "NLog heading";
		kryptonLabelHeadingNlog.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelHeadingNlog.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLabelHeadingNlog.LabelStyle = LabelStyle.BoldControl;
		kryptonLabelHeadingNlog.Location = new Point(6, 6);
		kryptonLabelHeadingNlog.Name = "kryptonLabelHeadingNlog";
		kryptonLabelHeadingNlog.Size = new Size(42, 20);
		kryptonLabelHeadingNlog.TabIndex = 9;
		kryptonLabelHeadingNlog.ToolTipValues.Description = "Heading for the NLog section.\r\nDouble-click or right-click to copy the information to the clipboard.";
		kryptonLabelHeadingNlog.ToolTipValues.EnableToolTips = true;
		kryptonLabelHeadingNlog.ToolTipValues.Heading = "NLog";
		kryptonLabelHeadingNlog.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLabelHeadingNlog.Values.Text = "NLog";
		kryptonLabelHeadingNlog.DoubleClick += CopyToClipboard_DoubleClick;
		kryptonLabelHeadingNlog.Enter += Control_Enter;
		kryptonLabelHeadingNlog.Leave += Control_Leave;
		kryptonLabelHeadingNlog.MouseDown += Control_MouseDown;
		kryptonLabelHeadingNlog.MouseEnter += Control_Enter;
		kryptonLabelHeadingNlog.MouseLeave += Control_Leave;
		// 
		// kryptonLabelLicenseNlog
		// 
		kryptonLabelLicenseNlog.AccessibleDescription = "Shows the NLog license";
		kryptonLabelLicenseNlog.AccessibleName = "NLog license";
		kryptonLabelLicenseNlog.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelLicenseNlog.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLabelLicenseNlog.Location = new Point(6, 58);
		kryptonLabelLicenseNlog.Name = "kryptonLabelLicenseNlog";
		kryptonLabelLicenseNlog.Size = new Size(129, 20);
		kryptonLabelLicenseNlog.TabIndex = 13;
		kryptonLabelLicenseNlog.ToolTipValues.Description = "Shows the NLog license.\r\nDouble-click or right-click to copy the information to the clipboard.";
		kryptonLabelLicenseNlog.ToolTipValues.EnableToolTips = true;
		kryptonLabelLicenseNlog.ToolTipValues.Heading = "NLog license";
		kryptonLabelLicenseNlog.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLabelLicenseNlog.Values.Text = "License: BSD 3-Clause";
		kryptonLabelLicenseNlog.DoubleClick += CopyToClipboard_DoubleClick;
		kryptonLabelLicenseNlog.Enter += Control_Enter;
		kryptonLabelLicenseNlog.Leave += Control_Leave;
		kryptonLabelLicenseNlog.MouseDown += Control_MouseDown;
		kryptonLabelLicenseNlog.MouseEnter += Control_Enter;
		kryptonLabelLicenseNlog.MouseLeave += Control_Leave;
		// 
		// kryptonLabelVersionNlog
		// 
		kryptonLabelVersionNlog.AccessibleDescription = "Shows the NLog version";
		kryptonLabelVersionNlog.AccessibleName = "NLog version";
		kryptonLabelVersionNlog.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelVersionNlog.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLabelVersionNlog.Location = new Point(6, 32);
		kryptonLabelVersionNlog.Name = "kryptonLabelVersionNlog";
		kryptonLabelVersionNlog.Size = new Size(83, 20);
		kryptonLabelVersionNlog.TabIndex = 10;
		kryptonLabelVersionNlog.ToolTipValues.Description = "Shows the NLog version.\r\nDouble-click or right-click to copy the information to the clipboard.";
		kryptonLabelVersionNlog.ToolTipValues.EnableToolTips = true;
		kryptonLabelVersionNlog.ToolTipValues.Heading = "NLog version";
		kryptonLabelVersionNlog.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLabelVersionNlog.Values.Text = "Version: 6.1.1";
		kryptonLabelVersionNlog.DoubleClick += CopyToClipboard_DoubleClick;
		kryptonLabelVersionNlog.Enter += Control_Enter;
		kryptonLabelVersionNlog.Leave += Control_Leave;
		kryptonLabelVersionNlog.MouseDown += Control_MouseDown;
		kryptonLabelVersionNlog.MouseEnter += Control_Enter;
		kryptonLabelVersionNlog.MouseLeave += Control_Leave;
		// 
		// kryptonLinkLabelWebsiteNlog
		// 
		kryptonLinkLabelWebsiteNlog.AccessibleDescription = "Opens the NLog website";
		kryptonLinkLabelWebsiteNlog.AccessibleName = "NLog website";
		kryptonLinkLabelWebsiteNlog.AccessibleRole = AccessibleRole.Link;
		kryptonLinkLabelWebsiteNlog.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLinkLabelWebsiteNlog.LinkBehavior = KryptonLinkBehavior.HoverUnderline;
		kryptonLinkLabelWebsiteNlog.Location = new Point(321, 6);
		kryptonLinkLabelWebsiteNlog.Name = "kryptonLinkLabelWebsiteNlog";
		kryptonLinkLabelWebsiteNlog.Size = new Size(157, 20);
		kryptonLinkLabelWebsiteNlog.TabIndex = 12;
		kryptonLinkLabelWebsiteNlog.ToolTipValues.Description = "Opens the NLog website.\r\nRight-click to copy the information to the clipboard.";
		kryptonLinkLabelWebsiteNlog.ToolTipValues.EnableToolTips = true;
		kryptonLinkLabelWebsiteNlog.ToolTipValues.Heading = "NLog website";
		kryptonLinkLabelWebsiteNlog.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLinkLabelWebsiteNlog.Values.Image = FatcowIcons16px.fatcow_world_16px;
		kryptonLinkLabelWebsiteNlog.Values.Text = "https://nlog-project.org";
		kryptonLinkLabelWebsiteNlog.LinkClicked += KryptonLinkLabelNLog_LinkClick;
		kryptonLinkLabelWebsiteNlog.Enter += Control_Enter;
		kryptonLinkLabelWebsiteNlog.Leave += Control_Leave;
		kryptonLinkLabelWebsiteNlog.MouseDown += Control_MouseDown;
		kryptonLinkLabelWebsiteNlog.MouseEnter += Control_Enter;
		kryptonLinkLabelWebsiteNlog.MouseLeave += Control_Leave;
		// 
		// kryptonLabelAuthorsNlog
		// 
		kryptonLabelAuthorsNlog.AccessibleDescription = "Shows the NLog authors";
		kryptonLabelAuthorsNlog.AccessibleName = "NLog authors";
		kryptonLabelAuthorsNlog.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelAuthorsNlog.ContextMenuStrip = contextMenuStripCopyToClipboard;
		kryptonLabelAuthorsNlog.Location = new Point(201, 32);
		kryptonLabelAuthorsNlog.Name = "kryptonLabelAuthorsNlog";
		kryptonLabelAuthorsNlog.Size = new Size(277, 20);
		kryptonLabelAuthorsNlog.TabIndex = 11;
		kryptonLabelAuthorsNlog.ToolTipValues.Description = "Shows the NLog authors.\r\nDouble-click or right-click to copy the information to the clipboard.";
		kryptonLabelAuthorsNlog.ToolTipValues.EnableToolTips = true;
		kryptonLabelAuthorsNlog.ToolTipValues.Heading = "NLog authors";
		kryptonLabelAuthorsNlog.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonLabelAuthorsNlog.Values.Text = "Authors: J. Kowalski, K. Christensen, J. Verdurmen";
		kryptonLabelAuthorsNlog.DoubleClick += CopyToClipboard_DoubleClick;
		kryptonLabelAuthorsNlog.Enter += Control_Enter;
		kryptonLabelAuthorsNlog.Leave += Control_Leave;
		kryptonLabelAuthorsNlog.MouseDown += Control_MouseDown;
		kryptonLabelAuthorsNlog.MouseEnter += Control_Enter;
		kryptonLabelAuthorsNlog.MouseLeave += Control_Leave;
		// 
		// imageListTabAbout
		// 
		imageListTabAbout.ColorDepth = ColorDepth.Depth32Bit;
		imageListTabAbout.ImageStream = (ImageListStreamer)resources.GetObject("imageListTabAbout.ImageStream");
		imageListTabAbout.TransparentColor = Color.Transparent;
		imageListTabAbout.Images.SetKeyName(0, "fatcow_information_16px.png");
		imageListTabAbout.Images.SetKeyName(1, "fatcow_bricks_16px.png");
		// 
		// pictureBoxBanner
		// 
		pictureBoxBanner.AccessibleDescription = "Shows the banner";
		pictureBoxBanner.AccessibleName = "Banner";
		pictureBoxBanner.AccessibleRole = AccessibleRole.Graphic;
		pictureBoxBanner.Image = (Image)resources.GetObject("pictureBoxBanner.Image");
		pictureBoxBanner.Location = new Point(4, 3);
		pictureBoxBanner.Name = "pictureBoxBanner";
		pictureBoxBanner.Size = new Size(500, 174);
		pictureBoxBanner.TabIndex = 0;
		pictureBoxBanner.TabStop = false;
		pictureBoxBanner.ToolTipValues.Description = "Shows the banner.";
		pictureBoxBanner.ToolTipValues.EnableToolTips = true;
		pictureBoxBanner.ToolTipValues.Heading = "Banner";
		pictureBoxBanner.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		pictureBoxBanner.MouseEnter += Control_Enter;
		pictureBoxBanner.MouseLeave += Control_Leave;
		// 
		// kryptoPanelMain
		// 
		kryptoPanelMain.AccessibleDescription = "Groups the data";
		kryptoPanelMain.AccessibleName = "pane";
		kryptoPanelMain.AccessibleRole = AccessibleRole.Pane;
		kryptoPanelMain.Controls.Add(pictureBoxBanner);
		kryptoPanelMain.Controls.Add(tabControlInfo);
		kryptoPanelMain.Controls.Add(kryptonStatusStrip);
		kryptoPanelMain.Dock = DockStyle.Fill;
		kryptoPanelMain.Location = new Point(0, 0);
		kryptoPanelMain.Name = "kryptoPanelMain";
		kryptoPanelMain.PanelBackStyle = PaletteBackStyle.FormMain;
		kryptoPanelMain.Size = new Size(511, 490);
		kryptoPanelMain.TabIndex = 0;
		kryptoPanelMain.TabStop = true;
		kryptoPanelMain.Text = "Main panel";
		kryptoPanelMain.Enter += Control_Enter;
		kryptoPanelMain.Leave += Control_Leave;
		kryptoPanelMain.MouseEnter += Control_Enter;
		kryptoPanelMain.MouseLeave += Control_Leave;
		// 
		// kryptonStatusStrip
		// 
		kryptonStatusStrip.AccessibleDescription = "Shows some information";
		kryptonStatusStrip.AccessibleName = "Status bar with some information";
		kryptonStatusStrip.AccessibleRole = AccessibleRole.StatusBar;
		kryptonStatusStrip.AllowClickThrough = true;
		kryptonStatusStrip.AllowItemReorder = true;
		kryptonStatusStrip.Font = new Font("Segoe UI", 9F);
		kryptonStatusStrip.Items.AddRange(new ToolStripItem[] { labelInformation });
		kryptonStatusStrip.Location = new Point(0, 468);
		kryptonStatusStrip.Name = "kryptonStatusStrip";
		kryptonStatusStrip.Padding = new Padding(1, 0, 16, 0);
		kryptonStatusStrip.ProgressBars = null;
		kryptonStatusStrip.RenderMode = ToolStripRenderMode.ManagerRenderMode;
		kryptonStatusStrip.ShowItemToolTips = true;
		kryptonStatusStrip.Size = new Size(511, 22);
		kryptonStatusStrip.SizingGrip = false;
		kryptonStatusStrip.TabIndex = 8;
		kryptonStatusStrip.TabStop = true;
		kryptonStatusStrip.Text = "Status bar";
		kryptonStatusStrip.MouseEnter += Control_Enter;
		kryptonStatusStrip.MouseLeave += Control_Leave;
		// 
		// labelInformation
		// 
		labelInformation.AccessibleDescription = "Shows some information";
		labelInformation.AccessibleName = "Shows some information";
		labelInformation.AccessibleRole = AccessibleRole.StaticText;
		labelInformation.AutoToolTip = true;
		labelInformation.Image = FatcowIcons16px.fatcow_lightbulb_16px;
		labelInformation.Margin = new Padding(0);
		labelInformation.Name = "labelInformation";
		labelInformation.Size = new Size(144, 22);
		labelInformation.Text = "some information here";
		labelInformation.ToolTipText = "Shows some information";
		labelInformation.MouseEnter += Control_Enter;
		labelInformation.MouseLeave += Control_Leave;
		// 
		// kryptonManager
		// 
		kryptonManager.GlobalPaletteMode = PaletteMode.Global;
		kryptonManager.ToolkitStrings.MessageBoxStrings.LessDetails = "L&ess Details...";
		kryptonManager.ToolkitStrings.MessageBoxStrings.MoreDetails = "&More Details...";
		// 
		// AppInfoForm
		// 
		AccessibleDescription = "Shows the program information";
		AccessibleName = "Program information";
		AccessibleRole = AccessibleRole.Dialog;
		AutoScaleDimensions = new SizeF(7F, 15F);
		AutoScaleMode = AutoScaleMode.Font;
		ClientSize = new Size(511, 490);
		ControlBox = false;
		Controls.Add(kryptoPanelMain);
		FormBorderStyle = FormBorderStyle.FixedToolWindow;
		Icon = (Icon)resources.GetObject("$this.Icon");
		Margin = new Padding(4, 3, 4, 3);
		MaximizeBox = false;
		MinimizeBox = false;
		Name = "AppInfoForm";
		StartPosition = FormStartPosition.CenterParent;
		Text = "Program information";
		Load += AppInfoForm_Load;
		contextMenuStripCopyToClipboard.ResumeLayout(false);
		tabControlInfo.ResumeLayout(false);
		tabPageAbout.ResumeLayout(false);
		tabPageAbout.PerformLayout();
		((ISupportInitialize)kryptonPictureBoxLogo).EndInit();
		((ISupportInitialize)kryptonPictureBoxVisualStudio).EndInit();
		((ISupportInitialize)kryptonPictureBoxDotNet).EndInit();
		((ISupportInitialize)kryptonPictureBoxCSharp).EndInit();
		tabPageComponents.ResumeLayout(false);
		tabControlComponents.ResumeLayout(false);
		tabPageComponentApplicationIcon.ResumeLayout(false);
		tabPageComponentApplicationIcon.PerformLayout();
		tabPageIconsetFatcow.ResumeLayout(false);
		tabPageIconsetFatcow.PerformLayout();
		tabPageComponentKryptonSuite.ResumeLayout(false);
		tabPageComponentKryptonSuite.PerformLayout();
		tabPageComponentNLog.ResumeLayout(false);
		tabPageComponentNLog.PerformLayout();
		((ISupportInitialize)pictureBoxBanner).EndInit();
		((ISupportInitialize)kryptoPanelMain).EndInit();
		kryptoPanelMain.ResumeLayout(false);
		kryptoPanelMain.PerformLayout();
		kryptonStatusStrip.ResumeLayout(false);
		kryptonStatusStrip.PerformLayout();
		ResumeLayout(false);
	}

	#endregion

	private KryptonPictureBox pictureBoxBanner;
	private KryptonLabel kryptonLabelTitle;
	private KryptonLabel kryptonLabelVersion;
	private KryptonLabel kryptonLabelCompany;
	private KryptonLabel kryptonLabelAuthor;
	private KryptonLabel kryptonLabelDescription;
	private KryptonLabel kryptonLabelCopyright;
	private KryptonLinkLabel kryptonLinkLabelWebsite;
	private KryptonLinkLabel kryptonLinkLabelEmail;
	private TabControl tabControlInfo;
	private TabPage tabPageAbout;
	private TabPage tabPageComponents;
	private KryptonLabel kryptonLabelIconHeadingFlaticon;
	private KryptonLabel kryptonLabelHeadingKryptonSuite;
	private KryptonLabel kryptonLabelVersionKryptonSuite;
	private KryptonLabel kryptonLabelAuthorsKryptonSuite;
	private KryptonLinkLabel kryptonLinkLabelWebsiteKryptonSuite;
	private KryptonLabel kryptonLabelLicenseKryptonSuite;
	private KryptonLabel kryptonLabelHeadingNlog;
	private KryptonLabel kryptonLabelVersionNlog;
	private KryptonLabel kryptonLabelAuthorsNlog;
	private KryptonLinkLabel kryptonLinkLabelWebsiteNlog;
	private KryptonLabel kryptonLabelLicenseNlog;
	private KryptonLabel kryptonLabelHeadingFatcowIcons;
	private KryptonLabel kryptonLabelAuthorsFatcow;
	private KryptonLinkLabel kryptonLinkLabelWebsiteFatcow;
	private KryptonLabel kryptonLabelLicenseFatcow;
	private KryptonPanel kryptoPanelMain;
	private KryptonStatusStrip kryptonStatusStrip;
	private ToolStripStatusLabel labelInformation;
	private KryptonManager kryptonManager;
	private ContextMenuStrip contextMenuStripCopyToClipboard;
	private ToolStripMenuItem toolStripMenuItemCopyToClipboard;
	private TabControl tabControlComponents;
	private TabPage tabPageComponentApplicationIcon;
	private TabPage tabPageIconsetFatcow;
	private TabPage tabPageComponentKryptonSuite;
	private TabPage tabPageComponentNLog;
	private KryptonTextBox kryptonTextBoxLicenseFlaticon;
	private KryptonLabel kryptonLabelLicenseFlaticon;
	private KryptonLinkLabel kryptonLinkLabelFlaticon;
	private KryptonLabel kryptonLabelAuthorFlaticon;
	private KryptonTextBox kryptonTextBoxLicenseFatcow;
	private KryptonTextBox kryptonTextBoxLicenseKryptonSuite;
	private KryptonTextBox kryptonTextBoxLicenseNlog;
	private KryptonPictureBox kryptonPictureBoxCSharp;
	private KryptonPictureBox kryptonPictureBoxDotNet;
	private KryptonPictureBox kryptonPictureBoxVisualStudio;
	private KryptonPictureBox kryptonPictureBoxLogo;
	private ImageList imageListTabAbout;
}