// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using Krypton.Toolkit;

using Planetoid_DB.Resources;

using System.ComponentModel;

namespace Planetoid_DB;

/// <summary>Represents a dialog form that displays essential application information, including the version, title, description,
/// and copyright details.</summary>
/// <remarks>AppInfoForm provides users with a centralized interface to view key program details and offers
/// convenient options to copy information to the clipboard. The form is typically shown as a modal dialog and includes
/// accessibility features for improved usability. It is not intended to be modified directly; use the designer for
/// layout changes.</remarks>
partial class AppInfoForm
  {
    /// <summary>Required designer variable.</summary>
	/// <remarks>This field is used by the Windows Forms designer to manage components.</remarks>
    private IContainer components = null;

    /// <summary>Clean up any resources being used.</summary>
    /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
	/// <remarks>This method is called when the form is being disposed.</remarks>
    protected override void Dispose(bool disposing)
    {
      if (disposing && (components != null))
      {
        components.Dispose();
      }
      base.Dispose(disposing);
    }

	#region Windows Form Designer generated code

	/// <summary>Required method for Designer support - do not modify
	/// the contents of this method with the code editor.</summary>
	/// <remarks>This method is automatically generated by the Windows Forms designer and should not be modified manually.
	/// It sets up the controls and their properties for the form.</remarks>
	private void InitializeComponent()
	{
		components = new Container();
		ComponentResourceManager resources = new ComponentResourceManager(typeof(AppInfoForm));
		labelVersion = new KryptonLabel();
		contextMenuStripCopyToClipboard = new ContextMenuStrip(components);
		toolStripMenuItemCopyToClipboard = new ToolStripMenuItem();
		labelTitle = new KryptonLabel();
		labelDescription = new KryptonLabel();
		pictureBoxBanner = new KryptonPictureBox();
		labelCopyright = new KryptonLabel();
		linkLabelEmail = new KryptonLinkLabel();
		linkLabelWebsite = new KryptonLinkLabel();
		kryptoPanelMain = new KryptonPanel();
		kryptonStatusStrip = new KryptonStatusStrip();
		labelInformation = new ToolStripStatusLabel();
		kryptonManager = new KryptonManager(components);
		contextMenuStripCopyToClipboard.SuspendLayout();
		((ISupportInitialize)pictureBoxBanner).BeginInit();
		((ISupportInitialize)kryptoPanelMain).BeginInit();
		kryptoPanelMain.SuspendLayout();
		kryptonStatusStrip.SuspendLayout();
		SuspendLayout();
		// 
		// labelVersion
		// 
		labelVersion.AccessibleDescription = "Shows the version number";
		labelVersion.AccessibleName = "Version";
		labelVersion.AccessibleRole = AccessibleRole.StaticText;
		labelVersion.ContextMenuStrip = contextMenuStripCopyToClipboard;
		labelVersion.Location = new Point(12, 216);
		labelVersion.Name = "labelVersion";
		labelVersion.Size = new Size(95, 20);
		labelVersion.TabIndex = 1;
		labelVersion.ToolTipValues.Description = "Shows the version number.\r\nDouble-click or right-click to copy the information to the clipboard.";
		labelVersion.ToolTipValues.EnableToolTips = true;
		labelVersion.ToolTipValues.Heading = "Version number";
		labelVersion.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelVersion.Values.Text = "Version: X.X.X.X";
		labelVersion.DoubleClick += CopyToClipboard_DoubleClick;
		labelVersion.Enter += Control_Enter;
		labelVersion.Leave += Control_Leave;
		labelVersion.MouseDown += Control_MouseDown;
		labelVersion.MouseEnter += Control_Enter;
		labelVersion.MouseLeave += Control_Leave;
		// 
		// contextMenuStripCopyToClipboard
		// 
		contextMenuStripCopyToClipboard.AccessibleDescription = "Shows the context menu for copying information to the clipboard";
		contextMenuStripCopyToClipboard.AccessibleName = "Context menu for copying information to the clipboard";
		contextMenuStripCopyToClipboard.AccessibleRole = AccessibleRole.MenuPopup;
		contextMenuStripCopyToClipboard.AllowClickThrough = true;
		contextMenuStripCopyToClipboard.Font = new Font("Segoe UI", 9F);
		contextMenuStripCopyToClipboard.Items.AddRange(new ToolStripItem[] { toolStripMenuItemCopyToClipboard });
		contextMenuStripCopyToClipboard.Name = "contextMenuStrip";
		contextMenuStripCopyToClipboard.Size = new Size(214, 26);
		contextMenuStripCopyToClipboard.TabStop = true;
		contextMenuStripCopyToClipboard.Text = "Copy to clipboard";
		contextMenuStripCopyToClipboard.MouseEnter += Control_Enter;
		contextMenuStripCopyToClipboard.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemCopyToClipboard
		// 
		toolStripMenuItemCopyToClipboard.AccessibleDescription = "Copies the text/value to the clipboard";
		toolStripMenuItemCopyToClipboard.AccessibleName = "Copy to clipboard";
		toolStripMenuItemCopyToClipboard.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemCopyToClipboard.AutoToolTip = true;
		toolStripMenuItemCopyToClipboard.Image = FatcowIcons16px.fatcow_page_copy_16px;
		toolStripMenuItemCopyToClipboard.Name = "toolStripMenuItemCopyToClipboard";
		toolStripMenuItemCopyToClipboard.ShortcutKeyDisplayString = "Strg+C";
		toolStripMenuItemCopyToClipboard.ShortcutKeys = Keys.Control | Keys.C;
		toolStripMenuItemCopyToClipboard.Size = new Size(213, 22);
		toolStripMenuItemCopyToClipboard.Text = "&Copy to clipboard";
		toolStripMenuItemCopyToClipboard.Click += CopyToClipboard_DoubleClick;
		toolStripMenuItemCopyToClipboard.MouseEnter += Control_Enter;
		toolStripMenuItemCopyToClipboard.MouseLeave += Control_Leave;
		// 
		// labelTitle
		// 
		labelTitle.AccessibleDescription = "Shows the application name";
		labelTitle.AccessibleName = "Application Name";
		labelTitle.AccessibleRole = AccessibleRole.StaticText;
		labelTitle.ContextMenuStrip = contextMenuStripCopyToClipboard;
		labelTitle.LabelStyle = LabelStyle.TitlePanel;
		labelTitle.Location = new Point(12, 187);
		labelTitle.Name = "labelTitle";
		labelTitle.Size = new Size(129, 29);
		labelTitle.TabIndex = 0;
		labelTitle.ToolTipValues.Description = "Shows the application name.\r\nDouble-click or right-click to copy the information to the clipboard.";
		labelTitle.ToolTipValues.EnableToolTips = true;
		labelTitle.ToolTipValues.Heading = "Application name";
		labelTitle.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelTitle.Values.Text = "Planetoid-DB";
		labelTitle.DoubleClick += CopyToClipboard_DoubleClick;
		labelTitle.Enter += Control_Enter;
		labelTitle.Leave += Control_Leave;
		labelTitle.MouseDown += Control_MouseDown;
		labelTitle.MouseEnter += Control_Enter;
		labelTitle.MouseLeave += Control_Leave;
		// 
		// labelDescription
		// 
		labelDescription.AccessibleDescription = "Shows the program description";
		labelDescription.AccessibleName = "Program description";
		labelDescription.AccessibleRole = AccessibleRole.StaticText;
		labelDescription.ContextMenuStrip = contextMenuStripCopyToClipboard;
		labelDescription.Location = new Point(12, 246);
		labelDescription.Name = "labelDescription";
		labelDescription.Size = new Size(80, 20);
		labelDescription.TabIndex = 2;
		labelDescription.ToolTipValues.Description = "Shows the program description.\r\nDouble-click or right-click to copy the information to the clipboard.";
		labelDescription.ToolTipValues.EnableToolTips = true;
		labelDescription.ToolTipValues.Heading = "Description";
		labelDescription.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelDescription.Values.Text = "[Description]";
		labelDescription.DoubleClick += CopyToClipboard_DoubleClick;
		labelDescription.Enter += Control_Enter;
		labelDescription.Leave += Control_Leave;
		labelDescription.MouseDown += Control_MouseDown;
		labelDescription.MouseEnter += Control_Enter;
		labelDescription.MouseLeave += Control_Leave;
		// 
		// pictureBoxBanner
		// 
		pictureBoxBanner.AccessibleDescription = "Shows the banner";
		pictureBoxBanner.AccessibleName = "Banner";
		pictureBoxBanner.AccessibleRole = AccessibleRole.Graphic;
		pictureBoxBanner.Image = (Image)resources.GetObject("pictureBoxBanner.Image");
		pictureBoxBanner.Location = new Point(4, 3);
		pictureBoxBanner.Name = "pictureBoxBanner";
		pictureBoxBanner.Size = new Size(500, 174);
		pictureBoxBanner.TabIndex = 0;
		pictureBoxBanner.TabStop = false;
		pictureBoxBanner.ToolTipValues.Description = "Shows the banner.";
		pictureBoxBanner.ToolTipValues.EnableToolTips = true;
		pictureBoxBanner.ToolTipValues.Heading = "Banner";
		pictureBoxBanner.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		pictureBoxBanner.MouseEnter += Control_Enter;
		pictureBoxBanner.MouseLeave += Control_Leave;
		// 
		// labelCopyright
		// 
		labelCopyright.AccessibleDescription = "Shows the copyright";
		labelCopyright.AccessibleName = "Copyright";
		labelCopyright.AccessibleRole = AccessibleRole.StaticText;
		labelCopyright.ContextMenuStrip = contextMenuStripCopyToClipboard;
		labelCopyright.Location = new Point(12, 269);
		labelCopyright.Name = "labelCopyright";
		labelCopyright.Size = new Size(72, 20);
		labelCopyright.TabIndex = 3;
		labelCopyright.ToolTipValues.Description = "Shows the copyright.\r\nDouble-click or right-click to copy the information to the clipboard.";
		labelCopyright.ToolTipValues.EnableToolTips = true;
		labelCopyright.ToolTipValues.Heading = "Copyright";
		labelCopyright.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelCopyright.Values.Text = "[Copyright]";
		labelCopyright.DoubleClick += CopyToClipboard_DoubleClick;
		labelCopyright.Enter += Control_Enter;
		labelCopyright.Leave += Control_Leave;
		labelCopyright.MouseDown += Control_MouseDown;
		labelCopyright.MouseEnter += Control_Enter;
		labelCopyright.MouseLeave += Control_Leave;
		// 
		// linkLabelEmail
		// 
		linkLabelEmail.AccessibleDescription = "Opens the mail client";
		linkLabelEmail.AccessibleName = "E-Mail";
		linkLabelEmail.AccessibleRole = AccessibleRole.Link;
		linkLabelEmail.LinkBehavior = KryptonLinkBehavior.HoverUnderline;
		linkLabelEmail.Location = new Point(424, 266);
		linkLabelEmail.Name = "linkLabelEmail";
		linkLabelEmail.Size = new Size(62, 20);
		linkLabelEmail.TabIndex = 5;
		linkLabelEmail.ToolTipValues.Description = "Opens the mail client.";
		linkLabelEmail.ToolTipValues.EnableToolTips = true;
		linkLabelEmail.ToolTipValues.Heading = "E-Mail";
		linkLabelEmail.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		linkLabelEmail.Values.Image = FatcowIcons16px.fatcow_email_16px;
		linkLabelEmail.Values.Text = "E-Mail";
		linkLabelEmail.LinkClicked += LinkLabelEmail_Clicked;
		linkLabelEmail.Enter += Control_Enter;
		linkLabelEmail.Leave += Control_Leave;
		linkLabelEmail.MouseEnter += Control_Enter;
		linkLabelEmail.MouseLeave += Control_Leave;
		// 
		// linkLabelWebsite
		// 
		linkLabelWebsite.AccessibleDescription = "Opens the website";
		linkLabelWebsite.AccessibleName = "Website";
		linkLabelWebsite.AccessibleRole = AccessibleRole.Link;
		linkLabelWebsite.LinkBehavior = KryptonLinkBehavior.HoverUnderline;
		linkLabelWebsite.Location = new Point(424, 246);
		linkLabelWebsite.Name = "linkLabelWebsite";
		linkLabelWebsite.Size = new Size(72, 20);
		linkLabelWebsite.TabIndex = 4;
		linkLabelWebsite.ToolTipValues.Description = "Opens the website.";
		linkLabelWebsite.ToolTipValues.EnableToolTips = true;
		linkLabelWebsite.ToolTipValues.Heading = "Website";
		linkLabelWebsite.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		linkLabelWebsite.Values.Image = FatcowIcons16px.fatcow_world_16px;
		linkLabelWebsite.Values.Text = "Website";
		linkLabelWebsite.LinkClicked += LinkLabelWebsite_Clicked;
		linkLabelWebsite.Enter += Control_Enter;
		linkLabelWebsite.Leave += Control_Leave;
		linkLabelWebsite.MouseEnter += Control_Enter;
		linkLabelWebsite.MouseLeave += Control_Leave;
		// 
		// kryptoPanelMain
		// 
		kryptoPanelMain.AccessibleDescription = "Groups the data";
		kryptoPanelMain.AccessibleName = "pane";
		kryptoPanelMain.AccessibleRole = AccessibleRole.Pane;
		kryptoPanelMain.Controls.Add(linkLabelEmail);
		kryptoPanelMain.Controls.Add(linkLabelWebsite);
		kryptoPanelMain.Controls.Add(kryptonStatusStrip);
		kryptoPanelMain.Controls.Add(labelCopyright);
		kryptoPanelMain.Controls.Add(labelTitle);
		kryptoPanelMain.Controls.Add(labelVersion);
		kryptoPanelMain.Controls.Add(labelDescription);
		kryptoPanelMain.Controls.Add(pictureBoxBanner);
		kryptoPanelMain.Dock = DockStyle.Fill;
		kryptoPanelMain.Location = new Point(0, 0);
		kryptoPanelMain.Name = "kryptoPanelMain";
		kryptoPanelMain.PanelBackStyle = PaletteBackStyle.FormMain;
		kryptoPanelMain.Size = new Size(508, 321);
		kryptoPanelMain.TabIndex = 0;
		// 
		// kryptonStatusStrip
		// 
		kryptonStatusStrip.AccessibleDescription = "Shows some information";
		kryptonStatusStrip.AccessibleName = "Status bar with some information";
		kryptonStatusStrip.AccessibleRole = AccessibleRole.StatusBar;
		kryptonStatusStrip.AllowClickThrough = true;
		kryptonStatusStrip.AllowItemReorder = true;
		kryptonStatusStrip.Font = new Font("Segoe UI", 9F);
		kryptonStatusStrip.Items.AddRange(new ToolStripItem[] { labelInformation });
		kryptonStatusStrip.Location = new Point(0, 299);
		kryptonStatusStrip.Name = "kryptonStatusStrip";
		kryptonStatusStrip.Padding = new Padding(1, 0, 16, 0);
		kryptonStatusStrip.ProgressBars = null;
		kryptonStatusStrip.RenderMode = ToolStripRenderMode.ManagerRenderMode;
		kryptonStatusStrip.ShowItemToolTips = true;
		kryptonStatusStrip.Size = new Size(508, 22);
		kryptonStatusStrip.SizingGrip = false;
		kryptonStatusStrip.TabIndex = 6;
		kryptonStatusStrip.TabStop = true;
		kryptonStatusStrip.Text = "Status bar";
		// 
		// labelInformation
		// 
		labelInformation.AccessibleDescription = "Shows some information";
		labelInformation.AccessibleName = "Shows some information";
		labelInformation.AccessibleRole = AccessibleRole.StaticText;
		labelInformation.AutoToolTip = true;
		labelInformation.Image = FatcowIcons16px.fatcow_lightbulb_16px;
		labelInformation.Margin = new Padding(0);
		labelInformation.Name = "labelInformation";
		labelInformation.Size = new Size(144, 22);
		labelInformation.Text = "some information here";
		labelInformation.ToolTipText = "Shows some information";
		// 
		// kryptonManager
		// 
		kryptonManager.GlobalPaletteMode = PaletteMode.Global;
		kryptonManager.ToolkitStrings.MessageBoxStrings.LessDetails = "L&ess Details...";
		kryptonManager.ToolkitStrings.MessageBoxStrings.MoreDetails = "&More Details...";
		// 
		// AppInfoForm
		// 
		AccessibleDescription = "Shows the program information";
		AccessibleName = "Program information";
		AccessibleRole = AccessibleRole.Dialog;
		AutoScaleDimensions = new SizeF(7F, 15F);
		AutoScaleMode = AutoScaleMode.Font;
		ClientSize = new Size(508, 321);
		ControlBox = false;
		Controls.Add(kryptoPanelMain);
		FormBorderStyle = FormBorderStyle.FixedToolWindow;
		Icon = (Icon)resources.GetObject("$this.Icon");
		Margin = new Padding(4, 3, 4, 3);
		MaximizeBox = false;
		MinimizeBox = false;
		Name = "AppInfoForm";
		ShowInTaskbar = false;
		StartPosition = FormStartPosition.CenterParent;
		Text = "Program information";
		Load += AppInfoForm_Load;
		contextMenuStripCopyToClipboard.ResumeLayout(false);
		((ISupportInitialize)pictureBoxBanner).EndInit();
		((ISupportInitialize)kryptoPanelMain).EndInit();
		kryptoPanelMain.ResumeLayout(false);
		kryptoPanelMain.PerformLayout();
		kryptonStatusStrip.ResumeLayout(false);
		kryptonStatusStrip.PerformLayout();
		ResumeLayout(false);

	}

	#endregion

	private KryptonPictureBox pictureBoxBanner;
    private KryptonLabel labelVersion;
    private KryptonLabel labelTitle;
    private KryptonLabel labelDescription;
	private KryptonLabel labelCopyright;
        private KryptonPanel kryptoPanelMain;
	private KryptonStatusStrip kryptonStatusStrip;
	private ToolStripStatusLabel labelInformation;
	private KryptonLinkLabel linkLabelWebsite;
	private KryptonLinkLabel linkLabelEmail;
	private KryptonManager kryptonManager;
	private ContextMenuStrip contextMenuStripCopyToClipboard;
	private ToolStripMenuItem toolStripMenuItemCopyToClipboard;
}