// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using Krypton.Toolkit;

using Planetoid_DB.Resources;

using System.ComponentModel;

namespace Planetoid_DB;

/// <summary>Represents a Windows Form that enables users to copy various types of astronomical or observational data to the
/// clipboard using dedicated buttons.</summary>
/// <remarks>Each button on the form is designed to copy a specific data field, such as index number, designation,
/// orbital parameters, or observation details, directly to the clipboard. This facilitates efficient data transfer and
/// reduces manual copying errors. The form is intended for scenarios where quick access to formatted data is required,
/// such as research or cataloging tasks.</remarks>
partial class CopyDataToClipboardForm
{
	/// <summary>Required designer variable.</summary>
	/// <remarks>This field is used by the Windows Forms designer to keep track of components.</remarks>
	private IContainer components = null;

	/// <summary>Clean up any resources being used.</summary>
	/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
	/// <remarks>This method is used to release unmanaged resources and optionally managed resources.</remarks>
	protected override void Dispose(bool disposing)
	{
		if (disposing && (components != null))
		{
			components.Dispose();
		}
		base.Dispose(disposing);
	}

	#region Windows Form Designer generated code

	/// <summary>Required method for Designer support - do not modify
	/// the contents of this method with the code editor.</summary>
	/// <remarks>This method is automatically generated by the Windows Forms designer and should not be modified manually.
	/// It sets up the controls and their properties for the form.</remarks>
	private void InitializeComponent()
	{
		components = new Container();
		ComponentResourceManager resources = new ComponentResourceManager(typeof(CopyDataToClipboardForm));
		buttonIndexNumber = new KryptonButton();
		buttonReadableDesignation = new KryptonButton();
		buttonEpoch = new KryptonButton();
		buttonMeanAnomaly = new KryptonButton();
		buttonArgumentOfPerihelion = new KryptonButton();
		buttonLongitudeOfTheAscendingNode = new KryptonButton();
		buttonInclination = new KryptonButton();
		buttonOrbitalEccentricity = new KryptonButton();
		buttonMeanDailyMotion = new KryptonButton();
		buttonSemimajorAxis = new KryptonButton();
		buttonAbsoluteMagnitude = new KryptonButton();
		buttonSlopeParameter = new KryptonButton();
		buttonReference = new KryptonButton();
		buttonObservationSpan = new KryptonButton();
		buttonNumberOfObservations = new KryptonButton();
		buttonNumberOfOppositions = new KryptonButton();
		buttonFlags = new KryptonButton();
		buttonComputerName = new KryptonButton();
		buttonRmsResidual = new KryptonButton();
		buttonDateOfLastObservation = new KryptonButton();
		kryptonPanelMain = new KryptonPanel();
		kryptonStatusStrip = new KryptonStatusStrip();
		labelInformation = new ToolStripStatusLabel();
		toolStripContainer = new ToolStripContainer();
		kryptonManager = new KryptonManager(components);
		((ISupportInitialize)kryptonPanelMain).BeginInit();
		kryptonPanelMain.SuspendLayout();
		kryptonStatusStrip.SuspendLayout();
		toolStripContainer.BottomToolStripPanel.SuspendLayout();
		toolStripContainer.ContentPanel.SuspendLayout();
		toolStripContainer.SuspendLayout();
		SuspendLayout();
		// 
		// buttonIndexNumber
		// 
		buttonIndexNumber.AccessibleDescription = "Copies to clipboard: Index No.";
		buttonIndexNumber.AccessibleName = "Copy to clipboard: Index No.";
		buttonIndexNumber.AccessibleRole = AccessibleRole.PushButton;
		buttonIndexNumber.ButtonStyle = ButtonStyle.Form;
		buttonIndexNumber.Location = new Point(14, 14);
		buttonIndexNumber.Name = "buttonIndexNumber";
		buttonIndexNumber.Size = new Size(306, 29);
		buttonIndexNumber.TabIndex = 0;
		buttonIndexNumber.ToolTipValues.Description = "Copy to clipboard: Index No.";
		buttonIndexNumber.ToolTipValues.EnableToolTips = true;
		buttonIndexNumber.ToolTipValues.Heading = "Index No.";
		buttonIndexNumber.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		buttonIndexNumber.Values.DropDownArrowColor = Color.Empty;
		buttonIndexNumber.Values.Text = "Index N&o.";
		buttonIndexNumber.Click += ButtonIndexNumber_Click;
		buttonIndexNumber.Enter += Control_Enter;
		buttonIndexNumber.Leave += Control_Leave;
		buttonIndexNumber.MouseEnter += Control_Enter;
		buttonIndexNumber.MouseLeave += Control_Leave;
		// 
		// buttonReadableDesignation
		// 
		buttonReadableDesignation.AccessibleDescription = "Copies to clipboard: Readable designation";
		buttonReadableDesignation.AccessibleName = "Copy to clipboard: Readable designation";
		buttonReadableDesignation.AccessibleRole = AccessibleRole.PushButton;
		buttonReadableDesignation.ButtonStyle = ButtonStyle.Form;
		buttonReadableDesignation.Location = new Point(14, 50);
		buttonReadableDesignation.Name = "buttonReadableDesignation";
		buttonReadableDesignation.Size = new Size(306, 29);
		buttonReadableDesignation.TabIndex = 1;
		buttonReadableDesignation.ToolTipValues.Description = "Copy to clipboard: Readable designation";
		buttonReadableDesignation.ToolTipValues.EnableToolTips = true;
		buttonReadableDesignation.ToolTipValues.Heading = "Readable designation";
		buttonReadableDesignation.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		buttonReadableDesignation.Values.DropDownArrowColor = Color.Empty;
		buttonReadableDesignation.Values.Text = "Readable &designation";
		buttonReadableDesignation.Click += ButtonReadableDesignation_Click;
		buttonReadableDesignation.Enter += Control_Enter;
		buttonReadableDesignation.Leave += Control_Leave;
		buttonReadableDesignation.MouseEnter += Control_Enter;
		buttonReadableDesignation.MouseLeave += Control_Leave;
		// 
		// buttonEpoch
		// 
		buttonEpoch.AccessibleDescription = "Copies to clipboard: Epoch (in packed form, .0 TT)";
		buttonEpoch.AccessibleName = "Copy to clipboard: Epoch (in packed form, .0 TT)";
		buttonEpoch.AccessibleRole = AccessibleRole.PushButton;
		buttonEpoch.ButtonStyle = ButtonStyle.Form;
		buttonEpoch.Location = new Point(14, 85);
		buttonEpoch.Name = "buttonEpoch";
		buttonEpoch.Size = new Size(306, 29);
		buttonEpoch.TabIndex = 2;
		buttonEpoch.ToolTipValues.Description = "Copy to clipboard: Epoch (in packed form, .0 TT)";
		buttonEpoch.ToolTipValues.EnableToolTips = true;
		buttonEpoch.ToolTipValues.Heading = "Epoch (in packed form, .0 TT)";
		buttonEpoch.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		buttonEpoch.Values.DropDownArrowColor = Color.Empty;
		buttonEpoch.Values.Text = "&Epoch (in packed form, .0 TT)";
		buttonEpoch.Click += ButtonEpoch_Click;
		buttonEpoch.Enter += Control_Enter;
		buttonEpoch.Leave += Control_Leave;
		buttonEpoch.MouseEnter += Control_Enter;
		buttonEpoch.MouseLeave += Control_Leave;
		// 
		// buttonMeanAnomaly
		// 
		buttonMeanAnomaly.AccessibleDescription = "Copies to clipboard: Mean anomaly at the epoch (degrees)";
		buttonMeanAnomaly.AccessibleName = "Copy to clipboard: Mean anomaly at the epoch (degrees)";
		buttonMeanAnomaly.AccessibleRole = AccessibleRole.PushButton;
		buttonMeanAnomaly.ButtonStyle = ButtonStyle.Form;
		buttonMeanAnomaly.Location = new Point(14, 121);
		buttonMeanAnomaly.Name = "buttonMeanAnomaly";
		buttonMeanAnomaly.Size = new Size(306, 29);
		buttonMeanAnomaly.TabIndex = 3;
		buttonMeanAnomaly.ToolTipValues.Description = "Copy to clipboard: Mean anomaly at the epoch (degrees)";
		buttonMeanAnomaly.ToolTipValues.EnableToolTips = true;
		buttonMeanAnomaly.ToolTipValues.Heading = "Mean anomaly at the epoch (degrees)";
		buttonMeanAnomaly.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		buttonMeanAnomaly.Values.DropDownArrowColor = Color.Empty;
		buttonMeanAnomaly.Values.Text = "&Mean anomaly at the epoch (°)";
		buttonMeanAnomaly.Click += ButtonMeanAnomaly_Click;
		buttonMeanAnomaly.Enter += Control_Enter;
		buttonMeanAnomaly.Leave += Control_Leave;
		buttonMeanAnomaly.MouseEnter += Control_Enter;
		buttonMeanAnomaly.MouseLeave += Control_Leave;
		// 
		// buttonArgumentOfPerihelion
		// 
		buttonArgumentOfPerihelion.AccessibleDescription = "Copies to clipboard: Argument of perihelion, J2000.0 (degrees)";
		buttonArgumentOfPerihelion.AccessibleName = "Copy to clipboard: Argument of perihelion, J2000.0 (degrees)";
		buttonArgumentOfPerihelion.AccessibleRole = AccessibleRole.PushButton;
		buttonArgumentOfPerihelion.ButtonStyle = ButtonStyle.Form;
		buttonArgumentOfPerihelion.Location = new Point(14, 157);
		buttonArgumentOfPerihelion.Name = "buttonArgumentOfPerihelion";
		buttonArgumentOfPerihelion.Size = new Size(306, 29);
		buttonArgumentOfPerihelion.TabIndex = 4;
		buttonArgumentOfPerihelion.ToolTipValues.Description = "Copy to clipboard: Argument of perihelion, J2000.0 (degrees)";
		buttonArgumentOfPerihelion.ToolTipValues.EnableToolTips = true;
		buttonArgumentOfPerihelion.ToolTipValues.Heading = "Argument of perihelion, J2000.0 (degrees)";
		buttonArgumentOfPerihelion.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		buttonArgumentOfPerihelion.Values.DropDownArrowColor = Color.Empty;
		buttonArgumentOfPerihelion.Values.Text = "Ar&gument of perihelion, J2000.0 (°)";
		buttonArgumentOfPerihelion.Click += ButtonArgumentOfPerihelion_Click;
		buttonArgumentOfPerihelion.Enter += Control_Enter;
		buttonArgumentOfPerihelion.Leave += Control_Leave;
		buttonArgumentOfPerihelion.MouseEnter += Control_Enter;
		buttonArgumentOfPerihelion.MouseLeave += Control_Leave;
		// 
		// buttonLongitudeOfTheAscendingNode
		// 
		buttonLongitudeOfTheAscendingNode.AccessibleDescription = "Copies to clipboard: Longitude of the ascending node, J2000.0 (degrees)";
		buttonLongitudeOfTheAscendingNode.AccessibleName = "Copy to clipboard: Longitude of the ascending node, J2000.0 (degrees)";
		buttonLongitudeOfTheAscendingNode.AccessibleRole = AccessibleRole.PushButton;
		buttonLongitudeOfTheAscendingNode.ButtonStyle = ButtonStyle.Form;
		buttonLongitudeOfTheAscendingNode.Location = new Point(14, 193);
		buttonLongitudeOfTheAscendingNode.Name = "buttonLongitudeOfTheAscendingNode";
		buttonLongitudeOfTheAscendingNode.Size = new Size(306, 29);
		buttonLongitudeOfTheAscendingNode.TabIndex = 5;
		buttonLongitudeOfTheAscendingNode.ToolTipValues.Description = "Copy to clipboard: Longitude of the ascending node, J2000.0 (degrees)";
		buttonLongitudeOfTheAscendingNode.ToolTipValues.EnableToolTips = true;
		buttonLongitudeOfTheAscendingNode.ToolTipValues.Heading = "Longitude of the ascending node, J2000.0 (degrees)";
		buttonLongitudeOfTheAscendingNode.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		buttonLongitudeOfTheAscendingNode.Values.DropDownArrowColor = Color.Empty;
		buttonLongitudeOfTheAscendingNode.Values.Text = "&Longitude of the ascending node, J2000.0 (°)";
		buttonLongitudeOfTheAscendingNode.Click += ButtonLongitudeOfTheAscendingNode_Click;
		buttonLongitudeOfTheAscendingNode.Enter += Control_Enter;
		buttonLongitudeOfTheAscendingNode.Leave += Control_Leave;
		buttonLongitudeOfTheAscendingNode.MouseEnter += Control_Enter;
		buttonLongitudeOfTheAscendingNode.MouseLeave += Control_Leave;
		// 
		// buttonInclination
		// 
		buttonInclination.AccessibleDescription = "Copies to clipboard: Inclination to the ecliptic, J2000.0 (degrees)";
		buttonInclination.AccessibleName = "Copy to clipboard: Inclination to the ecliptic, J2000.0 (degrees)";
		buttonInclination.AccessibleRole = AccessibleRole.PushButton;
		buttonInclination.ButtonStyle = ButtonStyle.Form;
		buttonInclination.Location = new Point(14, 228);
		buttonInclination.Name = "buttonInclination";
		buttonInclination.Size = new Size(306, 29);
		buttonInclination.TabIndex = 6;
		buttonInclination.ToolTipValues.Description = "Copy to clipboard: Inclination to the ecliptic, J2000.0 (degrees)";
		buttonInclination.ToolTipValues.EnableToolTips = true;
		buttonInclination.ToolTipValues.Heading = "Inclination to the ecliptic, J2000.0 (degrees)";
		buttonInclination.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		buttonInclination.Values.DropDownArrowColor = Color.Empty;
		buttonInclination.Values.Text = "&Inclination to the ecliptic, J2000.0 (°)";
		buttonInclination.Click += ButtonInclination_Click;
		buttonInclination.Enter += Control_Enter;
		buttonInclination.Leave += Control_Leave;
		buttonInclination.MouseEnter += Control_Enter;
		buttonInclination.MouseLeave += Control_Leave;
		// 
		// buttonOrbitalEccentricity
		// 
		buttonOrbitalEccentricity.AccessibleDescription = "Copies to clipboard: Orbital eccentricity";
		buttonOrbitalEccentricity.AccessibleName = "Copy to clipboard: Orbital eccentricity";
		buttonOrbitalEccentricity.AccessibleRole = AccessibleRole.PushButton;
		buttonOrbitalEccentricity.ButtonStyle = ButtonStyle.Form;
		buttonOrbitalEccentricity.Location = new Point(14, 264);
		buttonOrbitalEccentricity.Name = "buttonOrbitalEccentricity";
		buttonOrbitalEccentricity.Size = new Size(306, 29);
		buttonOrbitalEccentricity.TabIndex = 7;
		buttonOrbitalEccentricity.ToolTipValues.Description = "Copy to clipboard: Orbital eccentricity";
		buttonOrbitalEccentricity.ToolTipValues.EnableToolTips = true;
		buttonOrbitalEccentricity.ToolTipValues.Heading = "Orbital eccentricity";
		buttonOrbitalEccentricity.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		buttonOrbitalEccentricity.Values.DropDownArrowColor = Color.Empty;
		buttonOrbitalEccentricity.Values.Text = "Orbital e&ccentricity";
		buttonOrbitalEccentricity.Click += ButtonOrbitalEccentricity_Click;
		buttonOrbitalEccentricity.Enter += Control_Enter;
		buttonOrbitalEccentricity.Leave += Control_Leave;
		buttonOrbitalEccentricity.MouseEnter += Control_Enter;
		buttonOrbitalEccentricity.MouseLeave += Control_Leave;
		// 
		// buttonMeanDailyMotion
		// 
		buttonMeanDailyMotion.AccessibleDescription = "Copies to clipboard: Mean daily motion (degrees per day)";
		buttonMeanDailyMotion.AccessibleName = "Copy to clipboard: Mean daily motion (degrees per day)";
		buttonMeanDailyMotion.AccessibleRole = AccessibleRole.PushButton;
		buttonMeanDailyMotion.ButtonStyle = ButtonStyle.Form;
		buttonMeanDailyMotion.Location = new Point(14, 300);
		buttonMeanDailyMotion.Name = "buttonMeanDailyMotion";
		buttonMeanDailyMotion.Size = new Size(306, 29);
		buttonMeanDailyMotion.TabIndex = 8;
		buttonMeanDailyMotion.ToolTipValues.Description = "Copy to clipboard: Mean daily motion (degrees per day)";
		buttonMeanDailyMotion.ToolTipValues.EnableToolTips = true;
		buttonMeanDailyMotion.ToolTipValues.Heading = "Mean daily motion (degrees per day)";
		buttonMeanDailyMotion.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		buttonMeanDailyMotion.Values.DropDownArrowColor = Color.Empty;
		buttonMeanDailyMotion.Values.Text = "Mean dail&y motion (°/day)";
		buttonMeanDailyMotion.Click += ButtonMeanDailyMotion_Click;
		buttonMeanDailyMotion.Enter += Control_Enter;
		buttonMeanDailyMotion.Leave += Control_Leave;
		buttonMeanDailyMotion.MouseEnter += Control_Enter;
		buttonMeanDailyMotion.MouseLeave += Control_Leave;
		// 
		// buttonSemimajorAxis
		// 
		buttonSemimajorAxis.AccessibleDescription = "Copies to clipboard: Semi-major axis (AU)";
		buttonSemimajorAxis.AccessibleName = "Copy to clipboard: Semi-major axis (AU)";
		buttonSemimajorAxis.AccessibleRole = AccessibleRole.PushButton;
		buttonSemimajorAxis.ButtonStyle = ButtonStyle.Form;
		buttonSemimajorAxis.Location = new Point(14, 336);
		buttonSemimajorAxis.Name = "buttonSemimajorAxis";
		buttonSemimajorAxis.Size = new Size(306, 29);
		buttonSemimajorAxis.TabIndex = 9;
		buttonSemimajorAxis.ToolTipValues.Description = "Copy to clipboard: Semi-major axis (AU)";
		buttonSemimajorAxis.ToolTipValues.EnableToolTips = true;
		buttonSemimajorAxis.ToolTipValues.Heading = "Semi-major axis (AU)";
		buttonSemimajorAxis.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		buttonSemimajorAxis.Values.DropDownArrowColor = Color.Empty;
		buttonSemimajorAxis.Values.Text = "Semi-ma&jor axis (AU)";
		buttonSemimajorAxis.Click += ButtonSemiMajorAxis_Click;
		buttonSemimajorAxis.Enter += Control_Enter;
		buttonSemimajorAxis.Leave += Control_Leave;
		buttonSemimajorAxis.MouseEnter += Control_Enter;
		buttonSemimajorAxis.MouseLeave += Control_Leave;
		// 
		// buttonAbsoluteMagnitude
		// 
		buttonAbsoluteMagnitude.AccessibleDescription = "Copies to clipboard: Absolute magnitude, H";
		buttonAbsoluteMagnitude.AccessibleName = "Copy to clipboard: Absolute magnitude, H";
		buttonAbsoluteMagnitude.AccessibleRole = AccessibleRole.PushButton;
		buttonAbsoluteMagnitude.ButtonStyle = ButtonStyle.Form;
		buttonAbsoluteMagnitude.Location = new Point(327, 14);
		buttonAbsoluteMagnitude.Name = "buttonAbsoluteMagnitude";
		buttonAbsoluteMagnitude.Size = new Size(306, 29);
		buttonAbsoluteMagnitude.TabIndex = 10;
		buttonAbsoluteMagnitude.ToolTipValues.Description = "Copy to clipboard: Absolute magnitude, H";
		buttonAbsoluteMagnitude.ToolTipValues.EnableToolTips = true;
		buttonAbsoluteMagnitude.ToolTipValues.Heading = "Absolute magnitude, H";
		buttonAbsoluteMagnitude.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		buttonAbsoluteMagnitude.Values.DropDownArrowColor = Color.Empty;
		buttonAbsoluteMagnitude.Values.Text = "Absolute magnitude, &H";
		buttonAbsoluteMagnitude.Click += ButtonAbsoluteMagnitude_Click;
		buttonAbsoluteMagnitude.Enter += Control_Enter;
		buttonAbsoluteMagnitude.Leave += Control_Leave;
		buttonAbsoluteMagnitude.MouseEnter += Control_Enter;
		buttonAbsoluteMagnitude.MouseLeave += Control_Leave;
		// 
		// buttonSlopeParameter
		// 
		buttonSlopeParameter.AccessibleDescription = "Copies to clipboard: Slope parameter, G";
		buttonSlopeParameter.AccessibleName = "Copy to clipboard: Slope parameter, G";
		buttonSlopeParameter.AccessibleRole = AccessibleRole.PushButton;
		buttonSlopeParameter.ButtonStyle = ButtonStyle.Form;
		buttonSlopeParameter.Location = new Point(327, 50);
		buttonSlopeParameter.Name = "buttonSlopeParameter";
		buttonSlopeParameter.Size = new Size(306, 29);
		buttonSlopeParameter.TabIndex = 11;
		buttonSlopeParameter.ToolTipValues.Description = "Copy to clipboard: Slope parameter, G";
		buttonSlopeParameter.ToolTipValues.EnableToolTips = true;
		buttonSlopeParameter.ToolTipValues.Heading = "Slope parameter, G";
		buttonSlopeParameter.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		buttonSlopeParameter.Values.DropDownArrowColor = Color.Empty;
		buttonSlopeParameter.Values.Text = "Slope parame&ter, G";
		buttonSlopeParameter.Click += ButtonSlopeParameter_Click;
		buttonSlopeParameter.Enter += Control_Enter;
		buttonSlopeParameter.Leave += Control_Leave;
		buttonSlopeParameter.MouseEnter += Control_Enter;
		buttonSlopeParameter.MouseLeave += Control_Leave;
		// 
		// buttonReference
		// 
		buttonReference.AccessibleDescription = "Copies to clipboard: Reference";
		buttonReference.AccessibleName = "Copy to clipboard: Reference";
		buttonReference.AccessibleRole = AccessibleRole.PushButton;
		buttonReference.ButtonStyle = ButtonStyle.Form;
		buttonReference.Location = new Point(327, 85);
		buttonReference.Name = "buttonReference";
		buttonReference.Size = new Size(306, 29);
		buttonReference.TabIndex = 12;
		buttonReference.ToolTipValues.Description = "Copy to clipboard: Reference";
		buttonReference.ToolTipValues.EnableToolTips = true;
		buttonReference.ToolTipValues.Heading = "Reference";
		buttonReference.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		buttonReference.Values.DropDownArrowColor = Color.Empty;
		buttonReference.Values.Text = "&Reference";
		buttonReference.Click += ButtonReference_Click;
		buttonReference.Enter += Control_Enter;
		buttonReference.Leave += Control_Leave;
		buttonReference.MouseEnter += Control_Enter;
		buttonReference.MouseLeave += Control_Leave;
		// 
		// buttonObservationSpan
		// 
		buttonObservationSpan.AccessibleDescription = "Copies to clipboard: Observation span";
		buttonObservationSpan.AccessibleName = "Copy to clipboard: Observation span";
		buttonObservationSpan.AccessibleRole = AccessibleRole.PushButton;
		buttonObservationSpan.ButtonStyle = ButtonStyle.Form;
		buttonObservationSpan.Location = new Point(327, 193);
		buttonObservationSpan.Name = "buttonObservationSpan";
		buttonObservationSpan.Size = new Size(306, 29);
		buttonObservationSpan.TabIndex = 15;
		buttonObservationSpan.ToolTipValues.Description = "Copy to clipboard: Observation span";
		buttonObservationSpan.ToolTipValues.EnableToolTips = true;
		buttonObservationSpan.ToolTipValues.Heading = "Observation span";
		buttonObservationSpan.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		buttonObservationSpan.Values.DropDownArrowColor = Color.Empty;
		buttonObservationSpan.Values.Text = "Obser&vation span";
		buttonObservationSpan.Click += ButtonObservationSpan_Click;
		buttonObservationSpan.Enter += Control_Enter;
		buttonObservationSpan.Leave += Control_Leave;
		buttonObservationSpan.MouseEnter += Control_Enter;
		buttonObservationSpan.MouseLeave += Control_Leave;
		// 
		// buttonNumberOfObservations
		// 
		buttonNumberOfObservations.AccessibleDescription = "Copies to clipboard: Number of observations";
		buttonNumberOfObservations.AccessibleName = "Copy to clipboard: Number of observations";
		buttonNumberOfObservations.AccessibleRole = AccessibleRole.PushButton;
		buttonNumberOfObservations.ButtonStyle = ButtonStyle.Form;
		buttonNumberOfObservations.Location = new Point(327, 157);
		buttonNumberOfObservations.Name = "buttonNumberOfObservations";
		buttonNumberOfObservations.Size = new Size(306, 29);
		buttonNumberOfObservations.TabIndex = 14;
		buttonNumberOfObservations.ToolTipValues.Description = "Copy to clipboard: Number of observations";
		buttonNumberOfObservations.ToolTipValues.EnableToolTips = true;
		buttonNumberOfObservations.ToolTipValues.Heading = "Number of observations";
		buttonNumberOfObservations.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		buttonNumberOfObservations.Values.DropDownArrowColor = Color.Empty;
		buttonNumberOfObservations.Values.Text = "Number of o&bservations";
		buttonNumberOfObservations.Click += ButtonNumberOfObservations_Click;
		buttonNumberOfObservations.Enter += Control_Enter;
		buttonNumberOfObservations.Leave += Control_Leave;
		buttonNumberOfObservations.MouseEnter += Control_Enter;
		buttonNumberOfObservations.MouseLeave += Control_Leave;
		// 
		// buttonNumberOfOppositions
		// 
		buttonNumberOfOppositions.AccessibleDescription = "Copies to clipboard: Number of oppositions";
		buttonNumberOfOppositions.AccessibleName = "Copy to clipboard: Number of oppositions";
		buttonNumberOfOppositions.AccessibleRole = AccessibleRole.PushButton;
		buttonNumberOfOppositions.ButtonStyle = ButtonStyle.Form;
		buttonNumberOfOppositions.Location = new Point(327, 121);
		buttonNumberOfOppositions.Name = "buttonNumberOfOppositions";
		buttonNumberOfOppositions.Size = new Size(306, 29);
		buttonNumberOfOppositions.TabIndex = 13;
		buttonNumberOfOppositions.ToolTipValues.Description = "Copy to clipboard: Number of oppositions";
		buttonNumberOfOppositions.ToolTipValues.EnableToolTips = true;
		buttonNumberOfOppositions.ToolTipValues.Heading = "Number of oppositions";
		buttonNumberOfOppositions.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		buttonNumberOfOppositions.Values.DropDownArrowColor = Color.Empty;
		buttonNumberOfOppositions.Values.Text = "Number of o&ppositions";
		buttonNumberOfOppositions.Click += ButtonNumberOfOppositions_Click;
		buttonNumberOfOppositions.Enter += Control_Enter;
		buttonNumberOfOppositions.Leave += Control_Leave;
		buttonNumberOfOppositions.MouseEnter += Control_Enter;
		buttonNumberOfOppositions.MouseLeave += Control_Leave;
		// 
		// buttonFlags
		// 
		buttonFlags.AccessibleDescription = "Copies to clipboard: 4-hexdigit flags";
		buttonFlags.AccessibleName = "Copy to clipboard: 4-hexdigit flags";
		buttonFlags.AccessibleRole = AccessibleRole.PushButton;
		buttonFlags.ButtonStyle = ButtonStyle.Form;
		buttonFlags.Location = new Point(327, 300);
		buttonFlags.Name = "buttonFlags";
		buttonFlags.Size = new Size(306, 29);
		buttonFlags.TabIndex = 18;
		buttonFlags.ToolTipValues.Description = "Copy to clipboard: 4-hexdigit flags";
		buttonFlags.ToolTipValues.EnableToolTips = true;
		buttonFlags.ToolTipValues.Heading = "4-hexdigit flags";
		buttonFlags.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		buttonFlags.Values.DropDownArrowColor = Color.Empty;
		buttonFlags.Values.Text = "&4-hexdigit flags";
		buttonFlags.Click += ButtonFlags_Click;
		buttonFlags.Enter += Control_Enter;
		buttonFlags.Leave += Control_Leave;
		buttonFlags.MouseEnter += Control_Enter;
		buttonFlags.MouseLeave += Control_Leave;
		// 
		// buttonComputerName
		// 
		buttonComputerName.AccessibleDescription = "Copies to clipboard: Computer name";
		buttonComputerName.AccessibleName = "Copy to clipboard: Computer name";
		buttonComputerName.AccessibleRole = AccessibleRole.PushButton;
		buttonComputerName.ButtonStyle = ButtonStyle.Form;
		buttonComputerName.Location = new Point(327, 264);
		buttonComputerName.Name = "buttonComputerName";
		buttonComputerName.Size = new Size(306, 29);
		buttonComputerName.TabIndex = 17;
		buttonComputerName.ToolTipValues.Description = "Copy to clipboard: Computer name";
		buttonComputerName.ToolTipValues.EnableToolTips = true;
		buttonComputerName.ToolTipValues.Heading = "Computer name";
		buttonComputerName.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		buttonComputerName.Values.DropDownArrowColor = Color.Empty;
		buttonComputerName.Values.Text = "Computer &name";
		buttonComputerName.Click += ButtonComputerName_Click;
		buttonComputerName.Enter += Control_Enter;
		buttonComputerName.Leave += Control_Leave;
		buttonComputerName.MouseEnter += Control_Enter;
		buttonComputerName.MouseLeave += Control_Leave;
		// 
		// buttonRmsResidual
		// 
		buttonRmsResidual.AccessibleDescription = "Copies to clipboard: r.m.s. residual (\")";
		buttonRmsResidual.AccessibleName = "Copy to clipboard: r.m.s. residual (\")";
		buttonRmsResidual.AccessibleRole = AccessibleRole.PushButton;
		buttonRmsResidual.ButtonStyle = ButtonStyle.Form;
		buttonRmsResidual.Location = new Point(327, 228);
		buttonRmsResidual.Name = "buttonRmsResidual";
		buttonRmsResidual.Size = new Size(306, 29);
		buttonRmsResidual.TabIndex = 16;
		buttonRmsResidual.ToolTipValues.Description = "Copy to clipboard: r.m.s. residual (\")";
		buttonRmsResidual.ToolTipValues.EnableToolTips = true;
		buttonRmsResidual.ToolTipValues.Heading = "r.m.s. residual (\")";
		buttonRmsResidual.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		buttonRmsResidual.Values.DropDownArrowColor = Color.Empty;
		buttonRmsResidual.Values.Text = "r.m.s. resid&ual (\")";
		buttonRmsResidual.Click += ButtonRmsResidual_Click;
		buttonRmsResidual.Enter += Control_Enter;
		buttonRmsResidual.Leave += Control_Leave;
		buttonRmsResidual.MouseEnter += Control_Enter;
		buttonRmsResidual.MouseLeave += Control_Leave;
		// 
		// buttonDateOfLastObservation
		// 
		buttonDateOfLastObservation.AccessibleDescription = "Copies to clipboard: Date of last observation (YYYMMDD)";
		buttonDateOfLastObservation.AccessibleName = "Copy to clipboard: Date of last observation (YYYMMDD)";
		buttonDateOfLastObservation.AccessibleRole = AccessibleRole.PushButton;
		buttonDateOfLastObservation.ButtonStyle = ButtonStyle.Form;
		buttonDateOfLastObservation.Location = new Point(327, 336);
		buttonDateOfLastObservation.Name = "buttonDateOfLastObservation";
		buttonDateOfLastObservation.Size = new Size(306, 29);
		buttonDateOfLastObservation.TabIndex = 19;
		buttonDateOfLastObservation.ToolTipValues.Description = "Copy to clipboard: Date of last observation (YYYMMDD)";
		buttonDateOfLastObservation.ToolTipValues.EnableToolTips = true;
		buttonDateOfLastObservation.ToolTipValues.Heading = "Date of last observation (YYYMMDD)";
		buttonDateOfLastObservation.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		buttonDateOfLastObservation.Values.DropDownArrowColor = Color.Empty;
		buttonDateOfLastObservation.Values.Text = "Date of last observation &(YYYMMDD)";
		buttonDateOfLastObservation.Click += ButtonDateOfLastObservation_Click;
		buttonDateOfLastObservation.Enter += Control_Enter;
		buttonDateOfLastObservation.Leave += Control_Leave;
		buttonDateOfLastObservation.MouseEnter += Control_Enter;
		buttonDateOfLastObservation.MouseLeave += Control_Leave;
		// 
		// kryptonPanelMain
		// 
		kryptonPanelMain.AccessibleDescription = "Groups the data";
		kryptonPanelMain.AccessibleName = "Panel";
		kryptonPanelMain.AccessibleRole = AccessibleRole.Pane;
		kryptonPanelMain.Controls.Add(buttonDateOfLastObservation);
		kryptonPanelMain.Controls.Add(buttonFlags);
		kryptonPanelMain.Controls.Add(buttonComputerName);
		kryptonPanelMain.Controls.Add(buttonRmsResidual);
		kryptonPanelMain.Controls.Add(buttonObservationSpan);
		kryptonPanelMain.Controls.Add(buttonNumberOfObservations);
		kryptonPanelMain.Controls.Add(buttonNumberOfOppositions);
		kryptonPanelMain.Controls.Add(buttonReference);
		kryptonPanelMain.Controls.Add(buttonSlopeParameter);
		kryptonPanelMain.Controls.Add(buttonAbsoluteMagnitude);
		kryptonPanelMain.Controls.Add(buttonSemimajorAxis);
		kryptonPanelMain.Controls.Add(buttonMeanDailyMotion);
		kryptonPanelMain.Controls.Add(buttonOrbitalEccentricity);
		kryptonPanelMain.Controls.Add(buttonInclination);
		kryptonPanelMain.Controls.Add(buttonArgumentOfPerihelion);
		kryptonPanelMain.Controls.Add(buttonLongitudeOfTheAscendingNode);
		kryptonPanelMain.Controls.Add(buttonEpoch);
		kryptonPanelMain.Controls.Add(buttonMeanAnomaly);
		kryptonPanelMain.Controls.Add(buttonIndexNumber);
		kryptonPanelMain.Controls.Add(buttonReadableDesignation);
		kryptonPanelMain.Dock = DockStyle.Fill;
		kryptonPanelMain.Location = new Point(0, 0);
		kryptonPanelMain.Name = "kryptonPanelMain";
		kryptonPanelMain.PanelBackStyle = PaletteBackStyle.FormMain;
		kryptonPanelMain.Size = new Size(644, 377);
		kryptonPanelMain.TabIndex = 0;
		kryptonPanelMain.TabStop = true;
		// 
		// kryptonStatusStrip
		// 
		kryptonStatusStrip.AccessibleDescription = "Shows some information";
		kryptonStatusStrip.AccessibleName = "Status bar with some information";
		kryptonStatusStrip.AccessibleRole = AccessibleRole.StatusBar;
		kryptonStatusStrip.AllowClickThrough = true;
		kryptonStatusStrip.AllowItemReorder = true;
		kryptonStatusStrip.Dock = DockStyle.None;
		kryptonStatusStrip.Font = new Font("Segoe UI", 9F);
		kryptonStatusStrip.Items.AddRange(new ToolStripItem[] { labelInformation });
		kryptonStatusStrip.Location = new Point(0, 0);
		kryptonStatusStrip.Name = "kryptonStatusStrip";
		kryptonStatusStrip.Padding = new Padding(1, 0, 16, 0);
		kryptonStatusStrip.ProgressBars = null;
		kryptonStatusStrip.RenderMode = ToolStripRenderMode.ManagerRenderMode;
		kryptonStatusStrip.ShowItemToolTips = true;
		kryptonStatusStrip.Size = new Size(644, 22);
		kryptonStatusStrip.SizingGrip = false;
		kryptonStatusStrip.TabIndex = 20;
		kryptonStatusStrip.TabStop = true;
		kryptonStatusStrip.Text = "Status bar";
		// 
		// labelInformation
		// 
		labelInformation.AccessibleDescription = "Shows some information";
		labelInformation.AccessibleName = "Shows some information";
		labelInformation.AccessibleRole = AccessibleRole.StaticText;
		labelInformation.AutoToolTip = true;
		labelInformation.Image = FatcowIcons16px.fatcow_lightbulb_16px;
		labelInformation.Name = "labelInformation";
		labelInformation.Size = new Size(144, 17);
		labelInformation.Text = "some information here";
		labelInformation.ToolTipText = "Shows some information";
		// 
		// toolStripContainer
		// 
		// 
		// toolStripContainer.BottomToolStripPanel
		// 
		toolStripContainer.BottomToolStripPanel.Controls.Add(kryptonStatusStrip);
		// 
		// toolStripContainer.ContentPanel
		// 
		toolStripContainer.ContentPanel.Controls.Add(kryptonPanelMain);
		toolStripContainer.ContentPanel.Size = new Size(644, 377);
		toolStripContainer.Dock = DockStyle.Fill;
		toolStripContainer.Location = new Point(0, 0);
		toolStripContainer.Name = "toolStripContainer";
		toolStripContainer.Size = new Size(644, 399);
		toolStripContainer.TabIndex = 1;
		toolStripContainer.TopToolStripPanelVisible = false;
		// 
		// kryptonManager
		// 
		kryptonManager.GlobalPaletteMode = PaletteMode.Global;
		kryptonManager.ToolkitStrings.MessageBoxStrings.LessDetails = "L&ess Details...";
		kryptonManager.ToolkitStrings.MessageBoxStrings.MoreDetails = "&More Details...";
		// 
		// CopyDataToClipboardForm
		// 
		AccessibleDescription = "Copies data to clipboard";
		AccessibleName = "Copy data to clipboard";
		AccessibleRole = AccessibleRole.Dialog;
		AutoScaleDimensions = new SizeF(7F, 15F);
		AutoScaleMode = AutoScaleMode.Font;
		ClientSize = new Size(644, 399);
		ControlBox = false;
		Controls.Add(toolStripContainer);
		FormBorderStyle = FormBorderStyle.FixedToolWindow;
		Icon = (Icon)resources.GetObject("$this.Icon");
		Margin = new Padding(4, 3, 4, 3);
		MaximizeBox = false;
		MinimizeBox = false;
		Name = "CopyDataToClipboardForm";
		StartPosition = FormStartPosition.CenterScreen;
		Text = "Copy data to clipboard";
		Load += CopyDataToClipboardForm_Load;
		((ISupportInitialize)kryptonPanelMain).EndInit();
		kryptonPanelMain.ResumeLayout(false);
		kryptonStatusStrip.ResumeLayout(false);
		kryptonStatusStrip.PerformLayout();
		toolStripContainer.BottomToolStripPanel.ResumeLayout(false);
		toolStripContainer.BottomToolStripPanel.PerformLayout();
		toolStripContainer.ContentPanel.ResumeLayout(false);
		toolStripContainer.ResumeLayout(false);
		toolStripContainer.PerformLayout();
		ResumeLayout(false);
	}

	#endregion

	private KryptonButton buttonIndexNumber;
	private KryptonButton buttonReadableDesignation;
	private KryptonPanel kryptonPanelMain;
	private KryptonButton buttonArgumentOfPerihelion;
	private KryptonButton buttonLongitudeOfTheAscendingNode;
	private KryptonButton buttonEpoch;
	private KryptonButton buttonMeanAnomaly;
	private KryptonButton buttonReference;
	private KryptonButton buttonSlopeParameter;
	private KryptonButton buttonAbsoluteMagnitude;
	private KryptonButton buttonSemimajorAxis;
	private KryptonButton buttonMeanDailyMotion;
	private KryptonButton buttonOrbitalEccentricity;
	private KryptonButton buttonInclination;
	private KryptonButton buttonDateOfLastObservation;
	private KryptonButton buttonFlags;
	private KryptonButton buttonComputerName;
	private KryptonButton buttonRmsResidual;
	private KryptonButton buttonObservationSpan;
	private KryptonButton buttonNumberOfObservations;
	private KryptonButton buttonNumberOfOppositions;
	private KryptonStatusStrip kryptonStatusStrip;
	private ToolStripStatusLabel labelInformation;
	private ToolStripContainer toolStripContainer;
	private KryptonManager kryptonManager;
}