// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using Krypton.Toolkit;

using NLog;

using Planetoid_DB.Forms;
using Planetoid_DB.Helpers;

using System.Diagnostics;

using Settings = Planetoid_DB.Properties.Settings;

namespace Planetoid_DB;

/// <summary>Form for comparing two MPCORB.DAT files and displaying the differences.</summary>
/// <remarks>This form allows users to select two MPCORB.DAT files, compare their contents, and view the differences in a user-friendly interface. The form includes functionality for saving the comparison results in various formats and navigating to specific records in the main form based on the differences identified.</remarks>
// You can customize the debugger display for this class by providing a method that returns a string representation of the instance, which will be shown in the debugger when you inspect an object of this class. In this case, the GetDebuggerDisplay method is used to return a string representation of the instance, and the DebuggerDisplay attribute is applied to the class to specify that this method should be used for the debugger display.
[DebuggerDisplay(value: "{" + nameof(GetDebuggerDisplay) + "(),nq}")]
public partial class DatabaseDifferencesForm : BaseKryptonForm
{
	#region Export override properties

	/// <summary>Gets the ListView control used for export operations.</summary>
	/// <remarks>Overrides the base export source to use this form's virtual results list.</remarks>
	protected override ListView? ExportListView => listViewResults;

	/// <summary>Gets the title used for exported data.</summary>
	/// <remarks>Overrides the base export title for this form's content.</remarks>
	protected override string ExportTitle => "Database Differences";

	/// <summary>Gets the file name prefix used for exported files.</summary>
	/// <remarks>Overrides the default export file prefix for this form.</remarks>
	protected override string ExportFilePrefix => fileName;

	/// <summary>Gets the virtual row provider used during export operations.</summary>
	/// <remarks>Overrides the base export row provider to read items from the virtual list.</remarks>
	protected override Func<int, ListViewItem>? ExportVirtualRowProvider => GetVirtualListViewItem;

	#endregion

	/// <summary>NLog logger for logging messages and errors.</summary>
	/// <remarks>This logger is used to log messages and errors that occur within the form.</remarks>
	private static readonly Logger logger = LogManager.GetCurrentClassLogger();

	/// <summary>Gets the name of the file that stores the database differences.</summary>
	/// <remarks>This field stores the name of the file where the database differences are saved. It is used to identify the file when performing read or write operations related to database differences.</remarks>
	private readonly string fileName = "database-differences";

	/// <summary>Gets or sets the path of the first file.</summary>
	/// <remarks>This field stores the path of the first MPCORB.DAT file to be compared.</remarks>
	private string pathFile1 = string.Empty;

	/// <summary>Gets or sets the path of the second file.</summary>
	/// <remarks>This field stores the path of the second MPCORB.DAT file to be compared.</remarks>
	private string pathFile2 = string.Empty;

	/// <summary>Tracks the number of records that have been added, deleted, or changed during a data operation.</summary>
	/// <remarks>These fields are used to monitor the state of records as operations are performed. Their values are updated to reflect the outcome of add, delete, or change actions, enabling consumers to determine how many records were affected.</remarks>
	private int addedRecords, deletedRecords, changedRecords;

	/// <summary>Represents the result of a comparison, including the index, designation, and the difference observed.</summary>
	/// <param name="Index">The index of the item in the comparison, indicating its position in the original dataset.</param>
	/// <param name="Designation">The designation or label associated with the item being compared, providing context for the comparison.</param>
	/// <param name="Difference">The difference observed between the compared items, detailing the nature of the discrepancy.</param>
	/// <remarks>This record struct is used to encapsulate the result of a comparison between two items, including their index, designation, and the observed difference.</remarks>
	private record struct DifferenceResult(string Index, string Designation, string Difference);

	/// <summary>Contains the list of difference results that have been computed.</summary>
	/// <remarks>This field stores the results generated by difference computations. The list is initialized as empty and is populated during relevant operations. Access to this field is typically provided through a property or method for further analysis or reporting.</remarks>
	private readonly List<DifferenceResult> differenceResults = [];

	/// <summary>Gets the status label to be used for displaying information.</summary>
	/// <remarks>This property provides access to the status label used for displaying information in the form's status strip.</remarks>
	protected override ToolStripStatusLabel? StatusLabel => labelInformation;

	/// <summary>Cancellation token source for managing cancellation of asynchronous operations.</summary>
	/// <remarks>This field is used to signal cancellation requests for ongoing asynchronous operations. It should be properly disposed of when no longer needed to free resources.</remarks>
	private CancellationTokenSource? _cancellationTokenSource;

	#region Constructor

	/// <summary>Initializes a new instance of the <see cref="DatabaseDifferencesForm"/> class.</summary>
	/// <remarks>This constructor sets up the form.</remarks>
	public DatabaseDifferencesForm()
	{
		// Initialize the form's components, setting up the user interface elements and layout as defined in the designer file.
		InitializeComponent();
	}

	#endregion

	#region helpers

	/// <summary>Returns a short debugger display string for this instance.</summary>
	/// <returns>A string representation of the current instance for use in the debugger.</returns>
	/// <remarks>This method is used to provide a custom debugger display string.</remarks>
	private string GetDebuggerDisplay() => ToString();

	/// <summary>Compares two PlanetoidRecord objects and returns a string describing the differences.</summary>
	/// <param name="r1">The first PlanetoidRecord to compare.</param>
	/// <param name="r2">The second PlanetoidRecord to compare.</param>
	/// <returns>A string describing the differences between the two records, or an empty string if they are identical.</returns>
	private static string CompareRecords(PlanetoidRecord r1, PlanetoidRecord r2)
	{
		// Create a list to hold the differences between the two records
		List<string> diffs = [];
		// Compare the Epoch field of the two records and add a description of any differences to the list
		if (r1.Epoch != r2.Epoch)
		{
			diffs.Add(item: $"Epoch: {r1.Epoch} -> {r2.Epoch}");
		}
		// Compare the Mean Anomaly field of the two records and add a description of any differences to the list
		if (r1.MeanAnomaly != r2.MeanAnomaly)
		{
			diffs.Add(item: $"MA: {r1.MeanAnomaly} -> {r2.MeanAnomaly}");
		}
		// Compare the Argument of Perihelion field of the two records and add a description of any differences to the list
		if (r1.ArgPeri != r2.ArgPeri)
		{
			diffs.Add(item: $"ArgPeri: {r1.ArgPeri} -> {r2.ArgPeri}");
		}
		// Compare the Longitude of Ascending Node field of the two records and add a description of any differences to the list
		if (r1.LongAscNode != r2.LongAscNode)
		{
			diffs.Add(item: $"LAN: {r1.LongAscNode} -> {r2.LongAscNode}");
		}
		// Compare the Inclination field of the two records ListViewResults_DoubleClickand add a description of any differences to the list
		if (r1.Incl != r2.Incl)
		{
			diffs.Add(item: $"Incl: {r1.Incl} -> {r2.Incl}");
		}
		// Compare the Orbital Eccentricity field of the two records and add a description of any differences to the list
		if (r1.OrbEcc != r2.OrbEcc)
		{
			diffs.Add(item: $"Ecc: {r1.OrbEcc} -> {r2.OrbEcc}");
		}
		// Compare the Semi-Major Axis field of the two records and add a description of any differences to the list
		if (r1.SemiMajorAxis != r2.SemiMajorAxis)
		{
			diffs.Add(item: $"a: {r1.SemiMajorAxis} -> {r2.SemiMajorAxis}");
		}
		// Compare the Absolute Magnitude field of the two records and add a description of any differences to the list
		if (r1.MagAbs != r2.MagAbs)
		{
			diffs.Add(item: $"H: {r1.MagAbs} -> {r2.MagAbs}");
		}
		// Compare the Slope Parameter field of the two records and add a description of any differences to the list
		if (r1.SlopeParam != r2.SlopeParam)
		{
			diffs.Add(item: $"G: {r1.SlopeParam} -> {r2.SlopeParam}");
		}
		// Compare the Designation Name field of the two records and add a description of any differences to the list
		if (r1.DesignationName != r2.DesignationName)
		{
			diffs.Add(item: $"Desig: {r1.DesignationName} -> {r2.DesignationName}");
		}
		// Compare the Mean Daily Motion field of the two records and add a description of any differences to the list
		if (r1.Motion != r2.Motion)
		{
			diffs.Add(item: $"n: {r1.Motion} -> {r2.Motion}");
		}
		// Compare the Reference field of the two records and add a description of any differences to the list
		if (r1.Ref != r2.Ref)
		{
			diffs.Add(item: $"Ref: {r1.Ref} -> {r2.Ref}");
		}
		// Compare the Number of Oppositions field of the two records and add a description of any differences to the list
		if (r1.NumberOpposition != r2.NumberOpposition)
		{
			diffs.Add(item: $"Opps: {r1.NumberOpposition} -> {r2.NumberOpposition}");
		}
		// Compare the Number of Observations field of the two records and add a description of any differences to the list
		if (r1.NumberObservation != r2.NumberObservation)
		{
			diffs.Add(item: $"Obs: {r1.NumberObservation} -> {r2.NumberObservation}");
		}
		// Compare the Observation Span field of the two records and add a description of any differences to the list
		if (r1.ObsSpan != r2.ObsSpan)
		{
			diffs.Add(item: $"ObsSpan: {r1.ObsSpan} -> {r2.ObsSpan}");
		}
		// Compare the R.M.S. Residual field of the two records and add a description of any differences to the list
		if (r1.RmsResidual != r2.RmsResidual)
		{
			diffs.Add(item: $"rms: {r1.RmsResidual} -> {r2.RmsResidual}");
		}
		// Compare the Computer Name field of the two records and add a description of any differences to the list
		if (r1.ComputerName != r2.ComputerName)
		{
			diffs.Add(item: $"Computer: {r1.ComputerName} -> {r2.ComputerName}");
		}
		// Compare the Flags field of the two records and add a description of any differences to the list
		if (r1.Flags != r2.Flags)
		{
			diffs.Add(item: $"Flags: {r1.Flags} -> {r2.Flags}");
		}
		// Compare the Observation Last Date field of the two records and add a description of any differences to the list
		if (r1.ObservationLastDate != r2.ObservationLastDate)
		{
			diffs.Add(item: $"LastObs: {r1.ObservationLastDate} -> {r2.ObservationLastDate}");
		}
		// Join the list of differences into a single string separated by semicolons and return it; if there are no differences, return an empty string
		return diffs.Count > 0 ? string.Join(separator: "; ", values: diffs) : string.Empty;
	}

	/// <summary>Navigates to the corresponding record in the main form based on the user's selection in the ListView.</summary>
	/// <remarks>If no record is selected, a warning message is displayed. If the selected record has been deleted, a notification is shown. Otherwise, the method attempts to jump to the selected record in the main form. This method is intended to be used in response to user actions that require focusing on a specific record from a list of database differences.</remarks>
	private void GoToObject()
	{
		// Check if there are any selected indices in the ListView, and if not, return early to prevent errors; if there is a selected index, retrieve the corresponding DifferenceResult and either show a message if the record was deleted or jump to the record in the main form if it still exists
		if (listViewResults.SelectedIndices.Count == 0)
		{
			_ = KryptonMessageBox.Show(owner: this, text: "Please select a record to jump to.", caption: "No Record Selected", buttons: KryptonMessageBoxButtons.OK, icon: KryptonMessageBoxIcon.Warning);
			return;
		}
		// Get the first selected index from the ListView and check if it is within the bounds of the difference results list; if so, retrieve the corresponding DifferenceResult and determine whether to show a message about a deleted record or to jump to the record in the main form based on the type of difference
		int selectedIndex = listViewResults.SelectedIndices[index: 0];
		if (selectedIndex >= 0 && selectedIndex < differenceResults.Count)
		{
			DifferenceResult result = differenceResults[index: selectedIndex];
			if (result.Difference.Equals(value: "Deleted record", comparisonType: StringComparison.OrdinalIgnoreCase))
			{
				_ = KryptonMessageBox.Show(owner: this, text: "The selected record has been deleted and is no longer available.", caption: "Record Deleted", buttons: KryptonMessageBoxButtons.OK, icon: KryptonMessageBoxIcon.Warning);
			}
			else
			{
				// Attempt to find the main form of the application and, if it exists, call a method to jump to the record corresponding to the selected difference result based on its index and designation
				if (Application.OpenForms.OfType<PlanetoidDbForm>().FirstOrDefault() is PlanetoidDbForm mainForm)
				{
					Close();
					mainForm.JumpToRecord(index: result.Index, designation: result.Designation);
				}
			}
		}
	}

	/// <summary>Updates the progress bar and status label based on the provided report data.</summary>
	/// <param name="report">A tuple containing the percentage of completion, status message, and an optional batch of difference results to be added to the list view.</param>
	/// <remarks>This method is called to update the UI elements that display progress information during the comparison of files. It ensures that the progress bar value is clamped between 0 and 100, updates the text of the progress bar, and sets the taskbar progress value. If a batch of difference results is provided, it adds them to the list view and updates its virtual size accordingly.</remarks>
	private void UpdateProgress((int Percent, string Status, List<DifferenceResult>? Batch) report)
	{
		// Clamp the progress bar value between 0 and 100 to ensure it stays within valid bounds
		kryptonProgressBar.Value = Math.Max(0, Math.Min(100, report.Percent));
		// Update the text of the progress bar to show either the status message or the percentage completed, depending on whether a status message is provided
		kryptonProgressBar.Text = string.IsNullOrEmpty(value: report.Status) ? $"{report.Percent}%" : report.Status;
		// Update the taskbar progress value to reflect the current percentage of completion, using the window handle of the form and setting the maximum value to 100
		TaskbarProgress.SetValue(windowHandle: Handle, progressValue: (ulong)report.Percent, progressMax: 100);
		// If a batch of difference results is provided and it contains items, add them to the difference results list and update the virtual list size of the ListView to reflect the new total count of difference results
		if (report.Batch != null && report.Batch.Count > 0)
		{
			differenceResults.AddRange(collection: report.Batch);
			listViewResults.VirtualListSize = differenceResults.Count;
		}
	}

	/// <summary>Compares two MPCORB.DAT files asynchronously and reports progress.</summary>
	/// <param name="p1">The path to the first MPCORB.DAT file.</param>
	/// <param name="p2">The path to the second MPCORB.DAT file.</param>
	/// <param name="file1IsNewer">Indicates whether the first file is newer than the second.</param>
	/// <param name="progress">An object to report progress updates.</param>
	/// <param name="token">A cancellation token to cancel the operation.</param>
	/// <remarks>This method reads the first file into a dictionary of PlanetoidRecord objects, then reads the second file line by line, comparing each record to the corresponding record in the first file. Differences are collected and reported in batches to the progress reporter. The method also checks for added or deleted records and reports them accordingly.</remarks>
	private void CompareFilesAsync(string p1, string p2, bool file1IsNewer, IProgress<(int, string, List<DifferenceResult>?)> progress, CancellationToken token)
	{
		// Report initial progress indicating that the reference file is being loaded
		progress.Report(value: (0, "Loading Reference File...", null));
		// Create a dictionary to hold the records from the first file, using the designation name as the key
		Dictionary<string, PlanetoidRecord> records1 = new();
		// Read each line from the first file and parse it into a PlanetoidRecord, adding it to the dictionary if it has a valid designation name
		foreach (string line in File.ReadLines(path: p1))
		{
			// Check for cancellation requests and throw an exception if cancellation has been requested
			token.ThrowIfCancellationRequested();
			// Only process lines that are long enough to be valid records and do not start with a comment character
			if (line.Length > 200 && !line.StartsWith(value: '#'))
			{
				// Parse the line into a PlanetoidRecord and add it to the dictionary if it has a valid designation name
				PlanetoidRecord record = PlanetoidRecord.Parse(rawLine: line);
				if (!string.IsNullOrEmpty(value: record.DesignationName))
				{
					records1[key: record.DesignationName] = record;
				}
			}
		}
		// Report progress indicating that the comparison of files is starting
		progress.Report(value: (0, "Comparing Files...", null));
		// Get the total number of bytes in the second file to calculate progress percentage
		long totalBytesFile2 = new FileInfo(fileName: p2).Length;
		// Initialize a variable to track the number of bytes read from the second file
		long currentBytesRead = 0;
		// Initialize a list to hold the results of differences found during the comparison
		List<DifferenceResult> batchResults = new();
		// Initialize variables to track the last time progress was reported and the interval for reporting progress
		long lastReportTicks = DateTime.Now.Ticks;
		// Set the interval for reporting progress to 100 milliseconds
		long reportIntervalTicks = TimeSpan.FromMilliseconds(milliseconds: 100).Ticks;
		// Open the second file for reading and process it line by line
		using (StreamReader reader = new(path: p2))
		{
			// Read each line from the second file until the end of the file is reached
			string? line;
			// For each line, check for cancellation requests, update the number of bytes read, and compare the record to the corresponding record in the first file
			while ((line = reader.ReadLine()) != null)
			{
				// Check for cancellation requests and throw an exception if cancellation has been requested
				token.ThrowIfCancellationRequested();
				// Update the current number of bytes read by adding the length of the line and the newline characters (assumed to be 2 bytes for CRLF)
				currentBytesRead += line.Length + 2;
				// Only process lines that are long enough to be valid records and do not start with a comment character
				if (line.Length >= 200 && !line.StartsWith(value: '#'))
				{
					// Parse the line into a PlanetoidRecord and check if it has a valid designation name
					PlanetoidRecord record2 = PlanetoidRecord.Parse(rawLine: line);
					// If the record has a valid designation name, attempt to find the corresponding record in the first file's dictionary and compare them
					if (!string.IsNullOrEmpty(value: record2.DesignationName))
					{
						// If a corresponding record is found in the first file, compare the two records and add any differences to the batch results; if no corresponding record is found, note that the record was added or deleted based on which file is newer
						if (records1.TryGetValue(key: record2.DesignationName, value: out PlanetoidRecord record1))
						{
							// Compare the two records and get a string describing the differences, if any
							string diff = file1IsNewer ? CompareRecords(r1: record2, r2: record1) : CompareRecords(r1: record1, r2: record2);
							// If there are any differences, add a new DifferenceResult to the batch results and increment the count of changed records; then remove the record from the first file's dictionary to track which records have been processed
							if (!string.IsNullOrEmpty(value: diff))
							{
								// Add a new DifferenceResult to the batch results with the index, designation, and description of the differences
								batchResults.Add(item: new DifferenceResult(record2.Index, Designation: record2.DesignationName, Difference: diff));
								// Increment the count of changed records to reflect that a difference was found between the two files
								changedRecords++;
							}
							// Remove the record from the first file's dictionary to track which records have been processed and to identify any remaining records that may have been added or deleted
							records1.Remove(key: record2.DesignationName);
						}
						// If no corresponding record is found in the first file's dictionary, determine whether the record was added or deleted based on which file is newer, and add a new DifferenceResult to the batch results accordingly; also increment the count of added or deleted records
						else
						{
							// Determine whether the record was added or deleted based on which file is newer, and create a description of the difference
							string diffText = file1IsNewer ? "Deleted record" : "Added record";
							// Add a new DifferenceResult to the batch results with the index, designation, and description of the difference
							batchResults.Add(item: new DifferenceResult(record2.Index, Designation: record2.DesignationName, Difference: diffText));
							// Increment the count of added or deleted records based on which file is newer
							if (file1IsNewer)
							{
								deletedRecords++;
							}
							else
							{
								addedRecords++;
							}
						}
					}
				}
				// Check if the batch results have reached a size of 1000, and if so, report the current progress and clear the batch results for the next set of differences
				long currentTicks = DateTime.Now.Ticks;
				// If the time since the last report exceeds the report interval, report the current progress and clear the batch results; this ensures that progress is reported at regular intervals even if the batch size has not been reached
				if (currentTicks - lastReportTicks > reportIntervalTicks)
				{
					// Calculate the percentage of completion based on the total bytes read from the second file and the total size of the second file; if the total size is zero, set the percentage to zero to avoid division by zero
					int percent = totalBytesFile2 > 0 ? (int)((double)currentBytesRead / totalBytesFile2 * 100) : 0;
					// Report the current progress, including the percentage completed, an empty status message, and a copy of the current batch results; then clear the batch results and update the last report time
					progress.Report(value: (percent, string.Empty, new List<DifferenceResult>(collection: batchResults)));
					// Clear the batch results to prepare for the next set of differences to be collected
					batchResults.Clear();
					// Update the last report time to the current time to track when the next progress report should be sent
					lastReportTicks = currentTicks;
				}
			}
		}
		// After processing all lines in the second file, report progress indicating that the check for added records is starting
		progress.Report(value: (100, "Checking for added records...", null));
		// Iterate through any remaining records in the first file's dictionary, which represent records that were not found in the second file, and add them to the batch results as either added or deleted records based on which file is newer; also increment the count of added or deleted records accordingly
		foreach (var entry in records1)
		{
			// Check for cancellation requests and throw an exception if cancellation has been requested
			token.ThrowIfCancellationRequested();
			// Determine whether the record was added or deleted based on which file is newer, and create a description of the difference
			string diffText = file1IsNewer ? "Added record" : "Deleted record";
			// Add a new DifferenceResult to the batch results with the index, designation, and description of the difference
			batchResults.Add(item: new DifferenceResult(entry.Value.Index, Designation: entry.Key, Difference: diffText));
			// Increment the count of added or deleted records based on which file is newer
			if (file1IsNewer)
			{
				addedRecords++;
			}
			else
			{
				deletedRecords++;
			}
			// If the batch results have reached a size of 1000, report the current progress and clear the batch results for the next set of differences
			if (batchResults.Count >= 1000)
			{
				// Report the current progress, including a percentage of 100 (indicating completion), an empty status message, and a copy of the current batch results; then clear the batch results for the next set of differences
				progress.Report(value: (100, string.Empty, new List<DifferenceResult>(collection: batchResults)));
				// Clear the batch results to prepare for the next set of differences to be collected
				batchResults.Clear();
			}
		}
		// After processing all remaining records, if there are any results left in the batch, report them to ensure that all differences are captured and displayed to the user
		if (batchResults.Count > 0)
		{
			// Report the final batch of results, including a percentage of 100 (indicating completion), an empty status message, and a copy of the current batch results; this ensures that any remaining differences are displayed to the user
			progress.Report(value: (100, string.Empty, new List<DifferenceResult>(collection: batchResults)));
		}
	}

	#endregion

	#region Form event handlers

	/// <summary>Handles the <see cref="Form.Load"/> event for the <see cref="DatabaseDifferencesForm"/>. Initializes default file paths and updates the initial UI state.</summary>
	/// <param name="sender">The source of the event.</param>
	/// <param name="e">The <see cref="EventArgs"/> instance containing the event data.</param>
	/// <remarks>This method initializes the form with default file paths and updates the UI elements accordingly.</remarks>
	private void DatabaseDifferencesForm_Load(object sender, EventArgs e)
	{
		// Default to the currently configured MPCORB file
		pathFile1 = Settings.Default.systemFilenameMpcorbDat;
		// Check if the default file exists and update the label accordingly
		if (!File.Exists(path: pathFile1))
		{
			pathFile1 = string.Empty;
			kryptonLabelFile1.Text = "No file selected";
		}
		else
		{
			kryptonLabelFile1.Text = pathFile1;
		}
		// Initialize the second file path and label
		pathFile2 = string.Empty;
		kryptonLabelFile2.Text = "No file selected";
	}

	#endregion

	#region Click event handlers

	/// <summary>Handles the click event for the file selection button, allowing the user to select a file from the system.</summary>
	/// <remarks>The method opens a file dialog with a filter for MPCORB files and updates the label with the selected file path if a file is chosen.</remarks>
	/// <param name="sender">The source of the event, typically the button that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ButtonSelectFile1_Click(object sender, EventArgs e)
	{
		// Open a file dialog to allow the user to select the first MPCORB file for comparison
		using OpenFileDialog dlg = new();
		// Set the filter to show only .DAT files and all files, and set the title of the dialog
		dlg.Filter = "MPCORB Files (*.DAT)|*.DAT|All Files (*.*)|*.*";
		dlg.Title = "Select Reference MPCORB.DAT";
		// Show the dialog and if the user selects a file, update the path and label with the selected file path
		if (dlg.ShowDialog(owner: this) == DialogResult.OK)
		{
			pathFile1 = dlg.FileName;
			kryptonLabelFile1.Text = pathFile1;
		}
	}

	/// <summary>Handles the click event for the file selection button, allowing the user to select a file from the system.</summary>
	/// <remarks>The method opens a file dialog with a filter for MPCORB files and updates the label with the selected file path if a file is chosen.</remarks>
	/// <param name="sender">The source of the event, typically the button that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ButtonSelectFile2_Click(object sender, EventArgs e)
	{
		// Open a file dialog to allow the user to select the second MPCORB file for comparison
		using OpenFileDialog dlg = new();
		// Set the filter to show only .DAT files and all files, and set the title of the dialog
		dlg.Filter = "MPCORB Files (*.DAT)|*.DAT|All Files (*.*)|*.*";
		dlg.Title = "Select Comparison MPCORB.DAT";
		// Show the dialog and if the user selects a file, update the path and label with the selected file path
		if (dlg.ShowDialog(owner: this) == DialogResult.OK)
		{
			pathFile2 = dlg.FileName;
			kryptonLabelFile2.Text = pathFile2;
		}
	}

	/// <summary>Handles the click event for the compare button, initiating the comparison of the selected MPCORB files.</summary>
	/// <param name="sender">The source of the event, typically the button that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	/// <remarks>This method validates the selected files and initiates the comparison process asynchronously using <see cref="Task.Run"/> and <see cref="IProgress{T}"/>.</remarks>
	private async void ButtonCompare_Click(object sender, EventArgs e)
	{
		// Reset the counters for added, deleted, and changed records before starting the comparison
		addedRecords = deletedRecords = changedRecords = 0;
		// Validate that both file paths are not null or empty and that the files exist; if not, show an error message and return early
		if (string.IsNullOrEmpty(value: pathFile1) || !File.Exists(path: pathFile1))
		{
			ShowErrorMessage(message: "Please select a valid reference file (File 1).");
			return;
		}
		if (string.IsNullOrEmpty(value: pathFile2) || !File.Exists(path: pathFile2))
		{
			ShowErrorMessage(message: "Please select a valid comparison file (File 2).");
			return;
		}
		// Get the last write times of both files to determine if they are identical or which one is newer
		DateTime date1 = File.GetLastWriteTime(path: pathFile1);
		DateTime date2 = File.GetLastWriteTime(path: pathFile2);
		// If the last write times are identical, show a message indicating that the files are the same and abort further comparison
		if (date1 == date2)
		{
			KryptonMessageBox.Show(owner: this, text: "The file dates of both files are identical. The file contents of file 1 and file 2 are the same. Further comparison is aborted.", caption: "Notice", buttons: KryptonMessageBoxButtons.OK, icon: KryptonMessageBoxIcon.Information);
			return;
		}
		// Determine whether the first file is newer than the second file based on their last write times
		bool file1IsNewer = date1 > date2;
		// Clear any previous difference results and reset the ListView to prepare for new comparison results
		differenceResults.Clear();
		listViewResults.VirtualListSize = 0;
		listViewResults.Items.Clear();
		// Reset the progress bar to 0 and update the UI elements to reflect that a comparison is in progress
		kryptonProgressBar.Value = 0;
		toolStripButtonCompare.Enabled = false;
		kryptonButtonSelectFile1.Enabled = false;
		kryptonButtonSelectFile2.Enabled = false;
		toolStripButtonCancel.Enabled = true;
		// Create a new CancellationTokenSource to allow the user to cancel the comparison operation if needed
		_cancellationTokenSource = new CancellationTokenSource();
		// Create a new Progress object to report progress updates from the comparison operation, specifying the UpdateProgress method as the handler for progress updates
		Progress<(int Percent, string Status, List<DifferenceResult>? Batch)> progress = new(handler: UpdateProgress);
		// Use a try-catch-finally block to handle exceptions and ensure that UI elements are reset after the comparison operation completes or is canceled
		try
		{
			// Run the comparison operation asynchronously on a separate thread to avoid blocking the UI, passing in the file paths, whether the first file is newer, the progress reporter, and the cancellation token
			await Task.Run(action: () => CompareFilesAsync(p1: pathFile1, p2: pathFile2, file1IsNewer: file1IsNewer, progress: progress, token: _cancellationTokenSource.Token));
			// After the comparison operation completes successfully, update the progress bar text to indicate that the comparison is complete and show a message box summarizing the results of the comparison, including the counts of added, changed, and deleted records
			kryptonProgressBar.Text = "Comparison Complete";
			KryptonMessageBox.Show(owner: this, text: $"Comparison completed successfully.\n\nAdded records: {addedRecords}\nChanged records: {changedRecords}\nDeleted records: {deletedRecords}", caption: "Summary", buttons: KryptonMessageBoxButtons.OK, icon: KryptonMessageBoxIcon.Information);
		}
		// Catch an OperationCanceledException to handle the case where the user cancels the comparison operation, updating the progress bar text and showing a message box to inform the user that the comparison was cancelled
		catch (OperationCanceledException)
		{
			kryptonProgressBar.Text = "Comparison Cancelled";
			KryptonMessageBox.Show(owner: this, text: "Comparison cancelled by user", caption: "Cancelled", buttons: KryptonMessageBoxButtons.OK, icon: KryptonMessageBoxIcon.Information);
		}
		// Catch any other exceptions that may occur during the comparison operation, logging the error and updating the progress bar text and showing a message box to inform the user of the error
		catch (Exception ex)
		{
			logger.Error(exception: ex, message: "Error during comparison");
			kryptonProgressBar.Text = "Error occurred";
			ShowErrorMessage(message: $"An error occurred: {ex.Message}");
		}
		// In the finally block, reset the UI elements to their default state, re-enable buttons, and dispose of the cancellation token source to clean up resources
		finally
		{
			toolStripButtonCompare.Enabled = true;
			kryptonButtonSelectFile1.Enabled = true;
			kryptonButtonSelectFile2.Enabled = true;
			toolStripButtonCancel.Enabled = false;
			// Dispose of the cancellation token source to free up resources and set it to null to indicate that there is no ongoing comparison operation
			_cancellationTokenSource?.Dispose();
			_cancellationTokenSource = null;
		}
	}

	/// <summary>Handles the click event for the cancel button, allowing the user to cancel the ongoing comparison or close the form if no comparison is in progress.</summary>
	/// <param name="sender">The source of the event, typically the button that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	/// <remarks>This event is triggered when the user clicks the cancel button, allowing the ongoing comparison to be canceled or the form to be closed if no comparison is in progress.</remarks>
	private void ButtonCancel_Click(object sender, EventArgs e)
	{
		// Check if there is an ongoing comparison operation by verifying that the cancellation token source is not null and that cancellation has not already been requested; if so, cancel the operation and disable the cancel button to prevent further clicks
		if (_cancellationTokenSource != null && !_cancellationTokenSource.IsCancellationRequested)
		{
			_cancellationTokenSource.Cancel();
			toolStripButtonCancel.Enabled = false;
		}
		else
		{
			Close();
		}
	}

	/// <summary>Handles the click event for the button that displays a message box containing abbreviations used in the Designation and Difference columns.</summary>
	/// <remarks>The message box presents a predefined list of abbreviations and their meanings to assist users in understanding column values.</remarks>
	/// <param name="sender">The source of the event, typically the button control that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void KryptonButtonNoteAbbreviations_Click(object sender, EventArgs e)
	{
		string message = "Abbreviations used in the Designation and Difference columns:\n\n" +
						 "Epoch - Epoch\n" +
						 "MA - Mean Anomaly\n" +
						 "ArgPeri - Argument of the perihelion\n" +
						 "LAN - Longitude of the Ascending Node\n" +
						 "Inc - Inclination\n" +
						 "Ecc - Eccentricity\n" +
						 "a - Semi-Major Axis\n" +
						 "H - Absolute Magnitude\n" +
						 "G - Slope Parameter\n" +
						 "Desig - Readable Designation\n" +
						 "n - Mean Daily Motion\n" +
						 "Ref - Reference\n" +
						 "Opps - Number of Oppositions\n" +
						 "Obs - Number of Observations\n" +
						 "ObsSpan - Observation Span\n" +
						 "rms - R.M.S. Residual\n" +
						 "Computer - Computer Name\n" +
						 "Flags - 4-Hexdigit Flag\n" +
						 "LastObs - Date of the Last Observation";
		_ = KryptonMessageBox.Show(owner: this, text: message, caption: "Abbreviations", buttons: KryptonMessageBoxButtons.OK, icon: KryptonMessageBoxIcon.Information);
	}

	/// <summary>Handles the click event for the Krypton button and initiates navigation to a specific object.</summary>
	/// <remarks>Use this method to respond to user interactions that require navigating to a particular object
	/// within the form. This method is intended for UI event handling scenarios.</remarks>
	/// <param name="sender">The source of the event, typically the Krypton button that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void KryptonButtonGoto_Click(object sender, EventArgs e) => GoToObject();

	#endregion

	#region DoubleClick event handler

	/// <summary>Handles the DoubleClick event of the results ListView, allowing the user to jump to the selected record in the main form.</summary>
	/// <param name="sender">The source of the event.</param>
	/// <param name="e">The event data associated with the DoubleClick event.</param>
	/// <remarks>This event is triggered when the user double-clicks on an item in the ListView.</remarks>
	private void ListViewResults_DoubleClick(object? sender, EventArgs e) => GoToObject();

	#endregion

	#region RetrieveVirtualItem event handler

	/// <summary>Handles the RetrieveVirtualItem event for the results ListView. Provides virtual items on demand for display in the list view.</summary>
	/// <param name="sender">The source of the event.</param>
	/// <param name="e">The <see cref="RetrieveVirtualItemEventArgs"/> instance containing the event data.</param>
	/// <remarks>This event is triggered when the ListView requires a virtual item to be displayed.</remarks>
	private void ListViewResults_RetrieveVirtualItem(object? sender, RetrieveVirtualItemEventArgs e)
	{
		// Check if the requested item index is within the bounds of the difference results list, and if so, create a new ListViewItem based on the corresponding DifferenceResult and assign it to the event's Item property for display in the ListView
		if (e.ItemIndex >= 0 && e.ItemIndex < differenceResults.Count)
		{
			DifferenceResult result = differenceResults[index: e.ItemIndex];
			e.Item = new ListViewItem(items: [result.Index.ToString(), result.Designation, result.Difference]);
		}
	}

	/// <summary>Creates a <see cref="ListViewItem"/> for the specified index from <see cref="differenceResults"/>.</summary>
	/// <param name="index">The zero-based index of the item to retrieve.</param>
	/// <returns>A <see cref="ListViewItem"/> populated with the data from <see cref="differenceResults"/>, or an empty <see cref="ListViewItem"/> when <paramref name="index"/> is out of range.</returns>
	/// <remarks>Used as the <c>virtualRowProvider</c> delegate when exporting via <see cref="Helpers.ListViewExporter"/>.</remarks>
	private ListViewItem GetVirtualListViewItem(int index)
	{
		// Check if the provided index is within the valid range of the difference results list, and if so, create and return a new ListViewItem based on the corresponding DifferenceResult; otherwise, return an empty ListViewItem
		if (index >= 0 && index < differenceResults.Count)
		{
			DifferenceResult result = differenceResults[index: index];
			return new ListViewItem(items: [result.Index.ToString(), result.Designation, result.Difference]);
		}
		return new ListViewItem();
	}

	#endregion
}