// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using Krypton.Toolkit;

using Planetoid_DB.Resources;

using System.ComponentModel;

namespace Planetoid_DB;

/// <summary>Represents a Windows Form that provides a user interface for calculating ephemerides based on user-specified
/// parameters.</summary>
/// <remarks>EphemerisForm allows users to input the start and end dates, as well as the step size in days, for
/// ephemerides calculations. The form displays calculation progress and results, and is designed to be used as a dialog
/// within the application. Controls are organized to facilitate easy entry of parameters and review of
/// results.</remarks>
partial class EphemerisForm
{
	/// <summary>Required designer variable.</summary>
	/// <remarks>This field stores the components used by the form.</remarks>
	private IContainer components = null;

	/// <summary>Clean up any resources being used.</summary>
	/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
	/// <remarks>This method is called by the runtime to release resources used by the form.</remarks>
	protected override void Dispose(bool disposing)
	{
		if (disposing && (components != null))
		{
			components.Dispose();
		}
		base.Dispose(disposing);
	}

	#region Windows Form Designer generated code

	/// <summary>Required method for Designer support - do not modify
	/// the contents of this method with the code editor.</summary>
	/// <remarks>This method is automatically generated by the Windows Forms designer and should not be modified manually.
	/// It sets up the controls and their properties for the form.</remarks>
	private void InitializeComponent()
	{
		components = new Container();
		ComponentResourceManager resources = new ComponentResourceManager(typeof(EphemerisForm));
		kryptonStatusStrip = new KryptonStatusStrip();
		labelInformation = new ToolStripStatusLabel();
		toolStripContainer = new ToolStripContainer();
		kryptoPanelMain = new KryptonPanel();
		buttonCalculate = new KryptonButton();
		listView = new KryptonListView();
		labelPercent = new KryptonLabel();
		progressBar = new KryptonProgressBar();
		labelEphemeridesStepsInDays = new KryptonLabel();
		numericUpDownStepsInDays = new KryptonNumericUpDown();
		labelEphemeridesEnd = new KryptonLabel();
		dateTimePickerEphemeridesEnd = new KryptonDateTimePicker();
		labelEphemeridesBegin = new KryptonLabel();
		dateTimePickerEphemeridesBegin = new KryptonDateTimePicker();
		backgroundWorker = new BackgroundWorker();
		kryptonManager = new KryptonManager(components);
		kryptonStatusStrip.SuspendLayout();
		toolStripContainer.BottomToolStripPanel.SuspendLayout();
		toolStripContainer.ContentPanel.SuspendLayout();
		toolStripContainer.SuspendLayout();
		((ISupportInitialize)kryptoPanelMain).BeginInit();
		kryptoPanelMain.SuspendLayout();
		SuspendLayout();
		// 
		// kryptonStatusStrip
		// 
		kryptonStatusStrip.AccessibleDescription = "Shows some information";
		kryptonStatusStrip.AccessibleName = "Status bar with some information";
		kryptonStatusStrip.AccessibleRole = AccessibleRole.StatusBar;
		kryptonStatusStrip.AllowClickThrough = true;
		kryptonStatusStrip.AllowItemReorder = true;
		kryptonStatusStrip.Dock = DockStyle.None;
		kryptonStatusStrip.Font = new Font("Segoe UI", 9F);
		kryptonStatusStrip.Items.AddRange(new ToolStripItem[] { labelInformation });
		kryptonStatusStrip.Location = new Point(0, 0);
		kryptonStatusStrip.Name = "kryptonStatusStrip";
		kryptonStatusStrip.ProgressBars = null;
		kryptonStatusStrip.RenderMode = ToolStripRenderMode.ManagerRenderMode;
		kryptonStatusStrip.ShowItemToolTips = true;
		kryptonStatusStrip.Size = new Size(406, 22);
		kryptonStatusStrip.SizingGrip = false;
		kryptonStatusStrip.TabIndex = 0;
		kryptonStatusStrip.TabStop = true;
		kryptonStatusStrip.Text = "Status bar";
		// 
		// labelInformation
		// 
		labelInformation.AccessibleDescription = "Shows some information";
		labelInformation.AccessibleName = "Shows some information";
		labelInformation.AccessibleRole = AccessibleRole.StaticText;
		labelInformation.AutoToolTip = true;
		labelInformation.Image = FatcowIcons16px.fatcow_lightbulb_16px;
		labelInformation.Name = "labelInformation";
		labelInformation.Size = new Size(144, 17);
		labelInformation.Text = "some information here";
		labelInformation.ToolTipText = "Show some information";
		// 
		// toolStripContainer
		// 
		toolStripContainer.AccessibleDescription = "Groups the data";
		toolStripContainer.AccessibleName = "panel";
		toolStripContainer.AccessibleRole = AccessibleRole.Pane;
		// 
		// toolStripContainer.BottomToolStripPanel
		// 
		toolStripContainer.BottomToolStripPanel.Controls.Add(kryptonStatusStrip);
		// 
		// toolStripContainer.ContentPanel
		// 
		toolStripContainer.ContentPanel.Controls.Add(kryptoPanelMain);
		toolStripContainer.ContentPanel.Margin = new Padding(4, 3, 4, 3);
		toolStripContainer.ContentPanel.Size = new Size(406, 431);
		toolStripContainer.Dock = DockStyle.Fill;
		toolStripContainer.Location = new Point(0, 0);
		toolStripContainer.Name = "toolStripContainer";
		toolStripContainer.Size = new Size(406, 453);
		toolStripContainer.TabIndex = 11;
		toolStripContainer.Text = "toolStripContainer";
		toolStripContainer.TopToolStripPanelVisible = false;
		// 
		// kryptoPanelMain
		// 
		kryptoPanelMain.AccessibleDescription = "Groups the data";
		kryptoPanelMain.AccessibleName = "Panel";
		kryptoPanelMain.AccessibleRole = AccessibleRole.Pane;
		kryptoPanelMain.Controls.Add(buttonCalculate);
		kryptoPanelMain.Controls.Add(listView);
		kryptoPanelMain.Controls.Add(labelPercent);
		kryptoPanelMain.Controls.Add(progressBar);
		kryptoPanelMain.Controls.Add(labelEphemeridesStepsInDays);
		kryptoPanelMain.Controls.Add(numericUpDownStepsInDays);
		kryptoPanelMain.Controls.Add(labelEphemeridesEnd);
		kryptoPanelMain.Controls.Add(dateTimePickerEphemeridesEnd);
		kryptoPanelMain.Controls.Add(labelEphemeridesBegin);
		kryptoPanelMain.Controls.Add(dateTimePickerEphemeridesBegin);
		kryptoPanelMain.Dock = DockStyle.Fill;
		kryptoPanelMain.Location = new Point(0, 0);
		kryptoPanelMain.Name = "kryptoPanelMain";
		kryptoPanelMain.Size = new Size(406, 431);
		kryptoPanelMain.TabIndex = 0;
		kryptoPanelMain.TabStop = true;
		// 
		// buttonCalculate
		// 
		buttonCalculate.AccessibleDescription = "Calculates the ephemerides";
		buttonCalculate.AccessibleName = "Calculate the ephemerides";
		buttonCalculate.AccessibleRole = AccessibleRole.PushButton;
		buttonCalculate.Location = new Point(287, 115);
		buttonCalculate.Name = "buttonCalculate";
		buttonCalculate.Size = new Size(105, 29);
		buttonCalculate.TabIndex = 6;
		buttonCalculate.ToolTipValues.EnableToolTips = true;
		buttonCalculate.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		buttonCalculate.Values.DropDownArrowColor = Color.Empty;
		buttonCalculate.Values.Image = FatcowIcons16px.fatcow_calculator_16px;
		buttonCalculate.Values.Text = "&Calculate";
		buttonCalculate.Click += ButtonCalculate_Click;
		buttonCalculate.Enter += Control_Enter;
		buttonCalculate.Leave += Control_Leave;
		buttonCalculate.MouseEnter += Control_Enter;
		buttonCalculate.MouseLeave += Control_Leave;
		// 
		// listView
		// 
		listView.AccessibleDescription = "Shows the search results";
		listView.AccessibleName = "Search results";
		listView.AccessibleRole = AccessibleRole.List;
		listView.HideSelection = false;
		listView.Location = new Point(14, 203);
		listView.MultiSelect = false;
		listView.Name = "listView";
		listView.ShowItemToolTips = true;
		listView.Size = new Size(378, 209);
		listView.TabIndex = 9;
		listView.ToolTipValues.EnableToolTips = true;
		listView.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		listView.Enter += Control_Enter;
		listView.Leave += Control_Leave;
		listView.MouseEnter += Control_Enter;
		listView.MouseLeave += Control_Leave;
		// 
		// labelPercent
		// 
		labelPercent.AccessibleDescription = "Shows the percent status of the search";
		labelPercent.AccessibleName = "Percent status of the search";
		labelPercent.AccessibleRole = AccessibleRole.StaticText;
		labelPercent.Location = new Point(341, 162);
		labelPercent.Name = "labelPercent";
		labelPercent.Size = new Size(44, 20);
		labelPercent.TabIndex = 8;
		labelPercent.ToolTipValues.EnableToolTips = true;
		labelPercent.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelPercent.Values.Text = "100 %";
		labelPercent.Enter += Control_Enter;
		labelPercent.Leave += Control_Leave;
		labelPercent.MouseEnter += Control_Enter;
		labelPercent.MouseLeave += Control_Leave;
		// 
		// progressBar
		// 
		progressBar.AccessibleDescription = "Shows the progress status of the search";
		progressBar.AccessibleName = "Progress bar";
		progressBar.AccessibleRole = AccessibleRole.ProgressBar;
		progressBar.Location = new Point(14, 165);
		progressBar.Name = "progressBar";
		progressBar.Size = new Size(320, 20);
		progressBar.TabIndex = 7;
		progressBar.TextBackdropColor = Color.Empty;
		progressBar.TextShadowColor = Color.Empty;
		progressBar.Values.Text = "";
		progressBar.MouseEnter += Control_Enter;
		progressBar.MouseLeave += Control_Leave;
		// 
		// labelEphemeridesStepsInDays
		// 
		labelEphemeridesStepsInDays.AccessibleRole = AccessibleRole.StaticText;
		labelEphemeridesStepsInDays.Location = new Point(14, 78);
		labelEphemeridesStepsInDays.Name = "labelEphemeridesStepsInDays";
		labelEphemeridesStepsInDays.Size = new Size(82, 20);
		labelEphemeridesStepsInDays.TabIndex = 4;
		labelEphemeridesStepsInDays.ToolTipValues.EnableToolTips = true;
		labelEphemeridesStepsInDays.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelEphemeridesStepsInDays.Values.Text = "&Steps in days";
		labelEphemeridesStepsInDays.Enter += Control_Enter;
		labelEphemeridesStepsInDays.Leave += Control_Leave;
		labelEphemeridesStepsInDays.MouseEnter += Control_Enter;
		labelEphemeridesStepsInDays.MouseLeave += Control_Leave;
		// 
		// numericUpDownStepsInDays
		// 
		numericUpDownStepsInDays.AccessibleDescription = "Choose the steps in days";
		numericUpDownStepsInDays.AccessibleName = "Steps in days";
		numericUpDownStepsInDays.AccessibleRole = AccessibleRole.SpinButton;
		numericUpDownStepsInDays.Increment = new decimal(new int[] { 1, 0, 0, 0 });
		numericUpDownStepsInDays.Location = new Point(159, 76);
		numericUpDownStepsInDays.Maximum = new decimal(new int[] { 100, 0, 0, 0 });
		numericUpDownStepsInDays.Minimum = new decimal(new int[] { 0, 0, 0, 0 });
		numericUpDownStepsInDays.Name = "numericUpDownStepsInDays";
		numericUpDownStepsInDays.Size = new Size(92, 22);
		numericUpDownStepsInDays.TabIndex = 5;
		numericUpDownStepsInDays.ToolTipValues.EnableToolTips = true;
		numericUpDownStepsInDays.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		numericUpDownStepsInDays.Value = new decimal(new int[] { 0, 0, 0, 0 });
		numericUpDownStepsInDays.Enter += Control_Enter;
		numericUpDownStepsInDays.Leave += Control_Leave;
		numericUpDownStepsInDays.MouseEnter += Control_Enter;
		numericUpDownStepsInDays.MouseLeave += Control_Leave;
		// 
		// labelEphemeridesEnd
		// 
		labelEphemeridesEnd.AccessibleDescription = "Sets the end of the ephemerides";
		labelEphemeridesEnd.AccessibleName = "Ephemerides end";
		labelEphemeridesEnd.AccessibleRole = AccessibleRole.StaticText;
		labelEphemeridesEnd.Location = new Point(14, 45);
		labelEphemeridesEnd.Name = "labelEphemeridesEnd";
		labelEphemeridesEnd.Size = new Size(108, 20);
		labelEphemeridesEnd.TabIndex = 2;
		labelEphemeridesEnd.ToolTipValues.EnableToolTips = true;
		labelEphemeridesEnd.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelEphemeridesEnd.Values.Text = "Ephemerides &end:";
		labelEphemeridesEnd.Enter += Control_Enter;
		labelEphemeridesEnd.Leave += Control_Leave;
		labelEphemeridesEnd.MouseEnter += Control_Enter;
		labelEphemeridesEnd.MouseLeave += Control_Leave;
		// 
		// dateTimePickerEphemeridesEnd
		// 
		dateTimePickerEphemeridesEnd.AccessibleRole = AccessibleRole.DropList;
		dateTimePickerEphemeridesEnd.Location = new Point(159, 44);
		dateTimePickerEphemeridesEnd.Name = "dateTimePickerEphemeridesEnd";
		dateTimePickerEphemeridesEnd.Size = new Size(173, 21);
		dateTimePickerEphemeridesEnd.TabIndex = 3;
		dateTimePickerEphemeridesEnd.ToolTipValues.EnableToolTips = true;
		dateTimePickerEphemeridesEnd.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		dateTimePickerEphemeridesEnd.Enter += Control_Enter;
		dateTimePickerEphemeridesEnd.Leave += Control_Leave;
		dateTimePickerEphemeridesEnd.MouseEnter += Control_Enter;
		dateTimePickerEphemeridesEnd.MouseLeave += Control_Leave;
		// 
		// labelEphemeridesBegin
		// 
		labelEphemeridesBegin.AccessibleDescription = "Sets the begin of the ephemerides";
		labelEphemeridesBegin.AccessibleName = "Ephemerides begin";
		labelEphemeridesBegin.AccessibleRole = AccessibleRole.StaticText;
		labelEphemeridesBegin.Location = new Point(14, 14);
		labelEphemeridesBegin.Name = "labelEphemeridesBegin";
		labelEphemeridesBegin.Size = new Size(118, 20);
		labelEphemeridesBegin.TabIndex = 0;
		labelEphemeridesBegin.ToolTipValues.EnableToolTips = true;
		labelEphemeridesBegin.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelEphemeridesBegin.Values.Text = "Ephemerides &begin:";
		labelEphemeridesBegin.Enter += Control_Enter;
		labelEphemeridesBegin.Leave += Control_Leave;
		labelEphemeridesBegin.MouseEnter += Control_Enter;
		labelEphemeridesBegin.MouseLeave += Control_Leave;
		// 
		// dateTimePickerEphemeridesBegin
		// 
		dateTimePickerEphemeridesBegin.AccessibleRole = AccessibleRole.DropList;
		dateTimePickerEphemeridesBegin.Location = new Point(159, 13);
		dateTimePickerEphemeridesBegin.Name = "dateTimePickerEphemeridesBegin";
		dateTimePickerEphemeridesBegin.Size = new Size(173, 21);
		dateTimePickerEphemeridesBegin.TabIndex = 1;
		dateTimePickerEphemeridesBegin.ToolTipValues.EnableToolTips = true;
		dateTimePickerEphemeridesBegin.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		dateTimePickerEphemeridesBegin.Enter += Control_Enter;
		dateTimePickerEphemeridesBegin.Leave += Control_Leave;
		dateTimePickerEphemeridesBegin.MouseEnter += Control_Enter;
		dateTimePickerEphemeridesBegin.MouseLeave += Control_Leave;
		// 
		// backgroundWorker
		// 
		backgroundWorker.WorkerReportsProgress = true;
		backgroundWorker.WorkerSupportsCancellation = true;
		backgroundWorker.DoWork += BackgroundWorker_DoWork;
		backgroundWorker.ProgressChanged += BackgroundWorker_ProgressChanged;
		backgroundWorker.RunWorkerCompleted += BackgroundWorker_RunWorkerCompleted;
		// 
		// kryptonManager
		// 
		kryptonManager.GlobalPaletteMode = PaletteMode.Global;
		kryptonManager.ToolkitStrings.MessageBoxStrings.LessDetails = "L&ess Details...";
		kryptonManager.ToolkitStrings.MessageBoxStrings.MoreDetails = "&More Details...";
		// 
		// EphemerisForm
		// 
		AccessibleDescription = "Calculates the ephemerides";
		AccessibleName = "Ephemerides";
		AccessibleRole = AccessibleRole.Dialog;
		AutoScaleDimensions = new SizeF(7F, 15F);
		AutoScaleMode = AutoScaleMode.Font;
		ClientSize = new Size(406, 453);
		ControlBox = false;
		Controls.Add(toolStripContainer);
		FormBorderStyle = FormBorderStyle.FixedToolWindow;
		Icon = (Icon)resources.GetObject("$this.Icon");
		Margin = new Padding(4, 3, 4, 3);
		MaximizeBox = false;
		MinimizeBox = false;
		Name = "EphemerisForm";
		StartPosition = FormStartPosition.CenterParent;
		Text = "Ephemerides";
		Load += EphemerisForm_Load;
		kryptonStatusStrip.ResumeLayout(false);
		kryptonStatusStrip.PerformLayout();
		toolStripContainer.BottomToolStripPanel.ResumeLayout(false);
		toolStripContainer.BottomToolStripPanel.PerformLayout();
		toolStripContainer.ContentPanel.ResumeLayout(false);
		toolStripContainer.ResumeLayout(false);
		toolStripContainer.PerformLayout();
		((ISupportInitialize)kryptoPanelMain).EndInit();
		kryptoPanelMain.ResumeLayout(false);
		kryptoPanelMain.PerformLayout();
		ResumeLayout(false);

	}

	#endregion

	private KryptonStatusStrip kryptonStatusStrip;
	private ToolStripStatusLabel labelInformation;
	private ToolStripContainer toolStripContainer;
	private KryptonPanel kryptoPanelMain;
	private KryptonDateTimePicker dateTimePickerEphemeridesBegin;
	private BackgroundWorker backgroundWorker;
	private KryptonLabel labelEphemeridesEnd;
	private KryptonDateTimePicker dateTimePickerEphemeridesEnd;
	private KryptonLabel labelEphemeridesBegin;
	private KryptonNumericUpDown numericUpDownStepsInDays;
	private KryptonLabel labelEphemeridesStepsInDays;
	private KryptonLabel labelPercent;
	private KryptonProgressBar progressBar;
	private KryptonButton buttonCalculate;
	private KryptonListView listView;
	private KryptonManager kryptonManager;
}