// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using Krypton.Toolkit;

using Planetoid_DB.Resources;

using System.ComponentModel;

namespace Planetoid_DB;

/// <summary>Represents a dialog form that displays license information and provides options to copy or save the license text.</summary>
/// <remarks>Use this form to view the license associated with the application. The form allows users to copy the
/// license text to the clipboard or save it to a file for reference. It is intended to present license details in a
/// clear and accessible manner.</remarks>
partial class LicenseForm
{
	/// <summary>Required designer variable.</summary>
	/// <remarks>This field stores the components used by the form.</remarks>
	private IContainer components = null;

	/// <summary>Clean up any resources being used.</summary>
	/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
	/// <remarks>This method is called by the runtime to release resources used by the form.</remarks>
	protected override void Dispose(bool disposing)
	{
		if (disposing && (components != null))
		{
			components.Dispose();
		}
		base.Dispose(disposing);
	}

	#region Windows Form Designer generated code

	/// <summary>Required method for Designer support - do not modify
	/// the contents of this method with the code editor.</summary>
	/// <remarks>This method is automatically generated by the Windows Forms designer and should not be modified manually.
	/// It sets up the controls and their properties for the form.</remarks>
	private void InitializeComponent()
	{
		components = new Container();
		ComponentResourceManager resources = new ComponentResourceManager(typeof(LicenseForm));
		kryptoPanelMain = new KryptonPanel();
		kryptonButtonCopyLicenseToClipboard = new KryptonButton();
		kryptonButtonSaveLicense = new KryptonButton();
		kryptonButtonClose = new KryptonButton();
		kryptonPictureBoxLicenseLogo = new KryptonPictureBox();
		kryptonTextBoxLicense = new KryptonTextBox();
		kryptonStatusStrip = new KryptonStatusStrip();
		labelInformation = new ToolStripStatusLabel();
		saveFileDialog = new SaveFileDialog();
		kryptonManager = new KryptonManager(components);
		((ISupportInitialize)kryptoPanelMain).BeginInit();
		kryptoPanelMain.SuspendLayout();
		((ISupportInitialize)kryptonPictureBoxLicenseLogo).BeginInit();
		kryptonStatusStrip.SuspendLayout();
		SuspendLayout();
		// 
		// kryptoPanelMain
		// 
		kryptoPanelMain.AccessibleDescription = "Groups the data";
		kryptoPanelMain.AccessibleName = "Panel";
		kryptoPanelMain.AccessibleRole = AccessibleRole.Pane;
		kryptoPanelMain.Controls.Add(kryptonButtonCopyLicenseToClipboard);
		kryptoPanelMain.Controls.Add(kryptonButtonSaveLicense);
		kryptoPanelMain.Controls.Add(kryptonButtonClose);
		kryptoPanelMain.Controls.Add(kryptonPictureBoxLicenseLogo);
		kryptoPanelMain.Controls.Add(kryptonTextBoxLicense);
		kryptoPanelMain.Controls.Add(kryptonStatusStrip);
		kryptoPanelMain.Dock = DockStyle.Fill;
		kryptoPanelMain.Location = new Point(0, 0);
		kryptoPanelMain.Name = "kryptoPanelMain";
		kryptoPanelMain.PanelBackStyle = PaletteBackStyle.FormMain;
		kryptoPanelMain.Size = new Size(577, 225);
		kryptoPanelMain.TabIndex = 0;
		kryptoPanelMain.TabStop = true;
		// 
		// kryptonButtonCopyLicenseToClipboard
		// 
		kryptonButtonCopyLicenseToClipboard.AccessibleDescription = "Copies the license to the clipboard";
		kryptonButtonCopyLicenseToClipboard.AccessibleName = "Copy the license to the clipboard";
		kryptonButtonCopyLicenseToClipboard.AccessibleRole = AccessibleRole.PushButton;
		kryptonButtonCopyLicenseToClipboard.Location = new Point(438, 105);
		kryptonButtonCopyLicenseToClipboard.Name = "kryptonButtonCopyLicenseToClipboard";
		kryptonButtonCopyLicenseToClipboard.Size = new Size(127, 25);
		kryptonButtonCopyLicenseToClipboard.TabIndex = 1;
		kryptonButtonCopyLicenseToClipboard.ToolTipValues.Description = "Copies the license to the clipboard.";
		kryptonButtonCopyLicenseToClipboard.ToolTipValues.EnableToolTips = true;
		kryptonButtonCopyLicenseToClipboard.ToolTipValues.Heading = "Copy the license to the clipboard";
		kryptonButtonCopyLicenseToClipboard.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonButtonCopyLicenseToClipboard.Values.DropDownArrowColor = Color.Empty;
		kryptonButtonCopyLicenseToClipboard.Values.Image = FatcowIcons16px.fatcow_clipboard_empty_16px;
		kryptonButtonCopyLicenseToClipboard.Values.Text = "&Copy to clipboard";
		kryptonButtonCopyLicenseToClipboard.Click += KryptonButtonCopyLicenseToClipboard_Click;
		kryptonButtonCopyLicenseToClipboard.Enter += Control_Enter;
		kryptonButtonCopyLicenseToClipboard.Leave += Control_Leave;
		kryptonButtonCopyLicenseToClipboard.MouseEnter += Control_Enter;
		kryptonButtonCopyLicenseToClipboard.MouseLeave += Control_Leave;
		// 
		// kryptonButtonSaveLicense
		// 
		kryptonButtonSaveLicense.AccessibleDescription = "Saves the license to the hard drive";
		kryptonButtonSaveLicense.AccessibleName = "Save the license";
		kryptonButtonSaveLicense.AccessibleRole = AccessibleRole.PushButton;
		kryptonButtonSaveLicense.Location = new Point(439, 136);
		kryptonButtonSaveLicense.Name = "kryptonButtonSaveLicense";
		kryptonButtonSaveLicense.Size = new Size(127, 25);
		kryptonButtonSaveLicense.TabIndex = 2;
		kryptonButtonSaveLicense.ToolTipValues.Description = "Saves the license to the hard drive.";
		kryptonButtonSaveLicense.ToolTipValues.EnableToolTips = true;
		kryptonButtonSaveLicense.ToolTipValues.Heading = "Save the license";
		kryptonButtonSaveLicense.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonButtonSaveLicense.Values.DropDownArrowColor = Color.Empty;
		kryptonButtonSaveLicense.Values.Image = FatcowIcons16px.fatcow_diskette_16px;
		kryptonButtonSaveLicense.Values.Text = "&Save license";
		kryptonButtonSaveLicense.Click += KryptonButtonSaveLicense_ClickAsync;
		kryptonButtonSaveLicense.Enter += Control_Enter;
		kryptonButtonSaveLicense.Leave += Control_Leave;
		kryptonButtonSaveLicense.MouseEnter += Control_Enter;
		kryptonButtonSaveLicense.MouseLeave += Control_Leave;
		// 
		// kryptonButtonClose
		// 
		kryptonButtonClose.AccessibleDescription = "Closes the form";
		kryptonButtonClose.AccessibleName = "Close the form";
		kryptonButtonClose.AccessibleRole = AccessibleRole.PushButton;
		kryptonButtonClose.DialogResult = DialogResult.Cancel;
		kryptonButtonClose.Location = new Point(439, 167);
		kryptonButtonClose.Name = "kryptonButtonClose";
		kryptonButtonClose.Size = new Size(127, 25);
		kryptonButtonClose.TabIndex = 3;
		kryptonButtonClose.ToolTipValues.Description = "Closes the form.";
		kryptonButtonClose.ToolTipValues.EnableToolTips = true;
		kryptonButtonClose.ToolTipValues.Heading = "Close";
		kryptonButtonClose.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonButtonClose.Values.DropDownArrowColor = Color.Empty;
		kryptonButtonClose.Values.Image = FatcowIcons16px.fatcow_cancel_16px;
		kryptonButtonClose.Values.Text = "C&lose";
		kryptonButtonClose.Enter += Control_Enter;
		kryptonButtonClose.Leave += Control_Leave;
		kryptonButtonClose.MouseEnter += Control_Enter;
		kryptonButtonClose.MouseLeave += Control_Leave;
		// 
		// kryptonPictureBoxLicenseLogo
		// 
		kryptonPictureBoxLicenseLogo.AccessibleDescription = "Shows the logo of the license";
		kryptonPictureBoxLicenseLogo.AccessibleName = "GPL Logo";
		kryptonPictureBoxLicenseLogo.AccessibleRole = AccessibleRole.Graphic;
		kryptonPictureBoxLicenseLogo.Image = (Image)resources.GetObject("kryptonPictureBoxLicenseLogo.Image");
		kryptonPictureBoxLicenseLogo.Location = new Point(439, 12);
		kryptonPictureBoxLicenseLogo.Name = "kryptonPictureBoxLicenseLogo";
		kryptonPictureBoxLicenseLogo.Size = new Size(127, 71);
		kryptonPictureBoxLicenseLogo.SizeMode = PictureBoxSizeMode.Zoom;
		kryptonPictureBoxLicenseLogo.TabIndex = 8;
		kryptonPictureBoxLicenseLogo.TabStop = false;
		kryptonPictureBoxLicenseLogo.ToolTipValues.Description = "Shows the logo of the license.";
		kryptonPictureBoxLicenseLogo.ToolTipValues.EnableToolTips = true;
		kryptonPictureBoxLicenseLogo.ToolTipValues.Heading = "GPL v3 Logo";
		kryptonPictureBoxLicenseLogo.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonPictureBoxLicenseLogo.MouseEnter += Control_Enter;
		kryptonPictureBoxLicenseLogo.MouseLeave += Control_Leave;
		// 
		// kryptonTextBoxLicense
		// 
		kryptonTextBoxLicense.AccessibleDescription = "Shows the license";
		kryptonTextBoxLicense.AccessibleName = "License";
		kryptonTextBoxLicense.AccessibleRole = AccessibleRole.Text;
		kryptonTextBoxLicense.InputControlStyle = InputControlStyle.PanelAlternate;
		kryptonTextBoxLicense.Location = new Point(12, 12);
		kryptonTextBoxLicense.Multiline = true;
		kryptonTextBoxLicense.Name = "kryptonTextBoxLicense";
		kryptonTextBoxLicense.ReadOnly = true;
		kryptonTextBoxLicense.ScrollBars = ScrollBars.Both;
		kryptonTextBoxLicense.Size = new Size(421, 180);
		kryptonTextBoxLicense.TabIndex = 0;
		kryptonTextBoxLicense.TabStop = false;
		kryptonTextBoxLicense.Text = resources.GetString("kryptonTextBoxLicense.Text");
		kryptonTextBoxLicense.ToolTipValues.Description = "Shows the license.";
		kryptonTextBoxLicense.ToolTipValues.EnableToolTips = true;
		kryptonTextBoxLicense.ToolTipValues.Heading = "License";
		kryptonTextBoxLicense.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		kryptonTextBoxLicense.Enter += Control_Enter;
		kryptonTextBoxLicense.Leave += Control_Leave;
		kryptonTextBoxLicense.MouseEnter += Control_Enter;
		kryptonTextBoxLicense.MouseLeave += Control_Leave;
		// 
		// kryptonStatusStrip
		// 
		kryptonStatusStrip.AccessibleDescription = "Shows some information";
		kryptonStatusStrip.AccessibleName = "Status bar with some information";
		kryptonStatusStrip.AccessibleRole = AccessibleRole.StatusBar;
		kryptonStatusStrip.AllowClickThrough = true;
		kryptonStatusStrip.AllowItemReorder = true;
		kryptonStatusStrip.Font = new Font("Segoe UI", 9F);
		kryptonStatusStrip.Items.AddRange(new ToolStripItem[] { labelInformation });
		kryptonStatusStrip.Location = new Point(0, 203);
		kryptonStatusStrip.Name = "kryptonStatusStrip";
		kryptonStatusStrip.ProgressBars = null;
		kryptonStatusStrip.RenderMode = ToolStripRenderMode.ManagerRenderMode;
		kryptonStatusStrip.ShowItemToolTips = true;
		kryptonStatusStrip.Size = new Size(577, 22);
		kryptonStatusStrip.SizingGrip = false;
		kryptonStatusStrip.TabIndex = 4;
		kryptonStatusStrip.TabStop = true;
		kryptonStatusStrip.Text = "Status bar";
		// 
		// labelInformation
		// 
		labelInformation.AccessibleDescription = "Shows some information";
		labelInformation.AccessibleName = "Shows some information";
		labelInformation.AccessibleRole = AccessibleRole.StaticText;
		labelInformation.AutoToolTip = true;
		labelInformation.Image = FatcowIcons16px.fatcow_lightbulb_16px;
		labelInformation.Name = "labelInformation";
		labelInformation.Size = new Size(144, 17);
		labelInformation.Text = "some information here";
		labelInformation.ToolTipText = "Shows some information";
		// 
		// saveFileDialog
		// 
		saveFileDialog.Filter = "all files|*.*";
		// 
		// kryptonManager
		// 
		kryptonManager.GlobalPaletteMode = PaletteMode.Global;
		kryptonManager.ToolkitStrings.MessageBoxStrings.LessDetails = "L&ess Details...";
		kryptonManager.ToolkitStrings.MessageBoxStrings.MoreDetails = "&More Details...";
		// 
		// LicenseForm
		// 
		AccessibleDescription = "Shows the license information";
		AccessibleName = "License information";
		AccessibleRole = AccessibleRole.Dialog;
		AutoScaleDimensions = new SizeF(7F, 15F);
		AutoScaleMode = AutoScaleMode.Font;
		ClientSize = new Size(577, 225);
		ControlBox = false;
		Controls.Add(kryptoPanelMain);
		FormBorderStyle = FormBorderStyle.FixedToolWindow;
		Icon = (Icon)resources.GetObject("$this.Icon");
		MaximizeBox = false;
		MinimizeBox = false;
		Name = "LicenseForm";
		ShowInTaskbar = false;
		StartPosition = FormStartPosition.CenterParent;
		Text = "License: GPL-3.0";
		Load += LicenseForm_Load;
		((ISupportInitialize)kryptoPanelMain).EndInit();
		kryptoPanelMain.ResumeLayout(false);
		kryptoPanelMain.PerformLayout();
		((ISupportInitialize)kryptonPictureBoxLicenseLogo).EndInit();
		kryptonStatusStrip.ResumeLayout(false);
		kryptonStatusStrip.PerformLayout();
		ResumeLayout(false);
	}

	#endregion

	private KryptonPanel kryptoPanelMain;
	private KryptonStatusStrip kryptonStatusStrip;
	private ToolStripStatusLabel labelInformation;
	private KryptonTextBox kryptonTextBoxLicense;
	private KryptonPictureBox kryptonPictureBoxLicenseLogo;
	private KryptonButton kryptonButtonClose;
	private KryptonButton kryptonButtonSaveLicense;
	private SaveFileDialog saveFileDialog;
	private KryptonButton kryptonButtonCopyLicenseToClipboard;
	private KryptonManager kryptonManager;
}