// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using Krypton.Toolkit;

using Planetoid_DB.Resources;

using System.ComponentModel;

namespace Planetoid_DB;

/// <summary>Represents a dialog form that lists readable designations, allowing users to specify minimum and maximum values,
/// view the list, and save it in various file formats.</summary>
/// <remarks>The form provides controls for filtering the list by minimum and maximum values, displaying the
/// results in a list view, and saving the list in formats such as text, CSV, JSON, and more. It includes a status bar
/// for displaying information and supports accessibility features. The form is intended to be used as a modal dialog
/// within a parent application.</remarks>
partial class ListReadableDesignationsForm
{
	/// <summary>Required designer variable.</summary>
	/// <remarks>This field stores the components used by the form.</remarks>
	private IContainer components = null;

	/// <summary>Clean up any resources being used.</summary>
	/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
	/// <remarks>This method is called by the runtime to release resources used by the form.</remarks>
	protected override void Dispose(bool disposing)
	{
		if (disposing && (components != null))
		{
			components.Dispose();
		}
		base.Dispose(disposing);
	}

	#region Windows Form Designer generated code

	/// <summary>Required method for Designer support - do not modify
	/// the contents of this method with the code editor.</summary>
	/// <remarks>This method is automatically generated by the Windows Forms designer and should not be modified manually.
	/// It sets up the controls and their properties for the form.</remarks>
	private void InitializeComponent()
	{
		components = new Container();
		ComponentResourceManager resources = new ComponentResourceManager(typeof(ListReadableDesignationsForm));
		kryptonStatusStrip = new Krypton.Toolkit.KryptonStatusStrip();
		labelInformation = new ToolStripStatusLabel();
		contextMenuCopyToClipboard = new ContextMenuStrip(components);
		toolStripMenuItemCopyToClipboard = new ToolStripMenuItem();
		contextMenuSaveList = new ContextMenuStrip(components);
		toolStripMenuItemSaveAsText = new ToolStripMenuItem();
		toolStripMenuItemSaveAsLatex = new ToolStripMenuItem();
		toolStripMenuItemSaveAsMarkdown = new ToolStripMenuItem();
		toolStripMenuItemSaveAsWord = new ToolStripMenuItem();
		toolStripMenuItemSaveAsOdt = new ToolStripMenuItem();
		toolStripMenuItemSaveAsRtf = new ToolStripMenuItem();
		toolStripMenuItemSaveAsExcel = new ToolStripMenuItem();
		toolStripMenuItemSaveAsOds = new ToolStripMenuItem();
		toolStripMenuItemSaveAsCsv = new ToolStripMenuItem();
		toolStripMenuItemSaveAsTsv = new ToolStripMenuItem();
		toolStripMenuItemSaveAsPsv = new ToolStripMenuItem();
		toolStripMenuItemSaveAsHtml = new ToolStripMenuItem();
		toolStripMenuItemSaveAsXml = new ToolStripMenuItem();
		toolStripMenuItemSaveAsJson = new ToolStripMenuItem();
		toolStripMenuItemSaveAsYaml = new ToolStripMenuItem();
		toolStripMenuItemSaveAsSql = new ToolStripMenuItem();
		toolStripMenuItemSaveAsPdf = new ToolStripMenuItem();
		toolStripMenuItemSaveAsPostScript = new ToolStripMenuItem();
		toolStripMenuItemSaveAsEpub = new ToolStripMenuItem();
		toolStripMenuItemSaveAsMobi = new ToolStripMenuItem();
		toolStripDropDownButtonSaveList = new ToolStripDropDownButton();
		kryptoPanelMain = new KryptonPanel();
		listView = new ListView();
		columnHeaderIndex = new ColumnHeader();
		columnHeaderReadableDesignation = new ColumnHeader();
		kryptonManager = new KryptonManager(components);
		toolStripContainer = new ToolStripContainer();
		kryptonToolStripList = new Krypton.Toolkit.KryptonToolStrip();
		toolStripButtonCreateList = new ToolStripButton();
		toolStripSeparator1 = new ToolStripSeparator();
		toolStripLabelMinimum = new ToolStripLabel();
		toolStripNumericUpDownMinimum = new Planetoid_DB.Helpers.ToolStripNumericUpDown();
		toolStripLabelMaximum = new ToolStripLabel();
		toolStripNumericUpDownMaximum = new Planetoid_DB.Helpers.ToolStripNumericUpDown();
		kryptonToolStripSaveList = new Krypton.Toolkit.KryptonToolStrip();
		toolStripButtonLoad = new ToolStripButton();
		toolStripSeparator2 = new ToolStripSeparator();
		kryptonStatusStrip.SuspendLayout();
		contextMenuCopyToClipboard.SuspendLayout();
		contextMenuSaveList.SuspendLayout();
		((ISupportInitialize)kryptoPanelMain).BeginInit();
		kryptoPanelMain.SuspendLayout();
		toolStripContainer.BottomToolStripPanel.SuspendLayout();
		toolStripContainer.ContentPanel.SuspendLayout();
		toolStripContainer.TopToolStripPanel.SuspendLayout();
		toolStripContainer.SuspendLayout();
		kryptonToolStripList.SuspendLayout();
		kryptonToolStripSaveList.SuspendLayout();
		SuspendLayout();
		// 
		// kryptonStatusStrip
		// 
		kryptonStatusStrip.AccessibleDescription = "Shows some information";
		kryptonStatusStrip.AccessibleName = "Status bar with some information";
		kryptonStatusStrip.AccessibleRole = AccessibleRole.StatusBar;
		kryptonStatusStrip.AllowClickThrough = true;
		kryptonStatusStrip.AllowItemReorder = true;
		kryptonStatusStrip.Dock = DockStyle.None;
		kryptonStatusStrip.Font = new Font("Segoe UI", 9F);
		kryptonStatusStrip.Items.AddRange(new ToolStripItem[] { labelInformation });
		kryptonStatusStrip.Location = new Point(0, 0);
		kryptonStatusStrip.Name = "kryptonStatusStrip";
		kryptonStatusStrip.ProgressBars = null;
		kryptonStatusStrip.RenderMode = ToolStripRenderMode.ManagerRenderMode;
		kryptonStatusStrip.ShowItemToolTips = true;
		kryptonStatusStrip.Size = new Size(341, 22);
		kryptonStatusStrip.TabIndex = 1;
		kryptonStatusStrip.TabStop = true;
		kryptonStatusStrip.Text = "Status bar";
		kryptonStatusStrip.MouseEnter += Control_Enter;
		kryptonStatusStrip.MouseLeave += Control_Leave;
		// 
		// labelInformation
		// 
		labelInformation.AccessibleDescription = "Shows some information";
		labelInformation.AccessibleName = "Some information";
		labelInformation.AccessibleRole = AccessibleRole.StaticText;
		labelInformation.AutoToolTip = true;
		labelInformation.Image = FatcowIcons16px.fatcow_lightbulb_16px;
		labelInformation.Name = "labelInformation";
		labelInformation.Size = new Size(144, 17);
		labelInformation.Text = "some information here";
		labelInformation.ToolTipText = "Shows some information";
		labelInformation.MouseEnter += Control_Enter;
		labelInformation.MouseLeave += Control_Leave;
		// 
		// contextMenuCopyToClipboard
		// 
		contextMenuCopyToClipboard.AccessibleDescription = "Shows the context menu for copying database information to the clipboard";
		contextMenuCopyToClipboard.AccessibleName = "Context menu for copying database information to the clipboard";
		contextMenuCopyToClipboard.AccessibleRole = AccessibleRole.MenuPopup;
		contextMenuCopyToClipboard.AllowClickThrough = true;
		contextMenuCopyToClipboard.Font = new Font("Segoe UI", 9F);
		contextMenuCopyToClipboard.Items.AddRange(new ToolStripItem[] { toolStripMenuItemCopyToClipboard });
		contextMenuCopyToClipboard.Name = "contextMenuStrip";
		contextMenuCopyToClipboard.Size = new Size(214, 26);
		contextMenuCopyToClipboard.TabStop = true;
		contextMenuCopyToClipboard.Text = "Copy to clipboard";
		contextMenuCopyToClipboard.MouseEnter += Control_Enter;
		contextMenuCopyToClipboard.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemCopyToClipboard
		// 
		toolStripMenuItemCopyToClipboard.AccessibleDescription = "Copies the text/value to the clipboard";
		toolStripMenuItemCopyToClipboard.AccessibleName = "Copy to clipboard";
		toolStripMenuItemCopyToClipboard.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemCopyToClipboard.AutoToolTip = true;
		toolStripMenuItemCopyToClipboard.Image = FatcowIcons16px.fatcow_page_copy_16px;
		toolStripMenuItemCopyToClipboard.Name = "toolStripMenuItemCopyToClipboard";
		toolStripMenuItemCopyToClipboard.ShortcutKeyDisplayString = "Strg+C";
		toolStripMenuItemCopyToClipboard.ShortcutKeys = Keys.Control | Keys.C;
		toolStripMenuItemCopyToClipboard.Size = new Size(213, 22);
		toolStripMenuItemCopyToClipboard.Text = "&Copy to clipboard";
		toolStripMenuItemCopyToClipboard.Click += CopyToClipboard_DoubleClick;
		toolStripMenuItemCopyToClipboard.MouseEnter += Control_Enter;
		toolStripMenuItemCopyToClipboard.MouseLeave += Control_Leave;
		// 
		// contextMenuSaveList
		// 
		contextMenuSaveList.AccessibleDescription = "Save the list as file";
		contextMenuSaveList.AccessibleName = "Save list";
		contextMenuSaveList.AccessibleRole = AccessibleRole.MenuPopup;
		contextMenuSaveList.AllowClickThrough = true;
		contextMenuSaveList.Font = new Font("Segoe UI", 9F);
		contextMenuSaveList.Items.AddRange(new ToolStripItem[] { toolStripMenuItemSaveAsText, toolStripMenuItemSaveAsLatex, toolStripMenuItemSaveAsMarkdown, toolStripMenuItemSaveAsWord, toolStripMenuItemSaveAsOdt, toolStripMenuItemSaveAsRtf, toolStripMenuItemSaveAsExcel, toolStripMenuItemSaveAsOds, toolStripMenuItemSaveAsCsv, toolStripMenuItemSaveAsTsv, toolStripMenuItemSaveAsPsv, toolStripMenuItemSaveAsHtml, toolStripMenuItemSaveAsXml, toolStripMenuItemSaveAsJson, toolStripMenuItemSaveAsYaml, toolStripMenuItemSaveAsSql, toolStripMenuItemSaveAsPdf, toolStripMenuItemSaveAsPostScript, toolStripMenuItemSaveAsEpub, toolStripMenuItemSaveAsMobi });
		contextMenuSaveList.Name = "contextMenuStrip1";
		contextMenuSaveList.OwnerItem = toolStripDropDownButtonSaveList;
		contextMenuSaveList.Size = new Size(216, 444);
		contextMenuSaveList.TabStop = true;
		contextMenuSaveList.Text = "&Save list";
		contextMenuSaveList.MouseEnter += Control_Enter;
		contextMenuSaveList.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemSaveAsText
		// 
		toolStripMenuItemSaveAsText.AccessibleDescription = "Saves the list as text file";
		toolStripMenuItemSaveAsText.AccessibleName = "Save as text";
		toolStripMenuItemSaveAsText.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsText.AutoToolTip = true;
		toolStripMenuItemSaveAsText.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsText.Name = "toolStripMenuItemSaveAsText";
		toolStripMenuItemSaveAsText.ShortcutKeyDisplayString = "";
		toolStripMenuItemSaveAsText.ShortcutKeys = Keys.Control | Keys.X;
		toolStripMenuItemSaveAsText.Size = new Size(215, 22);
		toolStripMenuItemSaveAsText.Text = "Save as te&xt";
		toolStripMenuItemSaveAsText.Click += ToolStripMenuItemSaveAsText_Click;
		toolStripMenuItemSaveAsText.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsText.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemSaveAsLatex
		// 
		toolStripMenuItemSaveAsLatex.AccessibleDescription = "Saves the list as Latex file";
		toolStripMenuItemSaveAsLatex.AccessibleName = "Save as Latex";
		toolStripMenuItemSaveAsLatex.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsLatex.AutoToolTip = true;
		toolStripMenuItemSaveAsLatex.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsLatex.Name = "toolStripMenuItemSaveAsLatex";
		toolStripMenuItemSaveAsLatex.ShortcutKeyDisplayString = "Strg+E";
		toolStripMenuItemSaveAsLatex.ShortcutKeys = Keys.Control | Keys.E;
		toolStripMenuItemSaveAsLatex.Size = new Size(215, 22);
		toolStripMenuItemSaveAsLatex.Text = "Save as Lat&ex";
		toolStripMenuItemSaveAsLatex.Click += ToolStripMenuItemSaveAsLatex_Click;
		toolStripMenuItemSaveAsLatex.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsLatex.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemSaveAsMarkdown
		// 
		toolStripMenuItemSaveAsMarkdown.AccessibleDescription = "Saves the list as Markdown file";
		toolStripMenuItemSaveAsMarkdown.AccessibleName = "Save as Markdown";
		toolStripMenuItemSaveAsMarkdown.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsMarkdown.AutoToolTip = true;
		toolStripMenuItemSaveAsMarkdown.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsMarkdown.Name = "toolStripMenuItemSaveAsMarkdown";
		toolStripMenuItemSaveAsMarkdown.ShortcutKeyDisplayString = "Strg+K";
		toolStripMenuItemSaveAsMarkdown.ShortcutKeys = Keys.Control | Keys.K;
		toolStripMenuItemSaveAsMarkdown.Size = new Size(215, 22);
		toolStripMenuItemSaveAsMarkdown.Text = "Save as Mar&kdown";
		toolStripMenuItemSaveAsMarkdown.Click += ToolStripMenuItemSaveAsMarkdown_Click;
		toolStripMenuItemSaveAsMarkdown.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsMarkdown.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemSaveAsWord
		// 
		toolStripMenuItemSaveAsWord.AccessibleDescription = "Saves the list as Word file";
		toolStripMenuItemSaveAsWord.AccessibleName = "Save as Word";
		toolStripMenuItemSaveAsWord.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsWord.AutoToolTip = true;
		toolStripMenuItemSaveAsWord.Image = FatcowIcons16px.fatcow_page_white_word_16px;
		toolStripMenuItemSaveAsWord.Name = "toolStripMenuItemSaveAsWord";
		toolStripMenuItemSaveAsWord.ShortcutKeyDisplayString = "Strg+W";
		toolStripMenuItemSaveAsWord.ShortcutKeys = Keys.Control | Keys.W;
		toolStripMenuItemSaveAsWord.Size = new Size(215, 22);
		toolStripMenuItemSaveAsWord.Text = "Save as &Word";
		toolStripMenuItemSaveAsWord.Click += ToolStripMenuItemSaveAsWord_Click;
		toolStripMenuItemSaveAsWord.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsWord.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemSaveAsOdt
		// 
		toolStripMenuItemSaveAsOdt.AccessibleDescription = "Saves the list as ODT file";
		toolStripMenuItemSaveAsOdt.AccessibleName = "Save as ODT";
		toolStripMenuItemSaveAsOdt.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsOdt.AutoToolTip = true;
		toolStripMenuItemSaveAsOdt.Image = FatcowIcons16px.fatcow_page_white_word_16px;
		toolStripMenuItemSaveAsOdt.Name = "toolStripMenuItemSaveAsOdt";
		toolStripMenuItemSaveAsOdt.ShortcutKeyDisplayString = "Strg+D";
		toolStripMenuItemSaveAsOdt.ShortcutKeys = Keys.Control | Keys.D;
		toolStripMenuItemSaveAsOdt.Size = new Size(215, 22);
		toolStripMenuItemSaveAsOdt.Text = "Save as O&DT";
		toolStripMenuItemSaveAsOdt.Click += ToolStripMenuItemSaveAsOdt_Click;
		toolStripMenuItemSaveAsOdt.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsOdt.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemSaveAsRtf
		// 
		toolStripMenuItemSaveAsRtf.AccessibleDescription = "Saves the list as RTF file";
		toolStripMenuItemSaveAsRtf.AccessibleName = "Save as RTF";
		toolStripMenuItemSaveAsRtf.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsRtf.AutoToolTip = true;
		toolStripMenuItemSaveAsRtf.Image = FatcowIcons16px.fatcow_page_white_word_16px;
		toolStripMenuItemSaveAsRtf.Name = "toolStripMenuItemSaveAsRtf";
		toolStripMenuItemSaveAsRtf.ShortcutKeyDisplayString = "Strg+R";
		toolStripMenuItemSaveAsRtf.ShortcutKeys = Keys.Control | Keys.R;
		toolStripMenuItemSaveAsRtf.Size = new Size(215, 22);
		toolStripMenuItemSaveAsRtf.Text = "Save as &RTF";
		toolStripMenuItemSaveAsRtf.Click += ToolStripMenuItemSaveAsRtf_Click;
		toolStripMenuItemSaveAsRtf.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsRtf.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemSaveAsExcel
		// 
		toolStripMenuItemSaveAsExcel.AccessibleDescription = "Saves the list as Excel file";
		toolStripMenuItemSaveAsExcel.AccessibleName = "Save as Excel";
		toolStripMenuItemSaveAsExcel.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsExcel.AutoToolTip = true;
		toolStripMenuItemSaveAsExcel.Image = FatcowIcons16px.fatcow_page_white_excel_16px;
		toolStripMenuItemSaveAsExcel.Name = "toolStripMenuItemSaveAsExcel";
		toolStripMenuItemSaveAsExcel.ShortcutKeyDisplayString = "Strg+L";
		toolStripMenuItemSaveAsExcel.ShortcutKeys = Keys.Control | Keys.L;
		toolStripMenuItemSaveAsExcel.Size = new Size(215, 22);
		toolStripMenuItemSaveAsExcel.Text = "Save as Exce&l";
		toolStripMenuItemSaveAsExcel.Click += ToolStripMenuItemSaveAsExcel_Click;
		toolStripMenuItemSaveAsExcel.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsExcel.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemSaveAsOds
		// 
		toolStripMenuItemSaveAsOds.AccessibleDescription = "Saves the list as ODS file";
		toolStripMenuItemSaveAsOds.AccessibleName = "Save as ODS";
		toolStripMenuItemSaveAsOds.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsOds.AutoToolTip = true;
		toolStripMenuItemSaveAsOds.Image = FatcowIcons16px.fatcow_page_white_excel_16px;
		toolStripMenuItemSaveAsOds.Name = "toolStripMenuItemSaveAsOds";
		toolStripMenuItemSaveAsOds.ShortcutKeyDisplayString = "Strg+S";
		toolStripMenuItemSaveAsOds.ShortcutKeys = Keys.Control | Keys.S;
		toolStripMenuItemSaveAsOds.Size = new Size(215, 22);
		toolStripMenuItemSaveAsOds.Text = "Save as OD&S";
		toolStripMenuItemSaveAsOds.Click += ToolStripMenuItemSaveAsOds_Click;
		toolStripMenuItemSaveAsOds.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsOds.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemSaveAsCsv
		// 
		toolStripMenuItemSaveAsCsv.AccessibleDescription = "Saves the list as CSV file";
		toolStripMenuItemSaveAsCsv.AccessibleName = "Save as CSV";
		toolStripMenuItemSaveAsCsv.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsCsv.AutoToolTip = true;
		toolStripMenuItemSaveAsCsv.Image = FatcowIcons16px.fatcow_page_white_excel_16px;
		toolStripMenuItemSaveAsCsv.Name = "toolStripMenuItemSaveAsCsv";
		toolStripMenuItemSaveAsCsv.ShortcutKeyDisplayString = "Strg+C";
		toolStripMenuItemSaveAsCsv.ShortcutKeys = Keys.Control | Keys.C;
		toolStripMenuItemSaveAsCsv.Size = new Size(215, 22);
		toolStripMenuItemSaveAsCsv.Text = "Save as &CSV";
		toolStripMenuItemSaveAsCsv.Click += ToolStripMenuItemSaveAsCsv_Click;
		toolStripMenuItemSaveAsCsv.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsCsv.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemSaveAsTsv
		// 
		toolStripMenuItemSaveAsTsv.AccessibleDescription = "Saves the list as TSV file";
		toolStripMenuItemSaveAsTsv.AccessibleName = "Save as TSV";
		toolStripMenuItemSaveAsTsv.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsTsv.AutoToolTip = true;
		toolStripMenuItemSaveAsTsv.Image = FatcowIcons16px.fatcow_page_white_excel_16px;
		toolStripMenuItemSaveAsTsv.Name = "toolStripMenuItemSaveAsTsv";
		toolStripMenuItemSaveAsTsv.ShortcutKeyDisplayString = "Strg+T";
		toolStripMenuItemSaveAsTsv.ShortcutKeys = Keys.Control | Keys.T;
		toolStripMenuItemSaveAsTsv.Size = new Size(215, 22);
		toolStripMenuItemSaveAsTsv.Text = "Save as &TSV";
		toolStripMenuItemSaveAsTsv.Click += ToolStripMenuItemSaveAsTsv_Click;
		toolStripMenuItemSaveAsTsv.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsTsv.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemSaveAsPsv
		// 
		toolStripMenuItemSaveAsPsv.AccessibleDescription = "Saves the list as PSV file";
		toolStripMenuItemSaveAsPsv.AccessibleName = "Save as PSV";
		toolStripMenuItemSaveAsPsv.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsPsv.AutoToolTip = true;
		toolStripMenuItemSaveAsPsv.Image = FatcowIcons16px.fatcow_page_white_excel_16px;
		toolStripMenuItemSaveAsPsv.Name = "toolStripMenuItemSaveAsPsv";
		toolStripMenuItemSaveAsPsv.ShortcutKeyDisplayString = "Strg+V";
		toolStripMenuItemSaveAsPsv.ShortcutKeys = Keys.Control | Keys.V;
		toolStripMenuItemSaveAsPsv.Size = new Size(215, 22);
		toolStripMenuItemSaveAsPsv.Text = "Save as PS&V";
		toolStripMenuItemSaveAsPsv.Click += ToolStripMenuItemSaveAsPsv_Click;
		toolStripMenuItemSaveAsPsv.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsPsv.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemSaveAsHtml
		// 
		toolStripMenuItemSaveAsHtml.AccessibleDescription = "Saves the list as HTML file";
		toolStripMenuItemSaveAsHtml.AccessibleName = "Save as HTML";
		toolStripMenuItemSaveAsHtml.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsHtml.AutoToolTip = true;
		toolStripMenuItemSaveAsHtml.Image = FatcowIcons16px.fatcow_page_white_code_16px;
		toolStripMenuItemSaveAsHtml.Name = "toolStripMenuItemSaveAsHtml";
		toolStripMenuItemSaveAsHtml.ShortcutKeyDisplayString = "Strg+H";
		toolStripMenuItemSaveAsHtml.ShortcutKeys = Keys.Control | Keys.H;
		toolStripMenuItemSaveAsHtml.Size = new Size(215, 22);
		toolStripMenuItemSaveAsHtml.Text = "Save as &HTML";
		toolStripMenuItemSaveAsHtml.Click += ToolStripMenuItemSaveAsHtml_Click;
		toolStripMenuItemSaveAsHtml.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsHtml.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemSaveAsXml
		// 
		toolStripMenuItemSaveAsXml.AccessibleDescription = "Saves the list as XML file";
		toolStripMenuItemSaveAsXml.AccessibleName = "Save as XML";
		toolStripMenuItemSaveAsXml.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsXml.AutoToolTip = true;
		toolStripMenuItemSaveAsXml.Image = FatcowIcons16px.fatcow_page_white_code_16px;
		toolStripMenuItemSaveAsXml.Name = "toolStripMenuItemSaveAsXml";
		toolStripMenuItemSaveAsXml.ShortcutKeyDisplayString = "Strg+M";
		toolStripMenuItemSaveAsXml.ShortcutKeys = Keys.Control | Keys.M;
		toolStripMenuItemSaveAsXml.Size = new Size(215, 22);
		toolStripMenuItemSaveAsXml.Text = "Save as X&ML";
		toolStripMenuItemSaveAsXml.Click += ToolStripMenuItemSaveAsXml_Click;
		toolStripMenuItemSaveAsXml.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsXml.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemSaveAsJson
		// 
		toolStripMenuItemSaveAsJson.AccessibleDescription = "Saves the list as JSON file";
		toolStripMenuItemSaveAsJson.AccessibleName = "Save as JSON";
		toolStripMenuItemSaveAsJson.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsJson.AutoToolTip = true;
		toolStripMenuItemSaveAsJson.Image = FatcowIcons16px.fatcow_page_white_code_red_16px;
		toolStripMenuItemSaveAsJson.Name = "toolStripMenuItemSaveAsJson";
		toolStripMenuItemSaveAsJson.ShortcutKeyDisplayString = "Strg+J";
		toolStripMenuItemSaveAsJson.ShortcutKeys = Keys.Control | Keys.J;
		toolStripMenuItemSaveAsJson.Size = new Size(215, 22);
		toolStripMenuItemSaveAsJson.Text = "Save as &JSON";
		toolStripMenuItemSaveAsJson.Click += ToolStripMenuItemSaveAsJson_Click;
		toolStripMenuItemSaveAsJson.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsJson.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemSaveAsYaml
		// 
		toolStripMenuItemSaveAsYaml.AccessibleDescription = "Saves the list as YAML file";
		toolStripMenuItemSaveAsYaml.AccessibleName = "Save as YAML";
		toolStripMenuItemSaveAsYaml.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsYaml.AutoToolTip = true;
		toolStripMenuItemSaveAsYaml.Image = FatcowIcons16px.fatcow_page_white_code_red_16px;
		toolStripMenuItemSaveAsYaml.Name = "toolStripMenuItemSaveAsYaml";
		toolStripMenuItemSaveAsYaml.ShortcutKeyDisplayString = "Strg+Y";
		toolStripMenuItemSaveAsYaml.ShortcutKeys = Keys.Control | Keys.Y;
		toolStripMenuItemSaveAsYaml.Size = new Size(215, 22);
		toolStripMenuItemSaveAsYaml.Text = "Save as &YAML";
		toolStripMenuItemSaveAsYaml.Click += ToolStripMenuItemSaveAsYaml_Click;
		toolStripMenuItemSaveAsYaml.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsYaml.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemSaveAsSql
		// 
		toolStripMenuItemSaveAsSql.AccessibleDescription = "Saves the list as SQL script";
		toolStripMenuItemSaveAsSql.AccessibleName = "Save as SQL";
		toolStripMenuItemSaveAsSql.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsSql.AutoToolTip = true;
		toolStripMenuItemSaveAsSql.Image = FatcowIcons16px.fatcow_page_white_database_16px;
		toolStripMenuItemSaveAsSql.Name = "toolStripMenuItemSaveAsSql";
		toolStripMenuItemSaveAsSql.ShortcutKeyDisplayString = "Strg+Q";
		toolStripMenuItemSaveAsSql.ShortcutKeys = Keys.Control | Keys.Q;
		toolStripMenuItemSaveAsSql.Size = new Size(215, 22);
		toolStripMenuItemSaveAsSql.Text = "Save as S&QL";
		toolStripMenuItemSaveAsSql.Click += ToolStripMenuItemSaveAsSql_Click;
		toolStripMenuItemSaveAsSql.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsSql.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemSaveAsPdf
		// 
		toolStripMenuItemSaveAsPdf.AccessibleDescription = "Saves the list as PDF file";
		toolStripMenuItemSaveAsPdf.AccessibleName = "Save as PDF";
		toolStripMenuItemSaveAsPdf.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsPdf.AutoToolTip = true;
		toolStripMenuItemSaveAsPdf.Image = FatcowIcons16px.fatcow_page_white_acrobat_16px;
		toolStripMenuItemSaveAsPdf.Name = "toolStripMenuItemSaveAsPdf";
		toolStripMenuItemSaveAsPdf.ShortcutKeyDisplayString = "Strg+F";
		toolStripMenuItemSaveAsPdf.ShortcutKeys = Keys.Control | Keys.F;
		toolStripMenuItemSaveAsPdf.Size = new Size(215, 22);
		toolStripMenuItemSaveAsPdf.Text = "Save as PD&F";
		toolStripMenuItemSaveAsPdf.Click += ToolStripMenuItemSaveAsPdf_Click;
		toolStripMenuItemSaveAsPdf.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsPdf.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemSaveAsPostScript
		// 
		toolStripMenuItemSaveAsPostScript.AccessibleDescription = "Saves the list as PostScript file";
		toolStripMenuItemSaveAsPostScript.AccessibleName = "Save as PS";
		toolStripMenuItemSaveAsPostScript.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsPostScript.AutoToolTip = true;
		toolStripMenuItemSaveAsPostScript.Image = FatcowIcons16px.fatcow_page_white_acrobat_16px;
		toolStripMenuItemSaveAsPostScript.Name = "toolStripMenuItemSaveAsPostScript";
		toolStripMenuItemSaveAsPostScript.ShortcutKeyDisplayString = "Strg+P";
		toolStripMenuItemSaveAsPostScript.ShortcutKeys = Keys.Control | Keys.P;
		toolStripMenuItemSaveAsPostScript.Size = new Size(215, 22);
		toolStripMenuItemSaveAsPostScript.Text = "Save as &PS";
		toolStripMenuItemSaveAsPostScript.Click += ToolStripMenuItemSaveAsPostScript_Click;
		toolStripMenuItemSaveAsPostScript.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsPostScript.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemSaveAsEpub
		// 
		toolStripMenuItemSaveAsEpub.AccessibleDescription = "Saves the list as EPUB file";
		toolStripMenuItemSaveAsEpub.AccessibleName = "Save as EPUB";
		toolStripMenuItemSaveAsEpub.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsEpub.AutoToolTip = true;
		toolStripMenuItemSaveAsEpub.Image = FatcowIcons16px.fatcow_page_white_acrobat_16px;
		toolStripMenuItemSaveAsEpub.Name = "toolStripMenuItemSaveAsEpub";
		toolStripMenuItemSaveAsEpub.ShortcutKeyDisplayString = "Strg+B";
		toolStripMenuItemSaveAsEpub.ShortcutKeys = Keys.Control | Keys.B;
		toolStripMenuItemSaveAsEpub.Size = new Size(215, 22);
		toolStripMenuItemSaveAsEpub.Text = "Save as EPU&B";
		toolStripMenuItemSaveAsEpub.Click += ToolStripMenuItemSaveAsEpub_Click;
		toolStripMenuItemSaveAsEpub.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsEpub.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemSaveAsMobi
		// 
		toolStripMenuItemSaveAsMobi.AccessibleDescription = "Saves the list as MOBI file";
		toolStripMenuItemSaveAsMobi.AccessibleName = "Save as MOBI";
		toolStripMenuItemSaveAsMobi.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsMobi.AutoToolTip = true;
		toolStripMenuItemSaveAsMobi.Image = FatcowIcons16px.fatcow_page_white_acrobat_16px;
		toolStripMenuItemSaveAsMobi.Name = "toolStripMenuItemSaveAsMobi";
		toolStripMenuItemSaveAsMobi.ShortcutKeyDisplayString = "Strg+I";
		toolStripMenuItemSaveAsMobi.ShortcutKeys = Keys.Control | Keys.I;
		toolStripMenuItemSaveAsMobi.Size = new Size(215, 22);
		toolStripMenuItemSaveAsMobi.Text = "Save as MOB&I";
		toolStripMenuItemSaveAsMobi.Click += ToolStripMenuItemSaveAsMobi_Click;
		toolStripMenuItemSaveAsMobi.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsMobi.MouseLeave += Control_Leave;
		// 
		// toolStripDropDownButtonSaveList
		// 
		toolStripDropDownButtonSaveList.AccessibleDescription = "Saves the list as file";
		toolStripDropDownButtonSaveList.AccessibleName = "Save list";
		toolStripDropDownButtonSaveList.AccessibleRole = AccessibleRole.ButtonDropDown;
		toolStripDropDownButtonSaveList.DropDown = contextMenuSaveList;
		toolStripDropDownButtonSaveList.Image = FatcowIcons16px.fatcow_diskette_16px;
		toolStripDropDownButtonSaveList.ImageTransparentColor = Color.Magenta;
		toolStripDropDownButtonSaveList.Name = "toolStripDropDownButtonSaveList";
		toolStripDropDownButtonSaveList.Size = new Size(78, 22);
		toolStripDropDownButtonSaveList.Text = "&Save list";
		// 
		// kryptoPanelMain
		// 
		kryptoPanelMain.AccessibleDescription = "Groups the data";
		kryptoPanelMain.AccessibleName = "Panel";
		kryptoPanelMain.AccessibleRole = AccessibleRole.Pane;
		kryptoPanelMain.Controls.Add(listView);
		kryptoPanelMain.Dock = DockStyle.Fill;
		kryptoPanelMain.Location = new Point(0, 0);
		kryptoPanelMain.Name = "kryptoPanelMain";
		kryptoPanelMain.PanelBackStyle = PaletteBackStyle.FormMain;
		kryptoPanelMain.Size = new Size(341, 280);
		kryptoPanelMain.TabIndex = 0;
		kryptoPanelMain.TabStop = true;
		kryptoPanelMain.Text = "Mainpanel";
		kryptoPanelMain.Enter += Control_Enter;
		kryptoPanelMain.Leave += Control_Leave;
		kryptoPanelMain.MouseEnter += Control_Enter;
		kryptoPanelMain.MouseLeave += Control_Leave;
		// 
		// listView
		// 
		listView.AccessibleDescription = "Shows the list with the items";
		listView.AccessibleName = "List";
		listView.AccessibleRole = AccessibleRole.ListItem;
		listView.Activation = ItemActivation.OneClick;
		listView.AllowColumnReorder = true;
		listView.Columns.AddRange(new ColumnHeader[] { columnHeaderIndex, columnHeaderReadableDesignation });
		listView.Dock = DockStyle.Fill;
		listView.Font = new Font("Segoe UI", 8.5F);
		listView.FullRowSelect = true;
		listView.GridLines = true;
		listView.Location = new Point(0, 0);
		listView.MultiSelect = false;
		listView.Name = "listView";
		listView.ShowItemToolTips = true;
		listView.Size = new Size(341, 280);
		listView.TabIndex = 10;
		listView.UseCompatibleStateImageBehavior = false;
		listView.View = View.Details;
		listView.VirtualMode = true;
		listView.RetrieveVirtualItem += ListView_RetrieveVirtualItem;
		listView.SelectedIndexChanged += SelectedIndexChanged;
		listView.DoubleClick += ListView_DoubleClick;
		listView.Enter += Control_Enter;
		listView.Leave += Control_Leave;
		listView.MouseEnter += Control_Enter;
		listView.MouseLeave += Control_Leave;
		// 
		// columnHeaderIndex
		// 
		columnHeaderIndex.Text = "Index No.";
		columnHeaderIndex.Width = 80;
		// 
		// columnHeaderReadableDesignation
		// 
		columnHeaderReadableDesignation.Text = "Readable designation";
		columnHeaderReadableDesignation.Width = 180;
		// 
		// kryptonManager
		// 
		kryptonManager.GlobalPaletteMode = PaletteMode.Global;
		kryptonManager.ToolkitStrings.MessageBoxStrings.LessDetails = "L&ess Details...";
		kryptonManager.ToolkitStrings.MessageBoxStrings.MoreDetails = "&More Details...";
		// 
		// toolStripContainer
		// 
		toolStripContainer.AccessibleDescription = "Container to arrange the toolbars";
		toolStripContainer.AccessibleName = "Container to arrange the toolbars";
		toolStripContainer.AccessibleRole = AccessibleRole.Grouping;
		// 
		// toolStripContainer.BottomToolStripPanel
		// 
		toolStripContainer.BottomToolStripPanel.Controls.Add(kryptonStatusStrip);
		// 
		// toolStripContainer.ContentPanel
		// 
		toolStripContainer.ContentPanel.Controls.Add(kryptoPanelMain);
		toolStripContainer.ContentPanel.Size = new Size(341, 280);
		toolStripContainer.Dock = DockStyle.Fill;
		toolStripContainer.Location = new Point(0, 0);
		toolStripContainer.Name = "toolStripContainer";
		toolStripContainer.Size = new Size(341, 353);
		toolStripContainer.TabIndex = 3;
		toolStripContainer.Text = "toolStripContainer";
		// 
		// toolStripContainer.TopToolStripPanel
		// 
		toolStripContainer.TopToolStripPanel.Controls.Add(kryptonToolStripList);
		toolStripContainer.TopToolStripPanel.Controls.Add(kryptonToolStripSaveList);
		toolStripContainer.Enter += Control_Enter;
		toolStripContainer.Leave += Control_Leave;
		toolStripContainer.MouseEnter += Control_Enter;
		toolStripContainer.MouseLeave += Control_Leave;
		// 
		// kryptonToolStripList
		// 
		kryptonToolStripList.AccessibleDescription = "Toolbar of generating list";
		kryptonToolStripList.AccessibleName = "Toolbar of generating list";
		kryptonToolStripList.AccessibleRole = AccessibleRole.ToolBar;
		kryptonToolStripList.AllowClickThrough = true;
		kryptonToolStripList.AllowItemReorder = true;
		kryptonToolStripList.Dock = DockStyle.None;
		kryptonToolStripList.Font = new Font("Segoe UI", 9F);
		kryptonToolStripList.Items.AddRange(new ToolStripItem[] { toolStripButtonCreateList, toolStripSeparator1, toolStripLabelMinimum, toolStripNumericUpDownMinimum, toolStripLabelMaximum, toolStripNumericUpDownMaximum });
		kryptonToolStripList.Location = new Point(0, 0);
		kryptonToolStripList.Name = "kryptonToolStripList";
		kryptonToolStripList.Size = new Size(341, 26);
		kryptonToolStripList.Stretch = true;
		kryptonToolStripList.TabIndex = 0;
		kryptonToolStripList.TabStop = true;
		kryptonToolStripList.Text = "Toolbar of generating list";
		kryptonToolStripList.Enter += Control_Enter;
		kryptonToolStripList.Leave += Control_Leave;
		kryptonToolStripList.MouseEnter += Control_Enter;
		kryptonToolStripList.MouseLeave += Control_Leave;
		// 
		// toolStripButtonCreateList
		// 
		toolStripButtonCreateList.AccessibleDescription = "Starts the progress and create the list";
		toolStripButtonCreateList.AccessibleName = "Create the List";
		toolStripButtonCreateList.AccessibleRole = AccessibleRole.PushButton;
		toolStripButtonCreateList.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripButtonCreateList.ImageTransparentColor = Color.Magenta;
		toolStripButtonCreateList.Name = "toolStripButtonCreateList";
		toolStripButtonCreateList.Size = new Size(45, 23);
		toolStripButtonCreateList.Text = "&List";
		toolStripButtonCreateList.Click += ButtonCreateList_Click;
		toolStripButtonCreateList.MouseEnter += Control_Enter;
		toolStripButtonCreateList.MouseLeave += Control_Leave;
		// 
		// toolStripSeparator1
		// 
		toolStripSeparator1.AccessibleDescription = "Just a separator";
		toolStripSeparator1.AccessibleName = "Just a separator";
		toolStripSeparator1.AccessibleRole = AccessibleRole.Separator;
		toolStripSeparator1.Name = "toolStripSeparator1";
		toolStripSeparator1.Size = new Size(6, 26);
		toolStripSeparator1.MouseEnter += Control_Enter;
		toolStripSeparator1.MouseLeave += Control_Leave;
		// 
		// toolStripLabelMinimum
		// 
		toolStripLabelMinimum.AccessibleDescription = "Shows the minimum";
		toolStripLabelMinimum.AccessibleName = "Minimum";
		toolStripLabelMinimum.AccessibleRole = AccessibleRole.StaticText;
		toolStripLabelMinimum.AutoToolTip = true;
		toolStripLabelMinimum.Name = "toolStripLabelMinimum";
		toolStripLabelMinimum.Size = new Size(60, 23);
		toolStripLabelMinimum.Text = "M&inimum";
		toolStripLabelMinimum.MouseEnter += Control_Enter;
		toolStripLabelMinimum.MouseLeave += Control_Leave;
		// 
		// toolStripNumericUpDownMinimum
		// 
		toolStripNumericUpDownMinimum.AccessibleDescription = "Shows the minimum value for the list";
		toolStripNumericUpDownMinimum.AccessibleName = "Minimum value for the list";
		toolStripNumericUpDownMinimum.AccessibleRole = AccessibleRole.SpinButton;
		toolStripNumericUpDownMinimum.AutoSize = true;
		toolStripNumericUpDownMinimum.AutoToolTip = true;
		toolStripNumericUpDownMinimum.Name = "toolStripNumericUpDownMinimum";
		toolStripNumericUpDownMinimum.Size = new Size(41, 23);
		toolStripNumericUpDownMinimum.Text = "0";
		toolStripNumericUpDownMinimum.TextAlign = HorizontalAlignment.Center;
		toolStripNumericUpDownMinimum.MouseEnter += Control_Enter;
		toolStripNumericUpDownMinimum.MouseLeave += Control_Leave;
		// 
		// toolStripLabelMaximum
		// 
		toolStripLabelMaximum.AccessibleDescription = "Shows the maximum";
		toolStripLabelMaximum.AccessibleName = "Maximum";
		toolStripLabelMaximum.AccessibleRole = AccessibleRole.StaticText;
		toolStripLabelMaximum.AutoToolTip = true;
		toolStripLabelMaximum.Name = "toolStripLabelMaximum";
		toolStripLabelMaximum.Size = new Size(62, 23);
		toolStripLabelMaximum.Text = "M&aximum";
		toolStripLabelMaximum.MouseEnter += Control_Enter;
		toolStripLabelMaximum.MouseLeave += Control_Leave;
		// 
		// toolStripNumericUpDownMaximum
		// 
		toolStripNumericUpDownMaximum.AccessibleDescription = "Shows the maximum value for the list";
		toolStripNumericUpDownMaximum.AccessibleName = "Maximum value for the list";
		toolStripNumericUpDownMaximum.AccessibleRole = AccessibleRole.SpinButton;
		toolStripNumericUpDownMaximum.AutoSize = true;
		toolStripNumericUpDownMaximum.AutoToolTip = true;
		toolStripNumericUpDownMaximum.Name = "toolStripNumericUpDownMaximum";
		toolStripNumericUpDownMaximum.Size = new Size(41, 23);
		toolStripNumericUpDownMaximum.Text = "0";
		toolStripNumericUpDownMaximum.TextAlign = HorizontalAlignment.Center;
		toolStripNumericUpDownMaximum.MouseEnter += Control_Enter;
		toolStripNumericUpDownMaximum.MouseLeave += Control_Leave;
		// 
		// kryptonToolStripSaveList
		// 
		kryptonToolStripSaveList.AccessibleDescription = "Toolbar of saving list";
		kryptonToolStripSaveList.AccessibleName = "Toolbar of saving list";
		kryptonToolStripSaveList.AccessibleRole = AccessibleRole.ToolBar;
		kryptonToolStripSaveList.AllowClickThrough = true;
		kryptonToolStripSaveList.AllowItemReorder = true;
		kryptonToolStripSaveList.Dock = DockStyle.None;
		kryptonToolStripSaveList.Font = new Font("Segoe UI", 9F);
		kryptonToolStripSaveList.Items.AddRange(new ToolStripItem[] { toolStripButtonLoad, toolStripSeparator2, toolStripDropDownButtonSaveList });
		kryptonToolStripSaveList.Location = new Point(0, 26);
		kryptonToolStripSaveList.Name = "kryptonToolStripSaveList";
		kryptonToolStripSaveList.Size = new Size(341, 25);
		kryptonToolStripSaveList.Stretch = true;
		kryptonToolStripSaveList.TabIndex = 1;
		kryptonToolStripSaveList.TabStop = true;
		kryptonToolStripSaveList.MouseEnter += Control_Enter;
		kryptonToolStripSaveList.MouseLeave += Control_Leave;
		// 
		// toolStripButtonLoad
		// 
		toolStripButtonLoad.AccessibleDescription = "Loads the selected planetoid";
		toolStripButtonLoad.AccessibleName = "Load";
		toolStripButtonLoad.AccessibleRole = AccessibleRole.PushButton;
		toolStripButtonLoad.Image = FatcowIcons16px.fatcow_bullet_go_16px;
		toolStripButtonLoad.ImageTransparentColor = Color.Magenta;
		toolStripButtonLoad.Name = "toolStripButtonLoad";
		toolStripButtonLoad.Size = new Size(53, 22);
		toolStripButtonLoad.Text = "L&oad";
		toolStripButtonLoad.Click += ToolStripButtonLoad_Click;
		toolStripButtonLoad.MouseEnter += Control_Enter;
		toolStripButtonLoad.MouseLeave += Control_Leave;
		// 
		// toolStripSeparator2
		// 
		toolStripSeparator2.AccessibleDescription = "Just a separator";
		toolStripSeparator2.AccessibleName = "Just a separator";
		toolStripSeparator2.AccessibleRole = AccessibleRole.Separator;
		toolStripSeparator2.Name = "toolStripSeparator2";
		toolStripSeparator2.Size = new Size(6, 25);
		toolStripSeparator2.MouseEnter += Control_Enter;
		toolStripSeparator2.MouseLeave += Control_Leave;
		// 
		// ListReadableDesignationsForm
		// 
		AccessibleDescription = "Lists the readable designations";
		AccessibleName = "List of readable designations";
		AccessibleRole = AccessibleRole.Dialog;
		AutoScaleDimensions = new SizeF(7F, 15F);
		AutoScaleMode = AutoScaleMode.Font;
		ClientSize = new Size(341, 353);
		ControlBox = false;
		Controls.Add(toolStripContainer);
		FormBorderStyle = FormBorderStyle.SizableToolWindow;
		Icon = (Icon)resources.GetObject("$this.Icon");
		MaximizeBox = false;
		MinimizeBox = false;
		Name = "ListReadableDesignationsForm";
		StartPosition = FormStartPosition.CenterParent;
		Text = "List of readable designations";
		FormClosed += ListReadableDesignationsForm_FormClosed;
		Load += ListReadableDesignationsForm_Load;
		kryptonStatusStrip.ResumeLayout(false);
		kryptonStatusStrip.PerformLayout();
		contextMenuCopyToClipboard.ResumeLayout(false);
		contextMenuSaveList.ResumeLayout(false);
		((ISupportInitialize)kryptoPanelMain).EndInit();
		kryptoPanelMain.ResumeLayout(false);
		toolStripContainer.BottomToolStripPanel.ResumeLayout(false);
		toolStripContainer.BottomToolStripPanel.PerformLayout();
		toolStripContainer.ContentPanel.ResumeLayout(false);
		toolStripContainer.TopToolStripPanel.ResumeLayout(false);
		toolStripContainer.TopToolStripPanel.PerformLayout();
		toolStripContainer.ResumeLayout(false);
		toolStripContainer.PerformLayout();
		kryptonToolStripList.ResumeLayout(false);
		kryptonToolStripList.PerformLayout();
		kryptonToolStripSaveList.ResumeLayout(false);
		kryptonToolStripSaveList.PerformLayout();
		ResumeLayout(false);
	}

	#endregion

	private KryptonStatusStrip kryptonStatusStrip;
	private ToolStripStatusLabel labelInformation;
	private KryptonPanel kryptoPanelMain;
	private ListView listView;
	private ColumnHeader columnHeaderIndex;
	private ColumnHeader columnHeaderReadableDesignation;
	private ContextMenuStrip contextMenuSaveList;
	private ToolStripMenuItem toolStripMenuItemSaveAsCsv;
	private ToolStripMenuItem toolStripMenuItemSaveAsHtml;
	private ToolStripMenuItem toolStripMenuItemSaveAsXml;
	private ToolStripMenuItem toolStripMenuItemSaveAsJson;
	private KryptonManager kryptonManager;
	private ContextMenuStrip contextMenuCopyToClipboard;
	private ToolStripMenuItem toolStripMenuItemCopyToClipboard;
	private ToolStripMenuItem toolStripMenuItemSaveAsSql;
	private ToolStripMenuItem toolStripMenuItemSaveAsMarkdown;
	private ToolStripMenuItem toolStripMenuItemSaveAsYaml;
	private ToolStripMenuItem toolStripMenuItemSaveAsTsv;
	private ToolStripMenuItem toolStripMenuItemSaveAsLatex;
	private ToolStripMenuItem toolStripMenuItemSaveAsPostScript;
	private ToolStripMenuItem toolStripMenuItemSaveAsPdf;
	private ToolStripMenuItem toolStripMenuItemSaveAsPsv;
	private ToolStripMenuItem toolStripMenuItemSaveAsEpub;
	private ToolStripMenuItem toolStripMenuItemSaveAsWord;
	private ToolStripMenuItem toolStripMenuItemSaveAsExcel;
	private ToolStripMenuItem toolStripMenuItemSaveAsOdt;
	private ToolStripMenuItem toolStripMenuItemSaveAsOds;
	private ToolStripMenuItem toolStripMenuItemSaveAsMobi;
	private ToolStripMenuItem toolStripMenuItemSaveAsText;
	private ToolStripMenuItem toolStripMenuItemSaveAsRtf;
	private ToolStripContainer toolStripContainer;
	private KryptonToolStrip kryptonToolStripList;
	private ToolStripButton toolStripButtonCreateList;
	private KryptonToolStrip kryptonToolStripSaveList;
	private ToolStripButton toolStripButtonLoad;
	private ToolStripSeparator toolStripSeparator1;
	private Helpers.ToolStripNumericUpDown toolStripNumericUpDownMinimum;
	private ToolStripLabel toolStripLabelMinimum;
	private ToolStripLabel toolStripLabelMaximum;
	private Helpers.ToolStripNumericUpDown toolStripNumericUpDownMaximum;
	private ToolStripSeparator toolStripSeparator2;
	private ToolStripDropDownButton toolStripDropDownButtonSaveList;
}