// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using Krypton.Toolkit;

using Planetoid_DB.Resources;

using System.ComponentModel;

namespace Planetoid_DB;

/// <summary>Represents a Windows Form that displays the Minimum Orbit Intersection Distance (MOID) of a minor planet
/// relative to each of the eight solar system planets (Mercury through Neptune).</summary>
/// <remarks>The form presents data in a two-column <see cref="KryptonTableLayoutPanel"/> with eight rows —
/// one per planet. Column 1 shows the planet name; column 2 shows the corresponding MOID in AU.
/// Export to many file formats is available through the toolbar dropdown button.
/// The form does not appear in the taskbar and is intended to be used as a modal dialog.</remarks>
partial class MoidsOfOneMinorPlanetForm
{
	/// <summary>Required designer variable.</summary>
	/// <remarks>This field stores the components used by the form.</remarks>
	private IContainer components = null;

	/// <summary>Clean up any resources being used.</summary>
	/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
	/// <remarks>This method is called by the runtime to release resources used by the form.</remarks>
	protected override void Dispose(bool disposing)
	{
		if (disposing && (components != null))
		{
			components.Dispose();
		}
		base.Dispose(disposing);
	}

	#region Windows Form Designer generated code

	/// <summary>Required method for Designer support - do not modify
	/// the contents of this method with the code editor.</summary>
	/// <remarks>This method is automatically generated by the Windows Forms designer and should not be modified manually.
	/// It sets up the controls and their properties for the form.</remarks>
	private void InitializeComponent()
	{
		components = new Container();
		// ── planet description labels (column 0) ──────────────────────────────
		labelMercuryDesc = new KryptonLabel();
		labelVenusDesc = new KryptonLabel();
		labelEarthDesc = new KryptonLabel();
		labelMarsDesc = new KryptonLabel();
		labelJupiterDesc = new KryptonLabel();
		labelSaturnDesc = new KryptonLabel();
		labelUranusDesc = new KryptonLabel();
		labelNeptuneDesc = new KryptonLabel();
		// ── MOID data labels (column 1) ───────────────────────────────────────
		labelMercuryData = new KryptonLabel();
		labelVenusData = new KryptonLabel();
		labelEarthData = new KryptonLabel();
		labelMarsData = new KryptonLabel();
		labelJupiterData = new KryptonLabel();
		labelSaturnData = new KryptonLabel();
		labelUranusData = new KryptonLabel();
		labelNeptuneData = new KryptonLabel();
		// ── context menu for copying a single value ───────────────────────────
		contextMenuCopyToClipboard = new ContextMenuStrip(components);
		toolStripMenuItemCopyToClipboard = new ToolStripMenuItem();
		// ── layout / toolbar / status ─────────────────────────────────────────
		toolStripContainer = new ToolStripContainer();
		kryptonStatusStrip = new KryptonStatusStrip();
		labelInformation = new ToolStripStatusLabel();
		tableLayoutPanel = new KryptonTableLayoutPanel();
		toolStripIcons = new ToolStrip();
		toolStripDropDownButtonSaveToFile = new ToolStripDropDownButton();
		// ── save-to-file context menu ─────────────────────────────────────────
		contextMenuSaveToFile = new ContextMenuStrip(components);
		toolStripMenuItemTextFiles = new ToolStripMenuItem();
		toolStripMenuItemSaveAsText = new ToolStripMenuItem();
		toolStripMenuItemSaveAsLatex = new ToolStripMenuItem();
		toolStripMenuItemSaveAsMarkdown = new ToolStripMenuItem();
		toolStripMenuItemSaveAsAsciiDoc = new ToolStripMenuItem();
		toolStripMenuItemSaveAsReStructuredText = new ToolStripMenuItem();
		toolStripMenuItemSaveAsTextile = new ToolStripMenuItem();
		toolStripMenuItemWriterDocuments = new ToolStripMenuItem();
		toolStripMenuItemSaveAsWord = new ToolStripMenuItem();
		toolStripMenuItemSaveAsOdt = new ToolStripMenuItem();
		toolStripMenuItemSaveAsRtf = new ToolStripMenuItem();
		toolStripMenuItemSaveAsAbiword = new ToolStripMenuItem();
		toolStripMenuItemSaveAsWps = new ToolStripMenuItem();
		toolStripMenuItemSpreadsheetDocuments = new ToolStripMenuItem();
		toolStripMenuItemSaveAsExcel = new ToolStripMenuItem();
		toolStripMenuItemSaveAsOds = new ToolStripMenuItem();
		toolStripMenuItemSaveAsCsv = new ToolStripMenuItem();
		toolStripMenuItemSaveAsTsv = new ToolStripMenuItem();
		toolStripMenuItemSaveAsPsv = new ToolStripMenuItem();
		toolStripMenuItemSaveAsEt = new ToolStripMenuItem();
		toolStripMenuItemXmlDocuments = new ToolStripMenuItem();
		toolStripMenuItemSaveAsHtml = new ToolStripMenuItem();
		toolStripMenuItemSaveAsXml = new ToolStripMenuItem();
		toolStripMenuItemSaveAsDocBook = new ToolStripMenuItem();
		toolStripMenuItemConfigurationFiles = new ToolStripMenuItem();
		toolStripMenuItemSaveAsJson = new ToolStripMenuItem();
		toolStripMenuItemSaveAsYaml = new ToolStripMenuItem();
		toolStripMenuItemSaveAsToml = new ToolStripMenuItem();
		toolStripMenuItemDatabaseScripts = new ToolStripMenuItem();
		toolStripMenuItemSaveAsSql = new ToolStripMenuItem();
		toolStripMenuItemSaveAsSqlite = new ToolStripMenuItem();
		toolStripMenuItemPortableDocuments = new ToolStripMenuItem();
		toolStripMenuItemSaveAsPdf = new ToolStripMenuItem();
		toolStripMenuItemSaveAsPostScript = new ToolStripMenuItem();
		toolStripMenuItemSaveAsEpub = new ToolStripMenuItem();
		toolStripMenuItemSaveAsMobi = new ToolStripMenuItem();
		toolStripMenuItemSaveAsXps = new ToolStripMenuItem();
		toolStripMenuItemSaveAsFictionBook2 = new ToolStripMenuItem();
		toolStripMenuItemSaveAsChm = new ToolStripMenuItem();
		kryptonManager = new KryptonManager(components);
		// ── suspend layouts ───────────────────────────────────────────────────
		contextMenuCopyToClipboard.SuspendLayout();
		toolStripContainer.BottomToolStripPanel.SuspendLayout();
		toolStripContainer.ContentPanel.SuspendLayout();
		toolStripContainer.TopToolStripPanel.SuspendLayout();
		toolStripContainer.SuspendLayout();
		kryptonStatusStrip.SuspendLayout();
		tableLayoutPanel.SuspendLayout();
		toolStripIcons.SuspendLayout();
		contextMenuSaveToFile.SuspendLayout();
		SuspendLayout();

		// ── labelMercuryDesc ─────────────────────────────────────────────────
		labelMercuryDesc.AccessibleDescription = "Shows the name of the planet Mercury";
		labelMercuryDesc.AccessibleName = "Mercury";
		labelMercuryDesc.AccessibleRole = AccessibleRole.StaticText;
		labelMercuryDesc.ContextMenuStrip = contextMenuCopyToClipboard;
		labelMercuryDesc.Dock = DockStyle.Fill;
		labelMercuryDesc.LabelStyle = LabelStyle.BoldPanel;
		labelMercuryDesc.Location = new Point(3, 3);
		labelMercuryDesc.Name = "labelMercuryDesc";
		labelMercuryDesc.Size = new Size(240, 24);
		labelMercuryDesc.TabIndex = 0;
		labelMercuryDesc.ToolTipValues.Description = "MOID of the minor planet relative to Mercury (AU).\r\nDouble-click or right-click to copy the value to the clipboard.";
		labelMercuryDesc.ToolTipValues.EnableToolTips = true;
		labelMercuryDesc.ToolTipValues.Heading = "MOID to Mercury (AU)";
		labelMercuryDesc.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelMercuryDesc.Values.ExtraText = "AU";
		labelMercuryDesc.Values.Text = "Mercury";
		labelMercuryDesc.Enter += Control_Enter;
		labelMercuryDesc.Leave += Control_Leave;
		labelMercuryDesc.MouseEnter += Control_Enter;
		labelMercuryDesc.MouseLeave += Control_Leave;

		// ── labelVenusDesc ────────────────────────────────────────────────────
		labelVenusDesc.AccessibleDescription = "Shows the name of the planet Venus";
		labelVenusDesc.AccessibleName = "Venus";
		labelVenusDesc.AccessibleRole = AccessibleRole.StaticText;
		labelVenusDesc.ContextMenuStrip = contextMenuCopyToClipboard;
		labelVenusDesc.Dock = DockStyle.Fill;
		labelVenusDesc.LabelStyle = LabelStyle.BoldPanel;
		labelVenusDesc.Location = new Point(3, 33);
		labelVenusDesc.Name = "labelVenusDesc";
		labelVenusDesc.Size = new Size(240, 24);
		labelVenusDesc.TabIndex = 2;
		labelVenusDesc.ToolTipValues.Description = "MOID of the minor planet relative to Venus (AU).\r\nDouble-click or right-click to copy the value to the clipboard.";
		labelVenusDesc.ToolTipValues.EnableToolTips = true;
		labelVenusDesc.ToolTipValues.Heading = "MOID to Venus (AU)";
		labelVenusDesc.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelVenusDesc.Values.ExtraText = "AU";
		labelVenusDesc.Values.Text = "Venus";
		labelVenusDesc.Enter += Control_Enter;
		labelVenusDesc.Leave += Control_Leave;
		labelVenusDesc.MouseEnter += Control_Enter;
		labelVenusDesc.MouseLeave += Control_Leave;

		// ── labelEarthDesc ────────────────────────────────────────────────────
		labelEarthDesc.AccessibleDescription = "Shows the name of the planet Earth";
		labelEarthDesc.AccessibleName = "Earth";
		labelEarthDesc.AccessibleRole = AccessibleRole.StaticText;
		labelEarthDesc.ContextMenuStrip = contextMenuCopyToClipboard;
		labelEarthDesc.Dock = DockStyle.Fill;
		labelEarthDesc.LabelStyle = LabelStyle.BoldPanel;
		labelEarthDesc.Location = new Point(3, 63);
		labelEarthDesc.Name = "labelEarthDesc";
		labelEarthDesc.Size = new Size(240, 24);
		labelEarthDesc.TabIndex = 4;
		labelEarthDesc.ToolTipValues.Description = "MOID of the minor planet relative to Earth (AU).\r\nDouble-click or right-click to copy the value to the clipboard.";
		labelEarthDesc.ToolTipValues.EnableToolTips = true;
		labelEarthDesc.ToolTipValues.Heading = "MOID to Earth (AU)";
		labelEarthDesc.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelEarthDesc.Values.ExtraText = "AU";
		labelEarthDesc.Values.Text = "Earth";
		labelEarthDesc.Enter += Control_Enter;
		labelEarthDesc.Leave += Control_Leave;
		labelEarthDesc.MouseEnter += Control_Enter;
		labelEarthDesc.MouseLeave += Control_Leave;

		// ── labelMarsDesc ─────────────────────────────────────────────────────
		labelMarsDesc.AccessibleDescription = "Shows the name of the planet Mars";
		labelMarsDesc.AccessibleName = "Mars";
		labelMarsDesc.AccessibleRole = AccessibleRole.StaticText;
		labelMarsDesc.ContextMenuStrip = contextMenuCopyToClipboard;
		labelMarsDesc.Dock = DockStyle.Fill;
		labelMarsDesc.LabelStyle = LabelStyle.BoldPanel;
		labelMarsDesc.Location = new Point(3, 93);
		labelMarsDesc.Name = "labelMarsDesc";
		labelMarsDesc.Size = new Size(240, 24);
		labelMarsDesc.TabIndex = 6;
		labelMarsDesc.ToolTipValues.Description = "MOID of the minor planet relative to Mars (AU).\r\nDouble-click or right-click to copy the value to the clipboard.";
		labelMarsDesc.ToolTipValues.EnableToolTips = true;
		labelMarsDesc.ToolTipValues.Heading = "MOID to Mars (AU)";
		labelMarsDesc.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelMarsDesc.Values.ExtraText = "AU";
		labelMarsDesc.Values.Text = "Mars";
		labelMarsDesc.Enter += Control_Enter;
		labelMarsDesc.Leave += Control_Leave;
		labelMarsDesc.MouseEnter += Control_Enter;
		labelMarsDesc.MouseLeave += Control_Leave;

		// ── labelJupiterDesc ──────────────────────────────────────────────────
		labelJupiterDesc.AccessibleDescription = "Shows the name of the planet Jupiter";
		labelJupiterDesc.AccessibleName = "Jupiter";
		labelJupiterDesc.AccessibleRole = AccessibleRole.StaticText;
		labelJupiterDesc.ContextMenuStrip = contextMenuCopyToClipboard;
		labelJupiterDesc.Dock = DockStyle.Fill;
		labelJupiterDesc.LabelStyle = LabelStyle.BoldPanel;
		labelJupiterDesc.Location = new Point(3, 123);
		labelJupiterDesc.Name = "labelJupiterDesc";
		labelJupiterDesc.Size = new Size(240, 24);
		labelJupiterDesc.TabIndex = 8;
		labelJupiterDesc.ToolTipValues.Description = "MOID of the minor planet relative to Jupiter (AU).\r\nDouble-click or right-click to copy the value to the clipboard.";
		labelJupiterDesc.ToolTipValues.EnableToolTips = true;
		labelJupiterDesc.ToolTipValues.Heading = "MOID to Jupiter (AU)";
		labelJupiterDesc.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelJupiterDesc.Values.ExtraText = "AU";
		labelJupiterDesc.Values.Text = "Jupiter";
		labelJupiterDesc.Enter += Control_Enter;
		labelJupiterDesc.Leave += Control_Leave;
		labelJupiterDesc.MouseEnter += Control_Enter;
		labelJupiterDesc.MouseLeave += Control_Leave;

		// ── labelSaturnDesc ───────────────────────────────────────────────────
		labelSaturnDesc.AccessibleDescription = "Shows the name of the planet Saturn";
		labelSaturnDesc.AccessibleName = "Saturn";
		labelSaturnDesc.AccessibleRole = AccessibleRole.StaticText;
		labelSaturnDesc.ContextMenuStrip = contextMenuCopyToClipboard;
		labelSaturnDesc.Dock = DockStyle.Fill;
		labelSaturnDesc.LabelStyle = LabelStyle.BoldPanel;
		labelSaturnDesc.Location = new Point(3, 153);
		labelSaturnDesc.Name = "labelSaturnDesc";
		labelSaturnDesc.Size = new Size(240, 24);
		labelSaturnDesc.TabIndex = 10;
		labelSaturnDesc.ToolTipValues.Description = "MOID of the minor planet relative to Saturn (AU).\r\nDouble-click or right-click to copy the value to the clipboard.";
		labelSaturnDesc.ToolTipValues.EnableToolTips = true;
		labelSaturnDesc.ToolTipValues.Heading = "MOID to Saturn (AU)";
		labelSaturnDesc.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelSaturnDesc.Values.ExtraText = "AU";
		labelSaturnDesc.Values.Text = "Saturn";
		labelSaturnDesc.Enter += Control_Enter;
		labelSaturnDesc.Leave += Control_Leave;
		labelSaturnDesc.MouseEnter += Control_Enter;
		labelSaturnDesc.MouseLeave += Control_Leave;

		// ── labelUranusDesc ───────────────────────────────────────────────────
		labelUranusDesc.AccessibleDescription = "Shows the name of the planet Uranus";
		labelUranusDesc.AccessibleName = "Uranus";
		labelUranusDesc.AccessibleRole = AccessibleRole.StaticText;
		labelUranusDesc.ContextMenuStrip = contextMenuCopyToClipboard;
		labelUranusDesc.Dock = DockStyle.Fill;
		labelUranusDesc.LabelStyle = LabelStyle.BoldPanel;
		labelUranusDesc.Location = new Point(3, 183);
		labelUranusDesc.Name = "labelUranusDesc";
		labelUranusDesc.Size = new Size(240, 24);
		labelUranusDesc.TabIndex = 12;
		labelUranusDesc.ToolTipValues.Description = "MOID of the minor planet relative to Uranus (AU).\r\nDouble-click or right-click to copy the value to the clipboard.";
		labelUranusDesc.ToolTipValues.EnableToolTips = true;
		labelUranusDesc.ToolTipValues.Heading = "MOID to Uranus (AU)";
		labelUranusDesc.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelUranusDesc.Values.ExtraText = "AU";
		labelUranusDesc.Values.Text = "Uranus";
		labelUranusDesc.Enter += Control_Enter;
		labelUranusDesc.Leave += Control_Leave;
		labelUranusDesc.MouseEnter += Control_Enter;
		labelUranusDesc.MouseLeave += Control_Leave;

		// ── labelNeptuneDesc ──────────────────────────────────────────────────
		labelNeptuneDesc.AccessibleDescription = "Shows the name of the planet Neptune";
		labelNeptuneDesc.AccessibleName = "Neptune";
		labelNeptuneDesc.AccessibleRole = AccessibleRole.StaticText;
		labelNeptuneDesc.ContextMenuStrip = contextMenuCopyToClipboard;
		labelNeptuneDesc.Dock = DockStyle.Fill;
		labelNeptuneDesc.LabelStyle = LabelStyle.BoldPanel;
		labelNeptuneDesc.Location = new Point(3, 213);
		labelNeptuneDesc.Name = "labelNeptuneDesc";
		labelNeptuneDesc.Size = new Size(240, 24);
		labelNeptuneDesc.TabIndex = 14;
		labelNeptuneDesc.ToolTipValues.Description = "MOID of the minor planet relative to Neptune (AU).\r\nDouble-click or right-click to copy the value to the clipboard.";
		labelNeptuneDesc.ToolTipValues.EnableToolTips = true;
		labelNeptuneDesc.ToolTipValues.Heading = "MOID to Neptune (AU)";
		labelNeptuneDesc.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelNeptuneDesc.Values.ExtraText = "AU";
		labelNeptuneDesc.Values.Text = "Neptune";
		labelNeptuneDesc.Enter += Control_Enter;
		labelNeptuneDesc.Leave += Control_Leave;
		labelNeptuneDesc.MouseEnter += Control_Enter;
		labelNeptuneDesc.MouseLeave += Control_Leave;

		// ── labelMercuryData ──────────────────────────────────────────────────
		labelMercuryData.AccessibleDescription = "Shows the MOID relative to Mercury in AU";
		labelMercuryData.AccessibleName = "MOID to Mercury (AU)";
		labelMercuryData.AccessibleRole = AccessibleRole.StaticText;
		labelMercuryData.ContextMenuStrip = contextMenuCopyToClipboard;
		labelMercuryData.Dock = DockStyle.Fill;
		labelMercuryData.Location = new Point(249, 3);
		labelMercuryData.Name = "labelMercuryData";
		labelMercuryData.Size = new Size(242, 24);
		labelMercuryData.TabIndex = 1;
		labelMercuryData.ToolTipValues.Description = "Shows the MOID relative to Mercury in AU.\r\nDouble-click or right-click to copy the value to the clipboard.";
		labelMercuryData.ToolTipValues.EnableToolTips = true;
		labelMercuryData.ToolTipValues.Heading = "MOID to Mercury (AU)";
		labelMercuryData.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelMercuryData.Values.Text = "..................";
		labelMercuryData.DoubleClick += CopyToClipboard_DoubleClick;
		labelMercuryData.Enter += Control_Enter;
		labelMercuryData.Leave += Control_Leave;
		labelMercuryData.MouseDown += Control_MouseDown;
		labelMercuryData.MouseEnter += Control_Enter;
		labelMercuryData.MouseLeave += Control_Leave;

		// ── labelVenusData ────────────────────────────────────────────────────
		labelVenusData.AccessibleDescription = "Shows the MOID relative to Venus in AU";
		labelVenusData.AccessibleName = "MOID to Venus (AU)";
		labelVenusData.AccessibleRole = AccessibleRole.StaticText;
		labelVenusData.ContextMenuStrip = contextMenuCopyToClipboard;
		labelVenusData.Dock = DockStyle.Fill;
		labelVenusData.Location = new Point(249, 33);
		labelVenusData.Name = "labelVenusData";
		labelVenusData.Size = new Size(242, 24);
		labelVenusData.TabIndex = 3;
		labelVenusData.ToolTipValues.Description = "Shows the MOID relative to Venus in AU.\r\nDouble-click or right-click to copy the value to the clipboard.";
		labelVenusData.ToolTipValues.EnableToolTips = true;
		labelVenusData.ToolTipValues.Heading = "MOID to Venus (AU)";
		labelVenusData.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelVenusData.Values.Text = "..................";
		labelVenusData.DoubleClick += CopyToClipboard_DoubleClick;
		labelVenusData.Enter += Control_Enter;
		labelVenusData.Leave += Control_Leave;
		labelVenusData.MouseDown += Control_MouseDown;
		labelVenusData.MouseEnter += Control_Enter;
		labelVenusData.MouseLeave += Control_Leave;

		// ── labelEarthData ────────────────────────────────────────────────────
		labelEarthData.AccessibleDescription = "Shows the MOID relative to Earth in AU";
		labelEarthData.AccessibleName = "MOID to Earth (AU)";
		labelEarthData.AccessibleRole = AccessibleRole.StaticText;
		labelEarthData.ContextMenuStrip = contextMenuCopyToClipboard;
		labelEarthData.Dock = DockStyle.Fill;
		labelEarthData.Location = new Point(249, 63);
		labelEarthData.Name = "labelEarthData";
		labelEarthData.Size = new Size(242, 24);
		labelEarthData.TabIndex = 5;
		labelEarthData.ToolTipValues.Description = "Shows the MOID relative to Earth in AU.\r\nDouble-click or right-click to copy the value to the clipboard.";
		labelEarthData.ToolTipValues.EnableToolTips = true;
		labelEarthData.ToolTipValues.Heading = "MOID to Earth (AU)";
		labelEarthData.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelEarthData.Values.Text = "..................";
		labelEarthData.DoubleClick += CopyToClipboard_DoubleClick;
		labelEarthData.Enter += Control_Enter;
		labelEarthData.Leave += Control_Leave;
		labelEarthData.MouseDown += Control_MouseDown;
		labelEarthData.MouseEnter += Control_Enter;
		labelEarthData.MouseLeave += Control_Leave;

		// ── labelMarsData ─────────────────────────────────────────────────────
		labelMarsData.AccessibleDescription = "Shows the MOID relative to Mars in AU";
		labelMarsData.AccessibleName = "MOID to Mars (AU)";
		labelMarsData.AccessibleRole = AccessibleRole.StaticText;
		labelMarsData.ContextMenuStrip = contextMenuCopyToClipboard;
		labelMarsData.Dock = DockStyle.Fill;
		labelMarsData.Location = new Point(249, 93);
		labelMarsData.Name = "labelMarsData";
		labelMarsData.Size = new Size(242, 24);
		labelMarsData.TabIndex = 7;
		labelMarsData.ToolTipValues.Description = "Shows the MOID relative to Mars in AU.\r\nDouble-click or right-click to copy the value to the clipboard.";
		labelMarsData.ToolTipValues.EnableToolTips = true;
		labelMarsData.ToolTipValues.Heading = "MOID to Mars (AU)";
		labelMarsData.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelMarsData.Values.Text = "..................";
		labelMarsData.DoubleClick += CopyToClipboard_DoubleClick;
		labelMarsData.Enter += Control_Enter;
		labelMarsData.Leave += Control_Leave;
		labelMarsData.MouseDown += Control_MouseDown;
		labelMarsData.MouseEnter += Control_Enter;
		labelMarsData.MouseLeave += Control_Leave;

		// ── labelJupiterData ──────────────────────────────────────────────────
		labelJupiterData.AccessibleDescription = "Shows the MOID relative to Jupiter in AU";
		labelJupiterData.AccessibleName = "MOID to Jupiter (AU)";
		labelJupiterData.AccessibleRole = AccessibleRole.StaticText;
		labelJupiterData.ContextMenuStrip = contextMenuCopyToClipboard;
		labelJupiterData.Dock = DockStyle.Fill;
		labelJupiterData.Location = new Point(249, 123);
		labelJupiterData.Name = "labelJupiterData";
		labelJupiterData.Size = new Size(242, 24);
		labelJupiterData.TabIndex = 9;
		labelJupiterData.ToolTipValues.Description = "Shows the MOID relative to Jupiter in AU.\r\nDouble-click or right-click to copy the value to the clipboard.";
		labelJupiterData.ToolTipValues.EnableToolTips = true;
		labelJupiterData.ToolTipValues.Heading = "MOID to Jupiter (AU)";
		labelJupiterData.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelJupiterData.Values.Text = "..................";
		labelJupiterData.DoubleClick += CopyToClipboard_DoubleClick;
		labelJupiterData.Enter += Control_Enter;
		labelJupiterData.Leave += Control_Leave;
		labelJupiterData.MouseDown += Control_MouseDown;
		labelJupiterData.MouseEnter += Control_Enter;
		labelJupiterData.MouseLeave += Control_Leave;

		// ── labelSaturnData ───────────────────────────────────────────────────
		labelSaturnData.AccessibleDescription = "Shows the MOID relative to Saturn in AU";
		labelSaturnData.AccessibleName = "MOID to Saturn (AU)";
		labelSaturnData.AccessibleRole = AccessibleRole.StaticText;
		labelSaturnData.ContextMenuStrip = contextMenuCopyToClipboard;
		labelSaturnData.Dock = DockStyle.Fill;
		labelSaturnData.Location = new Point(249, 153);
		labelSaturnData.Name = "labelSaturnData";
		labelSaturnData.Size = new Size(242, 24);
		labelSaturnData.TabIndex = 11;
		labelSaturnData.ToolTipValues.Description = "Shows the MOID relative to Saturn in AU.\r\nDouble-click or right-click to copy the value to the clipboard.";
		labelSaturnData.ToolTipValues.EnableToolTips = true;
		labelSaturnData.ToolTipValues.Heading = "MOID to Saturn (AU)";
		labelSaturnData.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelSaturnData.Values.Text = "..................";
		labelSaturnData.DoubleClick += CopyToClipboard_DoubleClick;
		labelSaturnData.Enter += Control_Enter;
		labelSaturnData.Leave += Control_Leave;
		labelSaturnData.MouseDown += Control_MouseDown;
		labelSaturnData.MouseEnter += Control_Enter;
		labelSaturnData.MouseLeave += Control_Leave;

		// ── labelUranusData ───────────────────────────────────────────────────
		labelUranusData.AccessibleDescription = "Shows the MOID relative to Uranus in AU";
		labelUranusData.AccessibleName = "MOID to Uranus (AU)";
		labelUranusData.AccessibleRole = AccessibleRole.StaticText;
		labelUranusData.ContextMenuStrip = contextMenuCopyToClipboard;
		labelUranusData.Dock = DockStyle.Fill;
		labelUranusData.Location = new Point(249, 183);
		labelUranusData.Name = "labelUranusData";
		labelUranusData.Size = new Size(242, 24);
		labelUranusData.TabIndex = 13;
		labelUranusData.ToolTipValues.Description = "Shows the MOID relative to Uranus in AU.\r\nDouble-click or right-click to copy the value to the clipboard.";
		labelUranusData.ToolTipValues.EnableToolTips = true;
		labelUranusData.ToolTipValues.Heading = "MOID to Uranus (AU)";
		labelUranusData.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelUranusData.Values.Text = "..................";
		labelUranusData.DoubleClick += CopyToClipboard_DoubleClick;
		labelUranusData.Enter += Control_Enter;
		labelUranusData.Leave += Control_Leave;
		labelUranusData.MouseDown += Control_MouseDown;
		labelUranusData.MouseEnter += Control_Enter;
		labelUranusData.MouseLeave += Control_Leave;

		// ── labelNeptuneData ──────────────────────────────────────────────────
		labelNeptuneData.AccessibleDescription = "Shows the MOID relative to Neptune in AU";
		labelNeptuneData.AccessibleName = "MOID to Neptune (AU)";
		labelNeptuneData.AccessibleRole = AccessibleRole.StaticText;
		labelNeptuneData.ContextMenuStrip = contextMenuCopyToClipboard;
		labelNeptuneData.Dock = DockStyle.Fill;
		labelNeptuneData.Location = new Point(249, 213);
		labelNeptuneData.Name = "labelNeptuneData";
		labelNeptuneData.Size = new Size(242, 24);
		labelNeptuneData.TabIndex = 15;
		labelNeptuneData.ToolTipValues.Description = "Shows the MOID relative to Neptune in AU.\r\nDouble-click or right-click to copy the value to the clipboard.";
		labelNeptuneData.ToolTipValues.EnableToolTips = true;
		labelNeptuneData.ToolTipValues.Heading = "MOID to Neptune (AU)";
		labelNeptuneData.ToolTipValues.Image = FatcowIcons16px.fatcow_information_16px;
		labelNeptuneData.Values.Text = "..................";
		labelNeptuneData.DoubleClick += CopyToClipboard_DoubleClick;
		labelNeptuneData.Enter += Control_Enter;
		labelNeptuneData.Leave += Control_Leave;
		labelNeptuneData.MouseDown += Control_MouseDown;
		labelNeptuneData.MouseEnter += Control_Enter;
		labelNeptuneData.MouseLeave += Control_Leave;

		// ── contextMenuCopyToClipboard ────────────────────────────────────────
		contextMenuCopyToClipboard.AccessibleDescription = "Shows the context menu for copying the MOID value to the clipboard";
		contextMenuCopyToClipboard.AccessibleName = "Context menu for copying to the clipboard";
		contextMenuCopyToClipboard.AccessibleRole = AccessibleRole.MenuPopup;
		contextMenuCopyToClipboard.AllowClickThrough = true;
		contextMenuCopyToClipboard.Font = new Font("Segoe UI", 9F);
		contextMenuCopyToClipboard.Items.AddRange(new ToolStripItem[] { toolStripMenuItemCopyToClipboard });
		contextMenuCopyToClipboard.Name = "contextMenuCopyToClipboard";
		contextMenuCopyToClipboard.Size = new Size(214, 26);
		contextMenuCopyToClipboard.TabStop = true;
		contextMenuCopyToClipboard.Text = "Copy to clipboard";
		contextMenuCopyToClipboard.MouseEnter += Control_Enter;
		contextMenuCopyToClipboard.MouseLeave += Control_Leave;

		// ── toolStripMenuItemCopyToClipboard ──────────────────────────────────
		toolStripMenuItemCopyToClipboard.AccessibleDescription = "Copies the MOID value to the clipboard";
		toolStripMenuItemCopyToClipboard.AccessibleName = "Copy to clipboard";
		toolStripMenuItemCopyToClipboard.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemCopyToClipboard.AutoToolTip = true;
		toolStripMenuItemCopyToClipboard.Image = FatcowIcons16px.fatcow_page_copy_16px;
		toolStripMenuItemCopyToClipboard.Name = "toolStripMenuItemCopyToClipboard";
		toolStripMenuItemCopyToClipboard.ShortcutKeyDisplayString = "Strg+C";
		toolStripMenuItemCopyToClipboard.ShortcutKeys = Keys.Control | Keys.C;
		toolStripMenuItemCopyToClipboard.Size = new Size(213, 22);
		toolStripMenuItemCopyToClipboard.Text = "&Copy to clipboard";
		toolStripMenuItemCopyToClipboard.Click += CopyToClipboard_DoubleClick;
		toolStripMenuItemCopyToClipboard.MouseEnter += Control_Enter;
		toolStripMenuItemCopyToClipboard.MouseLeave += Control_Leave;

		// ── toolStripContainer ────────────────────────────────────────────────
		toolStripContainer.AccessibleDescription = "Container to arrange the toolbars";
		toolStripContainer.AccessibleName = "Container to arrange the toolbars";
		toolStripContainer.AccessibleRole = AccessibleRole.Grouping;
		// Bottom (status bar)
		toolStripContainer.BottomToolStripPanel.Controls.Add(kryptonStatusStrip);
		// Content panel (table)
		toolStripContainer.ContentPanel.Controls.Add(tableLayoutPanel);
		toolStripContainer.ContentPanel.Margin = new Padding(4, 3, 4, 3);
		toolStripContainer.ContentPanel.Size = new Size(494, 243);
		toolStripContainer.Dock = DockStyle.Fill;
		toolStripContainer.Location = new Point(0, 0);
		toolStripContainer.Name = "toolStripContainer";
		toolStripContainer.Size = new Size(494, 290);
		toolStripContainer.TabIndex = 0;
		toolStripContainer.Text = "toolStripContainer";
		// Top (toolbar)
		toolStripContainer.TopToolStripPanel.Controls.Add(toolStripIcons);
		toolStripContainer.MouseEnter += Control_Enter;
		toolStripContainer.MouseLeave += Control_Leave;

		// ── kryptonStatusStrip ────────────────────────────────────────────────
		kryptonStatusStrip.AccessibleDescription = "Shows some information";
		kryptonStatusStrip.AccessibleName = "Status bar with some information";
		kryptonStatusStrip.AccessibleRole = AccessibleRole.StatusBar;
		kryptonStatusStrip.AllowClickThrough = true;
		kryptonStatusStrip.AllowItemReorder = true;
		kryptonStatusStrip.Dock = DockStyle.None;
		kryptonStatusStrip.Font = new Font("Segoe UI", 9F);
		kryptonStatusStrip.Items.AddRange(new ToolStripItem[] { labelInformation });
		kryptonStatusStrip.Location = new Point(0, 0);
		kryptonStatusStrip.Name = "kryptonStatusStrip";
		kryptonStatusStrip.ProgressBars = null;
		kryptonStatusStrip.RenderMode = ToolStripRenderMode.ManagerRenderMode;
		kryptonStatusStrip.ShowItemToolTips = true;
		kryptonStatusStrip.Size = new Size(494, 22);
		kryptonStatusStrip.SizingGrip = false;
		kryptonStatusStrip.TabIndex = 1;
		kryptonStatusStrip.TabStop = true;
		kryptonStatusStrip.Text = "Status bar";
		kryptonStatusStrip.MouseEnter += Control_Enter;
		kryptonStatusStrip.MouseLeave += Control_Leave;

		// ── labelInformation ──────────────────────────────────────────────────
		labelInformation.AccessibleDescription = "Shows some information";
		labelInformation.AccessibleName = "Show some information";
		labelInformation.AccessibleRole = AccessibleRole.StaticText;
		labelInformation.AutoToolTip = true;
		labelInformation.Image = FatcowIcons16px.fatcow_lightbulb_16px;
		labelInformation.Name = "labelInformation";
		labelInformation.Size = new Size(144, 17);
		labelInformation.Text = "some information here";
		labelInformation.ToolTipText = "Shows some information";
		labelInformation.MouseEnter += Control_Enter;
		labelInformation.MouseLeave += Control_Leave;

		// ── tableLayoutPanel ──────────────────────────────────────────────────
		tableLayoutPanel.AccessibleDescription = "Table showing MOID values per planet";
		tableLayoutPanel.AccessibleName = "MOID table";
		tableLayoutPanel.AccessibleRole = AccessibleRole.Grouping;
		tableLayoutPanel.ColumnCount = 2;
		tableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
		tableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
		// Row 0: Mercury
		tableLayoutPanel.Controls.Add(labelMercuryDesc, 0, 0);
		tableLayoutPanel.Controls.Add(labelMercuryData, 1, 0);
		// Row 1: Venus
		tableLayoutPanel.Controls.Add(labelVenusDesc, 0, 1);
		tableLayoutPanel.Controls.Add(labelVenusData, 1, 1);
		// Row 2: Earth
		tableLayoutPanel.Controls.Add(labelEarthDesc, 0, 2);
		tableLayoutPanel.Controls.Add(labelEarthData, 1, 2);
		// Row 3: Mars
		tableLayoutPanel.Controls.Add(labelMarsDesc, 0, 3);
		tableLayoutPanel.Controls.Add(labelMarsData, 1, 3);
		// Row 4: Jupiter
		tableLayoutPanel.Controls.Add(labelJupiterDesc, 0, 4);
		tableLayoutPanel.Controls.Add(labelJupiterData, 1, 4);
		// Row 5: Saturn
		tableLayoutPanel.Controls.Add(labelSaturnDesc, 0, 5);
		tableLayoutPanel.Controls.Add(labelSaturnData, 1, 5);
		// Row 6: Uranus
		tableLayoutPanel.Controls.Add(labelUranusDesc, 0, 6);
		tableLayoutPanel.Controls.Add(labelUranusData, 1, 6);
		// Row 7: Neptune
		tableLayoutPanel.Controls.Add(labelNeptuneDesc, 0, 7);
		tableLayoutPanel.Controls.Add(labelNeptuneData, 1, 7);
		tableLayoutPanel.Dock = DockStyle.Fill;
		tableLayoutPanel.Location = new Point(0, 0);
		tableLayoutPanel.Name = "tableLayoutPanel";
		tableLayoutPanel.PanelBackStyle = PaletteBackStyle.FormMain;
		tableLayoutPanel.RowCount = 8;
		tableLayoutPanel.RowStyles.Add(new RowStyle());
		tableLayoutPanel.RowStyles.Add(new RowStyle());
		tableLayoutPanel.RowStyles.Add(new RowStyle());
		tableLayoutPanel.RowStyles.Add(new RowStyle());
		tableLayoutPanel.RowStyles.Add(new RowStyle());
		tableLayoutPanel.RowStyles.Add(new RowStyle());
		tableLayoutPanel.RowStyles.Add(new RowStyle());
		tableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
		tableLayoutPanel.Size = new Size(494, 243);
		tableLayoutPanel.TabIndex = 0;
		tableLayoutPanel.TabStop = true;

		// ── toolStripIcons ────────────────────────────────────────────────────
		toolStripIcons.AccessibleDescription = "Toolbar for exporting data";
		toolStripIcons.AccessibleName = "Toolbar for exporting data";
		toolStripIcons.AccessibleRole = AccessibleRole.ToolBar;
		toolStripIcons.AllowClickThrough = true;
		toolStripIcons.AllowItemReorder = true;
		toolStripIcons.BackColor = Color.Transparent;
		toolStripIcons.Dock = DockStyle.None;
		toolStripIcons.Font = new Font("Segoe UI", 9F);
		toolStripIcons.Items.AddRange(new ToolStripItem[] { toolStripDropDownButtonSaveToFile });
		toolStripIcons.Location = new Point(0, 0);
		toolStripIcons.Name = "toolStripIcons";
		toolStripIcons.Size = new Size(494, 25);
		toolStripIcons.Stretch = true;
		toolStripIcons.TabIndex = 0;
		toolStripIcons.TabStop = true;
		toolStripIcons.Text = "Toolbar for exporting data";
		toolStripIcons.Enter += Control_Enter;
		toolStripIcons.Leave += Control_Leave;
		toolStripIcons.MouseEnter += Control_Enter;
		toolStripIcons.MouseLeave += Control_Leave;

		// ── toolStripDropDownButtonSaveToFile ─────────────────────────────────
		toolStripDropDownButtonSaveToFile.AccessibleDescription = "Saves information to file";
		toolStripDropDownButtonSaveToFile.AccessibleName = "Save to file";
		toolStripDropDownButtonSaveToFile.AccessibleRole = AccessibleRole.ButtonDropDown;
		toolStripDropDownButtonSaveToFile.DropDown = contextMenuSaveToFile;
		toolStripDropDownButtonSaveToFile.Image = FatcowIcons16px.fatcow_diskette_16px;
		toolStripDropDownButtonSaveToFile.ImageTransparentColor = Color.Magenta;
		toolStripDropDownButtonSaveToFile.Name = "toolStripDropDownButtonSaveToFile";
		toolStripDropDownButtonSaveToFile.Size = new Size(93, 22);
		toolStripDropDownButtonSaveToFile.Text = "&Save to file";
		toolStripDropDownButtonSaveToFile.MouseEnter += Control_Enter;
		toolStripDropDownButtonSaveToFile.MouseLeave += Control_Leave;

		// ── contextMenuSaveToFile ─────────────────────────────────────────────
		contextMenuSaveToFile.AccessibleDescription = "Save the MOID data as file";
		contextMenuSaveToFile.AccessibleName = "Save MOID data";
		contextMenuSaveToFile.AccessibleRole = AccessibleRole.MenuPopup;
		contextMenuSaveToFile.AllowClickThrough = true;
		contextMenuSaveToFile.Font = new Font("Segoe UI", 9F);
		contextMenuSaveToFile.Items.AddRange(new ToolStripItem[]
		{
			toolStripMenuItemTextFiles,
			toolStripMenuItemWriterDocuments,
			toolStripMenuItemSpreadsheetDocuments,
			toolStripMenuItemXmlDocuments,
			toolStripMenuItemConfigurationFiles,
			toolStripMenuItemDatabaseScripts,
			toolStripMenuItemPortableDocuments
		});
		contextMenuSaveToFile.Name = "contextMenuSaveToFile";
		contextMenuSaveToFile.Size = new Size(202, 158);
		contextMenuSaveToFile.TabStop = true;
		contextMenuSaveToFile.Text = "&Save MOID data";
		contextMenuSaveToFile.MouseEnter += Control_Enter;
		contextMenuSaveToFile.MouseLeave += Control_Leave;

		// ── Text files sub-menu ───────────────────────────────────────────────
		toolStripMenuItemTextFiles.AccessibleDescription = "Saves the data as text file";
		toolStripMenuItemTextFiles.AccessibleName = "Save as text file";
		toolStripMenuItemTextFiles.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemTextFiles.AutoToolTip = true;
		toolStripMenuItemTextFiles.DropDownItems.AddRange(new ToolStripItem[]
		{
			toolStripMenuItemSaveAsText, toolStripMenuItemSaveAsLatex,
			toolStripMenuItemSaveAsMarkdown, toolStripMenuItemSaveAsAsciiDoc,
			toolStripMenuItemSaveAsReStructuredText, toolStripMenuItemSaveAsTextile
		});
		toolStripMenuItemTextFiles.Image = FatcowIcons16px.fatcow_file_extension_txt_16px;
		toolStripMenuItemTextFiles.Name = "toolStripMenuItemTextFiles";
		toolStripMenuItemTextFiles.Size = new Size(201, 22);
		toolStripMenuItemTextFiles.Text = "&Text files";
		toolStripMenuItemTextFiles.MouseEnter += Control_Enter;
		toolStripMenuItemTextFiles.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsText.AccessibleDescription = "Saves the data as text file";
		toolStripMenuItemSaveAsText.AccessibleName = "Save as text";
		toolStripMenuItemSaveAsText.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsText.AutoToolTip = true;
		toolStripMenuItemSaveAsText.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsText.Name = "toolStripMenuItemSaveAsText";
		toolStripMenuItemSaveAsText.Size = new Size(201, 22);
		toolStripMenuItemSaveAsText.Text = "Save as &text";
		toolStripMenuItemSaveAsText.Click += ToolStripMenuItemSaveAsText_Click;
		toolStripMenuItemSaveAsText.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsText.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsLatex.AccessibleDescription = "Saves the data as LaTeX file";
		toolStripMenuItemSaveAsLatex.AccessibleName = "Save as LaTeX";
		toolStripMenuItemSaveAsLatex.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsLatex.AutoToolTip = true;
		toolStripMenuItemSaveAsLatex.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsLatex.Name = "toolStripMenuItemSaveAsLatex";
		toolStripMenuItemSaveAsLatex.Size = new Size(201, 22);
		toolStripMenuItemSaveAsLatex.Text = "Save as &LaTeX";
		toolStripMenuItemSaveAsLatex.Click += ToolStripMenuItemSaveAsLatex_Click;
		toolStripMenuItemSaveAsLatex.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsLatex.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsMarkdown.AccessibleDescription = "Saves the data as Markdown file";
		toolStripMenuItemSaveAsMarkdown.AccessibleName = "Save as Markdown";
		toolStripMenuItemSaveAsMarkdown.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsMarkdown.AutoToolTip = true;
		toolStripMenuItemSaveAsMarkdown.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsMarkdown.Name = "toolStripMenuItemSaveAsMarkdown";
		toolStripMenuItemSaveAsMarkdown.Size = new Size(201, 22);
		toolStripMenuItemSaveAsMarkdown.Text = "Save as &Markdown";
		toolStripMenuItemSaveAsMarkdown.Click += ToolStripMenuItemSaveAsMarkdown_Click;
		toolStripMenuItemSaveAsMarkdown.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsMarkdown.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsAsciiDoc.AccessibleDescription = "Saves the data as AsciiDoc file";
		toolStripMenuItemSaveAsAsciiDoc.AccessibleName = "Save as AsciiDoc";
		toolStripMenuItemSaveAsAsciiDoc.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsAsciiDoc.AutoToolTip = true;
		toolStripMenuItemSaveAsAsciiDoc.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsAsciiDoc.Name = "toolStripMenuItemSaveAsAsciiDoc";
		toolStripMenuItemSaveAsAsciiDoc.Size = new Size(201, 22);
		toolStripMenuItemSaveAsAsciiDoc.Text = "Save as &AsciiDoc";
		toolStripMenuItemSaveAsAsciiDoc.Click += ToolStripMenuItemSaveAsAsciiDoc_Click;
		toolStripMenuItemSaveAsAsciiDoc.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsAsciiDoc.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsReStructuredText.AccessibleDescription = "Saves the data as reStructuredText file";
		toolStripMenuItemSaveAsReStructuredText.AccessibleName = "Save as reStructuredText";
		toolStripMenuItemSaveAsReStructuredText.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsReStructuredText.AutoToolTip = true;
		toolStripMenuItemSaveAsReStructuredText.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsReStructuredText.Name = "toolStripMenuItemSaveAsReStructuredText";
		toolStripMenuItemSaveAsReStructuredText.Size = new Size(201, 22);
		toolStripMenuItemSaveAsReStructuredText.Text = "Save as &reStructuredText";
		toolStripMenuItemSaveAsReStructuredText.Click += ToolStripMenuItemSaveAsReStructuredText_Click;
		toolStripMenuItemSaveAsReStructuredText.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsReStructuredText.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsTextile.AccessibleDescription = "Saves the data as Textile file";
		toolStripMenuItemSaveAsTextile.AccessibleName = "Save as Textile";
		toolStripMenuItemSaveAsTextile.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsTextile.AutoToolTip = true;
		toolStripMenuItemSaveAsTextile.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsTextile.Name = "toolStripMenuItemSaveAsTextile";
		toolStripMenuItemSaveAsTextile.Size = new Size(201, 22);
		toolStripMenuItemSaveAsTextile.Text = "Save as Te&xtile";
		toolStripMenuItemSaveAsTextile.Click += ToolStripMenuItemSaveAsTextile_Click;
		toolStripMenuItemSaveAsTextile.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsTextile.MouseLeave += Control_Leave;

		// ── Writer documents sub-menu ─────────────────────────────────────────
		toolStripMenuItemWriterDocuments.AccessibleDescription = "Saves the data as writer document";
		toolStripMenuItemWriterDocuments.AccessibleName = "Save as writer document";
		toolStripMenuItemWriterDocuments.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemWriterDocuments.AutoToolTip = true;
		toolStripMenuItemWriterDocuments.DropDownItems.AddRange(new ToolStripItem[]
		{
			toolStripMenuItemSaveAsWord, toolStripMenuItemSaveAsOdt,
			toolStripMenuItemSaveAsRtf, toolStripMenuItemSaveAsAbiword, toolStripMenuItemSaveAsWps
		});
		toolStripMenuItemWriterDocuments.Image = FatcowIcons16px.fatcow_file_extension_doc_16px;
		toolStripMenuItemWriterDocuments.Name = "toolStripMenuItemWriterDocuments";
		toolStripMenuItemWriterDocuments.Size = new Size(201, 22);
		toolStripMenuItemWriterDocuments.Text = "&Writer documents";
		toolStripMenuItemWriterDocuments.MouseEnter += Control_Enter;
		toolStripMenuItemWriterDocuments.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsWord.AccessibleDescription = "Saves the data as Word file";
		toolStripMenuItemSaveAsWord.AccessibleName = "Save as Word";
		toolStripMenuItemSaveAsWord.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsWord.AutoToolTip = true;
		toolStripMenuItemSaveAsWord.Image = FatcowIcons16px.fatcow_page_white_word_16px;
		toolStripMenuItemSaveAsWord.Name = "toolStripMenuItemSaveAsWord";
		toolStripMenuItemSaveAsWord.Size = new Size(257, 22);
		toolStripMenuItemSaveAsWord.Text = "Save as &Word Text (DOCX)";
		toolStripMenuItemSaveAsWord.Click += ToolStripMenuItemSaveAsWord_Click;
		toolStripMenuItemSaveAsWord.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsWord.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsOdt.AccessibleDescription = "Saves the data as ODT file";
		toolStripMenuItemSaveAsOdt.AccessibleName = "Save as ODT";
		toolStripMenuItemSaveAsOdt.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsOdt.AutoToolTip = true;
		toolStripMenuItemSaveAsOdt.Image = FatcowIcons16px.fatcow_page_white_word_16px;
		toolStripMenuItemSaveAsOdt.Name = "toolStripMenuItemSaveAsOdt";
		toolStripMenuItemSaveAsOdt.Size = new Size(257, 22);
		toolStripMenuItemSaveAsOdt.Text = "Save as &OpenDocument Text (ODT)";
		toolStripMenuItemSaveAsOdt.Click += ToolStripMenuItemSaveAsOdt_Click;
		toolStripMenuItemSaveAsOdt.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsOdt.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsRtf.AccessibleDescription = "Saves the data as RTF file";
		toolStripMenuItemSaveAsRtf.AccessibleName = "Save as RTF";
		toolStripMenuItemSaveAsRtf.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsRtf.AutoToolTip = true;
		toolStripMenuItemSaveAsRtf.Image = FatcowIcons16px.fatcow_page_white_word_16px;
		toolStripMenuItemSaveAsRtf.Name = "toolStripMenuItemSaveAsRtf";
		toolStripMenuItemSaveAsRtf.Size = new Size(257, 22);
		toolStripMenuItemSaveAsRtf.Text = "Save as &Rich Text Format (RTF)";
		toolStripMenuItemSaveAsRtf.Click += ToolStripMenuItemSaveAsRtf_Click;
		toolStripMenuItemSaveAsRtf.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsRtf.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsAbiword.AccessibleDescription = "Saves the data as Abiword file";
		toolStripMenuItemSaveAsAbiword.AccessibleName = "Save as Abiword";
		toolStripMenuItemSaveAsAbiword.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsAbiword.AutoToolTip = true;
		toolStripMenuItemSaveAsAbiword.Image = FatcowIcons16px.fatcow_page_white_word_16px;
		toolStripMenuItemSaveAsAbiword.Name = "toolStripMenuItemSaveAsAbiword";
		toolStripMenuItemSaveAsAbiword.Size = new Size(257, 22);
		toolStripMenuItemSaveAsAbiword.Text = "Save as &Abiword file (ABW)";
		toolStripMenuItemSaveAsAbiword.Click += ToolStripMenuItemSaveAsAbiword_Click;
		toolStripMenuItemSaveAsAbiword.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsAbiword.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsWps.AccessibleDescription = "Saves the data as WPS file";
		toolStripMenuItemSaveAsWps.AccessibleName = "Save as WPS";
		toolStripMenuItemSaveAsWps.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsWps.AutoToolTip = true;
		toolStripMenuItemSaveAsWps.Image = FatcowIcons16px.fatcow_page_white_word_16px;
		toolStripMenuItemSaveAsWps.Name = "toolStripMenuItemSaveAsWps";
		toolStripMenuItemSaveAsWps.Size = new Size(257, 22);
		toolStripMenuItemSaveAsWps.Text = "Save as W&PS Office Writer (WPS)";
		toolStripMenuItemSaveAsWps.Click += ToolStripMenuItemSaveAsWps_Click;
		toolStripMenuItemSaveAsWps.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsWps.MouseLeave += Control_Leave;

		// ── Spreadsheet documents sub-menu ────────────────────────────────────
		toolStripMenuItemSpreadsheetDocuments.AccessibleDescription = "Saves the data as spreadsheet document";
		toolStripMenuItemSpreadsheetDocuments.AccessibleName = "Save as spreadsheet document";
		toolStripMenuItemSpreadsheetDocuments.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSpreadsheetDocuments.AutoToolTip = true;
		toolStripMenuItemSpreadsheetDocuments.DropDownItems.AddRange(new ToolStripItem[]
		{
			toolStripMenuItemSaveAsExcel, toolStripMenuItemSaveAsOds,
			toolStripMenuItemSaveAsCsv, toolStripMenuItemSaveAsTsv,
			toolStripMenuItemSaveAsPsv, toolStripMenuItemSaveAsEt
		});
		toolStripMenuItemSpreadsheetDocuments.Image = FatcowIcons16px.fatcow_file_extension_xls_16px;
		toolStripMenuItemSpreadsheetDocuments.Name = "toolStripMenuItemSpreadsheetDocuments";
		toolStripMenuItemSpreadsheetDocuments.Size = new Size(201, 22);
		toolStripMenuItemSpreadsheetDocuments.Text = "&Spreadsheet documents";
		toolStripMenuItemSpreadsheetDocuments.MouseEnter += Control_Enter;
		toolStripMenuItemSpreadsheetDocuments.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsExcel.AccessibleDescription = "Saves the data as Excel file";
		toolStripMenuItemSaveAsExcel.AccessibleName = "Save as Excel";
		toolStripMenuItemSaveAsExcel.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsExcel.AutoToolTip = true;
		toolStripMenuItemSaveAsExcel.Image = FatcowIcons16px.fatcow_page_white_excel_16px;
		toolStripMenuItemSaveAsExcel.Name = "toolStripMenuItemSaveAsExcel";
		toolStripMenuItemSaveAsExcel.Size = new Size(301, 22);
		toolStripMenuItemSaveAsExcel.Text = "Save as &Excel Spreadsheet (XLSX)";
		toolStripMenuItemSaveAsExcel.Click += ToolStripMenuItemSaveAsExcel_Click;
		toolStripMenuItemSaveAsExcel.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsExcel.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsOds.AccessibleDescription = "Saves the data as ODS file";
		toolStripMenuItemSaveAsOds.AccessibleName = "Save as ODS";
		toolStripMenuItemSaveAsOds.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsOds.AutoToolTip = true;
		toolStripMenuItemSaveAsOds.Image = FatcowIcons16px.fatcow_page_white_excel_16px;
		toolStripMenuItemSaveAsOds.Name = "toolStripMenuItemSaveAsOds";
		toolStripMenuItemSaveAsOds.Size = new Size(301, 22);
		toolStripMenuItemSaveAsOds.Text = "Save as &OpenDocument Spreadsheet (ODS)";
		toolStripMenuItemSaveAsOds.Click += ToolStripMenuItemSaveAsOds_Click;
		toolStripMenuItemSaveAsOds.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsOds.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsCsv.AccessibleDescription = "Saves the data as CSV file";
		toolStripMenuItemSaveAsCsv.AccessibleName = "Save as CSV";
		toolStripMenuItemSaveAsCsv.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsCsv.AutoToolTip = true;
		toolStripMenuItemSaveAsCsv.Image = FatcowIcons16px.fatcow_page_white_excel_16px;
		toolStripMenuItemSaveAsCsv.Name = "toolStripMenuItemSaveAsCsv";
		toolStripMenuItemSaveAsCsv.Size = new Size(301, 22);
		toolStripMenuItemSaveAsCsv.Text = "Save as &Comma separated value (CSV)";
		toolStripMenuItemSaveAsCsv.Click += ToolStripMenuItemSaveAsCsv_Click;
		toolStripMenuItemSaveAsCsv.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsCsv.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsTsv.AccessibleDescription = "Saves the data as TSV file";
		toolStripMenuItemSaveAsTsv.AccessibleName = "Save as TSV";
		toolStripMenuItemSaveAsTsv.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsTsv.AutoToolTip = true;
		toolStripMenuItemSaveAsTsv.Image = FatcowIcons16px.fatcow_page_white_excel_16px;
		toolStripMenuItemSaveAsTsv.Name = "toolStripMenuItemSaveAsTsv";
		toolStripMenuItemSaveAsTsv.Size = new Size(301, 22);
		toolStripMenuItemSaveAsTsv.Text = "Save as &Tab separated value (TSV)";
		toolStripMenuItemSaveAsTsv.Click += ToolStripMenuItemSaveAsTsv_Click;
		toolStripMenuItemSaveAsTsv.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsTsv.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsPsv.AccessibleDescription = "Saves the data as PSV file";
		toolStripMenuItemSaveAsPsv.AccessibleName = "Save as PSV";
		toolStripMenuItemSaveAsPsv.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsPsv.AutoToolTip = true;
		toolStripMenuItemSaveAsPsv.Image = FatcowIcons16px.fatcow_page_white_excel_16px;
		toolStripMenuItemSaveAsPsv.Name = "toolStripMenuItemSaveAsPsv";
		toolStripMenuItemSaveAsPsv.Size = new Size(301, 22);
		toolStripMenuItemSaveAsPsv.Text = "Save as &Pipe separated value (PSV)";
		toolStripMenuItemSaveAsPsv.Click += ToolStripMenuItemSaveAsPsv_Click;
		toolStripMenuItemSaveAsPsv.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsPsv.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsEt.AccessibleDescription = "Saves the data as ET file";
		toolStripMenuItemSaveAsEt.AccessibleName = "Save as ET";
		toolStripMenuItemSaveAsEt.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsEt.AutoToolTip = true;
		toolStripMenuItemSaveAsEt.Image = FatcowIcons16px.fatcow_page_white_excel_16px;
		toolStripMenuItemSaveAsEt.Name = "toolStripMenuItemSaveAsEt";
		toolStripMenuItemSaveAsEt.Size = new Size(301, 22);
		toolStripMenuItemSaveAsEt.Text = "Save as WPS &ET Spreadsheet (ET)";
		toolStripMenuItemSaveAsEt.Click += ToolStripMenuItemSaveAsEt_Click;
		toolStripMenuItemSaveAsEt.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsEt.MouseLeave += Control_Leave;

		// ── XML documents sub-menu ────────────────────────────────────────────
		toolStripMenuItemXmlDocuments.AccessibleDescription = "Saves the data as XML document";
		toolStripMenuItemXmlDocuments.AccessibleName = "Save as XML document";
		toolStripMenuItemXmlDocuments.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemXmlDocuments.AutoToolTip = true;
		toolStripMenuItemXmlDocuments.DropDownItems.AddRange(new ToolStripItem[]
		{
			toolStripMenuItemSaveAsHtml, toolStripMenuItemSaveAsXml, toolStripMenuItemSaveAsDocBook
		});
		toolStripMenuItemXmlDocuments.Image = FatcowIcons16px.fatcow_file_extension_xml_16px;
		toolStripMenuItemXmlDocuments.Name = "toolStripMenuItemXmlDocuments";
		toolStripMenuItemXmlDocuments.Size = new Size(201, 22);
		toolStripMenuItemXmlDocuments.Text = "&XML documents";
		toolStripMenuItemXmlDocuments.MouseEnter += Control_Enter;
		toolStripMenuItemXmlDocuments.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsHtml.AccessibleDescription = "Saves the data as HTML file";
		toolStripMenuItemSaveAsHtml.AccessibleName = "Save as HTML";
		toolStripMenuItemSaveAsHtml.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsHtml.AutoToolTip = true;
		toolStripMenuItemSaveAsHtml.Image = FatcowIcons16px.fatcow_page_white_world_16px;
		toolStripMenuItemSaveAsHtml.Name = "toolStripMenuItemSaveAsHtml";
		toolStripMenuItemSaveAsHtml.Size = new Size(257, 22);
		toolStripMenuItemSaveAsHtml.Text = "Save as &HTML";
		toolStripMenuItemSaveAsHtml.Click += ToolStripMenuItemSaveAsHtml_Click;
		toolStripMenuItemSaveAsHtml.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsHtml.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsXml.AccessibleDescription = "Saves the data as XML file";
		toolStripMenuItemSaveAsXml.AccessibleName = "Save as XML";
		toolStripMenuItemSaveAsXml.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsXml.AutoToolTip = true;
		toolStripMenuItemSaveAsXml.Image = FatcowIcons16px.fatcow_page_white_code_16px;
		toolStripMenuItemSaveAsXml.Name = "toolStripMenuItemSaveAsXml";
		toolStripMenuItemSaveAsXml.Size = new Size(257, 22);
		toolStripMenuItemSaveAsXml.Text = "Save as &XML";
		toolStripMenuItemSaveAsXml.Click += ToolStripMenuItemSaveAsXml_Click;
		toolStripMenuItemSaveAsXml.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsXml.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsDocBook.AccessibleDescription = "Saves the data as DocBook file";
		toolStripMenuItemSaveAsDocBook.AccessibleName = "Save as DocBook";
		toolStripMenuItemSaveAsDocBook.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsDocBook.AutoToolTip = true;
		toolStripMenuItemSaveAsDocBook.Image = FatcowIcons16px.fatcow_page_white_code_16px;
		toolStripMenuItemSaveAsDocBook.Name = "toolStripMenuItemSaveAsDocBook";
		toolStripMenuItemSaveAsDocBook.Size = new Size(257, 22);
		toolStripMenuItemSaveAsDocBook.Text = "Save as &DocBook";
		toolStripMenuItemSaveAsDocBook.Click += ToolStripMenuItemSaveAsDocBook_Click;
		toolStripMenuItemSaveAsDocBook.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsDocBook.MouseLeave += Control_Leave;

		// ── Configuration files sub-menu ──────────────────────────────────────
		toolStripMenuItemConfigurationFiles.AccessibleDescription = "Saves the data as configuration file";
		toolStripMenuItemConfigurationFiles.AccessibleName = "Save as configuration file";
		toolStripMenuItemConfigurationFiles.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemConfigurationFiles.AutoToolTip = true;
		toolStripMenuItemConfigurationFiles.DropDownItems.AddRange(new ToolStripItem[]
		{
			toolStripMenuItemSaveAsJson, toolStripMenuItemSaveAsYaml, toolStripMenuItemSaveAsToml
		});
		toolStripMenuItemConfigurationFiles.Image = FatcowIcons16px.fatcow_page_white_gear_16px;
		toolStripMenuItemConfigurationFiles.Name = "toolStripMenuItemConfigurationFiles";
		toolStripMenuItemConfigurationFiles.Size = new Size(201, 22);
		toolStripMenuItemConfigurationFiles.Text = "&Configuration files";
		toolStripMenuItemConfigurationFiles.MouseEnter += Control_Enter;
		toolStripMenuItemConfigurationFiles.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsJson.AccessibleDescription = "Saves the data as JSON file";
		toolStripMenuItemSaveAsJson.AccessibleName = "Save as JSON";
		toolStripMenuItemSaveAsJson.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsJson.AutoToolTip = true;
		toolStripMenuItemSaveAsJson.Image = FatcowIcons16px.fatcow_page_white_gear_16px;
		toolStripMenuItemSaveAsJson.Name = "toolStripMenuItemSaveAsJson";
		toolStripMenuItemSaveAsJson.Size = new Size(201, 22);
		toolStripMenuItemSaveAsJson.Text = "Save as &JSON";
		toolStripMenuItemSaveAsJson.Click += ToolStripMenuItemSaveAsJson_Click;
		toolStripMenuItemSaveAsJson.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsJson.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsYaml.AccessibleDescription = "Saves the data as YAML file";
		toolStripMenuItemSaveAsYaml.AccessibleName = "Save as YAML";
		toolStripMenuItemSaveAsYaml.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsYaml.AutoToolTip = true;
		toolStripMenuItemSaveAsYaml.Image = FatcowIcons16px.fatcow_page_white_gear_16px;
		toolStripMenuItemSaveAsYaml.Name = "toolStripMenuItemSaveAsYaml";
		toolStripMenuItemSaveAsYaml.Size = new Size(201, 22);
		toolStripMenuItemSaveAsYaml.Text = "Save as &YAML";
		toolStripMenuItemSaveAsYaml.Click += ToolStripMenuItemSaveAsYaml_Click;
		toolStripMenuItemSaveAsYaml.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsYaml.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsToml.AccessibleDescription = "Saves the data as TOML file";
		toolStripMenuItemSaveAsToml.AccessibleName = "Save as TOML";
		toolStripMenuItemSaveAsToml.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsToml.AutoToolTip = true;
		toolStripMenuItemSaveAsToml.Image = FatcowIcons16px.fatcow_page_white_gear_16px;
		toolStripMenuItemSaveAsToml.Name = "toolStripMenuItemSaveAsToml";
		toolStripMenuItemSaveAsToml.Size = new Size(201, 22);
		toolStripMenuItemSaveAsToml.Text = "Save as &TOML";
		toolStripMenuItemSaveAsToml.Click += ToolStripMenuItemSaveAsToml_Click;
		toolStripMenuItemSaveAsToml.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsToml.MouseLeave += Control_Leave;

		// ── Database scripts sub-menu ─────────────────────────────────────────
		toolStripMenuItemDatabaseScripts.AccessibleDescription = "Saves the data as database script";
		toolStripMenuItemDatabaseScripts.AccessibleName = "Save as database script";
		toolStripMenuItemDatabaseScripts.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemDatabaseScripts.AutoToolTip = true;
		toolStripMenuItemDatabaseScripts.DropDownItems.AddRange(new ToolStripItem[]
		{
			toolStripMenuItemSaveAsSql, toolStripMenuItemSaveAsSqlite
		});
		toolStripMenuItemDatabaseScripts.Image = FatcowIcons16px.fatcow_database_16px;
		toolStripMenuItemDatabaseScripts.Name = "toolStripMenuItemDatabaseScripts";
		toolStripMenuItemDatabaseScripts.Size = new Size(201, 22);
		toolStripMenuItemDatabaseScripts.Text = "&Database scripts";
		toolStripMenuItemDatabaseScripts.MouseEnter += Control_Enter;
		toolStripMenuItemDatabaseScripts.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsSql.AccessibleDescription = "Saves the data as SQL file";
		toolStripMenuItemSaveAsSql.AccessibleName = "Save as SQL";
		toolStripMenuItemSaveAsSql.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsSql.AutoToolTip = true;
		toolStripMenuItemSaveAsSql.Image = FatcowIcons16px.fatcow_database_16px;
		toolStripMenuItemSaveAsSql.Name = "toolStripMenuItemSaveAsSql";
		toolStripMenuItemSaveAsSql.Size = new Size(201, 22);
		toolStripMenuItemSaveAsSql.Text = "Save as &SQL";
		toolStripMenuItemSaveAsSql.Click += ToolStripMenuItemSaveAsSql_Click;
		toolStripMenuItemSaveAsSql.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsSql.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsSqlite.AccessibleDescription = "Saves the data as SQLite file";
		toolStripMenuItemSaveAsSqlite.AccessibleName = "Save as SQLite";
		toolStripMenuItemSaveAsSqlite.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsSqlite.AutoToolTip = true;
		toolStripMenuItemSaveAsSqlite.Image = FatcowIcons16px.fatcow_database_16px;
		toolStripMenuItemSaveAsSqlite.Name = "toolStripMenuItemSaveAsSqlite";
		toolStripMenuItemSaveAsSqlite.Size = new Size(201, 22);
		toolStripMenuItemSaveAsSqlite.Text = "Save as S&QLite";
		toolStripMenuItemSaveAsSqlite.Click += ToolStripMenuItemSaveAsSqlite_Click;
		toolStripMenuItemSaveAsSqlite.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsSqlite.MouseLeave += Control_Leave;

		// ── Portable documents sub-menu ───────────────────────────────────────
		toolStripMenuItemPortableDocuments.AccessibleDescription = "Saves the data as portable document";
		toolStripMenuItemPortableDocuments.AccessibleName = "Save as portable document";
		toolStripMenuItemPortableDocuments.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemPortableDocuments.AutoToolTip = true;
		toolStripMenuItemPortableDocuments.DropDownItems.AddRange(new ToolStripItem[]
		{
			toolStripMenuItemSaveAsPdf, toolStripMenuItemSaveAsPostScript,
			toolStripMenuItemSaveAsEpub, toolStripMenuItemSaveAsMobi,
			toolStripMenuItemSaveAsXps, toolStripMenuItemSaveAsFictionBook2,
			toolStripMenuItemSaveAsChm
		});
		toolStripMenuItemPortableDocuments.Image = FatcowIcons16px.fatcow_file_extension_pdf_16px;
		toolStripMenuItemPortableDocuments.Name = "toolStripMenuItemPortableDocuments";
		toolStripMenuItemPortableDocuments.Size = new Size(201, 22);
		toolStripMenuItemPortableDocuments.Text = "&Portable documents";
		toolStripMenuItemPortableDocuments.MouseEnter += Control_Enter;
		toolStripMenuItemPortableDocuments.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsPdf.AccessibleDescription = "Saves the data as PDF file";
		toolStripMenuItemSaveAsPdf.AccessibleName = "Save as PDF";
		toolStripMenuItemSaveAsPdf.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsPdf.AutoToolTip = true;
		toolStripMenuItemSaveAsPdf.Image = FatcowIcons16px.fatcow_file_extension_pdf_16px;
		toolStripMenuItemSaveAsPdf.Name = "toolStripMenuItemSaveAsPdf";
		toolStripMenuItemSaveAsPdf.Size = new Size(257, 22);
		toolStripMenuItemSaveAsPdf.Text = "Save as &PDF";
		toolStripMenuItemSaveAsPdf.Click += ToolStripMenuItemSaveAsPdf_Click;
		toolStripMenuItemSaveAsPdf.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsPdf.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsPostScript.AccessibleDescription = "Saves the data as PostScript file";
		toolStripMenuItemSaveAsPostScript.AccessibleName = "Save as PostScript";
		toolStripMenuItemSaveAsPostScript.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsPostScript.AutoToolTip = true;
		toolStripMenuItemSaveAsPostScript.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsPostScript.Name = "toolStripMenuItemSaveAsPostScript";
		toolStripMenuItemSaveAsPostScript.Size = new Size(257, 22);
		toolStripMenuItemSaveAsPostScript.Text = "Save as &PostScript (PS)";
		toolStripMenuItemSaveAsPostScript.Click += ToolStripMenuItemSaveAsPostScript_Click;
		toolStripMenuItemSaveAsPostScript.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsPostScript.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsEpub.AccessibleDescription = "Saves the data as EPUB file";
		toolStripMenuItemSaveAsEpub.AccessibleName = "Save as EPUB";
		toolStripMenuItemSaveAsEpub.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsEpub.AutoToolTip = true;
		toolStripMenuItemSaveAsEpub.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsEpub.Name = "toolStripMenuItemSaveAsEpub";
		toolStripMenuItemSaveAsEpub.Size = new Size(257, 22);
		toolStripMenuItemSaveAsEpub.Text = "Save as &EPUB";
		toolStripMenuItemSaveAsEpub.Click += ToolStripMenuItemSaveAsEpub_Click;
		toolStripMenuItemSaveAsEpub.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsEpub.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsMobi.AccessibleDescription = "Saves the data as MOBI file";
		toolStripMenuItemSaveAsMobi.AccessibleName = "Save as MOBI";
		toolStripMenuItemSaveAsMobi.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsMobi.AutoToolTip = true;
		toolStripMenuItemSaveAsMobi.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsMobi.Name = "toolStripMenuItemSaveAsMobi";
		toolStripMenuItemSaveAsMobi.Size = new Size(257, 22);
		toolStripMenuItemSaveAsMobi.Text = "Save as &MOBI";
		toolStripMenuItemSaveAsMobi.Click += ToolStripMenuItemSaveAsMobi_Click;
		toolStripMenuItemSaveAsMobi.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsMobi.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsXps.AccessibleDescription = "Saves the data as XPS file";
		toolStripMenuItemSaveAsXps.AccessibleName = "Save as XPS";
		toolStripMenuItemSaveAsXps.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsXps.AutoToolTip = true;
		toolStripMenuItemSaveAsXps.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsXps.Name = "toolStripMenuItemSaveAsXps";
		toolStripMenuItemSaveAsXps.Size = new Size(257, 22);
		toolStripMenuItemSaveAsXps.Text = "Save as &XPS";
		toolStripMenuItemSaveAsXps.Click += ToolStripMenuItemSaveAsXps_Click;
		toolStripMenuItemSaveAsXps.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsXps.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsFictionBook2.AccessibleDescription = "Saves the data as FictionBook2 file";
		toolStripMenuItemSaveAsFictionBook2.AccessibleName = "Save as FictionBook2";
		toolStripMenuItemSaveAsFictionBook2.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsFictionBook2.AutoToolTip = true;
		toolStripMenuItemSaveAsFictionBook2.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsFictionBook2.Name = "toolStripMenuItemSaveAsFictionBook2";
		toolStripMenuItemSaveAsFictionBook2.Size = new Size(257, 22);
		toolStripMenuItemSaveAsFictionBook2.Text = "Save as &FictionBook2 (FB2)";
		toolStripMenuItemSaveAsFictionBook2.Click += ToolStripMenuItemSaveAsFictionBook2_Click;
		toolStripMenuItemSaveAsFictionBook2.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsFictionBook2.MouseLeave += Control_Leave;

		toolStripMenuItemSaveAsChm.AccessibleDescription = "Saves the data as CHM file";
		toolStripMenuItemSaveAsChm.AccessibleName = "Save as CHM";
		toolStripMenuItemSaveAsChm.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemSaveAsChm.AutoToolTip = true;
		toolStripMenuItemSaveAsChm.Image = FatcowIcons16px.fatcow_page_white_text_16px;
		toolStripMenuItemSaveAsChm.Name = "toolStripMenuItemSaveAsChm";
		toolStripMenuItemSaveAsChm.Size = new Size(257, 22);
		toolStripMenuItemSaveAsChm.Text = "Save as &CHM";
		toolStripMenuItemSaveAsChm.Click += ToolStripMenuItemSaveAsChm_Click;
		toolStripMenuItemSaveAsChm.MouseEnter += Control_Enter;
		toolStripMenuItemSaveAsChm.MouseLeave += Control_Leave;

		// ── Form properties ───────────────────────────────────────────────────
		AccessibleDescription = "Shows the MOID values of a minor planet relative to the eight solar system planets";
		AccessibleName = "MOIDs of a minor planet";
		AccessibleRole = AccessibleRole.Dialog;
		AutoScaleDimensions = new SizeF(7F, 15F);
		AutoScaleMode = AutoScaleMode.Font;
		ClientSize = new Size(494, 290);
		ControlBox = false;
		Controls.Add(toolStripContainer);
		FormBorderStyle = FormBorderStyle.FixedToolWindow;
		Margin = new Padding(4, 3, 4, 3);
		MaximizeBox = false;
		MinimizeBox = false;
		Name = "MoidsOfOneMinorPlanetForm";
		ShowInTaskbar = false;
		StartPosition = FormStartPosition.CenterParent;
		Text = "MOIDs of a minor planet";
		Load += MoidsOfOneMinorPlanetForm_Load;

		// ── resume layouts ────────────────────────────────────────────────────
		contextMenuCopyToClipboard.ResumeLayout(false);
		toolStripContainer.BottomToolStripPanel.ResumeLayout(false);
		toolStripContainer.BottomToolStripPanel.PerformLayout();
		toolStripContainer.ContentPanel.ResumeLayout(false);
		toolStripContainer.TopToolStripPanel.ResumeLayout(false);
		toolStripContainer.TopToolStripPanel.PerformLayout();
		toolStripContainer.ResumeLayout(false);
		toolStripContainer.PerformLayout();
		kryptonStatusStrip.ResumeLayout(false);
		kryptonStatusStrip.PerformLayout();
		tableLayoutPanel.ResumeLayout(false);
		tableLayoutPanel.PerformLayout();
		toolStripIcons.ResumeLayout(false);
		toolStripIcons.PerformLayout();
		contextMenuSaveToFile.ResumeLayout(false);
		ResumeLayout(false);
	}

	#endregion

	// ── planet description labels ──────────────────────────────────────────
	private KryptonLabel labelMercuryDesc;
	private KryptonLabel labelVenusDesc;
	private KryptonLabel labelEarthDesc;
	private KryptonLabel labelMarsDesc;
	private KryptonLabel labelJupiterDesc;
	private KryptonLabel labelSaturnDesc;
	private KryptonLabel labelUranusDesc;
	private KryptonLabel labelNeptuneDesc;

	// ── MOID data labels ───────────────────────────────────────────────────
	private KryptonLabel labelMercuryData;
	private KryptonLabel labelVenusData;
	private KryptonLabel labelEarthData;
	private KryptonLabel labelMarsData;
	private KryptonLabel labelJupiterData;
	private KryptonLabel labelSaturnData;
	private KryptonLabel labelUranusData;
	private KryptonLabel labelNeptuneData;

	// ── context menus ──────────────────────────────────────────────────────
	private ContextMenuStrip contextMenuCopyToClipboard;
	private ToolStripMenuItem toolStripMenuItemCopyToClipboard;

	// ── layout / toolbar / status ──────────────────────────────────────────
	private KryptonTableLayoutPanel tableLayoutPanel;
	private ToolStripContainer toolStripContainer;
	private KryptonStatusStrip kryptonStatusStrip;
	private ToolStripStatusLabel labelInformation;
	private ToolStrip toolStripIcons;
	private KryptonManager kryptonManager;

	// ── save-to-file toolbar button ────────────────────────────────────────
	private ToolStripDropDownButton toolStripDropDownButtonSaveToFile;
	private ContextMenuStrip contextMenuSaveToFile;
	private ToolStripMenuItem toolStripMenuItemTextFiles;
	private ToolStripMenuItem toolStripMenuItemSaveAsText;
	private ToolStripMenuItem toolStripMenuItemSaveAsLatex;
	private ToolStripMenuItem toolStripMenuItemSaveAsMarkdown;
	private ToolStripMenuItem toolStripMenuItemSaveAsAsciiDoc;
	private ToolStripMenuItem toolStripMenuItemSaveAsReStructuredText;
	private ToolStripMenuItem toolStripMenuItemSaveAsTextile;
	private ToolStripMenuItem toolStripMenuItemWriterDocuments;
	private ToolStripMenuItem toolStripMenuItemSaveAsWord;
	private ToolStripMenuItem toolStripMenuItemSaveAsOdt;
	private ToolStripMenuItem toolStripMenuItemSaveAsRtf;
	private ToolStripMenuItem toolStripMenuItemSaveAsAbiword;
	private ToolStripMenuItem toolStripMenuItemSaveAsWps;
	private ToolStripMenuItem toolStripMenuItemSpreadsheetDocuments;
	private ToolStripMenuItem toolStripMenuItemSaveAsExcel;
	private ToolStripMenuItem toolStripMenuItemSaveAsOds;
	private ToolStripMenuItem toolStripMenuItemSaveAsCsv;
	private ToolStripMenuItem toolStripMenuItemSaveAsTsv;
	private ToolStripMenuItem toolStripMenuItemSaveAsPsv;
	private ToolStripMenuItem toolStripMenuItemSaveAsEt;
	private ToolStripMenuItem toolStripMenuItemXmlDocuments;
	private ToolStripMenuItem toolStripMenuItemSaveAsHtml;
	private ToolStripMenuItem toolStripMenuItemSaveAsXml;
	private ToolStripMenuItem toolStripMenuItemSaveAsDocBook;
	private ToolStripMenuItem toolStripMenuItemConfigurationFiles;
	private ToolStripMenuItem toolStripMenuItemSaveAsJson;
	private ToolStripMenuItem toolStripMenuItemSaveAsYaml;
	private ToolStripMenuItem toolStripMenuItemSaveAsToml;
	private ToolStripMenuItem toolStripMenuItemDatabaseScripts;
	private ToolStripMenuItem toolStripMenuItemSaveAsSql;
	private ToolStripMenuItem toolStripMenuItemSaveAsSqlite;
	private ToolStripMenuItem toolStripMenuItemPortableDocuments;
	private ToolStripMenuItem toolStripMenuItemSaveAsPdf;
	private ToolStripMenuItem toolStripMenuItemSaveAsPostScript;
	private ToolStripMenuItem toolStripMenuItemSaveAsEpub;
	private ToolStripMenuItem toolStripMenuItemSaveAsMobi;
	private ToolStripMenuItem toolStripMenuItemSaveAsXps;
	private ToolStripMenuItem toolStripMenuItemSaveAsFictionBook2;
	private ToolStripMenuItem toolStripMenuItemSaveAsChm;
}
