// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using Krypton.Toolkit;

using Planetoid_DB.Resources;

using System.ComponentModel;

namespace Planetoid_DB;

/// <summary>Represents a Windows Form that calculates and displays the Minimum Orbit Intersection Distance (MOID) between two minor planets selected by the user from the loaded database.</summary>
/// <remarks>The form presents two drop-down combo boxes — one for each minor planet — populated with all planetoid designations from the loaded database. A random-selection button sits next to each combo box. The MOID result is shown in a label below the combo boxes and is recalculated automatically whenever the user changes the selection in either combo box. The form does not appear in the taskbar and is intended to be used as a modal dialog.</remarks>
partial class MoidsRelativeToMinorPlanetsForm
{
	/// <summary>Required designer variable.</summary>
	/// <remarks>This field stores the components used by the form.</remarks>
	private IContainer components = null;

	/// <summary>Clean up any resources being used.</summary>
	/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
	/// <remarks>This method is called by the runtime to release resources used by the form.</remarks>
	protected override void Dispose(bool disposing)
	{
		if (disposing && (components != null))
		{
			components.Dispose();
		}
		base.Dispose(disposing);
	}

	#region Windows Form Designer generated code

	/// <summary>Required method for Designer support - do not modify the contents of this method with the code editor.</summary>
	/// <remarks>This method is automatically generated by the Windows Forms designer and should not be modified manually. It sets up the controls and their properties for the form.</remarks>
	private void InitializeComponent()
	{
		components = new Container();
		ComponentResourceManager resources = new ComponentResourceManager(typeof(MoidsRelativeToMinorPlanetsForm));
		kryptonPanelMain = new KryptonPanel();
		tableLayoutPanel = new TableLayoutPanel();
		comboBoxPlanetoid1 = new ComboBox();
		kryptonButtonRandomPlanetoid1 = new KryptonButton();
		comboBoxPlanetoid2 = new ComboBox();
		kryptonButtonRandomPlanetoid2 = new KryptonButton();
		kryptonLabelMoidDesc = new KryptonLabel();
		kryptonLabelMoidValue = new KryptonLabel();
		kryptonStatusStrip = new KryptonStatusStrip();
		labelInformation = new ToolStripStatusLabel();
		kryptonManager = new KryptonManager(components);
		((ISupportInitialize)kryptonPanelMain).BeginInit();
		kryptonPanelMain.SuspendLayout();
		tableLayoutPanel.SuspendLayout();
		kryptonStatusStrip.SuspendLayout();
		SuspendLayout();
		// 
		// kryptonPanelMain
		// 
		kryptonPanelMain.AccessibleDescription = "Groups the main controls";
		kryptonPanelMain.AccessibleName = "Main panel";
		kryptonPanelMain.AccessibleRole = AccessibleRole.Pane;
		kryptonPanelMain.Controls.Add(tableLayoutPanel);
		kryptonPanelMain.Controls.Add(kryptonStatusStrip);
		kryptonPanelMain.Dock = DockStyle.Fill;
		kryptonPanelMain.Location = new Point(0, 0);
		kryptonPanelMain.Name = "kryptonPanelMain";
		kryptonPanelMain.PanelBackStyle = PaletteBackStyle.FormMain;
		kryptonPanelMain.Size = new Size(560, 160);
		kryptonPanelMain.TabIndex = 0;
		kryptonPanelMain.TabStop = true;
		// 
		// tableLayoutPanel
		// 
		tableLayoutPanel.AccessibleDescription = "Layout for the two combo boxes and the MOID label";
		tableLayoutPanel.AccessibleName = "Layout panel";
		tableLayoutPanel.AccessibleRole = AccessibleRole.Pane;
		tableLayoutPanel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		tableLayoutPanel.ColumnCount = 2;
		tableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
		tableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 110F));
		tableLayoutPanel.Controls.Add(comboBoxPlanetoid1, 0, 0);
		tableLayoutPanel.Controls.Add(kryptonButtonRandomPlanetoid1, 1, 0);
		tableLayoutPanel.Controls.Add(comboBoxPlanetoid2, 0, 1);
		tableLayoutPanel.Controls.Add(kryptonButtonRandomPlanetoid2, 1, 1);
		tableLayoutPanel.Controls.Add(kryptonLabelMoidDesc, 0, 2);
		tableLayoutPanel.Controls.Add(kryptonLabelMoidValue, 1, 2);
		tableLayoutPanel.Location = new Point(8, 8);
		tableLayoutPanel.Name = "tableLayoutPanel";
		tableLayoutPanel.RowCount = 3;
		tableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
		tableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
		tableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
		tableLayoutPanel.Size = new Size(544, 108);
		tableLayoutPanel.TabIndex = 1;
		// 
		// comboBoxPlanetoid1
		// 
		comboBoxPlanetoid1.AccessibleDescription = "Select the first minor planet for MOID calculation";
		comboBoxPlanetoid1.AccessibleName = "First minor planet";
		comboBoxPlanetoid1.AccessibleRole = AccessibleRole.ComboBox;
		comboBoxPlanetoid1.Anchor = AnchorStyles.Left | AnchorStyles.Right;
		comboBoxPlanetoid1.AutoCompleteMode = AutoCompleteMode.Suggest;
		comboBoxPlanetoid1.AutoCompleteSource = AutoCompleteSource.CustomSource;
		comboBoxPlanetoid1.Location = new Point(3, 6);
		comboBoxPlanetoid1.Name = "comboBoxPlanetoid1";
		comboBoxPlanetoid1.Size = new Size(428, 23);
		comboBoxPlanetoid1.TabIndex = 0;
		comboBoxPlanetoid1.SelectionChangeCommitted += ComboBoxPlanetoid_SelectionChangeCommitted;
		comboBoxPlanetoid1.TextChanged += ComboBoxPlanetoid1_TextChanged;
		comboBoxPlanetoid1.Enter += Control_Enter;
		comboBoxPlanetoid1.Leave += Control_Leave;
		// 
		// kryptonButtonRandomPlanetoid1
		// 
		kryptonButtonRandomPlanetoid1.AccessibleDescription = "Selects a random minor planet in the first list";
		kryptonButtonRandomPlanetoid1.AccessibleName = "Random first minor planet";
		kryptonButtonRandomPlanetoid1.AccessibleRole = AccessibleRole.PushButton;
		kryptonButtonRandomPlanetoid1.Anchor = AnchorStyles.Left | AnchorStyles.Right;
		kryptonButtonRandomPlanetoid1.Location = new Point(437, 5);
		kryptonButtonRandomPlanetoid1.Name = "kryptonButtonRandomPlanetoid1";
		kryptonButtonRandomPlanetoid1.Size = new Size(104, 25);
		kryptonButtonRandomPlanetoid1.TabIndex = 1;
		kryptonButtonRandomPlanetoid1.ToolTipValues.Description = "Selects a random minor planet from the first list.";
		kryptonButtonRandomPlanetoid1.ToolTipValues.EnableToolTips = true;
		kryptonButtonRandomPlanetoid1.ToolTipValues.Heading = "Random selection";
		kryptonButtonRandomPlanetoid1.ToolTipValues.Image = FatcowIcons16px.fatcow_dice_16px;
		kryptonButtonRandomPlanetoid1.Values.DropDownArrowColor = Color.Empty;
		kryptonButtonRandomPlanetoid1.Values.Image = FatcowIcons16px.fatcow_dice_16px;
		kryptonButtonRandomPlanetoid1.Values.Text = "&Random";
		kryptonButtonRandomPlanetoid1.Click += KryptonButtonRandomPlanetoid1_Click;
		kryptonButtonRandomPlanetoid1.Enter += Control_Enter;
		kryptonButtonRandomPlanetoid1.Leave += Control_Leave;
		// 
		// comboBoxPlanetoid2
		// 
		comboBoxPlanetoid2.AccessibleDescription = "Select the second minor planet for MOID calculation";
		comboBoxPlanetoid2.AccessibleName = "Second minor planet";
		comboBoxPlanetoid2.AccessibleRole = AccessibleRole.ComboBox;
		comboBoxPlanetoid2.Anchor = AnchorStyles.Left | AnchorStyles.Right;
		comboBoxPlanetoid2.AutoCompleteMode = AutoCompleteMode.Suggest;
		comboBoxPlanetoid2.AutoCompleteSource = AutoCompleteSource.CustomSource;
		comboBoxPlanetoid2.Location = new Point(3, 42);
		comboBoxPlanetoid2.Name = "comboBoxPlanetoid2";
		comboBoxPlanetoid2.Size = new Size(428, 23);
		comboBoxPlanetoid2.TabIndex = 2;
		comboBoxPlanetoid2.SelectionChangeCommitted += ComboBoxPlanetoid_SelectionChangeCommitted;
		comboBoxPlanetoid2.TextChanged += ComboBoxPlanetoid2_TextChanged;
		comboBoxPlanetoid2.Enter += Control_Enter;
		comboBoxPlanetoid2.Leave += Control_Leave;
		// 
		// kryptonButtonRandomPlanetoid2
		// 
		kryptonButtonRandomPlanetoid2.AccessibleDescription = "Selects a random minor planet in the second list";
		kryptonButtonRandomPlanetoid2.AccessibleName = "Random second minor planet";
		kryptonButtonRandomPlanetoid2.AccessibleRole = AccessibleRole.PushButton;
		kryptonButtonRandomPlanetoid2.Anchor = AnchorStyles.Left | AnchorStyles.Right;
		kryptonButtonRandomPlanetoid2.Location = new Point(437, 41);
		kryptonButtonRandomPlanetoid2.Name = "kryptonButtonRandomPlanetoid2";
		kryptonButtonRandomPlanetoid2.Size = new Size(104, 25);
		kryptonButtonRandomPlanetoid2.TabIndex = 3;
		kryptonButtonRandomPlanetoid2.ToolTipValues.Description = "Selects a random minor planet from the second list.";
		kryptonButtonRandomPlanetoid2.ToolTipValues.EnableToolTips = true;
		kryptonButtonRandomPlanetoid2.ToolTipValues.Heading = "Random selection";
		kryptonButtonRandomPlanetoid2.ToolTipValues.Image = FatcowIcons16px.fatcow_dice_16px;
		kryptonButtonRandomPlanetoid2.Values.DropDownArrowColor = Color.Empty;
		kryptonButtonRandomPlanetoid2.Values.Image = FatcowIcons16px.fatcow_dice_16px;
		kryptonButtonRandomPlanetoid2.Values.Text = "R&andom";
		kryptonButtonRandomPlanetoid2.Click += KryptonButtonRandomPlanetoid2_Click;
		kryptonButtonRandomPlanetoid2.Enter += Control_Enter;
		kryptonButtonRandomPlanetoid2.Leave += Control_Leave;
		// 
		// kryptonLabelMoidDesc
		// 
		kryptonLabelMoidDesc.AccessibleDescription = "Describes the MOID value label";
		kryptonLabelMoidDesc.AccessibleName = "MOID description";
		kryptonLabelMoidDesc.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelMoidDesc.Anchor = AnchorStyles.Left;
		kryptonLabelMoidDesc.LabelStyle = LabelStyle.BoldPanel;
		kryptonLabelMoidDesc.Location = new Point(3, 80);
		kryptonLabelMoidDesc.Name = "kryptonLabelMoidDesc";
		kryptonLabelMoidDesc.Size = new Size(200, 20);
		kryptonLabelMoidDesc.TabIndex = 4;
		kryptonLabelMoidDesc.Values.ExtraText = "AU";
		kryptonLabelMoidDesc.Values.Text = "MOID:";
		kryptonLabelMoidDesc.Enter += Control_Enter;
		kryptonLabelMoidDesc.Leave += Control_Leave;
		kryptonLabelMoidDesc.MouseEnter += Control_Enter;
		kryptonLabelMoidDesc.MouseLeave += Control_Leave;
		// 
		// kryptonLabelMoidValue
		// 
		kryptonLabelMoidValue.AccessibleDescription = "Shows the calculated MOID value in AU";
		kryptonLabelMoidValue.AccessibleName = "MOID value";
		kryptonLabelMoidValue.AccessibleRole = AccessibleRole.StaticText;
		kryptonLabelMoidValue.Anchor = AnchorStyles.Left;
		kryptonLabelMoidValue.Location = new Point(437, 80);
		kryptonLabelMoidValue.Name = "kryptonLabelMoidValue";
		kryptonLabelMoidValue.Size = new Size(104, 20);
		kryptonLabelMoidValue.TabIndex = 5;
		kryptonLabelMoidValue.Values.Text = "-";
		kryptonLabelMoidValue.Enter += Control_Enter;
		kryptonLabelMoidValue.Leave += Control_Leave;
		kryptonLabelMoidValue.MouseEnter += Control_Enter;
		kryptonLabelMoidValue.MouseLeave += Control_Leave;
		// 
		// kryptonStatusStrip
		// 
		kryptonStatusStrip.AccessibleDescription = "Status bar";
		kryptonStatusStrip.AccessibleName = "Status bar";
		kryptonStatusStrip.AccessibleRole = AccessibleRole.StatusBar;
		kryptonStatusStrip.Font = new Font("Segoe UI", 9F);
		kryptonStatusStrip.Items.AddRange(new ToolStripItem[] { labelInformation });
		kryptonStatusStrip.Location = new Point(0, 138);
		kryptonStatusStrip.Name = "kryptonStatusStrip";
		kryptonStatusStrip.ProgressBars = null;
		kryptonStatusStrip.RenderMode = ToolStripRenderMode.ManagerRenderMode;
		kryptonStatusStrip.Size = new Size(560, 22);
		kryptonStatusStrip.TabIndex = 0;
		// 
		// labelInformation
		// 
		labelInformation.AccessibleDescription = "Shows information about the selected control";
		labelInformation.AccessibleName = "Information";
		labelInformation.AccessibleRole = AccessibleRole.StaticText;
		labelInformation.Enabled = false;
		labelInformation.Name = "labelInformation";
		labelInformation.Size = new Size(545, 17);
		labelInformation.Spring = true;
		labelInformation.TextAlign = ContentAlignment.MiddleLeft;
		// 
		// kryptonManager
		// 
		kryptonManager.GlobalPaletteMode = PaletteMode.Global;
		kryptonManager.ToolkitStrings.MessageBoxStrings.LessDetails = "L&ess Details...";
		kryptonManager.ToolkitStrings.MessageBoxStrings.MoreDetails = "&More Details...";
		// 
		// MoidsRelativeToMinorPlanetsForm
		// 
		AccessibleDescription = "Form for calculating the MOID between two minor planets";
		AccessibleName = "MOIDs relative to minor planets";
		AccessibleRole = AccessibleRole.Window;
		AutoScaleDimensions = new SizeF(7F, 15F);
		AutoScaleMode = AutoScaleMode.Font;
		ClientSize = new Size(560, 160);
		ControlBox = false;
		Controls.Add(kryptonPanelMain);
		FormBorderStyle = FormBorderStyle.SizableToolWindow;
		Icon = (Icon)resources.GetObject("$this.Icon");
		MaximizeBox = false;
		MinimizeBox = false;
		Name = "MoidsRelativeToMinorPlanetsForm";
		ShowInTaskbar = false;
		StartPosition = FormStartPosition.CenterParent;
		Text = "MOIDs relative to minor planets";
		Load += MoidsRelativeToMinorPlanetsForm_Load;
		((ISupportInitialize)kryptonPanelMain).EndInit();
		kryptonPanelMain.ResumeLayout(false);
		kryptonPanelMain.PerformLayout();
		tableLayoutPanel.ResumeLayout(false);
		tableLayoutPanel.PerformLayout();
		kryptonStatusStrip.ResumeLayout(false);
		kryptonStatusStrip.PerformLayout();
		ResumeLayout(false);
	}

	#endregion

	private KryptonPanel kryptonPanelMain;
	private KryptonStatusStrip kryptonStatusStrip;
	private ToolStripStatusLabel labelInformation;
	private TableLayoutPanel tableLayoutPanel;
	private ComboBox comboBoxPlanetoid1;
	private KryptonButton kryptonButtonRandomPlanetoid1;
	private ComboBox comboBoxPlanetoid2;
	private KryptonButton kryptonButtonRandomPlanetoid2;
	private KryptonLabel kryptonLabelMoidDesc;
	private KryptonLabel kryptonLabelMoidValue;
	private KryptonManager kryptonManager;
}
