// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using Krypton.Toolkit;

using Planetoid_DB.Resources;

using System.ComponentModel;

namespace Planetoid_DB;

/// <summary>Represents a dialog form that displays orbital resonances of all minor planets relative to the eight solar system
/// planets.</summary>
/// <remarks>This form allows users to select which planets to include in the resonance search and provides a
/// progress indicator during the search process. Results are presented in a list view, and users can copy information
/// to the clipboard via a context menu. The form is designed for modal display and does not appear in the
/// taskbar.</remarks>
partial class OrbitalResonancesOfAllMinorPlanetsForm
{
	/// <summary>Required designer variable.</summary>
	/// <remarks>This field stores the components used by the form.</remarks>
	private IContainer components = null;

	/// <summary>Clean up any resources being used.</summary>
	/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
	/// <remarks>This method is called by the runtime to release resources used by the form.</remarks>
	protected override void Dispose(bool disposing)
	{
		if (disposing && (components != null))
		{
			components.Dispose();
		}
		base.Dispose(disposing);
	}

	#region Windows Form Designer generated code

	/// <summary>Required method for Designer support - do not modify
	/// the contents of this method with the code editor.</summary>
	/// <remarks>This method is automatically generated by the Windows Forms designer and should not be modified manually.
	/// It sets up the controls and their properties for the form.</remarks>
	private void InitializeComponent()
	{
		components = new Container();
		ComponentResourceManager resources = new ComponentResourceManager(typeof(OrbitalResonancesOfAllMinorPlanetsForm));
		kryptoPanelMain = new KryptonPanel();
		btnStart = new KryptonButton();
		btnCancel = new KryptonButton();
		checkBoxMercury = new KryptonCheckBox();
		checkBoxVenus = new KryptonCheckBox();
		checkBoxEarth = new KryptonCheckBox();
		checkBoxMars = new KryptonCheckBox();
		checkBoxJupiter = new KryptonCheckBox();
		checkBoxSaturn = new KryptonCheckBox();
		checkBoxUranus = new KryptonCheckBox();
		checkBoxNeptune = new KryptonCheckBox();
		kryptonProgressBar = new KryptonProgressBar();
		listView = new ListView();
		columnHeaderPlanetoid = new ColumnHeader();
		columnHeaderPlanet = new ColumnHeader();
		columnHeaderPlanetPeriod = new ColumnHeader();
		columnHeaderPlanetoidPeriod = new ColumnHeader();
		columnHeaderRatio = new ColumnHeader();
		columnHeaderResonance = new ColumnHeader();
		columnHeaderDeviation = new ColumnHeader();
		columnHeaderIsResonance = new ColumnHeader();
		contextMenuCopyToClipboard = new ContextMenuStrip(components);
		toolStripMenuItemCopyToClipboard = new ToolStripMenuItem();
		kryptonStatusStrip = new KryptonStatusStrip();
		labelInformation = new ToolStripStatusLabel();
		kryptonManager = new KryptonManager(components);
		((ISupportInitialize)kryptoPanelMain).BeginInit();
		kryptoPanelMain.SuspendLayout();
		contextMenuCopyToClipboard.SuspendLayout();
		kryptonStatusStrip.SuspendLayout();
		SuspendLayout();
		// 
		// kryptoPanelMain
		// 
		kryptoPanelMain.AccessibleDescription = "Groups the data";
		kryptoPanelMain.AccessibleName = "Panel";
		kryptoPanelMain.AccessibleRole = AccessibleRole.Pane;
		kryptoPanelMain.Controls.Add(btnStart);
		kryptoPanelMain.Controls.Add(btnCancel);
		kryptoPanelMain.Controls.Add(checkBoxMercury);
		kryptoPanelMain.Controls.Add(checkBoxVenus);
		kryptoPanelMain.Controls.Add(checkBoxEarth);
		kryptoPanelMain.Controls.Add(checkBoxMars);
		kryptoPanelMain.Controls.Add(checkBoxJupiter);
		kryptoPanelMain.Controls.Add(checkBoxSaturn);
		kryptoPanelMain.Controls.Add(checkBoxUranus);
		kryptoPanelMain.Controls.Add(checkBoxNeptune);
		kryptoPanelMain.Controls.Add(kryptonProgressBar);
		kryptoPanelMain.Controls.Add(listView);
		kryptoPanelMain.Controls.Add(kryptonStatusStrip);
		kryptoPanelMain.Dock = DockStyle.Fill;
		kryptoPanelMain.Location = new Point(0, 0);
		kryptoPanelMain.Name = "kryptoPanelMain";
		kryptoPanelMain.PanelBackStyle = PaletteBackStyle.FormMain;
		kryptoPanelMain.Size = new Size(918, 620);
		kryptoPanelMain.TabIndex = 0;
		kryptoPanelMain.TabStop = true;
		// 
		// btnStart
		// 
		btnStart.AccessibleDescription = "Starts the orbital resonance search for all minor planets";
		btnStart.AccessibleName = "Start search";
		btnStart.AccessibleRole = AccessibleRole.PushButton;
		btnStart.Location = new Point(12, 12);
		btnStart.Name = "btnStart";
		btnStart.Size = new Size(90, 25);
		btnStart.TabIndex = 0;
		btnStart.Values.DropDownArrowColor = Color.Empty;
		btnStart.Values.Text = "&Start Search";
		btnStart.Click += BtnStart_Click;
		btnStart.MouseEnter += Control_Enter;
		btnStart.MouseLeave += Control_Leave;
		// 
		// btnCancel
		// 
		btnCancel.AccessibleDescription = "Cancels the orbital resonance search";
		btnCancel.AccessibleName = "Cancel search";
		btnCancel.AccessibleRole = AccessibleRole.PushButton;
		btnCancel.Enabled = false;
		btnCancel.Location = new Point(108, 12);
		btnCancel.Name = "btnCancel";
		btnCancel.Size = new Size(90, 25);
		btnCancel.TabIndex = 1;
		btnCancel.Values.DropDownArrowColor = Color.Empty;
		btnCancel.Values.Text = "&Cancel";
		btnCancel.Click += BtnCancel_Click;
		btnCancel.MouseEnter += Control_Enter;
		btnCancel.MouseLeave += Control_Leave;
		// 
		// checkBoxMercury
		// 
		checkBoxMercury.AccessibleDescription = "Includes Mercury in the resonance search";
		checkBoxMercury.AccessibleName = "Mercury";
		checkBoxMercury.Checked = true;
		checkBoxMercury.CheckState = CheckState.Checked;
		checkBoxMercury.Location = new Point(225, 14);
		checkBoxMercury.Name = "checkBoxMercury";
		checkBoxMercury.Size = new Size(110, 20);
		checkBoxMercury.TabIndex = 2;
		checkBoxMercury.Values.Text = "Mercury";
		checkBoxMercury.MouseEnter += Control_Enter;
		checkBoxMercury.MouseLeave += Control_Leave;
		// 
		// checkBoxVenus
		// 
		checkBoxVenus.AccessibleDescription = "Includes Venus in the resonance search";
		checkBoxVenus.AccessibleName = "Venus";
		checkBoxVenus.Checked = true;
		checkBoxVenus.CheckState = CheckState.Checked;
		checkBoxVenus.Location = new Point(341, 14);
		checkBoxVenus.Name = "checkBoxVenus";
		checkBoxVenus.Size = new Size(90, 20);
		checkBoxVenus.TabIndex = 3;
		checkBoxVenus.Values.Text = "Venus";
		checkBoxVenus.MouseEnter += Control_Enter;
		checkBoxVenus.MouseLeave += Control_Leave;
		// 
		// checkBoxEarth
		// 
		checkBoxEarth.AccessibleDescription = "Includes Earth in the resonance search";
		checkBoxEarth.AccessibleName = "Earth";
		checkBoxEarth.Checked = true;
		checkBoxEarth.CheckState = CheckState.Checked;
		checkBoxEarth.Location = new Point(437, 14);
		checkBoxEarth.Name = "checkBoxEarth";
		checkBoxEarth.Size = new Size(85, 20);
		checkBoxEarth.TabIndex = 4;
		checkBoxEarth.Values.Text = "Earth";
		checkBoxEarth.MouseEnter += Control_Enter;
		checkBoxEarth.MouseLeave += Control_Leave;
		// 
		// checkBoxMars
		// 
		checkBoxMars.AccessibleDescription = "Includes Mars in the resonance search";
		checkBoxMars.AccessibleName = "Mars";
		checkBoxMars.Checked = true;
		checkBoxMars.CheckState = CheckState.Checked;
		checkBoxMars.Location = new Point(528, 14);
		checkBoxMars.Name = "checkBoxMars";
		checkBoxMars.Size = new Size(85, 20);
		checkBoxMars.TabIndex = 5;
		checkBoxMars.Values.Text = "Mars";
		checkBoxMars.MouseEnter += Control_Enter;
		checkBoxMars.MouseLeave += Control_Leave;
		// 
		// checkBoxJupiter
		// 
		checkBoxJupiter.AccessibleDescription = "Includes Jupiter in the resonance search";
		checkBoxJupiter.AccessibleName = "Jupiter";
		checkBoxJupiter.Checked = true;
		checkBoxJupiter.CheckState = CheckState.Checked;
		checkBoxJupiter.Location = new Point(225, 40);
		checkBoxJupiter.Name = "checkBoxJupiter";
		checkBoxJupiter.Size = new Size(110, 20);
		checkBoxJupiter.TabIndex = 6;
		checkBoxJupiter.Values.Text = "Jupiter";
		checkBoxJupiter.MouseEnter += Control_Enter;
		checkBoxJupiter.MouseLeave += Control_Leave;
		// 
		// checkBoxSaturn
		// 
		checkBoxSaturn.AccessibleDescription = "Includes Saturn in the resonance search";
		checkBoxSaturn.AccessibleName = "Saturn";
		checkBoxSaturn.Checked = true;
		checkBoxSaturn.CheckState = CheckState.Checked;
		checkBoxSaturn.Location = new Point(341, 40);
		checkBoxSaturn.Name = "checkBoxSaturn";
		checkBoxSaturn.Size = new Size(90, 20);
		checkBoxSaturn.TabIndex = 7;
		checkBoxSaturn.Values.Text = "Saturn";
		checkBoxSaturn.MouseEnter += Control_Enter;
		checkBoxSaturn.MouseLeave += Control_Leave;
		// 
		// checkBoxUranus
		// 
		checkBoxUranus.AccessibleDescription = "Includes Uranus in the resonance search";
		checkBoxUranus.AccessibleName = "Uranus";
		checkBoxUranus.Checked = true;
		checkBoxUranus.CheckState = CheckState.Checked;
		checkBoxUranus.Location = new Point(437, 40);
		checkBoxUranus.Name = "checkBoxUranus";
		checkBoxUranus.Size = new Size(90, 20);
		checkBoxUranus.TabIndex = 8;
		checkBoxUranus.Values.Text = "Uranus";
		checkBoxUranus.MouseEnter += Control_Enter;
		checkBoxUranus.MouseLeave += Control_Leave;
		// 
		// checkBoxNeptune
		// 
		checkBoxNeptune.AccessibleDescription = "Includes Neptune in the resonance search";
		checkBoxNeptune.AccessibleName = "Neptune";
		checkBoxNeptune.Checked = true;
		checkBoxNeptune.CheckState = CheckState.Checked;
		checkBoxNeptune.Location = new Point(528, 40);
		checkBoxNeptune.Name = "checkBoxNeptune";
		checkBoxNeptune.Size = new Size(100, 20);
		checkBoxNeptune.TabIndex = 9;
		checkBoxNeptune.Values.Text = "Neptune";
		checkBoxNeptune.MouseEnter += Control_Enter;
		checkBoxNeptune.MouseLeave += Control_Leave;
		// 
		// kryptonProgressBar
		// 
		kryptonProgressBar.AccessibleDescription = "Shows the progress of the orbital resonance search";
		kryptonProgressBar.AccessibleName = "Search progress";
		kryptonProgressBar.AccessibleRole = AccessibleRole.ProgressBar;
		kryptonProgressBar.Location = new Point(12, 72);
		kryptonProgressBar.Name = "kryptonProgressBar";
		kryptonProgressBar.Size = new Size(840, 23);
		kryptonProgressBar.TabIndex = 10;
		kryptonProgressBar.Text = "0%";
		kryptonProgressBar.TextBackdropColor = Color.Empty;
		kryptonProgressBar.TextShadowColor = Color.Empty;
		kryptonProgressBar.Values.Text = "0%";
		// 
		// listView
		// 
		listView.AccessibleDescription = "Shows the list of orbital resonances of all planetoids relative to the solar system planets";
		listView.AccessibleName = "Orbital resonances of all minor planets list";
		listView.AccessibleRole = AccessibleRole.List;
		listView.AllowColumnReorder = true;
		listView.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
		listView.Columns.AddRange(new ColumnHeader[] { columnHeaderPlanetoid, columnHeaderPlanet, columnHeaderPlanetPeriod, columnHeaderPlanetoidPeriod, columnHeaderRatio, columnHeaderResonance, columnHeaderDeviation, columnHeaderIsResonance });
		listView.ContextMenuStrip = contextMenuCopyToClipboard;
		listView.Font = new Font("Segoe UI", 9F);
		listView.FullRowSelect = true;
		listView.GridLines = true;
		listView.Location = new Point(12, 103);
		listView.Name = "listView";
		listView.ShowItemToolTips = true;
		listView.Size = new Size(894, 493);
		listView.TabIndex = 12;
		listView.UseCompatibleStateImageBehavior = false;
		listView.View = View.Details;
		listView.VirtualMode = true;
		listView.RetrieveVirtualItem += ListView_RetrieveVirtualItem;
		listView.Enter += Control_Enter;
		listView.Leave += Control_Leave;
		listView.MouseEnter += Control_Enter;
		listView.MouseLeave += Control_Leave;
		// 
		// columnHeaderPlanetoid
		// 
		columnHeaderPlanetoid.Text = "Planetoid";
		columnHeaderPlanetoid.Width = 200;
		// 
		// columnHeaderPlanet
		// 
		columnHeaderPlanet.Text = "Planet";
		columnHeaderPlanet.Width = 90;
		// 
		// columnHeaderPlanetPeriod
		// 
		columnHeaderPlanetPeriod.Text = "Planet Period (yr)";
		columnHeaderPlanetPeriod.TextAlign = HorizontalAlignment.Right;
		columnHeaderPlanetPeriod.Width = 120;
		// 
		// columnHeaderPlanetoidPeriod
		// 
		columnHeaderPlanetoidPeriod.Text = "Planetoid Period (yr)";
		columnHeaderPlanetoidPeriod.TextAlign = HorizontalAlignment.Right;
		columnHeaderPlanetoidPeriod.Width = 130;
		// 
		// columnHeaderRatio
		// 
		columnHeaderRatio.Text = "Ratio";
		columnHeaderRatio.TextAlign = HorizontalAlignment.Right;
		columnHeaderRatio.Width = 80;
		// 
		// columnHeaderResonance
		// 
		columnHeaderResonance.Text = "Resonance";
		columnHeaderResonance.TextAlign = HorizontalAlignment.Center;
		columnHeaderResonance.Width = 90;
		// 
		// columnHeaderDeviation
		// 
		columnHeaderDeviation.Text = "Deviation (%)";
		columnHeaderDeviation.TextAlign = HorizontalAlignment.Right;
		columnHeaderDeviation.Width = 90;
		// 
		// columnHeaderIsResonance
		// 
		columnHeaderIsResonance.Text = "Is Resonance";
		columnHeaderIsResonance.TextAlign = HorizontalAlignment.Center;
		columnHeaderIsResonance.Width = 90;
		// 
		// contextMenuCopyToClipboard
		// 
		contextMenuCopyToClipboard.AccessibleDescription = "Shows the context menu for copying information to the clipboard";
		contextMenuCopyToClipboard.AccessibleName = "Context menu for copying information to the clipboard";
		contextMenuCopyToClipboard.AccessibleRole = AccessibleRole.MenuPopup;
		contextMenuCopyToClipboard.AllowClickThrough = true;
		contextMenuCopyToClipboard.Font = new Font("Segoe UI", 9F);
		contextMenuCopyToClipboard.Items.AddRange(new ToolStripItem[] { toolStripMenuItemCopyToClipboard });
		contextMenuCopyToClipboard.Name = "contextMenuCopyToClipboard";
		contextMenuCopyToClipboard.Size = new Size(214, 26);
		contextMenuCopyToClipboard.TabStop = true;
		contextMenuCopyToClipboard.Text = "Copy to clipboard";
		contextMenuCopyToClipboard.MouseEnter += Control_Enter;
		contextMenuCopyToClipboard.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemCopyToClipboard
		// 
		toolStripMenuItemCopyToClipboard.AccessibleDescription = "Copies the selected row to the clipboard";
		toolStripMenuItemCopyToClipboard.AccessibleName = "Copy to clipboard";
		toolStripMenuItemCopyToClipboard.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemCopyToClipboard.AutoToolTip = true;
		toolStripMenuItemCopyToClipboard.Image = FatcowIcons16px.fatcow_page_copy_16px;
		toolStripMenuItemCopyToClipboard.Name = "toolStripMenuItemCopyToClipboard";
		toolStripMenuItemCopyToClipboard.ShortcutKeyDisplayString = "Strg+C";
		toolStripMenuItemCopyToClipboard.ShortcutKeys = Keys.Control | Keys.C;
		toolStripMenuItemCopyToClipboard.Size = new Size(213, 22);
		toolStripMenuItemCopyToClipboard.Text = "&Copy to clipboard";
		toolStripMenuItemCopyToClipboard.Click += ToolStripMenuItemCopyToClipboard_Click;
		toolStripMenuItemCopyToClipboard.MouseEnter += Control_Enter;
		toolStripMenuItemCopyToClipboard.MouseLeave += Control_Leave;
		// 
		// kryptonStatusStrip
		// 
		kryptonStatusStrip.AccessibleDescription = "Shows some information";
		kryptonStatusStrip.AccessibleName = "Status bar with some information";
		kryptonStatusStrip.AccessibleRole = AccessibleRole.StatusBar;
		kryptonStatusStrip.AllowClickThrough = true;
		kryptonStatusStrip.AllowItemReorder = true;
		kryptonStatusStrip.Font = new Font("Segoe UI", 9F);
		kryptonStatusStrip.Items.AddRange(new ToolStripItem[] { labelInformation });
		kryptonStatusStrip.Location = new Point(0, 598);
		kryptonStatusStrip.Name = "kryptonStatusStrip";
		kryptonStatusStrip.Padding = new Padding(1, 0, 16, 0);
		kryptonStatusStrip.ProgressBars = null;
		kryptonStatusStrip.RenderMode = ToolStripRenderMode.ManagerRenderMode;
		kryptonStatusStrip.ShowItemToolTips = true;
		kryptonStatusStrip.Size = new Size(918, 22);
		kryptonStatusStrip.SizingGrip = false;
		kryptonStatusStrip.TabIndex = 13;
		kryptonStatusStrip.TabStop = true;
		kryptonStatusStrip.Text = "Status bar";
		// 
		// labelInformation
		// 
		labelInformation.AccessibleDescription = "Shows some information";
		labelInformation.AccessibleName = "Shows some information";
		labelInformation.AccessibleRole = AccessibleRole.StaticText;
		labelInformation.AutoToolTip = true;
		labelInformation.Image = FatcowIcons16px.fatcow_lightbulb_16px;
		labelInformation.Name = "labelInformation";
		labelInformation.Size = new Size(144, 17);
		labelInformation.Text = "some information here";
		labelInformation.ToolTipText = "Shows some information";
		// 
		// kryptonManager
		// 
		kryptonManager.GlobalPaletteMode = PaletteMode.Global;
		kryptonManager.ToolkitStrings.MessageBoxStrings.LessDetails = "L&ess Details...";
		kryptonManager.ToolkitStrings.MessageBoxStrings.MoreDetails = "&More Details...";
		// 
		// OrbitalResonancesOfAllMinorPlanetsForm
		// 
		AccessibleDescription = "Shows orbital resonances of all minor planets relative to the 8 solar system planets";
		AccessibleName = "Orbital resonances of all minor planets";
		AccessibleRole = AccessibleRole.Dialog;
		AutoScaleDimensions = new SizeF(7F, 15F);
		AutoScaleMode = AutoScaleMode.Font;
		ClientSize = new Size(918, 620);
		ControlBox = false;
		Controls.Add(kryptoPanelMain);
		FormBorderStyle = FormBorderStyle.FixedToolWindow;
		Icon = (Icon)resources.GetObject("$this.Icon");
		Margin = new Padding(4, 3, 4, 3);
		MaximizeBox = false;
		MinimizeBox = false;
		MinimumSize = new Size(920, 620);
		Name = "OrbitalResonancesOfAllMinorPlanetsForm";
		StartPosition = FormStartPosition.CenterParent;
		Text = "Orbital resonances of all minor planets";
		FormClosing += OrbitalResonancesOfAllMinorPlanetsForm_FormClosing;
		Load += OrbitalResonancesOfAllMinorPlanetsForm_Load;
		((ISupportInitialize)kryptoPanelMain).EndInit();
		kryptoPanelMain.ResumeLayout(false);
		kryptoPanelMain.PerformLayout();
		contextMenuCopyToClipboard.ResumeLayout(false);
		kryptonStatusStrip.ResumeLayout(false);
		kryptonStatusStrip.PerformLayout();
		ResumeLayout(false);
	}

	#endregion

	private KryptonPanel kryptoPanelMain;
	private KryptonButton btnStart;
	private KryptonButton btnCancel;
	private KryptonCheckBox checkBoxMercury;
	private KryptonCheckBox checkBoxVenus;
	private KryptonCheckBox checkBoxEarth;
	private KryptonCheckBox checkBoxMars;
	private KryptonCheckBox checkBoxJupiter;
	private KryptonCheckBox checkBoxSaturn;
	private KryptonCheckBox checkBoxUranus;
	private KryptonCheckBox checkBoxNeptune;
	private KryptonProgressBar kryptonProgressBar;
	private ListView listView;
	private ColumnHeader columnHeaderPlanetoid;
	private ColumnHeader columnHeaderPlanet;
	private ColumnHeader columnHeaderPlanetPeriod;
	private ColumnHeader columnHeaderPlanetoidPeriod;
	private ColumnHeader columnHeaderRatio;
	private ColumnHeader columnHeaderResonance;
	private ColumnHeader columnHeaderDeviation;
	private ColumnHeader columnHeaderIsResonance;
	private ContextMenuStrip contextMenuCopyToClipboard;
	private ToolStripMenuItem toolStripMenuItemCopyToClipboard;
	private KryptonStatusStrip kryptonStatusStrip;
	private ToolStripStatusLabel labelInformation;
	private KryptonManager kryptonManager;
}
