// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using Krypton.Toolkit;

using Planetoid_DB.Resources;

using System.ComponentModel;

namespace Planetoid_DB;

/// <summary>Represents a Windows Form that displays the orbital resonances of a minor planet relative to the eight planets in
/// the solar system.</summary>
/// <remarks>This form provides a user interface for visualizing and interacting with orbital resonance data,
/// including a detailed list view and a status bar for additional information. It is intended to be used as a dialog
/// and does not appear in the taskbar. Controls are organized to facilitate accessibility and usability for exploring
/// resonance relationships.</remarks>
partial class OrbitalResonancesOfOneMinorPlanetForm
{
	/// <summary>Required designer variable.</summary>
	/// <remarks>This field stores the components used by the form.</remarks>
	private IContainer components = null;

	/// <summary>Clean up any resources being used.</summary>
	/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
	/// <remarks>This method is called by the runtime to release resources used by the form.</remarks>
	protected override void Dispose(bool disposing)
	{
		if (disposing && (components != null))
		{
			components.Dispose();
		}
		base.Dispose(disposing);
	}

	#region Windows Form Designer generated code

	/// <summary>Required method for Designer support - do not modify
	/// the contents of this method with the code editor.</summary>
	/// <remarks>This method is automatically generated by the Windows Forms designer and should not be modified manually.
	/// It sets up the controls and their properties for the form.</remarks>
	private void InitializeComponent()
	{
		components = new Container();
		ComponentResourceManager resources = new ComponentResourceManager(typeof(OrbitalResonancesOfOneMinorPlanetForm));
		kryptoPanelMain = new KryptonPanel();
		listView = new ListView();
		columnHeaderPlanet = new ColumnHeader();
		columnHeaderPlanetPeriod = new ColumnHeader();
		columnHeaderPlanetoidPeriod = new ColumnHeader();
		columnHeaderRatio = new ColumnHeader();
		columnHeaderResonance = new ColumnHeader();
		columnHeaderDeviation = new ColumnHeader();
		columnHeaderIsResonance = new ColumnHeader();
		contextMenuCopyToClipboard = new ContextMenuStrip(components);
		toolStripMenuItemCopyToClipboard = new ToolStripMenuItem();
		kryptonStatusStrip = new KryptonStatusStrip();
		labelInformation = new ToolStripStatusLabel();
		kryptonManager = new KryptonManager(components);
		((ISupportInitialize)kryptoPanelMain).BeginInit();
		kryptoPanelMain.SuspendLayout();
		contextMenuCopyToClipboard.SuspendLayout();
		kryptonStatusStrip.SuspendLayout();
		SuspendLayout();
		// 
		// kryptoPanelMain
		// 
		kryptoPanelMain.AccessibleDescription = "Groups the data";
		kryptoPanelMain.AccessibleName = "Panel";
		kryptoPanelMain.AccessibleRole = AccessibleRole.Pane;
		kryptoPanelMain.Controls.Add(listView);
		kryptoPanelMain.Controls.Add(kryptonStatusStrip);
		kryptoPanelMain.Dock = DockStyle.Fill;
		kryptoPanelMain.Location = new Point(0, 0);
		kryptoPanelMain.Name = "kryptoPanelMain";
		kryptoPanelMain.PanelBackStyle = PaletteBackStyle.FormMain;
		kryptoPanelMain.Size = new Size(729, 227);
		kryptoPanelMain.TabIndex = 0;
		kryptoPanelMain.TabStop = true;
		// 
		// listView
		// 
		listView.AccessibleDescription = "Shows the list of orbital resonances relative to the solar system planets";
		listView.AccessibleName = "Orbital resonances list";
		listView.AccessibleRole = AccessibleRole.List;
		listView.AllowColumnReorder = true;
		listView.Columns.AddRange(new ColumnHeader[] { columnHeaderPlanet, columnHeaderPlanetPeriod, columnHeaderPlanetoidPeriod, columnHeaderRatio, columnHeaderResonance, columnHeaderDeviation, columnHeaderIsResonance });
		listView.ContextMenuStrip = contextMenuCopyToClipboard;
		listView.Dock = DockStyle.Fill;
		listView.Font = new Font("Segoe UI", 9F);
		listView.FullRowSelect = true;
		listView.GridLines = true;
		listView.Location = new Point(0, 0);
		listView.Name = "listView";
		listView.ShowItemToolTips = true;
		listView.Size = new Size(729, 205);
		listView.TabIndex = 0;
		listView.UseCompatibleStateImageBehavior = false;
		listView.View = View.Details;
		listView.Enter += Control_Enter;
		listView.Leave += Control_Leave;
		listView.MouseEnter += Control_Enter;
		listView.MouseLeave += Control_Leave;
		// 
		// columnHeaderPlanet
		// 
		columnHeaderPlanet.Text = "Planet";
		columnHeaderPlanet.Width = 120;
		// 
		// columnHeaderPlanetPeriod
		// 
		columnHeaderPlanetPeriod.Text = "Planet Period (yr)";
		columnHeaderPlanetPeriod.TextAlign = HorizontalAlignment.Right;
		columnHeaderPlanetPeriod.Width = 120;
		// 
		// columnHeaderPlanetoidPeriod
		// 
		columnHeaderPlanetoidPeriod.Text = "Planetoid Period (yr)";
		columnHeaderPlanetoidPeriod.TextAlign = HorizontalAlignment.Right;
		columnHeaderPlanetoidPeriod.Width = 130;
		// 
		// columnHeaderRatio
		// 
		columnHeaderRatio.Text = "Ratio";
		columnHeaderRatio.TextAlign = HorizontalAlignment.Right;
		columnHeaderRatio.Width = 80;
		// 
		// columnHeaderResonance
		// 
		columnHeaderResonance.Text = "Resonance";
		columnHeaderResonance.TextAlign = HorizontalAlignment.Center;
		columnHeaderResonance.Width = 90;
		// 
		// columnHeaderDeviation
		// 
		columnHeaderDeviation.Text = "Deviation (%)";
		columnHeaderDeviation.TextAlign = HorizontalAlignment.Right;
		columnHeaderDeviation.Width = 90;
		// 
		// columnHeaderIsResonance
		// 
		columnHeaderIsResonance.Text = "Is Resonance";
		columnHeaderIsResonance.TextAlign = HorizontalAlignment.Center;
		columnHeaderIsResonance.Width = 90;
		// 
		// contextMenuCopyToClipboard
		// 
		contextMenuCopyToClipboard.AccessibleDescription = "Shows the context menu for copying information to the clipboard";
		contextMenuCopyToClipboard.AccessibleName = "Context menu for copying information to the clipboard";
		contextMenuCopyToClipboard.AccessibleRole = AccessibleRole.MenuPopup;
		contextMenuCopyToClipboard.AllowClickThrough = true;
		contextMenuCopyToClipboard.Font = new Font("Segoe UI", 9F);
		contextMenuCopyToClipboard.Items.AddRange(new ToolStripItem[] { toolStripMenuItemCopyToClipboard });
		contextMenuCopyToClipboard.Name = "contextMenuStrip";
		contextMenuCopyToClipboard.Size = new Size(214, 26);
		contextMenuCopyToClipboard.TabStop = true;
		contextMenuCopyToClipboard.Text = "Copy to clipboard";
		contextMenuCopyToClipboard.MouseEnter += Control_Enter;
		contextMenuCopyToClipboard.MouseLeave += Control_Leave;
		// 
		// toolStripMenuItemCopyToClipboard
		// 
		toolStripMenuItemCopyToClipboard.AccessibleDescription = "Copies the selected row to the clipboard";
		toolStripMenuItemCopyToClipboard.AccessibleName = "Copy to clipboard";
		toolStripMenuItemCopyToClipboard.AccessibleRole = AccessibleRole.MenuItem;
		toolStripMenuItemCopyToClipboard.AutoToolTip = true;
		toolStripMenuItemCopyToClipboard.Image = FatcowIcons16px.fatcow_page_copy_16px;
		toolStripMenuItemCopyToClipboard.Name = "toolStripMenuItemCopyToClipboard";
		toolStripMenuItemCopyToClipboard.ShortcutKeyDisplayString = "Strg+C";
		toolStripMenuItemCopyToClipboard.ShortcutKeys = Keys.Control | Keys.C;
		toolStripMenuItemCopyToClipboard.Size = new Size(213, 22);
		toolStripMenuItemCopyToClipboard.Text = "&Copy to clipboard";
		toolStripMenuItemCopyToClipboard.Click += ToolStripMenuItemCopyToClipboard_Click;
		toolStripMenuItemCopyToClipboard.MouseEnter += Control_Enter;
		toolStripMenuItemCopyToClipboard.MouseLeave += Control_Leave;
		// 
		// kryptonStatusStrip
		// 
		kryptonStatusStrip.AccessibleDescription = "Shows some information";
		kryptonStatusStrip.AccessibleName = "Status bar with some information";
		kryptonStatusStrip.AccessibleRole = AccessibleRole.StatusBar;
		kryptonStatusStrip.AllowClickThrough = true;
		kryptonStatusStrip.AllowItemReorder = true;
		kryptonStatusStrip.Font = new Font("Segoe UI", 9F);
		kryptonStatusStrip.Items.AddRange(new ToolStripItem[] { labelInformation });
		kryptonStatusStrip.Location = new Point(0, 205);
		kryptonStatusStrip.Name = "kryptonStatusStrip";
		kryptonStatusStrip.Padding = new Padding(1, 0, 16, 0);
		kryptonStatusStrip.ProgressBars = null;
		kryptonStatusStrip.RenderMode = ToolStripRenderMode.ManagerRenderMode;
		kryptonStatusStrip.ShowItemToolTips = true;
		kryptonStatusStrip.Size = new Size(729, 22);
		kryptonStatusStrip.SizingGrip = false;
		kryptonStatusStrip.TabIndex = 1;
		kryptonStatusStrip.TabStop = true;
		kryptonStatusStrip.Text = "Status bar";
		// 
		// labelInformation
		// 
		labelInformation.AccessibleDescription = "Shows some information";
		labelInformation.AccessibleName = "Shows some information";
		labelInformation.AccessibleRole = AccessibleRole.StaticText;
		labelInformation.AutoToolTip = true;
		labelInformation.Image = FatcowIcons16px.fatcow_lightbulb_16px;
		labelInformation.Margin = new Padding(5, 3, 0, 2);
		labelInformation.Name = "labelInformation";
		labelInformation.Size = new Size(144, 17);
		labelInformation.Text = "some information here";
		labelInformation.ToolTipText = "Shows some information";
		// 
		// kryptonManager
		// 
		kryptonManager.GlobalPaletteMode = PaletteMode.Global;
		kryptonManager.ToolkitStrings.MessageBoxStrings.LessDetails = "L&ess Details...";
		kryptonManager.ToolkitStrings.MessageBoxStrings.MoreDetails = "&More Details...";
		// 
		// OrbitalResonancesOfOneMinorPlanetForm
		// 
		AccessibleDescription = "Shows orbital resonances of the planetoid relative to the 8 planets";
		AccessibleName = "Orbital resonances";
		AccessibleRole = AccessibleRole.Dialog;
		AutoScaleDimensions = new SizeF(7F, 15F);
		AutoScaleMode = AutoScaleMode.Font;
		ClientSize = new Size(729, 227);
		ControlBox = false;
		Controls.Add(kryptoPanelMain);
		FormBorderStyle = FormBorderStyle.FixedToolWindow;
		Icon = (Icon)resources.GetObject("$this.Icon");
		Margin = new Padding(4, 3, 4, 3);
		MaximizeBox = false;
		MinimizeBox = false;
		Name = "OrbitalResonancesOfOneMinorPlanetForm";
		StartPosition = FormStartPosition.CenterParent;
		Text = "Orbital resonances";
		Load += OrbitalResonanceForm_Load;
		((ISupportInitialize)kryptoPanelMain).EndInit();
		kryptoPanelMain.ResumeLayout(false);
		kryptoPanelMain.PerformLayout();
		contextMenuCopyToClipboard.ResumeLayout(false);
		kryptonStatusStrip.ResumeLayout(false);
		kryptonStatusStrip.PerformLayout();
		ResumeLayout(false);
	}

	#endregion

	private KryptonPanel kryptoPanelMain;
	private ListView listView;
	private ColumnHeader columnHeaderPlanet;
	private ColumnHeader columnHeaderPlanetPeriod;
	private ColumnHeader columnHeaderPlanetoidPeriod;
	private ColumnHeader columnHeaderRatio;
	private ColumnHeader columnHeaderResonance;
	private ColumnHeader columnHeaderDeviation;
	private ColumnHeader columnHeaderIsResonance;
	private ContextMenuStrip contextMenuCopyToClipboard;
	private ToolStripMenuItem toolStripMenuItemCopyToClipboard;
	private KryptonStatusStrip kryptonStatusStrip;
	private ToolStripStatusLabel labelInformation;
	private KryptonManager kryptonManager;
}
