// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using Krypton.Toolkit;

using System.ComponentModel;

namespace Planetoid_DB.Forms;

/// <summary>Provides a user interface for grouping orbital elements of planetoids.</summary>
/// <remarks>This form allows users to specify parameters for grouping orbital elements, including tolerance and
/// the number of elements to compare. It also displays progress during the grouping operation.</remarks>
partial class OrbitElementsGroupingForm
{
	/// <summary>Required designer variable.</summary>
	/// <remarks>This field stores the components used by the form.</remarks>
	private IContainer components = null;

    /// <summary>Releases all resources used by the <see cref="OrbitElementsGroupingForm"/>.</summary>
    /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
    /// <remarks>This method is called by the runtime to release resources used by the form.</remarks>
	protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }
        base.Dispose(disposing);
    }

	/// <summary>Initializes the components of the form.</summary>
	/// <remarks>This method is automatically generated by the Windows Forms designer and should not be modified manually.
	/// It sets up the controls and their properties for the form.</remarks>
	private void InitializeComponent()
	{
		ComponentResourceManager resources = new ComponentResourceManager(typeof(OrbitElementsGroupingForm));
		kryptoPanelMain = new KryptonPanel();
		lblProgress = new KryptonLabel();
		progressBar = new KryptonProgressBar();
		lblElementsCount = new KryptonLabel();
		numElementsToCompare = new KryptonNumericUpDown();
		lblTolerance = new KryptonLabel();
		numTolerance = new KryptonNumericUpDown();
		btnCancel = new KryptonButton();
		btnStart = new KryptonButton();
		txtOutput = new KryptonRichTextBox();
		((ISupportInitialize)kryptoPanelMain).BeginInit();
		kryptoPanelMain.SuspendLayout();
		SuspendLayout();
		// 
		// kryptoPanelMain
		// 
		kryptoPanelMain.AccessibleDescription = "Groups the data";
		kryptoPanelMain.AccessibleName = "Panel";
		kryptoPanelMain.AccessibleRole = AccessibleRole.Pane;
		kryptoPanelMain.Controls.Add(lblProgress);
		kryptoPanelMain.Controls.Add(progressBar);
		kryptoPanelMain.Controls.Add(lblElementsCount);
		kryptoPanelMain.Controls.Add(numElementsToCompare);
		kryptoPanelMain.Controls.Add(lblTolerance);
		kryptoPanelMain.Controls.Add(numTolerance);
		kryptoPanelMain.Controls.Add(btnCancel);
		kryptoPanelMain.Controls.Add(btnStart);
		kryptoPanelMain.Controls.Add(txtOutput);
		kryptoPanelMain.Dock = DockStyle.Fill;
		kryptoPanelMain.Location = new Point(0, 0);
		kryptoPanelMain.Name = "kryptoPanelMain";
		kryptoPanelMain.Size = new Size(784, 561);
		kryptoPanelMain.TabIndex = 0;
		kryptoPanelMain.TabStop = true;
		// 
		// lblProgress
		// 
		lblProgress.Location = new Point(718, 51);
		lblProgress.Name = "lblProgress";
		lblProgress.Size = new Size(40, 20);
		lblProgress.TabIndex = 7;
		lblProgress.Values.Text = "0%";
		// 
		// progressBar
		// 
		progressBar.Location = new Point(12, 50);
		progressBar.Name = "progressBar";
		progressBar.Size = new Size(700, 23);
		progressBar.TabIndex = 6;
		progressBar.Text = "Label";
		progressBar.TextBackdropColor = Color.Empty;
		progressBar.TextShadowColor = Color.Empty;
		// 
		// lblElementsCount
		// 
		lblElementsCount.Location = new Point(390, 15);
		lblElementsCount.Name = "lblElementsCount";
		lblElementsCount.Size = new Size(130, 20);
		lblElementsCount.TabIndex = 4;
		lblElementsCount.Values.Text = "Elements vs Elements:";
		// 
		// numElementsToCompare
		// 
		numElementsToCompare.Increment = new decimal(new int[] { 1, 0, 0, 0 });
		numElementsToCompare.Location = new Point(520, 14);
		numElementsToCompare.Maximum = new decimal(new int[] { 7, 0, 0, 0 });
		numElementsToCompare.Minimum = new decimal(new int[] { 2, 0, 0, 0 });
		numElementsToCompare.Name = "numElementsToCompare";
		numElementsToCompare.Size = new Size(60, 22);
		numElementsToCompare.TabIndex = 5;
		numElementsToCompare.Value = new decimal(new int[] { 3, 0, 0, 0 });
		// 
		// lblTolerance
		// 
		lblTolerance.Location = new Point(210, 15);
		lblTolerance.Name = "lblTolerance";
		lblTolerance.Size = new Size(94, 20);
		lblTolerance.TabIndex = 2;
		lblTolerance.Values.Text = "Tolerance (%):";
		// 
		// numTolerance
		// 
		numTolerance.Increment = new decimal(new int[] { 1, 0, 0, 0 });
		numTolerance.Location = new Point(310, 14);
		numTolerance.Maximum = new decimal(new int[] { 100, 0, 0, 0 });
		numTolerance.Minimum = new decimal(new int[] { 1, 0, 0, 65536 });
		numTolerance.Name = "numTolerance";
		numTolerance.Size = new Size(60, 22);
		numTolerance.TabIndex = 3;
		numTolerance.Value = new decimal(new int[] { 5, 0, 0, 0 });
		// 
		// btnCancel
		// 
		btnCancel.Enabled = false;
		btnCancel.Location = new Point(108, 12);
		btnCancel.Name = "btnCancel";
		btnCancel.Size = new Size(90, 25);
		btnCancel.TabIndex = 1;
		btnCancel.Values.DropDownArrowColor = Color.Empty;
		btnCancel.Values.Text = "&Cancel";
		btnCancel.Click += BtnCancel_Click;
		// 
		// btnStart
		// 
		btnStart.Location = new Point(12, 12);
		btnStart.Name = "btnStart";
		btnStart.Size = new Size(90, 25);
		btnStart.TabIndex = 0;
		btnStart.Values.DropDownArrowColor = Color.Empty;
		btnStart.Values.Text = "&Start Search";
		btnStart.Click += BtnStart_Click;
		// 
		// txtOutput
		// 
		txtOutput.Location = new Point(12, 85);
		txtOutput.Name = "txtOutput";
		txtOutput.ReadOnly = true;
		txtOutput.ShowSelectionMargin = true;
		txtOutput.Size = new Size(760, 464);
		txtOutput.TabIndex = 8;
		txtOutput.Text = "";
		txtOutput.WordWrap = false;
		// 
		// OrbitElementsGroupingForm
		// 
		AccessibleDescription = "Shows orbit element grouping";
		AccessibleName = "Orbit elements grouping";
		AccessibleRole = AccessibleRole.Dialog;
		AutoScaleDimensions = new SizeF(7F, 15F);
		AutoScaleMode = AutoScaleMode.Font;
		ClientSize = new Size(784, 561);
		ControlBox = false;
		Controls.Add(kryptoPanelMain);
		FormBorderStyle = FormBorderStyle.FixedToolWindow;
		Icon = (Icon)resources.GetObject("$this.Icon");
		MaximizeBox = false;
		MinimizeBox = false;
		Name = "OrbitElementsGroupingForm";
		ShowInTaskbar = false;
		StartPosition = FormStartPosition.CenterParent;
		Text = "Planetoid Orbital Elements Grouping";
		FormClosing += OrbitElementsGroupingForm_FormClosing;
		((ISupportInitialize)kryptoPanelMain).EndInit();
		kryptoPanelMain.ResumeLayout(false);
		kryptoPanelMain.PerformLayout();
		ResumeLayout(false);
	}

	private KryptonPanel kryptoPanelMain;
    private KryptonButton btnStart;
    private KryptonButton btnCancel;
    private KryptonProgressBar progressBar;
    private KryptonRichTextBox txtOutput;
    private KryptonNumericUpDown numTolerance;
    private KryptonLabel lblTolerance;
    private KryptonNumericUpDown numElementsToCompare;
    private KryptonLabel lblElementsCount;
    private KryptonLabel lblProgress;
}
