// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using Krypton.Toolkit;

using NLog;

using Planetoid_DB.Forms;
using Planetoid_DB.Helpers;

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Reflection;

namespace Planetoid_DB;

/// <summary>Main form for managing records in the Planetoid database.</summary>
/// <remarks>This form provides a user interface for viewing and editing records in the database.</remarks>
// You can customize the debugger display for this class by providing a method that returns a string representation of the instance, which will be shown in the debugger when you inspect an object of this class. In this case, the GetDebuggerDisplay method is used to return a string representation of the instance, and the DebuggerDisplay attribute is applied to the class to specify that this method should be used for the debugger display.
[DebuggerDisplay(value: "{" + nameof(GetDebuggerDisplay) + "(),nq}")]
public partial class RecordsTop10Form : BaseKryptonForm
{
	/// <summary>NLog logger instance for the class.</summary>
	/// <remarks>This logger is used to log messages for the database downloader.</remarks>
	private static readonly Logger logger = LogManager.GetCurrentClassLogger();

	/// <summary>Stores a copy of the planetoids database used for record scanning.</summary>
	/// <remarks>The data is copied so scans remain independent from live edits in the main form.</remarks>
	private List<string> planetoidsDatabase = [];

	/// <summary>Holds the currently displayed top-ten result list.</summary>
	/// <remarks>The list order reflects the active sort order from the toolbar.</remarks>
	private List<TopRecordEntry> topRecords = [];

	/// <summary>Cancellation token source for the currently running scan.</summary>
	/// <remarks>When null, no scan is currently active.</remarks>
	private CancellationTokenSource? cancellationTokenSource;

	/// <summary>Holds one top-ten entry containing designation, numeric value, and display value.</summary>
	/// <param name="Designation">Readable designation of the planetoid.</param>
	/// <param name="StringValue">Original string value as shown from source data.</param>
	/// <param name="NumericValue">Numeric value used for ranking and comparison.</param>
	private readonly record struct TopRecordEntry(string Designation, string StringValue, double NumericValue);

	/// <summary>Gets the status label to be used for displaying information.</summary>
	/// <remarks>Derived classes should override this property to provide the specific label.</remarks>
	protected override ToolStripStatusLabel? StatusLabel => labelInformation;

	#region constructor

	/// <summary>Initializes a new instance of the <see cref="RecordsTop10Form"/> class.</summary>
	/// <remarks>This constructor initializes the form components.</remarks>
	public RecordsTop10Form() : this(arrTemp: [], selectedElement: null)
	{
	}

	/// <summary>Initializes a new instance of the <see cref="RecordsTop10Form"/> class with an initial database copy and an optional preselected element.</summary>
	/// <param name="arrTemp">Source database records to copy into this form.</param>
	/// <param name="selectedElement">Optional orbital element text to preselect in the element list.</param>
	/// <remarks>This overload supports opening the form directly on a specific orbital element.</remarks>
	public RecordsTop10Form(List<string> arrTemp, string? selectedElement)
	{
		// Initialize the form components, which sets up the UI controls and layout. This is typically generated by the Windows Forms designer and should be called before any other initialization logic to ensure that the controls are available for configuration.
		InitializeComponent();
		// Copy the provided database records into this form's local list to ensure the scan operates on a consistent snapshot, independent of any live edits in the main form. This allows the user to start a scan immediately after opening the form with a specific element preselected, without needing to rely on external data assignment after construction.
		FillArray(arrTemp: arrTemp);
		// Attempt to preselect the specified orbital element in the list box. If the provided text is null, empty, or does not match any item, the first element will be selected by default.
		PreselectOrbitalElement(selectedElement: selectedElement);
		// Initialize UI behavior such as wiring sort order toggles and enabling double buffering for smoother updates.
		InitializeUiBehavior();
	}

	#endregion

	#region helper methods

	/// <summary>Returns a short debugger display string for this instance.</summary>
	/// <returns>A string representation of the current instance for use in the debugger.</returns>
	/// <remarks>This method is called to obtain a string representation of the current instance.</remarks>
	private string GetDebuggerDisplay() => ToString();

	/// <summary>Copies the provided planetoid database into this form instance.</summary>
	/// <param name="arrTemp">Source records from the main form.</param>
	/// <remarks>Use this when the parameterless constructor is used and data is assigned afterwards.</remarks>
	public void FillArray(List<string> arrTemp) => planetoidsDatabase = [.. arrTemp];

	/// <summary>Initializes runtime UI wiring and default state for scan interactions.</summary>
	/// <remarks>Wires sort-order toggle behavior, configures defaults, and enables smoother repainting of the table layout.</remarks>
	private void InitializeUiBehavior()
	{
		// Wire sort order toggle behavior to ensure only one can be active at a time
		if (listBox.SelectedIndex < 0 && listBox.Items.Count > 0)
		{
			listBox.SelectedIndex = 0;
		}
		// Enable double buffering on the table layout panel to reduce flickering during updates. This is done via reflection since the DoubleBuffered property is protected on Control. If this fails, we log a warning but continue without double buffering.
		SetGotoButtonsEnabled(isEnabled: false);
		toolStripButtonCancel.Enabled = false;
		// The following code attempts to set the DoubleBuffered property of the tableLayoutPanel to true using reflection, and also invokes the SetStyle method to enable optimized double buffering and reduce flickering during updates. If any exceptions occur during this process, a warning is logged but the application continues to function without double buffering.
		try
		{
			// Use reflection to set the protected DoubleBuffered property to true
			PropertyInfo? dbProp = typeof(Control).GetProperty(name: "DoubleBuffered", bindingAttr: BindingFlags.NonPublic | BindingFlags.Instance);
			// If the property is found, set it to true for the tableLayoutPanel
			dbProp?.SetValue(obj: tableLayoutPanel, value: true, index: null);
			// Additionally, invoke the SetStyle method to enable optimized double buffering and all painting in WM_PAINT to further reduce flickering
			MethodInfo? setStyleMethod = typeof(Control).GetMethod(name: "SetStyle", bindingAttr: BindingFlags.NonPublic | BindingFlags.Instance);
			// If the SetStyle method is found, invoke it with the appropriate ControlStyles flags to enable double buffering and reduce flickering
			setStyleMethod?.Invoke(obj: tableLayoutPanel, parameters: [ControlStyles.OptimizedDoubleBuffer | ControlStyles.AllPaintingInWmPaint, true]);
		}
		// Catch any exceptions that may occur during reflection and log a warning. This ensures that if double buffering cannot be enabled for some reason, the application will still run without it, albeit with potentially more flickering during updates.
		catch (Exception ex)
		{
			// Log a warning if we fail to set double buffering, but continue without it
			logger.Warn(exception: ex, message: "Could not set DoubleBuffered on tableLayoutPanel");
		}
	}

	/// <summary>Preselects an orbital element by display text when available.</summary>
	/// <param name="selectedElement">The element name to select, such as "Semi-major axis".</param>
	/// <remarks>Matching is case-insensitive and allows partial text matches.</remarks>
	private void PreselectOrbitalElement(string? selectedElement)
	{
		// If the provided selectedElement text is null, empty, or consists only of whitespace, or if the list box has no items, we default to selecting the first item (index 0) if nothing is currently selected. This ensures that there is always a valid selection when the form is initialized, even if the input for preselection is not valid.
		if (string.IsNullOrWhiteSpace(value: selectedElement) || listBox.Items.Count == 0)
		{
			// No valid preselection text or no items in the list box, default to selecting the first item if nothing is currently selected
			if (listBox.SelectedIndex < 0)
			{
				listBox.SelectedIndex = 0;
			}
			return;
		}
		// We attempt to find a matching item in the list box by comparing the display text of each item with the provided selectedElement text. The comparison is case-insensitive and allows for partial matches (i.e., if the item text contains the selectedElement text). If a match is found, we select that item; otherwise, we default to selecting the first item (index 0).
		int matchIndex = -1;
		for (int i = 0; i < listBox.Items.Count; i++)
		{
			// Get the display text of the current item, ensuring we handle null values gracefully by treating them as empty strings. This allows us to perform comparisons without risking null reference exceptions.
			string itemText = listBox.Items[index: i]?.ToString() ?? string.Empty;
			// Perform a case-insensitive comparison to check if the item text matches the selectedElement text exactly or contains it as a substring. If a match is found, we store the index and break out of the loop.
			if (itemText.Equals(value: selectedElement, comparisonType: StringComparison.OrdinalIgnoreCase) || itemText.Contains(value: selectedElement, comparisonType: StringComparison.OrdinalIgnoreCase))
			{
				// A match is found, store the index and exit the loop
				matchIndex = i;
				break;
			}
		}
		// Set the selected index to the found match or default to 0 if no match is found
		listBox.SelectedIndex = matchIndex >= 0 ? matchIndex : 0;
	}

	/// <summary>Gets designation labels in rank order from place 1 to place 10.</summary>
	/// <returns>Array of designation labels bound to rank rows.</returns>
	/// <remarks>The designation labels are used to display the readable designation of the planetoid for each rank in the top-ten list.</remarks>
	private KryptonLabel[] GetDesignationLabels() =>
	[
		labelReadableDesignation01, labelReadableDesignation02, labelReadableDesignation03, labelReadableDesignation04, labelReadableDesignation05,
		labelReadableDesignation06, labelReadableDesignation07, labelReadableDesignation08, labelReadableDesignation09, labelReadableDesignation10
	];

	/// <summary>Gets value labels in rank order from place 1 to place 10.</summary>
	/// <returns>Array of value labels bound to rank rows.</returns>
	/// <remarks>The value labels are used to display the numeric value of the selected orbital element for each rank in the top-ten list.</remarks>
	private KryptonLabel[] GetValueLabels() =>
	[
		labelValue01, labelValue02, labelValue03, labelValue04, labelValue05,
		labelValue06, labelValue07, labelValue08, labelValue09, labelValue10
	];

	/// <summary>Gets "Goto" buttons in rank order from place 1 to place 10.</summary>
	/// <returns>Array of navigation buttons bound to rank rows.</returns>
	/// <remarks>The "Goto" buttons allow the user to navigate from a specific rank in the top-ten list to the corresponding planetoid record in the main form.</remarks>
	private KryptonButton[] GetGotoButtons() =>
	[
		buttonGoto01, buttonGoto02, buttonGoto03, buttonGoto04, buttonGoto05,
		buttonGoto06, buttonGoto07, buttonGoto08, buttonGoto09, buttonGoto10
	];

	/// <summary>Resets all result labels and clears tracked top-ten data.</summary>
	/// <remarks>This method is called before each new scan run.</remarks>
	private void ResetLabels()
	{
		// Reset all designation and value labels to a default state (e.g., "-") to indicate that no data is currently displayed. This prepares the UI for a new scan run by clearing any previous results from the labels. Additionally, we clear the topRecords list to remove any previously tracked top-ten entries, ensuring that the new scan starts with a clean slate.
		KryptonLabel[] designationLabels = GetDesignationLabels();
		KryptonLabel[] valueLabels = GetValueLabels();
		// Iterate through each pair of designation and value labels and set their text to a default placeholder (e.g., "-"). This visually indicates to the user that the previous results have been cleared and that new results will be displayed after the next scan is performed.
		for (int i = 0; i < designationLabels.Length; i++)
		{
			// Set the text of each designation and value label to a default placeholder (e.g., "-") to indicate that no results are currently displayed. This visually resets the table for the user before a new scan is performed.
			designationLabels[i].Values.Text = "-";
			valueLabels[i].Values.Text = "-";
		}
		// Clear the tracked top-ten records to ensure we start fresh for the new scan
		topRecords = [];
	}

	/// <summary>Enables or disables all rank navigation buttons.</summary>
	/// <param name="isEnabled">True to enable, false to disable.</param>
	/// <remarks>Buttons are enabled when there are valid top-ten records to navigate to, and disabled when no records are available or during an active scan.</remarks>
	private void SetGotoButtonsEnabled(bool isEnabled)
	{
		// Iterate through each "Goto" button and set its Enabled property based on the provided isEnabled parameter. This allows us to enable the buttons when there are valid top-ten records to navigate to, and disable them when no records are available or during an active scan to prevent navigation to non-existent records.
		foreach (KryptonButton button in GetGotoButtons())
		{
			button.Enabled = isEnabled;
		}
	}

	/// <summary>Attempts to extract the currently selected orbital element as a numeric and display value.</summary>
	/// <param name="record">Parsed planetoid record.</param>
	/// <param name="selectedElementIndex">Selected orbital element index from the list box.</param>
	/// <param name="stringValue">Returns the original string representation for display.</param>
	/// <param name="numericValue">Returns the numeric value used for comparison.</param>
	/// <returns>True when extraction and parsing succeed; otherwise false.</returns>
	/// <remarks>The method maps the selected element index to the corresponding field in the record, retrieves the original string value for display, and attempts to parse it into a numeric value for ranking. It handles both integer and floating-point fields appropriately based on the selected element.</remarks>
	private static bool TryGetSelectedElementValue(PlanetoidRecord record, int selectedElementIndex, [NotNullWhen(returnValue: true)] out string? stringValue, out double numericValue)
	{
		// Map the selected element index to the corresponding field in the PlanetoidRecord and retrieve the original string value for display. The mapping is based on the order of elements in the list box, where each index corresponds to a specific orbital element. If the selected index does not match any known element, stringValue will be set to null.
		stringValue = selectedElementIndex switch
		{
			0 => record.MeanAnomaly,
			1 => record.ArgPeri,
			2 => record.LongAscNode,
			3 => record.Incl,
			4 => record.OrbEcc,
			5 => record.Motion,
			6 => record.SemiMajorAxis,
			7 => record.MagAbs,
			8 => record.SlopeParam,
			9 => record.NumberOpposition,
			10 => record.NumberObservation,
			11 => record.RmsResidual,
			_ => null
		};
		// If the retrieved string value is null, empty, or consists only of whitespace, we cannot parse it into a numeric value, so we set numericValue to 0 and return false to indicate that extraction and parsing did not succeed.
		if (string.IsNullOrWhiteSpace(value: stringValue))
		{
			numericValue = 0;
			return false;
		}
		// Determine if the selected element is an integer field (Number of Oppositions or Number of Observations) based on the selected index. This is important because we need to use different parsing logic for integer fields versus floating-point fields. The method uses int.TryParse for integer fields and double.TryParse for floating-point fields, both with invariant culture to ensure consistent parsing regardless of the user's locale settings.
		bool isIntegerField = selectedElementIndex is 9 or 10;
		if (isIntegerField && int.TryParse(s: stringValue, style: NumberStyles.Integer, provider: CultureInfo.InvariantCulture, result: out int intValue))
		{
			numericValue = intValue;
			return true;
		}
		// For non-integer fields, we attempt to parse the string value as a double. If parsing succeeds, we return true and set numericValue to the parsed double value. If parsing fails, we set numericValue to 0 and return false to indicate that extraction and parsing did not succeed.
		if (!isIntegerField && double.TryParse(s: stringValue, style: NumberStyles.Float, provider: CultureInfo.InvariantCulture, result: out double doubleValue))
		{
			numericValue = doubleValue;
			return true;
		}
		// If we reach this point, it means that parsing failed for the selected element, so we set numericValue to 0 and return false to indicate that extraction and parsing did not succeed.
		numericValue = 0;
		return false;
	}

	/// <summary>Inserts a candidate into the top-ten list when it qualifies for the active sort order.</summary>
	/// <param name="entries">Mutable list with current top-ten entries.</param>
	/// <param name="candidate">Candidate entry to evaluate.</param>
	/// <param name="isAscending">True for ascending (smallest first), false for descending (largest first).</param>
	/// <returns>True when the visible top-ten list changed; otherwise false.</returns>
	/// <remarks>The method adds the candidate to the list, sorts it according to the active sort order, and then trims it to maintain only the top ten entries. It returns true if the candidate remains in the list after this process, indicating that it qualifies for the top-ten display.</remarks>
	private static bool TryInsertTopRecord(List<TopRecordEntry> entries, TopRecordEntry candidate, bool isAscending)
	{
		// Add the candidate entry to the list of current top-ten entries and sort the list based on the active sort order. The sorting is done using a comparison that compares the NumericValue of the entries, either in ascending or descending order depending on the isAscending parameter. After sorting, we check if the list exceeds ten entries, and if so, we remove the excess entries to maintain only the top ten. Finally, we return true if the candidate entry remains in the list after this process, indicating that it qualifies for the top-ten display; otherwise, we return false.
		entries.Add(item: candidate);
		// Sort the entries based on the active sort order. If isAscending is true, we sort in ascending order (smallest values first); if false, we sort in descending order (largest values first). The comparison is done by comparing the NumericValue of the entries.
		entries.Sort(comparison: (left, right) => isAscending
			? left.NumericValue.CompareTo(value: right.NumericValue)
			: right.NumericValue.CompareTo(value: left.NumericValue));
		// If the list exceeds ten entries after adding the candidate and sorting, we remove the excess entries starting from index 10 to maintain only the top ten entries in the list. This ensures that the list always contains at most ten entries, which are the top records based on the active sort order.
		if (entries.Count > 10)
		{
			entries.RemoveRange(index: 10, count: entries.Count - 10);
		}
		// Return true if the candidate entry is still in the list after adding, sorting, and trimming to the top ten; otherwise, return false. This indicates whether the candidate qualifies for the top-ten display based on its numeric value and the active sort order.
		return entries.Contains(item: candidate);
	}

	/// <summary>Applies a top-ten snapshot to the table labels.</summary>
	/// <param name="entries">Ordered top-ten entries to display.</param>
	/// <remarks>Values are shown exactly as original source strings.</remarks>
	private void ApplyTopRecords(IReadOnlyList<TopRecordEntry> entries)
	{
		// Update the designation and value labels for each rank based on the provided top-ten entries. The method iterates through the labels and updates their text with the corresponding designation and string value from the entries list. If there are fewer than ten entries, the remaining labels are set to a default placeholder (e.g., "-") to indicate that no data is available for those ranks. This ensures that the UI accurately reflects the current top-ten records based on the latest scan results.
		KryptonLabel[] designationLabels = GetDesignationLabels();
		KryptonLabel[] valueLabels = GetValueLabels();
		for (int i = 0; i < designationLabels.Length; i++)
		{
			// Update the designation and value labels based on the corresponding entry in the top-ten entries list. If an entry exists for the current index, we set the labels to the entry's Designation and StringValue; otherwise, we set them to a default placeholder (e.g., "-").
			if (i < entries.Count)
			{
				// Set the designation label to the entry's Designation and the value label to the entry's StringValue for the current index. This updates the UI to reflect the current top-ten records based on the latest scan results.
				designationLabels[i].Values.Text = entries[index: i].Designation;
				valueLabels[i].Values.Text = entries[index: i].StringValue;
			}
			else
			{
				// No entry exists for this index, so we set the labels to a default placeholder (e.g., "-") to indicate that no data is available for this rank.
				designationLabels[i].Values.Text = "-";
				valueLabels[i].Values.Text = "-";
			}
		}
	}

	/// <summary>Runs the top-ten scan asynchronously for the selected orbital element.</summary>
	/// <param name="selectedElementIndex">Selected orbital element index.</param>
	/// <param name="isAscending">True for ascending (smallest values first), false for descending.</param>
	/// <param name="token">Cancellation token for cooperative cancellation.</param>
	/// <param name="progress">Progress callback for percent and live top-ten updates.</param>
	/// <returns>A task that completes when scanning is finished or cancelled.</returns>
	/// <remarks>The method runs the scan on a background thread to keep the UI responsive. It iterates through the planetoid records, extracts the relevant value for the selected element, and maintains a live top-ten list based on the active sort order. Progress updates are reported to update the progress bar and optionally refresh the displayed top-ten results as they are found.</remarks>
	private async Task ScanTopRecordsAsync(int selectedElementIndex, bool isAscending, CancellationToken token, IProgress<(int Percent, List<TopRecordEntry>? UpdatedEntries)> progress)
	{
		// Run the scan on a background thread to keep the UI responsive. The method iterates through the planetoid records, extracts the relevant value for the selected element, and maintains a live top-ten list based on the active sort order. Progress updates are reported to update the progress bar and optionally refresh the displayed top-ten results as they are found.
		await Task.Run(action: () =>
		{
			// Initialize a mutable list to hold the current top-ten entries as we scan through the records. This list will be updated dynamically as we evaluate each record and determine if it qualifies for the top-ten display based on the selected orbital element and active sort order.
			List<TopRecordEntry> currentTopEntries = [];
			int total = planetoidsDatabase.Count;
			int lastPercent = -1;
			// Iterate through each record in the planetoids database, checking for cancellation at each step to allow for cooperative cancellation of the scan. For each record, we attempt to parse it into a PlanetoidRecord and extract the relevant value for the selected orbital element. If the value is valid and qualifies for the top-ten list based on the active sort order, we update the current top-ten entries and report progress to update the UI with the latest results.
			for (int i = 0; i < total; i++)
			{
				token.ThrowIfCancellationRequested();
				int percent = (int)((i + 1) * 100L / total);
				// Attempt to parse the current record and extract the relevant value for the selected orbital element. If parsing fails or the value is invalid, we log a warning and skip to the next record. If the value is valid and qualifies for the top-ten list, we update the current top-ten entries and report progress to update the UI with the latest results.
				try
				{
					// Parse the raw line from the planetoids database into a PlanetoidRecord. If the DesignationName is null, empty, or consists only of whitespace, we skip this record as it does not have a valid designation to display in the top-ten list.
					PlanetoidRecord record = PlanetoidRecord.Parse(rawLine: planetoidsDatabase[index: i]);
					// If the DesignationName is null, empty, or consists only of whitespace, we skip this record as it does not have a valid designation to display in the top-ten list. This ensures that we only consider records with valid designations for inclusion in the top-ten results.
					if (string.IsNullOrWhiteSpace(value: record.DesignationName))
					{
						continue;
					}
					// Attempt to extract the selected orbital element's value from the record as both a string for display and a numeric value for comparison. If extraction and parsing succeed, we create a candidate TopRecordEntry and attempt to insert it into the current top-ten list based on the active sort order. If the candidate qualifies for the top-ten display, we report progress with the updated list of top entries to refresh the UI.
					if (TryGetSelectedElementValue(record: record, selectedElementIndex: selectedElementIndex, stringValue: out string? stringValue, numericValue: out double numericValue))
					{
						// Create a candidate TopRecordEntry with the designation, original string value, and numeric value for comparison. We then attempt to insert this candidate into the current top-ten list based on the active sort order. If the candidate qualifies for the top-ten display (i.e., it remains in the list after insertion), we report progress with the updated list of top entries to refresh the UI with the latest results.
						TopRecordEntry candidate = new(Designation: record.DesignationName, StringValue: stringValue, NumericValue: numericValue);
						if (TryInsertTopRecord(entries: currentTopEntries, candidate: candidate, isAscending: isAscending))
						{
							progress.Report(value: (percent, [.. currentTopEntries]));
						}
					}
				}
				// Catch any exceptions that may occur during parsing or value extraction, log a warning with the index of the record being processed and the exception message, and then continue to the next record. This ensures that a single malformed record does not disrupt the entire scanning process.
				catch (Exception ex)
				{
					// Log a warning if we fail to parse the record or extract the value, including the index of the record being processed and the exception message. This helps with debugging and allows us to identify any issues with specific records in the database without crashing the entire scan.
					logger.Warn(exception: ex, message: $"Skipping entry at index {i}: {ex.Message}");
				}
				// Report progress with the current percentage. We only report when the percentage changes to avoid excessive updates to the UI, which can cause performance issues. The progress report includes the current percentage and optionally the updated list of top entries if a new top record was found.
				if (percent != lastPercent)
				{
					progress.Report(value: (percent, null));
					lastPercent = percent;
				}
			}
		}, cancellationToken: token);
	}

	/// <summary>Updates the progress bar and top-ten labels from a progress callback.</summary>
	/// <param name="percent">Current scan percentage.</param>
	/// <param name="updatedEntries">Optional live top-ten snapshot.</param>
	/// <remarks>This method is called from the progress callback to update the progress bar and optionally refresh the displayed top-ten results as they are found during the scan. It checks if the percentage has changed before updating the progress bar to avoid unnecessary UI updates, and it applies any updated top-ten entries to the labels if provided.</remarks>
	private void HandleProgressUpdate(int percent, List<TopRecordEntry>? updatedEntries)
	{
		// Update the progress bar if the percentage has changed to avoid unnecessary UI updates. The progress bar's value is set to the current percentage, and the text is updated to show the percentage as well. Additionally, we update the taskbar progress indicator for this window to reflect the current scan progress.
		if (kryptonProgressBar.Value != percent)
		{
			kryptonProgressBar.Value = percent;
			kryptonProgressBar.Text = $"{percent} %";
			TaskbarProgress.SetValue(windowHandle: Handle, progressValue: (ulong)percent, progressMax: 100);
		}
		// If an updated list of top-ten entries is provided, we update the local topRecords list and apply it to the labels to refresh the displayed results. This allows the UI to show live updates of the top-ten records as they are found during the scan, providing immediate feedback to the user without waiting for the entire scan to complete.
		if (updatedEntries != null)
		{
			topRecords = updatedEntries;
			ApplyTopRecords(entries: topRecords);
		}
	}

	/// <summary>Navigates from a rank row to the corresponding planetoid in the main form.</summary>
	/// <param name="rankIndex">Zero-based rank index from 0 to 9.</param>
	/// <remarks>On success, the selected record is opened in the main form and this dialog closes.</remarks>
	private void NavigateToRank(int rankIndex)
	{
		// Validate the rank index to ensure it is within the valid range of 0 to 9, which corresponds to the top-ten ranks. If the index is out of range, we simply return without performing any navigation, as there is no valid record to navigate to for an invalid rank index.
		if (rankIndex < 0 || rankIndex >= topRecords.Count)
		{
			return;
		}
		// Attempt to find the main form (PlanetoidDbForm) among the open forms in the application. If the main form is not found, we show an error message to the user indicating that the main form is not available and return without performing any navigation. This ensures that we only attempt to navigate if the main form is accessible, preventing potential errors or crashes if the main form has been closed or is otherwise unavailable.
		if (Application.OpenForms.OfType<PlanetoidDbForm>().FirstOrDefault() is not PlanetoidDbForm mainForm)
		{
			ShowErrorMessage(message: "Main form is not available.");
			return;
		}
		// If the main form is found, we call the JumpToRecord method on the main form, passing an empty string for the index (since we are navigating by designation) and the designation of the selected top record. This will cause the main form to navigate to the corresponding planetoid record based on its designation. After invoking the navigation, we bring the main form to the front to ensure it is visible to the user, set the dialog result to OK to indicate a successful navigation, and then close this dialog.
		mainForm.JumpToRecord(index: string.Empty, designation: topRecords[index: rankIndex].Designation);
		mainForm.BringToFront();
		DialogResult = DialogResult.OK;
		Close();
	}

	/// <summary>Prepares and displays a save file dialog with a default file name and initial directory set to the user's Documents folder.</summary>
	/// <remarks>The method sets the dialog's initial directory to the user's Documents folder and generates a default file name based on the current date and time. The dialog is shown modally, and the result indicates whether the user confirmed the selection.</remarks>
	/// <param name="dialog">The file dialog to configure and display. Must not be null.</param>
	/// <param name="ext">The file extension to use for the default file name, without the leading period.</param>
	/// <returns>true if the user selects a file and confirms the dialog; otherwise, false.</returns>
	private static bool PrepareSaveDialog(FileDialog dialog, string ext)
	{
		// Set up the save dialog properties
		dialog.InitialDirectory = Environment.GetFolderPath(folder: Environment.SpecialFolder.MyDocuments);
		// Set default file name
		dialog.FileName = $"Top-Ten-Records_{DateTime.Now:yyyy-MM-dd_HH-mm-ss}.{ext}";
		// Show the dialog and return the result
		return dialog.ShowDialog(owner: Form.ActiveForm) == DialogResult.OK;
	}

	/// <summary>Displays a save dialog and exports the table layout panel contents using the specified export action.</summary>
	/// <param name="filter">The file type filter for the save dialog.</param>
	/// <param name="defaultExt">The default file extension.</param>
	/// <param name="dialogTitle">The title of the save dialog.</param>
	/// <param name="exportAction">The export action to invoke with the table layout panel, title, and file name.</param>
	/// <remarks>This method encapsulates the logic for displaying a save dialog and performing the export action based on the user's selection. It handles the preparation of the dialog, execution of the export action, and manages the cursor state during the operation.</remarks>
	private void PerformSaveExport(string filter, string defaultExt, string dialogTitle, Action<TableLayoutPanel, string, string> exportAction)
	{
		// Create and configure the save file dialog with the specified filter, default extension, and title. The dialog allows the user to choose where to save the exported file and what name to give it.
		using SaveFileDialog saveFileDialog = new()
		{
			Filter = filter,
			DefaultExt = defaultExt,
			Title = dialogTitle
		};
		// Prepare and show the save dialog. If the user cancels the dialog, the method returns without performing any export action.
		if (!PrepareSaveDialog(dialog: saveFileDialog, ext: defaultExt))
		{
			return;
		}
		// If the user selects a file and confirms the dialog, set the cursor to a wait cursor to indicate that an operation is in progress, and then invoke the specified export action with the text box containing the output, the title for the export, and the selected file name. After the export action is completed, reset the cursor to the default state.
		try
		{
			Cursor.Current = Cursors.WaitCursor;
			exportAction(arg1: tableLayoutPanel, arg2: "Top Ten Records", arg3: saveFileDialog.FileName);
		}
		// Handle any exceptions that may occur during the export action
		catch (Exception ex)
		{
			logger.Error(message: $"An error occurred during export: {ex}");
			ShowErrorMessage(message: $"An error has occurred during export: {ex.Message}");
		}
		// In the finally block, ensure that the cursor is reset to the default state regardless of whether the export action succeeds or fails. This ensures that the user interface remains responsive and provides appropriate feedback to the user.
		finally
		{
			Cursor.Current = Cursors.Default;
		}
	}

	#endregion

	#region form event handlers

	/// <summary>Handles the Load event of the form.</summary>
	/// <param name="sender">The event source.</param>
	/// <param name="e">The <see cref="EventArgs"/> instance that contains the event data.</param>
	/// <remarks>This method is called when the RecordsMainForm is loaded.</remarks>
	private void RecordsMainForm_Load(object sender, EventArgs e)
	{
		// On form load, we clear the status bar to ensure it starts in a clean state, disable the Cancel button since no scan is active, and disable the "Goto" buttons since there are no records to navigate to yet. This sets up the initial state of the UI for the user when they first open the form.
		ClearStatusBar(label: labelInformation);
		toolStripButtonCancel.Enabled = false;
		SetGotoButtonsEnabled(isEnabled: false);
	}

	#endregion

	#region Click event handlers

	/// <summary>Handles the Click event of the Start control. Starts the main process.</summary>
	/// <param name="sender">The event source.</param>
	/// <param name="e">The <see cref="EventArgs"/> instance that contains the event data.</param>
	/// <remarks>This method is called when the Start control is clicked.</remarks>
	private async void Start_Click(object sender, EventArgs e)
	{
		// Validate that the planetoids database is loaded and that an orbital element is selected before starting the scan. If the database is empty, we show an error message to the user indicating that the MPCORB.DAT file was not found and return without starting the scan. If no orbital element is selected in the list box, we show an error message prompting the user to select an orbital element and return without starting the scan. This ensures that we have the necessary data and user input to perform a meaningful scan before we proceed.
		if (planetoidsDatabase.Count == 0)
		{
			ShowErrorMessage(message: I18nStrings.MpcorbDatNotFoundText);
			return;
		}
		// Check if an orbital element is selected in the list box. If not, show an error message prompting the user to select an orbital element and return without starting the scan. This ensures that we have a valid selection for the orbital element to rank by before we proceed with the scan.
		if (listBox.SelectedIndex < 0)
		{
			ShowErrorMessage(message: "Please select an orbital element first.");
			return;
		}
		// If we reach this point, it means that the database is loaded and an orbital element is selected, so we can proceed with starting the scan. We first cancel any existing scan if it is still running by calling Cancel on the cancellation token source, and then dispose of it to clean up resources. We create a new CancellationTokenSource for the new scan run. We reset the labels to clear any previous results from the UI, and we update the enabled state of the buttons and controls to reflect that a scan is now active (e.g., disable the Start button, enable the Cancel button, disable sort order buttons and list box to prevent changes during the scan). We also reset the progress bar to 0% and set its text accordingly.
		cancellationTokenSource?.Cancel();
		cancellationTokenSource?.Dispose();
		cancellationTokenSource = new CancellationTokenSource();
		ResetLabels();
		toolStripButtonStart.Enabled = false;
		toolStripButtonCancel.Enabled = true;
		toolStripButtonSortOrderAscending.Enabled = false;
		toolStripButtonSortOrderDescending.Enabled = false;
		listBox.Enabled = false;
		toolStripDropDownButtonSaveList.Enabled = false;
		contextMenuSaveToFile.Enabled = false;
		SetGotoButtonsEnabled(isEnabled: false);
		kryptonProgressBar.Value = 0;
		kryptonProgressBar.Text = "0 %";
		// Determine the active sort order based on the state of the sort order buttons. If the ascending button is checked, we set isAscending to true; if the descending button is checked, we set isAscending to false. This will be used to determine how we maintain the top-ten list during the scan, whether we are looking for the smallest values (ascending) or the largest values (descending) for the selected orbital element.
		bool isAscending = toolStripButtonSortOrderAscending.Checked;
		Progress<(int Percent, List<TopRecordEntry>? UpdatedEntries)> progress = new(handler: update => HandleProgressUpdate(percent: update.Percent, updatedEntries: update.UpdatedEntries));
		// Run the scan asynchronously and await its completion. We pass the selected orbital element index, the active sort order, the cancellation token for cooperative cancellation, and the progress callback to receive updates during the scan. If the scan completes successfully, we set the progress bar text to "100 %". If the scan is cancelled, we catch the OperationCanceledException and update the progress bar text to indicate that the scan was cancelled. If any other exceptions occur during the scan, we log an error with the exception details and update the progress bar text to show an error message. Finally, in the finally block, we reset the enabled state of the buttons and controls to allow for a new scan to be started, enable navigation if there are valid top-ten records, and dispose of the cancellation token source to clean up resources.
		try
		{
			await ScanTopRecordsAsync(
				selectedElementIndex: listBox.SelectedIndex,
				isAscending: isAscending,
				token: cancellationTokenSource.Token,
				progress: progress);
			kryptonProgressBar.Text = "100 %";
		}
		// Catch the OperationCanceledException to handle the case when the scan is cancelled by the user. We update the progress bar text to indicate that the scan was cancelled, providing feedback to the user that their cancellation request was acknowledged and processed.
		catch (OperationCanceledException)
		{
			kryptonProgressBar.Text = "Scan cancelled";
		}
		// Catch any other exceptions that may occur during the scan, log an error with the exception details, and update the progress bar text to show an error message. This ensures that we handle unexpected errors gracefully and provide feedback to the user about what went wrong.
		catch (Exception ex)
		{
			logger.Error(exception: ex, message: ex.Message);
			kryptonProgressBar.Text = I18nStrings.ErrorCaption;
		}
		// In the finally block, we reset the enabled state of the buttons and controls to allow for a new scan to be started, enable navigation if there are valid top-ten records, and dispose of the cancellation token source to clean up resources. This ensures that the UI is returned to a ready state for the user to start a new scan or navigate to records after the current scan has completed or been cancelled.
		finally
		{
			toolStripButtonStart.Enabled = true;
			toolStripButtonCancel.Enabled = false;
			toolStripButtonSortOrderAscending.Enabled = true;
			toolStripButtonSortOrderDescending.Enabled = true;
			listBox.Enabled = true;
			toolStripDropDownButtonSaveList.Enabled = true;
			contextMenuSaveToFile.Enabled = true;
			SetGotoButtonsEnabled(isEnabled: topRecords.Count > 0);
			cancellationTokenSource?.Dispose();
			cancellationTokenSource = null;
		}
	}

	/// <summary>Handles the Click event of the Cancel control. Cancels the main process.</summary>
	/// <param name="sender">The event source.</param>
	/// <param name="e">The <see cref="EventArgs"/> instance that contains the event data.</param>
	/// <remarks>This method is called when the Cancel control is clicked.</remarks>
	private void Cancel_Click(object sender, EventArgs e)
	{
		// When the Cancel button is clicked, we call Cancel on the cancellation token source to signal that the ongoing scan should be cancelled. We also disable the Cancel button to prevent multiple cancellation requests while the cancellation is being processed. The actual handling of the cancellation will occur in the ScanTopRecordsAsync method, where we check for cancellation and throw an OperationCanceledException to exit the scan loop gracefully.
		cancellationTokenSource?.Cancel();
		toolStripButtonCancel.Enabled = false;
	}

	/// <summary>Handles the Click event of the Goto01 control. Navigates to the first record.</summary>
	/// <param name="sender">The event source.</param>
	/// <param name="e">The <see cref="EventArgs"/> instance that contains the event data.</param>
	/// <remarks>This method is called when the Goto01 control is clicked.</remarks>
	private void Goto01_Click(object sender, EventArgs e) => NavigateToRank(rankIndex: 0);

	/// <summary>Handles the Click event of the Goto02 control. Navigates to the second record.</summary>
	/// <param name="sender">The event source.</param>
	/// <param name="e">The <see cref="EventArgs"/> instance that contains the event data.</param>
	/// <remarks>This method is called when the Goto02 control is clicked.</remarks>
	private void Goto02_Click(object sender, EventArgs e) => NavigateToRank(rankIndex: 1);

	/// <summary>Handles the Click event of the Goto03 control. Navigates to the third record.</summary>
	/// <param name="sender">The event source.</param>
	/// <param name="e">The <see cref="EventArgs"/> instance that contains the event data.</param>
	/// <remarks>This method is called when the Goto03 control is clicked.</remarks>
	private void Goto03_Click(object sender, EventArgs e) => NavigateToRank(rankIndex: 2);

	/// <summary>Handles the Click event of the Goto04 control. Navigates to the fourth record.</summary>
	/// <param name="sender">The event source.</param>
	/// <param name="e">The <see cref="EventArgs"/> instance that contains the event data.</param>
	/// <remarks>This method is called when the Goto04 control is clicked.</remarks>
	private void Goto04_Click(object sender, EventArgs e) => NavigateToRank(rankIndex: 3);

	/// <summary>Handles the Click event of the Goto05 control. Navigates to the fifth record.</summary>
	/// <param name="sender">The event source.</param>
	/// <param name="e">The <see cref="EventArgs"/> instance that contains the event data.</param>
	/// <remarks>This method is called when the Goto05 control is clicked.</remarks>
	private void Goto05_Click(object sender, EventArgs e) => NavigateToRank(rankIndex: 4);

	/// <summary>Handles the Click event of the Goto06 control. Navigates to the sixth record.</summary>
	/// <param name="sender">The event source.</param>
	/// <param name="e">The <see cref="EventArgs"/> instance that contains the event data.</param>
	/// <remarks>This method is called when the Goto06 control is clicked.</remarks>
	private void Goto06_Click(object sender, EventArgs e) => NavigateToRank(rankIndex: 5);

	/// <summary>Handles the Click event of the Goto07 control. Navigates to the seventh record.</summary>
	/// <param name="sender">The event source.</param>
	/// <param name="e">The <see cref="EventArgs"/> instance that contains the event data.</param>
	/// <remarks>This method is called when the Goto07 control is clicked.</remarks>
	private void Goto07_Click(object sender, EventArgs e) => NavigateToRank(rankIndex: 6);

	/// <summary>Handles the Click event of the Goto08 control. Navigates to the eighth record.</summary>
	/// <param name="sender">The event source.</param>
	/// <param name="e">The <see cref="EventArgs"/> instance that contains the event data.</param>
	/// <remarks>This method is called when the Goto08 control is clicked.</remarks>
	private void Goto08_Click(object sender, EventArgs e) => NavigateToRank(rankIndex: 7);

	/// <summary>Handles the Click event of the Goto09 control. Navigates to the ninth record.</summary>
	/// <param name="sender">The event source.</param>
	/// <param name="e">The <see cref="EventArgs"/> instance that contains the event data.</param>
	/// <remarks>This method is called when the Goto09 control is clicked.</remarks>
	private void Goto09_Click(object sender, EventArgs e) => NavigateToRank(rankIndex: 8);

	/// <summary>Handles the Click event of the Goto10 control. Navigates to the tenth record.</summary>
	/// <param name="sender">The event source.</param>
	/// <param name="e">The <see cref="EventArgs"/> instance that contains the event data.</param>
	/// <remarks>This method is called when the Goto10 control is clicked.</remarks>
	private void Goto10_Click(object sender, EventArgs e) => NavigateToRank(rankIndex: 9);

	/// <summary>Handles the Click event of the ascending sort order button.</summary>
	/// <param name="sender">The event source.</param>
	/// <param name="e">The event data associated with the click.</param>
	/// <remarks>Ensures only one sort direction is checked at a time.</remarks>
	private void SetAscendingSortOrder_Click(object sender, EventArgs e)
	{
		// If neither sort order button is currently checked, we default to checking the ascending sort order button. This ensures that there is always a valid sort order selected, even if the user clicks on the currently unchecked button.
		if (!toolStripButtonSortOrderAscending.Checked && !toolStripButtonSortOrderDescending.Checked)
		{
			toolStripButtonSortOrderAscending.Checked = true;
		}
		// Ensure that only one sort order button is checked at a time by setting the opposite button's checked state to the inverse of the current button's checked state. This maintains a consistent state where either ascending or descending is selected, but not both.
		toolStripButtonSortOrderDescending.Checked = !toolStripButtonSortOrderAscending.Checked;
	}

	/// <summary>Handles the Click event of the descending sort order button.</summary>
	/// <param name="sender">The event source.</param>
	/// <param name="e">The event data associated with the click.</param>
	/// <remarks>Ensures only one sort direction is checked at a time.</remarks>
	private void SetDescendingSortOrder_Click(object sender, EventArgs e)
	{
		// If neither sort order button is currently checked, we default to checking the descending sort order button. This ensures that there is always a valid sort order selected, even if the user clicks on the currently unchecked button.
		if (!toolStripButtonSortOrderDescending.Checked && !toolStripButtonSortOrderAscending.Checked)
		{
			toolStripButtonSortOrderDescending.Checked = true;
		}
		// Ensure that only one sort order button is checked at a time by setting the opposite button's checked state to the inverse of the current button's checked state. This maintains a consistent state where either ascending or descending is selected, but not both.
		toolStripButtonSortOrderAscending.Checked = !toolStripButtonSortOrderDescending.Checked;
	}

	/// <summary>Handles the Click event to export the output as a text file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as a text file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item for saving as text.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsText_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "Text Files (*.txt)|*.txt|All Files (*.*)|*.*", defaultExt: "txt", dialogTitle: "Save as Text", exportAction: TableLayoutPanelExporter.SaveAsText);

	/// <summary>Handles the Click event to export the output as a LaTeX file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as a LaTeX file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsLatex_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "LaTeX Files (*.tex)|*.tex|All Files (*.*)|*.*", defaultExt: "tex", dialogTitle: "Save as LaTeX", exportAction: TableLayoutPanelExporter.SaveAsLatex);

	/// <summary>Handles the Click event to export the output as a Markdown file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as a Markdown file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsMarkdown_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "Markdown Files (*.md)|*.md|All Files (*.*)|*.*", defaultExt: "md", dialogTitle: "Save as Markdown", exportAction: TableLayoutPanelExporter.SaveAsMarkdown);

	/// <summary>Handles the Click event to export the output as an AsciiDoc file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as an AsciiDoc file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsAsciiDoc_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "AsciiDoc Files (*.adoc)|*.adoc|All Files (*.*)|*.*", defaultExt: "adoc", dialogTitle: "Save as AsciiDoc", exportAction: TableLayoutPanelExporter.SaveAsAsciiDoc);

	/// <summary>Handles the Click event to export the output as a ReStructuredText file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as a ReStructuredText file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsReStructuredText_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "ReStructuredText Files (*.rst)|*.rst|All Files (*.*)|*.*", defaultExt: "rst", dialogTitle: "Save as ReStructuredText", exportAction: TableLayoutPanelExporter.SaveAsReStructuredText);

	/// <summary>Handles the Click event to export the output as a Textile file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as a Textile file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsTextile_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "Textile Files (*.textile)|*.textile|All Files (*.*)|*.*", defaultExt: "textile", dialogTitle: "Save as Textile", exportAction: TableLayoutPanelExporter.SaveAsTextile);

	/// <summary>Handles the Click event to export the output as a Word document.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as a Word file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsWord_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "Word Files (*.docx)|*.docx|All Files (*.*)|*.*", defaultExt: "docx", dialogTitle: "Save as Word", exportAction: TableLayoutPanelExporter.SaveAsWord);

	/// <summary>Handles the Click event to export the output as an OpenDocument Text file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as an ODT file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsOdt_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "OpenDocument Text Files (*.odt)|*.odt|All Files (*.*)|*.*", defaultExt: "odt", dialogTitle: "Save as OpenDocument Text", exportAction: TableLayoutPanelExporter.SaveAsOdt);

	/// <summary>Handles the Click event to export the output as an RTF file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as an RTF file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the Save As RTF menu item.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsRtf_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "Rich Text Format Files (*.rtf)|*.rtf|All Files (*.*)|*.*", defaultExt: "rtf", dialogTitle: "Save as RTF", exportAction: TableLayoutPanelExporter.SaveAsRtf);

	/// <summary>Handles the Click event to export the output as an Abiword file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as an Abiword file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsAbiword_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "Abiword Files (*.abw)|*.abw|All Files (*.*)|*.*", defaultExt: "abw", dialogTitle: "Save as Abiword", exportAction: TableLayoutPanelExporter.SaveAsAbiword);

	/// <summary>Handles the Click event to export the output as a WPS file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as a WPS file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the Save As WPS menu item.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsWps_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "WPS Files (*.wps)|*.wps|All Files (*.*)|*.*", defaultExt: "wps", dialogTitle: "Save as WPS", exportAction: TableLayoutPanelExporter.SaveAsWps);

	/// <summary>Handles the Click event to export the output as an Excel file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as an Excel file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsExcel_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "Excel Files (*.xlsx)|*.xlsx|All Files (*.*)|*.*", defaultExt: "xlsx", dialogTitle: "Save as Excel", exportAction: TableLayoutPanelExporter.SaveAsExcel);

	/// <summary>Handles the Click event to export the output as an ODS file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as an ODS file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsOds_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "OpenDocument Spreadsheet Files (*.ods)|*.ods|All Files (*.*)|*.*", defaultExt: "ods", dialogTitle: "Save as ODS", exportAction: TableLayoutPanelExporter.SaveAsOds);

	/// <summary>Handles the Click event to export the output as a CSV file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as a CSV file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsCsv_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "Comma-Separated Values (*.csv)|*.csv|All Files (*.*)|*.*", defaultExt: "csv", dialogTitle: "Save as CSV", exportAction: TableLayoutPanelExporter.SaveAsCsv);

	/// <summary>Handles the Click event to export the output as a TSV file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as a TSV file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsTsv_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "Tab-Separated Values (*.tsv)|*.tsv|All Files (*.*)|*.*", defaultExt: "tsv", dialogTitle: "Save as TSV", exportAction: TableLayoutPanelExporter.SaveAsTsv);

	/// <summary>Handles the Click event to export the output as a PSV file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as a PSV file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsPsv_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "Pipe-Separated Values (*.psv)|*.psv|All Files (*.*)|*.*", defaultExt: "psv", dialogTitle: "Save as PSV", exportAction: TableLayoutPanelExporter.SaveAsPsv);

	/// <summary>Handles the Click event to export the output as an ET file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as an ET file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsEt_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "ET Files (*.et)|*.et|All Files (*.*)|*.*", defaultExt: "et", dialogTitle: "Save as ET", exportAction: TableLayoutPanelExporter.SaveAsEt);

	/// <summary>Handles the Click event to export the output as an HTML file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as an HTML file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsHtml_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "HTML Files (*.html)|*.html|All Files (*.*)|*.*", defaultExt: "html", dialogTitle: "Save as HTML", exportAction: TableLayoutPanelExporter.SaveAsHtml);

	/// <summary>Handles the Click event to export the output as an XML file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as an XML file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsXml_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "XML Files (*.xml)|*.xml|All Files (*.*)|*.*", defaultExt: "xml", dialogTitle: "Save as XML", exportAction: TableLayoutPanelExporter.SaveAsXml);

	/// <summary>Handles the Click event to export the output as a DocBook file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as a DocBook file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsDocBook_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "DocBook Files (*.xml)|*.xml|All Files (*.*)|*.*", defaultExt: "xml", dialogTitle: "Save as DocBook", exportAction: TableLayoutPanelExporter.SaveAsDocBook);

	/// <summary>Handles the Click event to export the output as a JSON file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as a JSON file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsJson_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "JSON Files (*.json)|*.json|All Files (*.*)|*.*", defaultExt: "json", dialogTitle: "Save as JSON", exportAction: TableLayoutPanelExporter.SaveAsJson);

	/// <summary>Handles the Click event to export the output as a YAML file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as a YAML file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsYaml_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "YAML Files (*.yaml)|*.yaml|All Files (*.*)|*.*", defaultExt: "yaml", dialogTitle: "Save as YAML", exportAction: TableLayoutPanelExporter.SaveAsYaml);

	/// <summary>Handles the Click event to export the output as a TOML file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as a TOML file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsToml_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "TOML Files (*.toml)|*.toml|All Files (*.*)|*.*", defaultExt: "toml", dialogTitle: "Save as TOML", exportAction: TableLayoutPanelExporter.SaveAsToml);

	/// <summary>Handles the Click event to export the output as a SQL file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as a SQL file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the Save As SQL menu item.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsSql_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "SQL Files (*.sql)|*.sql|All Files (*.*)|*.*", defaultExt: "sql", dialogTitle: "Save as SQL", exportAction: TableLayoutPanelExporter.SaveAsSql);

	/// <summary>Handles the Click event to export the output as a SQLite file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as a SQLite file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsSqlite_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "SQLite Files (*.sqlite)|*.sqlite|All Files (*.*)|*.*", defaultExt: "sqlite", dialogTitle: "Save as SQLite", exportAction: TableLayoutPanelExporter.SaveAsSqlite);

	/// <summary>Handles the Click event to export the output as a PDF file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as a PDF file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsPdf_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "PDF Files (*.pdf)|*.pdf|All Files (*.*)|*.*", defaultExt: "pdf", dialogTitle: "Save as PDF", exportAction: TableLayoutPanelExporter.SaveAsPdf);

	/// <summary>Handles the Click event to export the output as a PostScript file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as a PostScript file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the Save As PostScript menu item.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsPostScript_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "PostScript Files (*.ps)|*.ps|All Files (*.*)|*.*", defaultExt: "ps", dialogTitle: "Save as PostScript", exportAction: TableLayoutPanelExporter.SaveAsPostScript);

	/// <summary>Handles the Click event to export the output as an EPUB file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as an EPUB file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsEpub_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "EPUB Files (*.epub)|*.epub|All Files (*.*)|*.*", defaultExt: "epub", dialogTitle: "Save as EPUB", exportAction: TableLayoutPanelExporter.SaveAsEpub);

	/// <summary>Handles the Click event to export the output as a MOBI file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as a MOBI file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsMobi_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "MOBI Files (*.mobi)|*.mobi|All Files (*.*)|*.*", defaultExt: "mobi", dialogTitle: "Save as MOBI", exportAction: TableLayoutPanelExporter.SaveAsMobi);

	/// <summary>Handles the Click event to export the output as an XPS file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as an XPS file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the Save As XPS menu item.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsXps_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "XPS Files (*.xps)|*.xps|All Files (*.*)|*.*", defaultExt: "xps", dialogTitle: "Save as XPS", exportAction: TableLayoutPanelExporter.SaveAsXps);

	/// <summary>Handles the Click event to export the output as a FictionBook2 file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as a FictionBook2 file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsFictionBook2_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "FictionBook2 Files (*.fb2)|*.fb2|All Files (*.*)|*.*", defaultExt: "fb2", dialogTitle: "Save as FictionBook2", exportAction: TableLayoutPanelExporter.SaveAsFictionBook2);

	/// <summary>Handles the Click event to export the output as a CHM file.</summary>
	/// <remarks>Invokes the PerformSaveExport method with parameters specific to exporting as a CHM file, including the file filter, default extension, dialog title, and export action.</remarks>
	/// <param name="sender">The source of the event, typically the menu item that was clicked.</param>
	/// <param name="e">The event data associated with the click event.</param>
	private void ToolStripMenuItemSaveAsChm_Click(object sender, EventArgs e)
		=> PerformSaveExport(filter: "Compiled HTML Help Files (*.chm)|*.chm|All Files (*.*)|*.*", defaultExt: "chm", dialogTitle: "Save as CHM", exportAction: TableLayoutPanelExporter.SaveAsChm);

	#endregion
}